### ISSUE TITLE
[Request] TechReborn compatibility

### ISSUE THREAD

**Issue by draldan** [TinyModularThings/IC2Classic#100]
I really loved the old IC2 and Gregtech combo, and I think being able to use IC2Classic with TechReborn would give a very similar feeling :)

**Comment by Carbon-Ghost** [comment]
It has already been planned for a long time now ;)
Once TechReborn gets a normal release for IC2 exp, we will work and release a seperate version of TechReborn named TechRebornClassic, made specially for IC2 classic so they work together ( I am both in IC2 classic and GregTech Reborn team :D ). So please close this, it will be done :)

**Comment by Speiger** [comment]
From my side there will be support.
What that means we will see ^^
