### ISSUE TITLE
Crashing when open Fluid-O-Mat

### ISSUE THREAD

**Issue by 4679** [TinyModularThings/IC2Classic#101]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 15-8-12 下午2:44
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at ic2.core.block.personal.ContainerFluidOMatOpen.func_75137_b(ContainerFluidOMatOpen.java:114)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at ic2.core.block.personal.ContainerFluidOMatOpen.func_75137_b(ContainerFluidOMatOpen.java:114)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['4679kun'/156, l='MpServer', x=-966.32, y=5.62, z=-1411.99]]
	Chunk stats: MultiplayerChunkCache: 225, 234
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1015,4,-1378), Chunk: (at 9,0,14 in -64,-87; contains blocks -1024,0,-1392 to -1009,255,-1377), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,0,-1536 to -513,255,-1025)
	Level time: 57589 game time, 148862 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 114 total; [EntitySheep['羊'/24, l='MpServer', x=-1028.25, y=4.00, z=-1474.22], EntityHorse['马'/25, l='MpServer', x=-1030.25, y=4.00, z=-1482.94], EntitySheep['羊'/26, l='MpServer', x=-1024.75, y=4.00, z=-1474.69], EntityVillager['村民'/27, l='MpServer', x=-1024.31, y=5.00, z=-1365.31], EntityVillager['村民'/28, l='MpServer', x=-1024.31, y=5.00, z=-1368.69], EntityVillager['村民'/29, l='MpServer', x=-1024.56, y=5.00, z=-1367.44], EntityVillager['村民'/30, l='MpServer', x=-1024.31, y=5.00, z=-1368.69], EntityVillager['村民'/31, l='MpServer', x=-1025.16, y=5.00, z=-1365.31], EntityVillager['村民'/32, l='MpServer', x=-1026.03, y=5.00, z=-1365.31], EntityVillager['村民'/33, l='MpServer', x=-1025.72, y=5.00, z=-1374.53], EntitySheep['羊'/34, l='MpServer', x=-1018.78, y=4.00, z=-1484.97], EntitySheep['羊'/35, l='MpServer', x=-1012.19, y=4.00, z=-1482.34], EntityPig['猪'/36, l='MpServer', x=-1023.78, y=4.00, z=-1459.44], EntityCow['牛'/37, l='MpServer', x=-1021.88, y=4.00, z=-1461.97], EntityPig['猪'/38, l='MpServer', x=-1021.84, y=4.00, z=-1410.34], EntitySheep['羊'/39, l='MpServer', x=-1022.94, y=4.00, z=-1393.97], EntityPig['猪'/40, l='MpServer', x=-1020.78, y=4.00, z=-1402.69], EntityHorse['马'/41, l='MpServer', x=-1022.00, y=4.00, z=-1405.91], EntityVillager['村民'/42, l='MpServer', x=-1022.66, y=5.00, z=-1377.38], EntityVillager['村民'/43, l='MpServer', x=-1004.50, y=5.00, z=-1364.94], EntityVillager['村民'/44, l='MpServer', x=-1023.13, y=4.00, z=-1372.56], EntityVillager['村民'/45, l='MpServer', x=-1008.53, y=6.00, z=-1374.50], EntityVillager['村民'/46, l='MpServer', x=-1022.31, y=5.00, z=-1374.31], EntityVillager['村民'/47, l='MpServer', x=-1021.09, y=4.00, z=-1370.31], EntityVillager['村民'/48, l='MpServer', x=-1019.69, y=4.00, z=-1374.16], EntityVillager['村民'/49, l='MpServer', x=-1016.72, y=4.00, z=-1363.72], EntityVillager['村民'/50, l='MpServer', x=-1022.50, y=5.00, z=-1353.31], EntityVillager['村民'/51, l='MpServer', x=-1012.53, y=4.00, z=-1359.38], EntityVillager['村民'/52, l='MpServer', x=-1003.56, y=4.00, z=-1351.16], EntityVillager['村民'/53, l='MpServer', x=-1008.63, y=5.00, z=-1358.69], EntityVillager['村民'/54, l='MpServer', x=-1010.28, y=5.00, z=-1359.50], EntitySheep['羊'/55, l='MpServer', x=-1016.94, y=4.00, z=-1449.13], EntityChicken['鸡'/56, l='MpServer', x=-1003.47, y=4.00, z=-1430.56], EntityItem['item.item.egg'/57, l='MpServer', x=-993.59, y=4.13, z=-1431.09], EntityVillager['村民'/58, l='MpServer', x=-994.50, y=5.00, z=-1375.91], EntityVillager['村民'/59, l='MpServer', x=-993.50, y=5.00, z=-1366.94], EntityVillager['村民'/60, l='MpServer', x=-993.50, y=5.00, z=-1367.94], EntityVillager['村民'/61, l='MpServer', x=-994.94, y=5.00, z=-1372.59], EntityVillager['村民'/62, l='MpServer', x=-999.56, y=5.00, z=-1361.38], EntityVillager['村民'/63, l='MpServer', x=-1006.31, y=5.00, z=-1365.69], EntityVillager['村民'/64, l='MpServer', x=-996.84, y=4.00, z=-1372.69], EntityVillager['村民'/65, l='MpServer', x=-1003.66, y=4.00, z=-1364.09], EntityVillager['村民'/66, l='MpServer', x=-1005.47, y=5.00, z=-1369.13], EntityVillager['村民'/67, l='MpServer', x=-998.31, y=6.00, z=-1356.41], EntityVillager['村民'/68, l='MpServer', x=-998.94, y=5.00, z=-1357.50], EntityVillager['村民'/69, l='MpServer', x=-1013.59, y=4.00, z=-1359.13], EntityPig['猪'/70, l='MpServer', x=-994.16, y=4.00, z=-1437.09], EntityHorse['马'/71, l='MpServer', x=-992.25, y=4.00, z=-1444.38], EntityCow['牛'/72, l='MpServer', x=-981.03, y=4.00, z=-1455.22], EntityCow['牛'/73, l='MpServer', x=-988.94, y=4.00, z=-1460.91], EntityHorse['马'/74, l='MpServer', x=-989.84, y=4.00, z=-1453.06], EntityItemFrame['物品展示框'/75, l='MpServer', x=-981.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/76, l='MpServer', x=-982.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/77, l='MpServer', x=-983.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/78, l='MpServer', x=-984.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/79, l='MpServer', x=-984.50, y=6.50, z=-1413.94], EntityItemFrame['物品展示框'/80, l='MpServer', x=-983.50, y=6.50, z=-1413.94], EntityItemFrame['物品展示框'/81, l='MpServer', x=-982.50, y=6.50, z=-1413.94], EntityItemFrame['物品展示框'/82, l='MpServer', x=-982.50, y=4.50, z=-1413.94], EntityItemFrame['物品展示框'/83, l='MpServer', x=-983.50, y=4.50, z=-1413.94], EntityItemFrame['物品展示框'/84, l='MpServer', x=-984.50, y=4.50, z=-1413.94], EntityItemFrame['物品展示框'/85, l='MpServer', x=-976.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/86, l='MpServer', x=-977.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/87, l='MpServer', x=-979.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/88, l='MpServer', x=-978.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/89, l='MpServer', x=-979.50, y=6.50, z=-1413.94], EntityItemFrame['物品展示框'/90, l='MpServer', x=-978.50, y=6.50, z=-1413.94], EntityItemFrame['物品展示框'/91, l='MpServer', x=-977.50, y=6.50, z=-1413.94], EntityItemFrame['物品展示框'/92, l='MpServer', x=-977.50, y=4.50, z=-1413.94], EntityItemFrame['物品展示框'/93, l='MpServer', x=-978.50, y=4.50, z=-1413.94], EntityItemFrame['物品展示框'/94, l='MpServer', x=-979.50, y=4.50, z=-1413.94], EntityVillager['村民'/95, l='MpServer', x=-988.75, y=5.00, z=-1366.50], EntityChicken['鸡'/96, l='MpServer', x=-990.72, y=5.00, z=-1352.56], EntityPig['猪'/97, l='MpServer', x=-970.75, y=4.00, z=-1462.34], EntityCow['牛'/98, l='MpServer', x=-962.19, y=4.00, z=-1458.91], EntityPig['猪'/99, l='MpServer', x=-970.19, y=4.00, z=-1465.88], EntitySheep['羊'/100, l='MpServer', x=-961.03, y=4.00, z=-1466.03], EntityPig['猪'/101, l='MpServer', x=-974.13, y=4.00, z=-1444.19], EntityItemFrame['物品展示框'/102, l='MpServer', x=-969.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/103, l='MpServer', x=-970.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/104, l='MpServer', x=-971.50, y=5.50, z=-1413.94], EntityItemFrame['物品展示框'/105, l='MpServer', x=-971.50, y=4.50, z=-1413.94], EntityItemFrame['物品展示框'/106, l='MpServer', x=-970.50, y=4.50, z=-1413.94], EntityItemFrame['物品展示框'/107, l='MpServer', x=-969.50, y=4.50, z=-1413.94], EntityItemFrame['物品展示框'/108, l='MpServer', x=-969.50, y=6.50, z=-1413.94], EntityItemFrame['物品展示框'/109, l='MpServer', x=-970.50, y=6.50, z=-1413.94], EntityItemFrame['物品展示框'/110, l='MpServer', x=-971.50, y=6.50, z=-1413.94], EntityItemFrame['物品展示框'/111, l='MpServer', x=-968.50, y=5.50, z=-1413.94], EntityCow['牛'/112, l='MpServer', x=-964.38, y=5.00, z=-1361.50], EntityCow['牛'/113, l='MpServer', x=-964.81, y=4.00, z=-1344.81], EntitySheep['羊'/114, l='MpServer', x=-958.38, y=4.00, z=-1459.78], EntityPig['猪'/115, l='MpServer', x=-951.97, y=4.00, z=-1459.94], EntitySheep['羊'/116, l='MpServer', x=-944.22, y=4.00, z=-1452.34], EntitySheep['羊'/117, l='MpServer', x=-950.06, y=4.00, z=-1443.94], EntityCow['牛'/118, l='MpServer', x=-944.45, y=4.00, z=-1402.89], EntityPig['猪'/119, l='MpServer', x=-944.09, y=4.00, z=-1365.09], EntitySheep['羊'/128, l='MpServer', x=-937.22, y=1.00, z=-1471.22], EntityPig['猪'/129, l='MpServer', x=-950.41, y=4.00, z=-1400.81], EntityPig['猪'/130, l='MpServer', x=-934.63, y=4.00, z=-1365.16], EntityCow['牛'/131, l='MpServer', x=-934.28, y=4.00, z=-1366.44], EntityCow['牛'/132, l='MpServer', x=-931.84, y=4.00, z=-1370.16], EntityPig['猪'/133, l='MpServer', x=-937.41, y=4.00, z=-1372.31], EntityPig['猪'/134, l='MpServer', x=-936.94, y=4.00, z=-1373.69], EntityCow['牛'/135, l='MpServer', x=-938.78, y=4.00, z=-1354.34], EntityCow['牛'/136, l='MpServer', x=-932.09, y=4.00, z=-1336.84], EntitySheep['羊'/141, l='MpServer', x=-923.09, y=4.00, z=-1392.09], EntityCow['牛'/142, l='MpServer', x=-914.88, y=4.00, z=-1384.06], EntitySheep['羊'/143, l='MpServer', x=-926.78, y=4.00, z=-1387.84], EntityPig['猪'/144, l='MpServer', x=-922.06, y=4.00, z=-1367.78], EntityCow['牛'/145, l='MpServer', x=-924.31, y=4.00, z=-1343.59], EntitySheep['羊'/146, l='MpServer', x=-903.50, y=4.00, z=-1396.50], EntitySheep['羊'/147, l='MpServer', x=-900.06, y=4.00, z=-1396.09], EntityCow['牛'/148, l='MpServer', x=-897.69, y=4.00, z=-1370.41], EntityClientPlayerMP['4679kun'/156, l='MpServer', x=-966.32, y=5.62, z=-1411.99]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 246853288 bytes (235 MB) / 515903488 bytes (492 MB) up to 1060372480 bytes (1011 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.5.16
	LaunchWrapper: 37 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: lain.mods.inputfix.InputFixTransformer
          - Transformer: me.guichaguri.betterfps.BetterFpsTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: me.isuzutsuki.betterfonts.BTFClassTransformer
          - Transformer: mods.core.PaneInTheGlass.ClassTransformer
          - Transformer: org.devinprogress.uniskinmod.CoreTransformer
          - Transformer: nce.nceLoader
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: shadersmodcore.transform.SMCClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 2 total; -Xincgc -Xmx1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJAAAA	betterfps{1.0.0} [BetterFps] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	BetterFonts{1.1.3} [BetterFonts] (minecraft.jar) 
	UCHIJAAAA	PaneInTheGlass{1.2.0} [Pane In The Glass CoreMod] (minecraft.jar) 
	UCHIJAAAA	uniskinmod{1.2-dev4} [Universal Skin Mod] (minecraft.jar) 
	UCHIJAAAA	NCE-CORE{1.0.1} [No Creeper Explorsions!] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAA	NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial] ([NEI插件]NEIPlugins-1.1.0.11.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] ([优化]fastcraft-1.21.jar) 
	UCHIJAAAA	D3Core{1.1.0.30} [D3Core] ([依赖]D3Core-1.7.10-1.1.0.30.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.21} [LunatriusCore] ([依赖]LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJAAAA	SlimevoidLib{2.0.4.7} [Slimevoid Library] ([依赖]SlimevoidLibrary-2.0.4.7.jar) 
	UCHIJAAAA	InGameInfoXML{2.8.1.81} [InGame Info XML] ([信息显示]InGameInfoXML-1.7.10-2.8.1.81-universal.jar) 
	UCHIJAAAA	MemoryCleaner{1.0} [Memory Cleaner] ([内存清理]MemoryCleaner-1.4-mc.1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] ([区块载入器]ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	PlaceableTools{1.2.0.33} [PlaceableTools] ([可放置工具]PlaceableTools-1.7.10-1.2.0.33.jar) 
	UCHIJAAAA	utilityworlds{1.0.7} [Utility Worlds] ([实用世界]UtilityWorlds-1.7.10_1.0.7.jar) 
	UCHIJAAAA	ganyssurface{1.12.3} [Gany's Surface] ([实用工具]Ganys Surface-1.12.3.jar) 
	UCHIJAAAA	cfm{3.4.8} [?9MrCrayfish's Furniture Mod] ([家具]MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJAAAA	LittleBlocks{2.2.4.4} [Little Blocks] ([小方块]LittleBlocks-2.2.4.4.jar) 
	UCHIJAAAA	doggytalents{v1.9.0a} [Doggy Talents] ([小狗天才] Doggy Talents - v1.9.0b-CN.zip) 
	UCHIJAAAA	shit{1.3} [Poop Mod] ([屎]shit-1.3_1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.1} [BuildCraft] ([建筑]buildcraft-7.1.1.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.1} [BC Silicon] ([建筑]buildcraft-7.1.1.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.1} [BC Factory] ([建筑]buildcraft-7.1.1.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.1} [BC Robotics] ([建筑]buildcraft-7.1.1.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.1} [BC Builders] ([建筑]buildcraft-7.1.1.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.1} [BC Transport] ([建筑]buildcraft-7.1.1.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.1} [BC Energy] ([建筑]buildcraft-7.1.1.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.0.11} [BuildCraft Compat] ([建筑插件]buildcraft-compat-7.0.11.jar) 
	UCHIJAAAA	mobends{0.20.1} [Mo' Bends] ([弯曲动作]MoBends-0.20.1 for MC 1.7.10.jar) 
	UCHIJAAAA	yarr_cutemobmodels{1.0.9} [Cute Mob Models] ([怪物萌化]yarrcutemobmodels-1.0.9-1.7.10.jar) 
	UCHIJAAAA	zetorches{1.1} [Ze Torches] ([更多火把]Ze Torches Mod 1.3.5.jar) 
	UCHIJAAAA	craft++{1.0} [Craft++] ([更好的MC]Craft-Plus-Plus-Mod-1.7.10.jar) 
	UCHIJAAAA	ComputerCraft{1.74} [ComputerCraft] ([电脑]ComputerCraft1.74.jar) 
	UCHIJAAAA	RWG{Alpha 1.3.2} [Realistic World Gen Alpha] ([真实世界生成]Sub-RWG-alpha-1.3.2.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([依赖]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([砍树]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] ([竹]Bamboo-2.6.8.5.jar) 
	UCHIJAAAA	InfernalMobs{1.5.4} [Infernal Mobs] ([精英怪]InfernalMobs-1.7.10.jar) 
	UCHIJAAAA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([耐久显示]ArmorStatusHUD-client-1.28.jar) 
	UCHIJAAAA	Backpack{2.0.0} [Backpack] ([背包]Backpacks-Mod.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] ([背包整理]InventoryTweaks-1.58-147.jar) 
	UCHIJAAAA	Ding{MC1.7.10} [Ding] ([载入音效]Ding-MC1.7.10.jar) 
	UCHIJAAAA	IronFist{1.3.1} [Iron Fist] ([铁拳]ironfist-1.3.1.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] ([附魔]EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	LotsOfFood{1.7.10} [Lots of Food] ([食物]Lots of Food-1.7.10 v7.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] ([鼠标提示]Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.2} [Waila Harvestability] ([鼠标提示插件]WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJAAAA	IC2{2.2.999} [Industrial Craft Classic] (IC2.Classic.Version.1.0.9.10.jar) 
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GT 240/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [faithful32packOptiFine.zip]
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Speiger** [comment]
Next time please a pastebin.
Simple crash because IC2 Classic was at that version not adjusted to the FluidUpdate from  forge...
It is with the next update that comes out the comming weekend... Saturday or sunday not sure yet... (Which of them)
But it is fixed simply avoid that fluid-o-mat for now. It is the only broken part of IC2 Classic (as far as i know) ^^"
