### ISSUE TITLE
Simplified Chinese translation for IC2.lang

### ISSUE THREAD

**Issue by 4679** [TinyModularThings/IC2Classic#102]
Sorry for my bad english.
I translated this mod to Simplified Chinese.
There is the IC2.lang file.
Hope this will help you.

https://pastebin.mozilla.org/8842518

**Comment by Speiger** [comment]
O.O
Thanks. That is really helpfull.

**Comment by Speiger** [comment]
Just a question, i am done with the update which is coming out next weekend.
If i give you that langfile could you just add the things from that update to that?
Then it would be already up to date^^"
Also your english is good enough :)

**Comment by 4679** [comment]
Sorry,but I am a student in senior grade three.The summer vacation is nearly over.I have no time to do this.Only I can do it when I'm free.

**Comment by Speiger** [comment]
Ok. I am fine with that. No problem^^"
Just ping me if you have time

**Comment by 4679** [comment]
Okay.

**Comment by 4679** [comment]
IC2.lang fir 1.1.0.19 https://pastebin.mozilla.org/8842834

**Comment by Speiger** [comment]
Implementing

**Comment by Speiger** [comment]
@4679 i did a whole redesign on the Lang support. It is no longer a IC2C config it is now a lang file in the asserts folder.
Could you updated it before i release it?

**Comment by 4679** [comment]
Sorry,I'm in the school now.Next weekend,I'm free.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.4.8&pv=7.1.2&source=email_footer_2]
On 周四, 11月 5, 2015 at 6:10, TinyModularThings/IC2Classic
<reply@reply.github.com>
wrote:
@4679 [https://github.com/4679] i did a whole redesign on the Lang support. It is no longer a IC2C config it is
now a lang file in the asserts folder.
Could you updated it before i release it?

—
Reply to this email directly or view it on GitHub
[https://github.com/TinyModularThings/IC2Classic/issues/102#issuecomment-153885096] .[https://github.com/notifications/beacon/AB77RAIfoQv8rnxUoiP4YAYIemw6mL-9ks5pCnm_gaJpZM4FqKuN.gif]
