### ISSUE TITLE
Single-use battery instantly discharges when placed into power input slot

### ISSUE THREAD

**Issue by keenerb** [TinyModularThings/IC2Classic#107]
I'm not 100% sure that is a bug or not, but when I place a single-use battery into the power input slot of a machine or, say, batbox it instantly absorbs the energy.

IC2 Classic Version 1.1.0.19

KCauldron build 152, Forge 1498.

**Comment by keenerb** [comment]
Never mind.  I think it's because the batteries are only 1000 energy so it simply happens extremely quickly rather than instantly.

**Comment by Carbon-Ghost** [comment]
Single use battery, everything in the name, basically a way to use your redstone from renewable farms more efficiently for making more energy, the most accurate description I can give you xD

**Comment by Speiger** [comment]
@keenerb Batteries (not renewable/reloadable) produce 1000 eu in everything that accepts them, but redstone is a special thing: it produces 500 EU but in machines they fill up the entire storage^^. Keep that in mind.
