### ISSUE TITLE
Buildcraft Gate Triggers

### ISSUE THREAD

**Issue by LuigiHutch** [TinyModularThings/IC2Classic#108]
IC2 Classic 1.1.0.19
BC 7.0.20

Request: Add the Buildcraft gate triggers that were in IC2 and are currently in IC2 exp. They are quite useful :)

  -LuigiHutch

**Comment by Speiger** [comment]
Ok. I will do that. Could you provide me with textures?

**Comment by LuigiHutch** [comment]
How should i do that? I am no texture artist :p

**Comment by Speiger** [comment]
^^Me either... But i will find a way^^

**Comment by Carbon-Ghost** [comment]
Me = A way, what textures do you need :P

**Comment by Speiger** [comment]
I found (thanks to IC2s really old download) a texture file that is really helpfull^^"
But adding BC support will be hard. Ill try my best... xD

**Comment by Speiger** [comment]
released
