### ISSUE TITLE
ConcurrentModificationException crash when machine is placed next to MFE (and explodes) and issue with placing MFE after explosion

### ISSUE THREAD

**Issue by Nentify** [TinyModularThings/IC2Classic#109]
Video: http://i.nentify.me/AZGKYF8z.mp4

Crash report: http://pastebin.com/ZepKZ7NH

If you place an MFE next to a generator after an explosion, the MFE doesn't fill.

Not all the time, but frequently when you make a machine explode with generator -> MFE -> machine, you get a CME crash.

This is all in SSP with Forge 1490 and IC2 Classic 1.1.0.19

**Comment by Carbon-Ghost** [comment]
That's a very weird bug...

**Comment by Speiger** [comment]
Lool a generator should not be able to explode a MFE @Nentify how did you do that? Configs?
And yeah i already know whats causing it not really sure how to solve it with keeping the feature...

**Comment by Nentify** [comment]
This is a fresh install of the mod, so whatever the default config is. I assumed the furnace explosion caused the MFE to explode too. ;P

**Comment by Carbon-Ghost** [comment]
I am the Easy net tester, so I wasn't aware of that bug, Choco is more the one who tests by default stuff ^^

**Comment by Speiger** [comment]
Ok MFE should be capable of 128 EU per tick flowing input the generator produces 10 EU per tick there is something weird... I think that feature has to leave..

**Comment by Carbon-Ghost** [comment]
Feature ? What feature, it looks like more like A FUCKING MAJOR BUG xD ( like the BFG in Doom ^^ ). 

But more srsly, this one is important :O

**Comment by Speiger** [comment]
The feature of Threaded Enet which should throw the lag not on the World which would have a better performance... That feature has to leave sadly...

**Comment by Carbon-Ghost** [comment]
But I don't understand the bug, does this mean that E-net won't work ever again ?

**Comment by Nentify** [comment]
Ahh.. Threads, aha. That's a shame, hopefully the enet isn't too intensive. Threads are a blessing and a curse. ;P

**Comment by Carbon-Ghost** [comment]
But that's... Very strange...  We need to do something, because that's... Broken as fuck O.o, But I don't understand, what the hell causes this ?

**Comment by Carbon-Ghost** [comment]
Like, the explosion shouldn't be happening....

**Comment by Nentify** [comment]
The furnace should explode (I think), because it's being powered by an MFE.

**Comment by Carbon-Ghost** [comment]
yes, but why does the MFE goes BOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOM O.o

**Comment by Nentify** [comment]
I assume from what Speiger says, currently the energy net is threaded (calculations done outside of the main thread - can provide very good performance improvements). However, threading can be difficult to implement well and you can often get situations where the main thread and the energy net thread don't communicate properly. I assume this may be part of the reason these oddities occur. (ConcurrentModificationException - 2 things, eg the enet thread and main thread trying to modify the same thing at the same time).

**Comment by Carbon-Ghost** [comment]
Yes, but that should happen... Sigh, glad that at least it's working on the easy mode side ^^

**Comment by Speiger** [comment]
@Carbon-Ghost @Nentify is right but i am synchronizing the threads to each other but the thing is that the FMLASM thing come into place so we have 3 things interacting with each other and that is a real problem... Anyway with the next update no longer Threaded Enet i will find another way to solve this problem but it should improve for servers^^

**Comment by Carbon-Ghost** [comment]
Well ok :/

**Comment by Speiger** [comment]
Changed the Enet to NoneThreaded now so Testers need only to test if everything is fine and then we can talk if there is no problem anymore^^"

**Comment by Carbon-Ghost** [comment]
gonna test it asap, waiting for a alpha stable version of GT reborn classic ^^

**Comment by Speiger** [comment]
Fixed
