### ISSUE TITLE
IC2 Easy Mode

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#11]
This mode allows people to build IC2 Energy Systems without exploding machines.
Machines but will only accept power if they do not get overcharged.

Some more additions for an easy IC2 Mode just post them here..

**Comment by Carbon-Ghost** [comment]
So far here are the bugs : 

-No power loss in cables
-The OverCharged mechanic is broken

**Comment by Speiger** [comment]
Thanks

**Comment by Speiger** [comment]
Ok did fix it^^"

**Comment by Carbon-Ghost** [comment]
Nice, you fixed power loss and overcharged ? :D

**Comment by Speiger** [comment]
Yup. The Overcharge took me a couple hours. I made everything right but instead of just saying you added nothing to the machine i had to say skip it... (there is a difference because he would loop so long until he added energy which was also a lag provider)

**Comment by Speiger** [comment]
Fixed: EnergyLoss is happening now and also how it should be...
Added: Cables do no longer melt down if the powerflow is to high.
Added: Cables do only send so much power that they are capable of. So overcharging cables and it will stop working.

**Comment by Speiger** [comment]
Plans:
Changing Config so that you can choose what has easy Mode and what not.
Also thinking of making an easy mode for crops...

**Comment by Carbon-Ghost** [comment]
Then, there isn't going to be real easy mode anymore, you would have choice with Machine explosion and cable melting, the first resulting to not accept power when overflowing, but the second can still melt. 

As for crops, what about adding copper and tin crops ? They would work exactly like the ferru one, just requiring a copper block underneath ^.^

But imo, don't add easy mode crops, they are already OP like it's not even possible xD

Adding a config for mass fabricator uu matter energy requirement would be nice though. 

Last thing that would also be cool, but I didn't figured out how to do it is to add bauble batteries and a .js config file to add armor that you want to use as an eu generator, so they can recharge your Tools, by putting the localisation, and the condition to generate eu and the amount. 

Also, bug : IC2 foam system doesn't work at all :/

**Comment by Speiger** [comment]
@Carbon-Ghost 
to the IC2 Foam i know that already and i will work on that. tomorrow. Today my day is already over.
Ok you have a point there in the Config. So that idea is canceld.

Adding Tin&Copper crops hmmm. well you can generate Tin&Copper through UU Matter really cheap, also scrapboxes you gain a tone of it over 1 day with a good scrapproducer (20-40 stacks),
I am not sure about that. Maybe...

Config for massfab nope. 1Mio EU for 1 UUMatter is totally ok. And if you want to have less than just add scrap or scrapboxes to it that will decrease it to 100k EU per UU.

A sending system will not exsist (performance reason) but the requesting system already exsist i can make a baubles addition to it. So you can put a Battery or something in there and it will drain from there too. Generator well... I have there already ideas but that would not fit in IC2 at all...
The only thing that i will maybe add will be a Nuclear Jetpack that you can fill with Uran to power it.
But that is the max addition i will add. I try to stay at the classic and try to move not so far away...
Thats a thing i keep always in mind..

**Comment by Carbon-Ghost** [comment]
Speiger,  I didn't wanted a config for uu matter to decrease the eu cost, BUT TO INCREASE IT xD

**Comment by Speiger** [comment]
Maybe general energy scale config for consumers (>=1)?

**Comment by Carbon-Ghost** [comment]
+1, do that, so I can set it to 10 :D ( for balance purposes ).

**Comment by Speiger** [comment]
Well the tiers of the machines get not effected by that. So a machine that uses 8 eu uses than 80 EU and you can only power 32 EU per tick in it...
And reason why i do not the tier get effected by that is because of  multipackets. If NuclearControll makes the Transformer compatible to my version then you can turn 8K EU in 8K eu but with 1 EU packets xD

**Comment by Carbon-Ghost** [comment]
Lol, it will be universal uber voltage xD

And I know that the tiers will not get affected by that, I played IC2 before experimental after all xD

**Comment by Carbon-Ghost** [comment]
Which had packets, unlike experimental, so for exemple you could set a quantum generator to output 100 000 eu/tick in 1 eu/packets :D

**Comment by Speiger** [comment]
Em yeah the Packet option with the Quantum generator is only a fake... The button exsist and the thing remebers it but thats it, it does not effect things at all.
So if you send 100K Eu through 100k packets you only send 100K EU through 1 Packet which will make every machine from IC2 Classic explode instantly...
Since IC2 Classic has a PacketAPI they can actually make the packet system work....

**Comment by Carbon-Ghost** [comment]
I mean't the old 1.4.7 Q-generator xD

I don't play with Advanced solar panels since 1.5.2 ;P

**Comment by Speiger** [comment]
XD ok. Just wanted to tell that the thing is since 1.6.4 a fake with the packetsystem.

**Comment by Speiger** [comment]
Seem stable so closed.
