### ISSUE TITLE
Change the assets path

### ISSUE THREAD

**Issue by Xen1290** [TinyModularThings/IC2Classic#111]
Hi @Speiger ,
As title says, if possible, change the textures path from ic2 to ic2classic or similar, this avoid some issues with texture packs that support both mods in the same pack.

**Comment by Speiger** [comment]
@Xen1290 no that is sadly not possible. Reason beeing that this require a modID which is IC2...
But exept for guis all textures are in differend places anyway so there can  be no conflicts.
But i will merge the guis in another folder which is not clamed by IC2 Exp.^^"

**Comment by Xen1290** [comment]
Thanks!

**Comment by Speiger** [comment]
@Xen1290 i did change now the GuiTextures from textures/gui to textures/guiSprites. That means no longer any conflict with that. I checked everything else. It is fine. So you can start working on the TexturePack if you want i have everything ready.

Little note: You have to keep 16x16 icon textures. Pixels can be like mc handles it, but it has to be always like the textures that. (So a 32x32 pixels Texture file has to be 16*32x16*32)

**Comment by Xen1290** [comment]
Thanks @Speiger !
