### ISSUE TITLE
[1.19.2) Miner with Quarry Scanner is Stuck...on it's own Mining Pipe?

### ISSUE THREAD

**Issue by Geekerandy** [TinyModularThings/IC2Classic#1112]
In the linked video, I have a: 
-Miner with a Mining Laser (also was reproduced with a Diamond Drill) 
-A 12-block range Quarry Scanner (also tested with an upgraded Quarry Scanner at 64 blocks)
-64 Mining Pipe
-A tube
-A chest for the tube
https://youtu.be/DZg5C8tGAmk

After mining 6 blocks (the initial "+" and 1 block) on one layer, the Miner will then proceed to be Stuck, highlighting its own Mining Pipe as what it appears to be stuck on.

**Comment by DmitryProskurin** [comment]
Looks like quarry scanner issue, with scanner of different type it works fine.
