### ISSUE TITLE
Industrial worktable eats held stack of items when press Save button

### ISSUE THREAD

**Issue by DmitryProskurin** [TinyModularThings/IC2Classic#1113]
IC2 Classic 2.0.9
MC 1.19.2

https://github.com/TinyModularThings/IC2Classic/assets/14220482/cc021f62-1342-43b0-b373-a21815c62007

Also, if i close workbench gui after Save button is pressed(craftable item on cursor), items were held before also disappear.

**Comment by DmitryProskurin** [comment]
@Speiger, i made modpack without Refined Storage and AE2(IC2 Classis is core), so industrial worktable is only one option for me.
I want Request Logistics Pipe from Logistic pipes 😒

**Comment by Speiger** [comment]
fixed
