### ISSUE TITLE
[1.19.2] Random Server Crash #1

### ISSUE THREAD

**Issue by ObscuriaLithium** [TinyModularThings/IC2Classic#1118]
The public server randomly crashes during the game
IC2 Classic 2.0.9.1, Forge 1.19.2-43.3.8

[crash-2024-03-11_19.51.25-server.txt](https://github.com/TinyModularThings/IC2Classic/files/14576785/crash-2024-03-11_19.51.25-server.txt)
[crash-2024-03-12_17.25.33-server.txt](https://github.com/TinyModularThings/IC2Classic/files/14576787/crash-2024-03-12_17.25.33-server.txt)

**Comment by Speiger** [comment]
@ObscuriaLithium looks more like an issue with the pack.
It basically states: The reactor or  the energy net is not allowed to request chunks. 
Even so it should be allowed to. It is a vanilla mechanic after all.

Unless you can reproduce this exact issue with vanilla+forge+ic2c itself, i am pretty sure IC2Classic isn't at fault.
