### ISSUE TITLE
[1.7.10] Breeder reactor turns Depleted NetherStar Isotope cells into Re-enriched Uranium cells

### ISSUE THREAD

**Issue by flawedworld** [TinyModularThings/IC2Classic#1121]
Hi! Unsure if this is a bug, I'm fairly sure it is though. If it is not, then I am sorry for wasting your time.

Below is a screenshot of my breeder design. I placed Depleted NetherStar Isotope cells next to my Uranium cells.

![image](https://github.com/TinyModularThings/IC2Classic/assets/38294951/b4bac3fc-71f9-44ee-835d-62f2ebdf8827)

And here is an "after" screenshot where they turned into Re-enriched Uranium cells

![image](https://github.com/TinyModularThings/IC2Classic/assets/38294951/6b7bfd84-a0b7-41c8-95d0-5049ea872f9f)

Forge: 10.13.4.1614
IC2C: IC2Classic-1.7.10-1.2.4.jar

**Comment by Speiger** [comment]
Thank you.
I can't promise that i can fix this bug in a relative time because I have a extremely busy time period coming up.
So it might take like a couple months before this is patched.

But it will get patched with the next patch.
TY

**Comment by flawedworld** [comment]
Absolutely not a problem. Thank you for maintaining my favourite mod in Minecraft :)
