### ISSUE TITLE
[1.19.2] How exactly works the filter pipe?

### ISSUE THREAD

**Issue by Maburillo** [TinyModularThings/IC2Classic#1123]
In Buildcraft the filter pipe works different. If you're putting the diamond (for example) in red direction, then in this direction will go ONLY diamonds. In your mod all the items can go in that direction, unless you configure ALL other items to go anywhere else. I don't understand, how can i configure the filter pipe, so all the different items, except diamonds (for example), go elsewhere. Should i block the red diamond route for every item one by one?

**Comment by Maburillo** [comment]
Thank you! I didn't realize at first that these buttons (on the screenshot) works for a non defined items.
![P](https://github.com/TinyModularThings/IC2Classic/assets/163580571/1e414762-0497-440e-978e-055067c7d17e)

**Comment by Speiger** [comment]
@Maburillo it even states it in the tooltip :)
