### ISSUE TITLE
 Can't build a IC2

### ISSUE THREAD

**Issue by Alpha012** [TinyModularThings/IC2Classic#1126]
Gives an error with a reason "compileJava'
How i can build IC2, and how can i change version, 1.19.4 for example, or this is impossible?

**Comment by Speiger** [comment]
@Alpha012 the Sourcecode on github is just the API.

**Comment by Alpha012** [comment]
> @Alpha012 the Sourcecode on github is just the API.

Will industrial be updated to 1.19.4 or not?

**Comment by Speiger** [comment]
@Alpha012 the next version will be announced once it is ready to be played :)
I am not giving any commitments until its ready :)
