### ISSUE TITLE
[1.19.2] 2.0.8.1 Terraformer doesn't replace game-placed blocks, only self-placed blocks

### ISSUE THREAD

**Issue by Venia04** [TinyModularThings/IC2Classic#1128]
Biome blueprints work as expected, changing the biome (weather, colors, mob spawning).
But regular blueprints like Cultivation, don't work on blocks that are formed by world generation. Blocks that i've placed myself - are replaced, as expected.
So i can't complete the achievement with terraforming The End into Plains

**Comment by Speiger** [comment]
@Venia04 terraformer only replaces very specific blocks.
There are only a few blocks they replace. That means it will not replace most player placed blocks.

This is not a bug due to the nature of the terraformer.
