### ISSUE TITLE
[1.12.2] Recipe for Fortune III diamond drill doesn't seem to work

### ISSUE THREAD

**Issue by 1chan-level-journalist** [TinyModularThings/IC2Classic#1129]
I have all the necessary ingredients, but nothing happens.
![screen](https://github.com/TinyModularThings/IC2Classic/assets/16210758/1a0da730-1c96-4238-94a4-b6590818e73e)
Is there something I'm missing?

**Comment by DmitryProskurin** [comment]
@1chan-level-journalist you need number of some items
![image](https://github.com/TinyModularThings/IC2Classic/assets/14220482/69c79492-b927-4d8f-946f-c91dc58f604c)
