### ISSUE TITLE
[1.19.2]Electrolyzer on IC2Classic does not work!!

### ISSUE THREAD

**Issue by shishen575** [TinyModularThings/IC2Classic#1131]
No cable connection to Electrolyzer!!!
↓For Electrolyzer.
![2024-03-27_14 24 38](https://github.com/TinyModularThings/IC2Classic/assets/120293634/80dd3058-ca5a-455d-8a4d-945ba46a71c8)
↓For Electric furnace.
![2024-03-27_14 27 19](https://github.com/TinyModularThings/IC2Classic/assets/120293634/d76bd06b-4d77-4afb-a7a3-f30efdefdcfa)
Please fix this!

**Comment by CrossVas** [comment]
Electrolyzer doesn't need direct cable connection. 
To get it work it needs to be placed next to an energy storage block: `BatBox`, `MFE`, `MFSU`, etc. the bigger energy storage capacity, the better.

![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/35115acd-c825-48f2-b38e-01a9ea875fb3)

**Comment by shishen575** [comment]
20000EUis in the MFSU but cannot magnet...

**Comment by shishen575** [comment]
![2024-03-27_14 40 00](https://github.com/TinyModularThings/IC2Classic/assets/120293634/818b69c6-016c-47c6-9581-7762b2b00d1b)

**Comment by CrossVas** [comment]
> 20000EUis in the MFSU but cannot magnet...

The storage level needs to be around 85% and higher.

**Comment by shishen575** [comment]
I was wrong. I'm sorry.

**Comment by bakebread000** [comment]
I ask this question here because it is a similar topic. Ocean Wave does not work in my environment. When I place it on the bottom of the ocean, it does not show a pattern like the Wave Generator. Does the direction of installation, other machinery, or biome matter in order to make it function?
![2024-03-27_15 09 40](https://github.com/TinyModularThings/IC2Classic/assets/163288788/a1bbbc11-143f-491e-8364-626b3cc4969d)

**Comment by CrossVas** [comment]
> I ask this question here because it is a similar topic. Ocean Wave does not work in my environment. When I place it on the bottom of the ocean, it does not show a pattern like the Wave Generator. Does the direction of installation, other machinery, or biome matter in order to make it function? ![2024-03-27_15 09 40](https://private-user-images.githubusercontent.com/163288788/317149810-a1bbbc11-143f-491e-8364-626b3cc4969d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjAyOTcsIm5iZiI6MTcxMTUxOTk5NywicGF0aCI6Ii8xNjMyODg3ODgvMzE3MTQ5ODEwLWExYmJiYzExLTE0M2YtNDkxZS04MzY0LTYyNmIzY2M0OTY5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNjEzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzFkOTk3ZTc4NjNiZmE4OTYyNzU2MDUyYWJkMTE5MzczOGJjM2RiMmMzYTkyNjBiNjlhNGVhMTBkOTY5NGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lAkhQvOi4uc7tTyxMPxlONTPES5EC_FShntaipIaTxI)

This isn't related to the topic, but I'll answer anyway. I guess you meant to ask about `Ocean Generator`
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/4caf3f1d-eabf-4c95-85fa-dbb32a26277e)
Here is the wiki page. 
This means that `Ocean Generator` only generates power when at least 26 blocks of Coral are present.

**Comment by shishen575** [comment]
Tighten the Issue.
Thank you for your response
