### ISSUE TITLE
[1.19.2] signed 32-bit integer overflow limit for fluid Tank 

### ISSUE THREAD

**Issue by Geekerandy** [TinyModularThings/IC2Classic#1132]
Dunno what happens if it fills up past 2.147billion mB of fluid.
Caused by making the tank so large it's maximum capacity goes past the limit.
![image](https://github.com/TinyModularThings/IC2Classic/assets/14936715/4c6ade5e-da53-426b-a6ac-310232a143cb)

**Comment by Speiger** [comment]
Intentional.
Not a bug
