### ISSUE TITLE
[1.19.2] Improve documentation of insulation effects

### ISSUE THREAD

**Issue by BurningEnlightenment** [TinyModularThings/IC2Classic#1136]
Thank you for porting to newer Minecraft versions and supporting this old gem; brings back good old memories :)

Can you improve the documentation of cable insulation? Specifically its effect on "resistance" losses over cable length as there is quite a bit outdated information on the internet, it would help to get a definitive statement into the in-game wiki. Additionally it would be nice to have a comprehensive table (like [this one on the old IC2 wiki](https://wiki.industrial-craft.net/index.php?title=Cable#Cable_Efficiency)) somewhere.

Thanks!

**Comment by Geekerandy** [comment]
EU Reader in game.

**Comment by BurningEnlightenment** [comment]
> EU Reader in game.

Sure, I can find those values by experimenting, but given that there is a chance that the wrench eats the machines used during experimentation, I'd like to skip that part. I also think that this would make the topic a bit more accessible to newcomers.

**Comment by Speiger** [comment]
@BurningEnlightenment no he literally means the eureader in-game.

Go to your jei/REI or any item Lister. Search for ic2 cables and have a EU reader in your hotbar/helmet.

It will show you all values directly in-game that you need. That also includes machine info.

It's no table on a website but it's still all accessible to you :)
In a fast way

**Comment by BurningEnlightenment** [comment]
Ah, that sounds nice. My only nitpick would be that IIRC the EU Reader is gated behind a nether trip due to the glowstone. In my case I've been preplanning my workspace area beforehands and I got confused due to the somewhat spotty information in the in-game wiki. So maybe I'll compile a spreadsheet later on and share it here. Thanks!

**Comment by Speiger** [comment]
@BurningEnlightenment maybe its locked behing the nether, maybe it's not.
I wonder if ic2c has some secrets that could help with that xD

(I did implement a few knowledge features that can be helpful only if you know them)
