### ISSUE TITLE
IC2 cllassic Crash with Everlasting.

### ISSUE THREAD

**Issue by Periam** [TinyModularThings/IC2Classic#1137]
After installed the latest version of IC2 the same crashed with Everlasting mod.
I downgraded the same several version and still crashed.

I saw a closed post about a similar crash.

I only installed IC2, Everlasting and their dependencies. 

curios-forge-1.19.2-5.1.6.1
CyclopsCore-1.19.2-1.19.0
EverlastingAbilities-1.19.2-2.1.2
IC2Classic-1.19.2-2.0.9.2
theoneprobe-1.19-6.2.2.

[crash-2024-04-04_11.24.16-fml.txt](https://github.com/TinyModularThings/IC2Classic/files/14872689/crash-2024-04-04_11.24.16-fml.txt)

**Comment by Speiger** [comment]
Ever lasting abilities basically requires a client world to exist for creative search to work.

Which is a function that has 0 world access in its function.
In other words not a ic2c bug when it is using that to generate accurate item caches on startup
