### ISSUE TITLE
Visual error: Construction foam covered tubes still act as transparent block.

### ISSUE THREAD

**Issue by AstoriaFloyd** [TinyModularThings/IC2Classic#1138]
Construction foam covered tubes, despite the fact they should appear identical to true construction foam blocks, are in fact still transparent, which leads to certain... oddities.
1. They let light through the wall, which can lead to confusing lighting if you are hiding pipes for logistics, such as letting outside light in or inside light out
2. They have no ambient occlusion, leading to distinct, visually confusing hard boundaries where lighting is brighter than it should be

Oddly, it appears this was already solved for wires, as they work as expected. May be a simple fix?

**Comment by Speiger** [comment]
@AstoriaFloyd a technical limitation of the minecraft engine.
Not a bug

**Comment by AstoriaFloyd** [comment]
@Speiger Why do wires have ambient occlusion then? Even glass fiber cables, which have transparency, render correctly when foamed. The difference between pipes and wires is distinct.
![2024-04-04_17 00 49](https://github.com/TinyModularThings/IC2Classic/assets/39976417/6e786c8c-1aff-45b8-a0b4-3cb786e306d1)
