### ISSUE TITLE
Compressor Blazerod

### ISSUE THREAD

**Issue by dustojnikhummer** [TinyModularThings/IC2Classic#114]
Feature request.
Please add option to make blazerods from 5 powders in compressor. Same receipe as in IC2 Experimental.w (usable with TE4 to make rods)

**Comment by Speiger** [comment]
@dustojnikhummer that does not get a config option. But i will throw a lot of new Recipes in anyway^^" Just so you know.

**Comment by Speiger** [comment]
Closed. Because not nessesary. Its planed anyway.

**Comment by Carbon-Ghost** [comment]
No config now cause Modtweaker I guess ? :D

**Comment by Speiger** [comment]
@Carbon-Ghost no the reason simply is that i implement it anyways and it will be a full part of IC2 Classic so there is no config need.
