### ISSUE TITLE
HV Solar Array Recipe Bug

### ISSUE THREAD

**Issue by Red8567** [TinyModularThings/IC2Classic#1140]
The HV Solar array requires a IV transformer instead of a HV transformer. If this is a balance change though sorry for the trouble
![craft 2](https://github.com/TinyModularThings/IC2Classic/assets/134241377/f394b38b-7318-47b4-97bb-b740f5d17a37)
![craft 1](https://github.com/TinyModularThings/IC2Classic/assets/134241377/1c492ce2-502e-4392-8d1c-25f2a8b6a8a7)

**Comment by Geekerandy** [comment]
Intentional. See Issue #962 for reasons.

**Comment by Geekerandy** [comment]
However, if you want to change it, you can create a custom recipe with a Datapack. https://github.com/TinyModularThings/IC2Classic/wiki/How-to-add-custom-Recipes

**Comment by Red8567** [comment]
Ahh ok thanks.
