### ISSUE TITLE
Any plans for 1.20.1 or 1.20.4?

### ISSUE THREAD

**Issue by millennIumAMbiguity** [TinyModularThings/IC2Classic#1143]
Are there any plans to update this mod for Minecraft versions 1.20.1 or 1.20.4?
This mod would be a great combo for Nostalgic Tweaks! (they are currently on 1.20.1 but will migrate to 1.20.4 soon; and they don't appear to update old versions)

**Comment by Speiger** [comment]
These types of questions are not answered until the build is already in beta or about to do its beta test.

So no comment
