### ISSUE TITLE
[1.19.2] GUI scale changes after reading the wiki book

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#1145]
GUI scale above or equal to 3 changes to 2 after reading the wiki book in windowed mode.

To reproduce:
- set the gui scale (in my case I use GUI scale 3)
- set minecraft in windowed mode (not fullscreen windowed)
- open the wiki book
- go full screen windowed and see that the gui scale has changed.

Video:

https://github.com/TinyModularThings/IC2Classic/assets/25727222/9dacafbe-bfef-49c7-a0ba-48f35a2d6050

**Comment by Speiger** [comment]
@CrossVas that happens due to everytime the screen is changing the gui being reset...
Its a real problem with minecrafts guis...
