### ISSUE TITLE
Prevent opening fullscreen map mod with button `m` on keyboard

### ISSUE THREAD

**Issue by yifanplanet** [TinyModularThings/IC2Classic#1148]
It's blocking opening fullscreen map mod with button `m` on keyboard. 
One example is using [Xaero's World Map for Forge 1.19.2](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/files/5262411)

**Comment by CrossVas** [comment]
This can be easily changed in `Options - Controls - Key Binds` menu. Just map it to something else, the issue should be gone. Same works for any mod.
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/6c418d18-6e69-46b1-9c9b-a5b1f843da06)

**Comment by yifanplanet** [comment]
@CrossVas Ahh I'm just stupid. Thanks! 

But why would we have default key bindings to `m` though

**Comment by CrossVas** [comment]
> @CrossVas Ahh I'm just stupid. Thanks!
> 
> But why would we have default key bindings to `m` though

This was the default key since it got introduced, i.e. LONG time ago, way before maps and other mods were released.
