### ISSUE TITLE
RandomThings 2.2.4 issue with IndustrialCraft Classic (newest) cannot create singleplayer world.

### ISSUE THREAD

**Issue by VenomFrog** [TinyModularThings/IC2Classic#115]
Creating singleplayer world (upon clicking Create) boots you back to the menu. It creates the world (if you check the \saves\ folder, its there) 

It then makes a second java platform SE Platform that runs in the background.

**Comment by VenomFrog** [comment]
I feel dumb, i submitted and googled, it was mod ID conflict with compact machines. Nevermind D:

**Comment by Speiger** [comment]
oh ok

**Comment by Speiger** [comment]
@VenomFrog never Change it. Its important that these things keep documented!

**Comment by VenomFrog** [comment]
Oh okay, I'm sorry. I changed it because it wasn't even related to IC2!

On Friday, September 25, 2015, Speiger <notifications@github.com> wrote:

> @VenomFrog <https://github.com/VenomFrog> never Change it. Its important
> that these things keep documented!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TinyModularThings/IC2Classic/issues/115#issuecomment-143394991>
> .
>


-- 
~Hudson Doerr
