### ISSUE TITLE
[1.12.2] EU-Reader bug with dedicated server -> singleplayer

### ISSUE THREAD

**Issue by xJon** [TinyModularThings/IC2Classic#1152]
1. Launch the game
2. Enter dedicated server (do nothing, don't have an EU-Reader)
3. Enter singleplayer world, get EU-Reader
4. No tooltips are shown

Reproducible with just IC2 Classic installed.

(Hours of troubleshooting)

**Comment by xJon** [comment]
- If you get an EU-Reader in the server within the same session, the bug won't occur.
- If you enter a singleplayer world upon launch, the bug won't occur.
- If you afterwards enter a server and get an EU-Reader then go back to singleplayer, the bug won't occur.

**Comment by Speiger** [comment]
Yeah ok. I know what happens.
Basically there is a Playerhandler inside of ic2c iirc even in 1.12.2

And that isn't properly split in 1.12.2 and pollutes the state in MP vs SP...

Ugh yeah I will address that with the next patch.

But the next patch is a bit far away and you might want to distribute the previous patch first
