### ISSUE TITLE
[1.19.2] Intended? Component Heat Vent works on Condensators

### ISSUE THREAD

**Issue by Geekerandy** [TinyModularThings/IC2Classic#1153]
IC2Classic-1.19.2-2.0.9.2.jar
Whether in a Reactor Planner, Nuclear Reactor, or Steam Reactor, both Condensators can be cooled by Component Heat Vents.
Since the nature of Condensators is that heat cannot be taken out of them because lore-wise, they're chemical cold packs, and thus their "fuel" must be replaced with redstone/lapis, this behavior seems unintended.
It's not like this is particularly game-breaking, as the cooling is far too slow compared to the setups people use Condensators with, even if they super-speed the cooling process by using a Steam Reactor.

**Comment by Speiger** [comment]
Nah this is intended behavior and works in all MC versions
