### ISSUE TITLE
[1.19.2] Game/Server crashing when using Ruberwood boats

### ISSUE THREAD

**Issue by edukny94** [TinyModularThings/IC2Classic#1154]
So pretty much title.

After a few days off I found my server off and it was related to someone using a Ruberwood boat and I could recreate the crash by myself again.

I don't know too much about modding but it's something related with the mod "It Shall Not Tick" and the "ic2:ruberwood_boat".

As far I know that mod is not suported anymore so... you guys are my only hope.

I got two logs (one from the server, another from client side).

**Server crash log.**

[crash-2024-04-28_20.53.49-server.txt](https://github.com/TinyModularThings/IC2Classic/files/15143753/crash-2024-04-28_20.53.49-server.txt)

**Client crash log.**

[crash-2024-04-28_22.53.51-client.txt](https://github.com/TinyModularThings/IC2Classic/files/15143746/crash-2024-04-28_22.53.51-client.txt)

**Comment by Speiger** [comment]
@edukny94 
Please reproduce this issue with just IC2Classic.
Because IC2Classic just uses the Boat internal logic and doesn't change the logic at all to this extend.

This is in 99.99999% of the case caused by another mod.
Even forge assumes it is not IC2Classic at fault.

**Comment by edukny94** [comment]
Not happening with just IC2Classic, @Speiger.

I think you can close this, I'm gonna do something with that.
