### ISSUE TITLE
IC2 1.19.2 forge crash by monitors

### ISSUE THREAD

**Issue by NnutT1980** [TinyModularThings/IC2Classic#1156]
![image](https://github.com/TinyModularThings/IC2Classic/assets/117589405/a1163b47-b879-460a-a51b-50a0d651fddc)
If you make a large (or not very large) monitor and try to twist it, your game will die, a small monitor of 40 blocks on the server was able to turn it off for about 3-4 hours.

**Comment by Speiger** [comment]
Please provide an crash log.
