### ISSUE TITLE
IC2 1.19.2 unlimited amount of energy in nanofiber or quantum armor

### ISSUE THREAD

**Issue by NnutT1980** [TinyModularThings/IC2Classic#1157]
if you put any part of nanofiber or quantum armor into the armor configurator and try to put a crystal into the crystal slot using the middle mouse button from the inventory, the crystal will ignore the fact that there is already a crystal in its slot and rely on it, you can do this indefinitely crystals cannot be removed

**Comment by Speiger** [comment]
@NnutT1980 i would need a video clip to show what you did because i can't reproduce it.
