### ISSUE TITLE
Export upgrade and Miner dupe bug

### ISSUE THREAD

**Issue by nigraforce** [TinyModularThings/IC2Classic#116]
Machines with export upgrade will duplicate items in the inventory they are supposed to export to for the cost of the processed material. 
Miner will do the same for the cost of nothing, or the ore that it mines. I had a miner duplicate cobblestone when it was mining tin and copper ore.
![2015-09-21_00 02 31](https://cloud.githubusercontent.com/assets/9677869/9982404/c69d2f9a-5ff4-11e5-9e34-9713c0c6cd15.png)
![2015-09-21_00 02 40](https://cloud.githubusercontent.com/assets/9677869/9982402/c66dd826-5ff4-11e5-83c3-59dcd7bbd1a4.png)
![2015-09-21_00 02 45](https://cloud.githubusercontent.com/assets/9677869/9982403/c670793c-5ff4-11e5-83a9-b1a61df7577b.png)

I was playing on my server when I found that.

Mod list:
![image](https://cloud.githubusercontent.com/assets/9677869/9982419/32e6150e-5ff5-11e5-95eb-55fbe35dfe02.png)

**Comment by Speiger** [comment]
thanks i will work on that now.

**Comment by Speiger** [comment]
Fixed

**Comment by Speiger** [comment]
It was a dep bug by the way. I check: is the Item a with the Item b equal (and i made it is Item a with Item a Equal)
