### ISSUE TITLE
[IC2C 2.0.9.2]The rocket miner will get stuck in lily pad

### ISSUE THREAD

**Issue by IR8104** [TinyModularThings/IC2Classic#1160]
When the rocket miner flies to the next location, if there is a lily pad at the drop location, then the miner will get stuck in the lily pad and cannot be turned into a machine.

**Comment by Geekerandy** [comment]
Haven’t reproduced this yet, but to get around this, either destroy the lilypad or wrench the Rocket Miner entity itself.

**Comment by IR8104** [comment]
> Haven’t reproduced this yet, but to get around this, either destroy the lilypad or wrench the Rocket Miner entity itself.

Hope the miner doesn't fly into the Swamp.

**Comment by Speiger** [comment]
@IR8104 the likelyhood that the miner lands on a lilipad is astonomically low ^^"
but yeah i can look at it

**Comment by Geekerandy** [comment]
In the meantime, I did reproduce the glitch for redundancy.
Forge 1.19.2, version 43.3.8
IC2 Classic version 2.0.9.2
https://youtu.be/qZXygmZ9PeI

**Comment by Kellien** [comment]
у меня ракетный шахтер залезает в воду, и стоит пока не потратит всю энергию, потом возвращается на базу, его заряжают и он повторяет это снова... проблема в том, что базу окружает огромный океан с небольшими островами, при исследованиях примерно 2000 блоков вокруг базы есть только небольшие острова, так что если он застрянет в воде из-за бага, то для меня это критично

**Comment by Speiger** [comment]
@Kellien i can't read that

**Comment by il-an** [comment]
he said the rocket miner flies into water and stands there until all energy depleted, then returns to the base, is recharged, and does all of that again.
