### ISSUE TITLE
[IC2C 2.0.9.2]Electric Minecart Loader texture problem

### ISSUE THREAD

**Issue by IR8104** [TinyModularThings/IC2Classic#1161]
![2048](https://github.com/TinyModularThings/IC2Classic/assets/29350643/9da619f9-d5fa-4f13-88a4-43f22e52d270)
![512](https://github.com/TinyModularThings/IC2Classic/assets/29350643/2e3ca0cf-5ece-4b37-a1c8-43de724cd46c)

The HV and EV Electric Minecart Loader textures are reversed, HV should be red and EV should be yellow.

**Comment by Speiger** [comment]
will be addressed next patch
