### ISSUE TITLE
[IC2C 2.0.9.2]Cannot select the single slot to set the machine access control in the Nuclear reactor.

### ISSUE THREAD

**Issue by IR8104** [TinyModularThings/IC2Classic#1162]
All the machines could set the machine access control for the slots, but nuclear reactor cannot, I could only set the entire machine and cannot select any slots to set the inventory settings. The same things are happened in steam reactor.

**Comment by Speiger** [comment]
It is intentional due to the nature of the reactor being a dynamic inventory.

This simply can not be changed ^^"
