### ISSUE TITLE
[IC2 1.19.2] Problem with miner and nano saber

### ISSUE THREAD

**Issue by Ullimunate** [TinyModularThings/IC2Classic#1163]
Hello, the problem is that my rocket miner does not mine: Uranium, tin and silver. Although on another survival I had all this work properly. The problem with the saber is generally specific. A friend of mine lost a saber on the server, they started looking for it and I decided to throw it into the grass to see how it could be seen so that I could notice it. In the end, as I said, I discovered this bug purely by accident. When I checked without recording a video, I could only call it when: I turned on the saber - LMB+RMB and Q (quickly), but on the recording I could just throw it away after turning it on and the bug worked, naturally the bug is visual, but the funny thing is that the visual saber inflicts damage as if it was turned off. lmao
https://youtu.be/_23IwyESDKQ

**Comment by Speiger** [comment]
Interesting.
This could be happening due to the energy drain tick.
Where it causes a "changed" update while the drop is already through and giving you the item client sided back.
Technically that can happen to any item that has a constant NBT change applied to it ^^"

**Comment by Ullimunate** [comment]
understandable... but how can I solve the problem that the miner does not mine tin and uranium, which I desperately need?

**Comment by Ullimunate** [comment]
Is it possible to somehow give the miner other drilling coordinates rather than zero ones?

**Comment by Speiger** [comment]
@Ullimunate nope it is drilling in the area it is designated to.
