### ISSUE TITLE
1.20.x

### ISSUE THREAD

**Issue by GeorgeFence** [TinyModularThings/IC2Classic#1164]
Add support for latest versions!
Please

**Comment by gfbbkon** [comment]
> Add support for latest versions! Please

When the developer wants it and when he has time for it, then there will be a port to new versions.

**Comment by gfbbkon** [comment]
https://github.com/TinyModularThings/IC2Classic/issues/1143#issue-2239729014

**Comment by Speiger** [comment]
Yeah I am not answering these requests.

**Comment by GeorgeFence** [comment]
At least How to compile it?

**Comment by GeorgeFence** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/105986123/813273d7-e597-44fc-b0c0-4940ff0a9c41)

**Comment by Meduris** [comment]
You can't. IC2 Classic is closed source (and the license from the original industrial craft doesn't allow us to change anything about that).

The code here is simply the api modders can use to interact with ic2 classic
