### ISSUE TITLE
Crafting upgrade

### ISSUE THREAD

**Issue by Exter0800** [TinyModularThings/IC2Classic#1166]
There is nothing written on the wiki on how to use it, could someone explain it to me?

**Comment by CrossVas** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/1ef12bc0-e4d2-475b-b3b7-9775626efcdc)

`Crafting Upgrade` use internal inventory to craft items and export them into a connected inventory.
How it works:
1. By pressing `Side Inventory Key` (`c` in my case) and `Right-Click`, the inventory will open.
2. `Red` zone is for your recipe. Simple as that.
3. After you placed your recipe, the `yellow' button called `Validate` will help validate the recipe, if everything is correct, the result stack will appear inside the `aqua/cyan` box.
4. Additionally, you can set the export direction using buttons from `green box`. By default, the direction is set to `Down`. That means that crafted stack will be exported into inventory connected at the bottom.
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/340b6d10-622c-47aa-85fb-2a444d0b33a0)

It can work only with the items from the inventory where it is placed.
For instance, if placed into a `Macerator` that macerated only iron ore, it'll work only with iron ore dust. I.e. the output of the machine.

The most common use for this upgrade is `Machine Buffer`. Here is a setup:
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/341e84ba-c7c5-43bb-8a02-099eb38fcb72)
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/bdc32cf2-17b0-4dd1-92c9-6b09f7b396e2)
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/940b33c3-567e-48bf-9837-2d13e17a1d75)
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/02577d20-e625-4334-b451-7a16df4eb4db)

**Comment by Exter0800** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/173752679/c7ce3f45-4f13-4971-8d4f-c9fe0d8e987d)
its not exporting the item to the chest

**Comment by CrossVas** [comment]
`Items stuck in output` usually means that the adjacent container is full or doesn't accept items
Try replacing the chest.

**Comment by Exter0800** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/173752679/6d1e15d0-7fc5-475a-bc58-3fe1971b7851)
i used a iron chest already and a normal chest and nothing :/

**Comment by Exter0800** [comment]
thanks :)
