### ISSUE TITLE
When logging into a single player world half of my reactors contents are "kicked" out into the world as items and inventory items are cloned.

### ISSUE THREAD

**Issue by E100-cpu** [TinyModularThings/IC2Classic#1167]
I have encountered a strange bug. When I log into my single player world the reactor removes half of its contents and then dumps them around itself as dropped items. Furthermore, some of my inventory is cloned into the reactor which cannot be removed by clicking on the items normally, The items are just duplicated, even the shulker boxes and tool boxes and the items inside of them. Initially when I logged off the world I saved and exited above one of my reactors, I figured this had something to do with the issue. So I entered creative mode to rapidly fix the bugged reactors by breaking and replacing them and placing the components back into them. I then saved and exited again this time away from the reactors and then logged back in which I then encounted the same issues. 

Adding onto this the two breeder reactors that are located in the back of the same building were unaffected by these issues. I was also in the middle of building an automated loading and unloading system for my reactors using provider and acceptor tubes. I had finished the automated uranium rod loading portion of the system for the 8 power generation reactors. The breeders didn't have any tubes connected to them yet and required manual loading and unloading for them to be refueled. The provided screen shots are from the second attempt. 

![2024-06-20_21 04 32](https://github.com/TinyModularThings/IC2Classic/assets/126428428/0f15b6a3-7a32-45c3-9684-3816b8226fe1)
![2024-06-26_08 39 45](https://github.com/TinyModularThings/IC2Classic/assets/126428428/8ea0a3bc-e1e9-4f89-b3f9-2e34de0dc5ec)
![2024-06-26_09 06 43](https://github.com/TinyModularThings/IC2Classic/assets/126428428/fd4f149f-0964-4d5b-9a91-320d55b1f2b2)
![2024-06-26_09 06 49](https://github.com/TinyModularThings/IC2Classic/assets/126428428/56a7c039-c3d8-41e3-85b5-b854b371d884)
![2024-06-26_09 07 23](https://github.com/TinyModularThings/IC2Classic/assets/126428428/e48b6b2d-0ebe-4ea5-8c9d-e402d0435474)
![2024-06-26_09 07 29](https://github.com/TinyModularThings/IC2Classic/assets/126428428/d7adb4d0-fc1a-4c17-b37b-517f68fab86d)
![2024-06-26_09 07 39](https://github.com/TinyModularThings/IC2Classic/assets/126428428/b06fd491-becf-4b5b-8682-d846a0c97e24)

Mod list:
![Screenshot 2024-06-26 093425](https://github.com/TinyModularThings/IC2Classic/assets/126428428/16409ff3-6d88-4bc8-9e48-d52dbdd7eaa0)
![Screenshot 2024-06-26 093501](https://github.com/TinyModularThings/IC2Classic/assets/126428428/ab173f5c-932e-48c7-a866-407d44362b78)
![Screenshot 2024-06-26 093529](https://github.com/TinyModularThings/IC2Classic/assets/126428428/06ac4a8b-c83b-46f1-8e0d-02adb875d8bf)
![Screenshot 2024-06-26 093608](https://github.com/TinyModularThings/IC2Classic/assets/126428428/68373269-62c9-4dcb-b83a-fbdb1ddcf1ba)
![Screenshot 2024-06-26 093638](https://github.com/TinyModularThings/IC2Classic/assets/126428428/103b8bca-4172-4de8-834a-9924aa132678)
![Screenshot 2024-06-26 093710](https://github.com/TinyModularThings/IC2Classic/assets/126428428/a6cc9925-5d20-463b-8ae7-03a4b77700ff)

**Comment by Speiger** [comment]
@E100-cpu this is from what i know a Desync bug.
And not an IC2 bug specifically.
There could also be a mod that messes with inventory sync because this is a relatively new issue showing up.

Not sure. But if your items were in the reactor in the gameplay side and not the rendering side, the reactor would eject them from the inventory by the next tick.
Because it is coded to dump any item you are not supposed to put into the reactor before the simulation starts.
