### ISSUE TITLE
Using IC2 in modpack (not a bug,i dont know how to contact  Speiger on github)

### ISSUE THREAD

**Issue by dustojnikhummer** [TinyModularThings/IC2Classic#118]
I dont know how to contatct  Speiger directly. I want make a HQM styled map with big usage of your IC2 Classic (because all new packs are RFOnly). I want to ask you if i can use it.

**Comment by Speiger** [comment]
@dustojnikhummer i am called SpeigerCut on Twitter. I nodest here and there always an Email whenever you send something. So i nodest that at the same day.
I have no problem with modpacks... It is promotion for me and i even want that^^"
Little note: Texture packs with IC2 Classic (with bigger texture sizes then 16x16 per texture) will crash. I fixed that already^^"

**Comment by dustojnikhummer** [comment]
Thank you.

**Comment by Speiger** [comment]
No Problem^^
