### ISSUE TITLE
[1.7.10] Crash with railcraft

### ISSUE THREAD

**Issue by jarezzz** [TinyModularThings/IC2Classic#1180]
java.lang.NoSuchFieldError: POTION_RADIATION
Tested it, issue disappears with disabled railcraft or enabled IC2experimental
[crash-2024-07-21_13.06.01-client.txt](https://github.com/user-attachments/files/16323899/crash-2024-07-21_13.06.01-client.txt)

**Comment by Speiger** [comment]
There are only 2 reasons why this happens.

- 1: your ic2c/rail craft version corrupted during download (redownload both to test)
- 2: Rail craft ships an outdated ic2 API which breaks everything. To fix that you need to open the rail craft jar and delete the ic2 folder containing the ic2c jar.

**Comment by jarezzz** [comment]
Oh, yeah, that's what happened, thank you a lot
