### ISSUE TITLE
[1.19.2] Bugs Identified

### ISSUE THREAD

**Issue by EnderVonSlayer** [TinyModularThings/IC2Classic#1181]
The auto-feeder upgrade consumes the entirety of chip rolls

Crafting upgrades seem to have an infinite internal storage as identified by CrossVas (or they just had thousands of crafts queued up?)

**Comment by Speiger** [comment]
first one isn't a bug

**Comment by EnderVonSlayer** [comment]
Damn, we really just each 192 fries in one bit once we lose half a hunger bar?

**Comment by Speiger** [comment]
@EnderVonSlayer your description sounded like this:
"The eating upgrade will fully consume the chipsroll and not leave it at 1 durability"

**Comment by EnderVonSlayer** [comment]
https://github.com/user-attachments/assets/59fda4ac-b3fd-4445-b56c-3921b57b9510
