### ISSUE TITLE
Quantum and Nano armor do not lose their charge when they receive physical damage from players, mobs, etc.  

### ISSUE THREAD

**Issue by xxiber** [TinyModularThings/IC2Classic#1188]
The problem occurs only when I run the mod on the server. This does not happen in single player. When receiving damage from mobs (zombies, skeletons, for example), the energy charge does not decrease and the damage is slightly reduced, as in diamond armor. I'm not talking about potions, but standard damage. I did not change the configurations. Any working version of the mod on 1.19.2 has this problem. I saw that a thread was already made on this topic. But there was no solution to the problem in it. I'm using the Arclight core, and I've tried several versions. If someone has already encountered this problem, how did you solve it?

**Comment by Sa1ZeR** [comment]
Don't use arclight

**Comment by xxiber** [comment]
Thank you! I just installed the forge kernel myself and the problem is indeed gone. Could you tell me if you know? I want to use some plugins additionally. How can I install them on this core? If it is possible

**Comment by Sa1ZeR** [comment]
> Thank you! I just installed the forge kernel myself and the problem is indeed gone. Could you tell me if you know? I want to use some plugins additionally. How can I install them on this core? If it is possible

arclight has a lot of incompatible mods, it's useless
