### ISSUE TITLE
Power Stops

### ISSUE THREAD

**Issue by Bluedog444** [TinyModularThings/IC2Classic#119]
Hi,
Sorry I have another bug.
When a machine explodes due to high voltage it seems to stop power flowing through anything (IC2 related) on the server.

This also happens when I connect up power converters to the power cable.
Power works again after a server restart.

The addons that I have are:
Advanced Repulsion Systems
Advanced Solar Panels
Gravitation Suite
Nuclear Control 2

Server Console:
27.09 16:58:36 [Server] INFO [16:58:36] [EnergyNetThread: Overworld/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.World.func_147460_e(World.java:730)

27.09 16:58:36 [Server] INFO Exception in thread "EnergyNetThread: Overworld" [16:58:36] [EnergyNetThread: Overworld/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: net.minecraft.util.ReportedException: Exception while updating neighbours

Hope it helps

Kind Regards Bluedog444

**Comment by Speiger** [comment]
@Bluedog444 which version is that. I am a bit confused because of the date when this opened.

**Comment by Bluedog444** [comment]
@Speiger Oh these were very old versions of the mod. I doubt it happens now. It was an issue with integration with other mods but that got fixed ages ago.
