### ISSUE TITLE
Add nuclear reactor component's config file

### ISSUE THREAD

**Issue by Roma32e32** [TinyModularThings/IC2Classic#1200]
Add config file for edit reactor component's parameters.
For example: vent's power, rod's heat generation.

**Comment by Speiger** [comment]
Sorry but no.

**Comment by Roma32e32** [comment]
why

**Comment by Speiger** [comment]
@Roma32e32 TLDR We have to provide consistency for setups

We provide examples that simply would no longer be reliable the moment we add such a config.
And reactors are already with a really bad stigma in the first place. 
Such customization is simply not feasable with everything in the works.

**Comment by Speiger** [comment]
> Is exist another method to edit these parameters?

Create your own components via addons :)

**Comment by Roma32e32** [comment]
Ok

**Comment by Roma32e32** [comment]
Where i can find an api documentation (for 1.12.2)?
