### ISSUE TITLE
ic2.core not found when building

### ISSUE THREAD

**Issue by GeorgeFence** [TinyModularThings/IC2Classic#1202]
Hi, I wanned to build IC2Classic on my own, but it gives me this error
![image](https://github.com/user-attachments/assets/7ca0fdd3-f7bc-4732-b7cc-4502ea0c63d3)

**Comment by Speiger** [comment]
@GeorgeFence this repo only contains the API, the sourcecode of the core isn't part of this repo, and never will be.
