### ISSUE TITLE
[IC2C - 1.19.2-2.1.1] Whiskey(0) -> Alcohol in a Refinery is nonfunctional.  

### ISSUE THREAD

**Issue by Emberglow5000** [TinyModularThings/IC2Classic#1208]
Whisky(0) does not produce any Alcohol when used in alcohol production in a refinery.   Whisky(15) seems to produce the correct amount, though JEI claims that it can produce 10k, 12k, 15k, 25k, and 50k mB - scrolling through the full list of potential outcomes regardless of which quality is viewed in the JEI Preview.

Additionally, for specifically Whisky, JEI claims that there are 6 quantities of Alcohol that can be created when processing Whisky.  

Whisky ages: 0, 10, 12, 15, 25, 50
The potential quantities of Alcohol that can result from Whisky Processing are 10k, 12k, 15k, 25k, 50k mB 

When attempting to use Whisky(0) to make Alcohol - the Refinery will consume the Whisky and Water, and produce no Alcohol output at all.  Given that there appears to be no Alcohol output quantity associated with Whisky(0) refinery processing, this seems to be a blank recipe with no outcome, which explains why it is a valid input, but no output is produced beyond the empty mug.

**Comment by Speiger** [comment]
@Emberglow5000 Whiskey(0) -> Unbrewed Whiskey that means there is 0 alcohol in it.
Meaning this isn't a bug.

**Comment by Emberglow5000** [comment]
@Speiger Ah, thank you for confirming. I suspected that this might be the case, though the fact that the recipe works, and gives no output with no documentation (that I could find, at least) lead me to believe that something unintended was going on.  The fact that its a valid input with empty outputs combined with the incorrect JEI listings associated with the recipe(s) seemed to be much too buggy to be the intended behavior.   


JEI lists that the recipe should output alcohol - that at least could use addressing.  (Screenshot below) 

If you don't mind a suggestion, perhaps assign Whisky(s) an output beyond nothing, or remove it as a valid input?  Even water as an output would be less misleading than JEI citing a recipe that functions, but provides no fluid output.   

![Capture](https://github.com/user-attachments/assets/73cf3e32-b633-4882-9a04-0f5907ce34e1)

Anyway, thanks for taking a look!
