### ISSUE TITLE
[1.19.2] Cannot connect MEKANISM universal cables to machines or pipes (or anything) 

### ISSUE THREAD

**Issue by SillySalamandar** [TinyModularThings/IC2Classic#1218]
Im trying to use the Mekanism energy cables so i can transfer power to my IC2 machines. Energy cubes also dont transfer power to anything (machines and pipes). Love your mod btw. Thank you for helping when u get to this!

**Comment by CrossVas** [comment]
Yeah, you can't really use mekanism energy for IC2C anymore (how they use to work on previous versions). For that you'll have to install a converter mod.
IC2C removed any RF->EU converters and now only has EU->RF (see [here](https://github.com/TinyModularThings/IC2Classic/issues/856) for more info)
So, the solution is simple:
EU -> RF: use IC2C own `Flux Generator`
RF -> EU: Use any available power converter mod (there is one, I won't link)
