### ISSUE TITLE
Electric Fisher

### ISSUE THREAD

**Issue by Vertix8** [TinyModularThings/IC2Classic#1219]
I made a multiblock structure as written in the wiki but it doesn't work. I don't even understand how to supply power to it.
Please tell me if I'm doing something wrong or is this a bug?
1.19.2-2.1.1
Forge 43.4.4

**Comment by Speiger** [comment]
If you build it wrong or in the wrong place the structure doesn't form.
If the structure doesn't form cables do not connect to it.
If it forms any block part of the structure (even the wood) accepts power.

Please send an image of how/where you built it.

**Comment by Vertix8** [comment]
> If you build it wrong or in the wrong place the structure doesn't form. If the structure doesn't form cables do not connect to it. If it forms any block part of the structure (even the wood) accepts power.
> 
> Please send an image of how/where you built it.

![2024-11-09_04 21 11](https://github.com/user-attachments/assets/947fe7d1-14dc-4d15-9f85-16accd3542cf)
![2024-11-09_04 22 02](https://github.com/user-attachments/assets/6dc159a1-3a70-42d9-b80b-4b85b15c4bc3)
![2024-11-09_04 21 29](https://github.com/user-attachments/assets/197d862b-dffd-4688-8213-6e4329ef2610)
As I understand it, there is enough water in creative mode, but in my survival there is very little?
(The designs are the same, but in creative mode it works)

**Comment by CrossVas** [comment]
You've built it right as I can tell from the fact that the cable is connecting.
Just make sure you have enough power provided.
![image](https://github.com/user-attachments/assets/102f20e5-37f4-400f-9ae2-37cd6894e547)

Also `EU Reader` and TOP/Jade might give you some more info on the progress.

**Comment by CrossVas** [comment]
Also make sure the chain length is between 5-10 blocks

**Comment by Vertix8** [comment]
I just rebuilt this structure in the ocean biome and it worked, sorry for bothering you, I should have checked it before opening an issue. Thank you for your help!
