### ISSUE TITLE
Missing important info in wiki

### ISSUE THREAD

**Issue by Aleksei-Tavadyan** [TinyModularThings/IC2Classic#1224]
1. In wiki it is said that I can make reinforced stone from foam, but it doesn't say how. Which block should I place?
2. **There is no info in wiki that I also must put tank in multiblock liquid tank structure, not only valve.** 
3. Is there nano-bow in game? I saw youtube clip of guy playing 1.19.2 with nano-bow, but I can't find a recipe in same version o_o
![изображение](https://github.com/user-attachments/assets/d81ab6d8-5699-485a-8a44-368b3bb1ebcb)

**Comment by CrossVas** [comment]
1. Similar to IC2: Experimental, Wooden scaffoldings are used to create regular CFoam shapes and Iron Scaffoldings are used to create Reinforced Stone shapes. How it works:
-place down scaffoldings;
-right click with a CF Sprayer. 

2. The wiki entry refers to the `Tank` block itself and not to the random tank out there (multiblock tank in this case). Of course you need to include the `Tank` into the structure... 
*the Multiblock Structure also shows you that:
![image](https://github.com/user-attachments/assets/4c7fbf62-f551-4c26-ac52-2ecefba715a5)

3. Nano Bow is part of an IC2Classic addon - [IC2C Additions](https://www.curseforge.com/minecraft/mc-mods/ic2c-additions) which was a part of the beta testing server pack where the video was recorded.

**Comment by Speiger** [comment]
o/
To append to these answers a bit.
IC2Classic contains a lot of Intentionally undocumented features in it.
These are there as "hidden features" or "knowledge features" that spread around through community posts/videos or in general self experimentation.
None of these are required to play the mod at all and are only optional routes.
But from the feedback i have received to far it is not a bad thing.

And you just ran into one. Congratulations.
You now know something not everyone else knows :)

That was point one now.

Point two:
You know you read the "Tank entry" specifically? Do you expect the same if you read the "macerator entry" that it actually applies to the Electric Enchanter?
Please apply common sense here.

Point 3:
Read Crossvas answer.
