### ISSUE TITLE
How to turn off transformers?

### ISSUE THREAD

**Issue by proxima812** [TinyModularThings/IC2Classic#1226]
How to turn off transformers and make unlimited energy flow of wires?

**Comment by Speiger** [comment]
@proxima812 by removing them.
FYI transformers aren't the one doing it.
Its the whole system.
All transformer do is combine packets together.
So if you have 51 normal generators and pump them into a HV transformer you turn them from 51x 10EU packets into a 1x 512EU packet.

**Comment by proxima812** [comment]
> @proxima812  by removing them.
FYI transformers aren't the one doing it.
he whole system.
ransformer do is combine packets together.
you have 51 normal generators and pump them into a HV transformer you turn them from 51x 10EU packets into a 1x 512EU packet.

with light settings in the transformer upgrade config, it does not work in the game. Why?

**Comment by Speiger** [comment]
@proxima812 with the what in the what now?
I don't know what you are talking about.
What you are talking about doesn't exist in the mod at least the way you described it.

**Comment by proxima812** [comment]
> @proxima812 with the what in the what now? I don't know what you are talking about. What you are talking about doesn't exist in the mod at least the way you described it.

I'm sorry, I wrote the wrong thing. It was about a "easy mode" without explosions. The point is that the "transformer improvement" does not work in easy mode.

It's in ic2.cfg there's a setting

**Comment by Speiger** [comment]
@proxima812 all that the easy mode does is effectively check if sending energy to a receiver would  cause an explosion and simply interrupt the transfer of energy instead.
Deadlocking the local energy grid in place. Same with wires melting.
