### ISSUE TITLE
dont work high pressure alloy plant

### ISSUE THREAD

**Issue by proxima812** [TinyModularThings/IC2Classic#1228]
I can't log into it stupidly in the interface

**Comment by Speiger** [comment]
Did you follow the instructions in the wiki?
Of building the multi block and putting the master in the top left?

**Comment by proxima812** [comment]
> Did you follow the instructions in the wiki? Of building the multi block and putting the master in the top left?

ok. I understood, thanks, I didn't know that this is a colossal building for an alloy plant

**Comment by proxima812** [comment]
> Вы следовали инструкциям в вики? Построили мультиблок и поместили главный блок в левый верхний угол?

The alloy plant for the colossal block does not work after all

**Comment by CrossVas** [comment]
> The alloy plant for the colossal block does not work after all

It's not a colossal multiblock. The block you need is called `Pressure Alloy Furnace Structure` or `Структурный блок завода сплавов` if you're playing with Russian language. I've made sure to keep the same name, so people could be less confused what block they need. 
Common sense moment here.
![image](https://github.com/user-attachments/assets/95dd51f1-c3b3-48e8-baff-b154e12411b9)

**Comment by proxima812** [comment]
> > Завод по производству сплава для колоссального блока так и не заработал
> 
> Это не колоссальный мультиблок. Нужный вам блок называется `Pressure Alloy Furnace Structure`или, `Структурный блок завода сплавов`если вы играете с русским языком. Я позаботился о том, чтобы сохранить то же имя, чтобы люди меньше путались, какой блок им нужен. Момент здравого смысла здесь. ![изображение](https://private-user-images.githubusercontent.com/25727222/394050692-95dd51f1-c3b3-48e8-baff-b154e12411b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDM2MzQsIm5iZiI6MTczMzgwMzMzNCwicGF0aCI6Ii8yNTcyNzIyMi8zOTQwNTA2OTItOTVkZDUxZjEtYzNiMy00OGU4LWJhZmYtYjE1NGUxMjQxMWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA0MDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMzY5NmRkZmFkOTIzZDUyNWJlNDM3MzIwNGYxZDZmNDJhNzVhNDczN2E1YjhmOTNmNjg1NDdiMzVjODVlNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lc_Wb2OgMvYmultAVSNPX_ghZtciq4Ng9JjcbU_PfFU)
 

Thanks! 🙏
