### ISSUE TITLE
Connecting the pump to the farm to the forestry 1.19.2 module.

### ISSUE THREAD

**Issue by proxima812** [TinyModularThings/IC2Classic#1229]
It doesn't connect with turbos either. I don't understand how to pour water into the farm

**Comment by Speiger** [comment]
Please elaborate and also show a image of what you want to do.

**Comment by proxima812** [comment]
> Please elaborate and also show a image of what you want to do.
![Снимок экрана 2024-12-06 в 16 22 52](https://github.com/user-attachments/assets/aa3ad9c1-8752-494a-a9f7-e5c90b5ce9b0)
![Снимок экрана 2024-12-06 в 16 22 33](https://github.com/user-attachments/assets/397447f1-6835-45c3-a916-1fc3d1d1075d)

**Comment by Speiger** [comment]
@proxima812 the ic2c pump only pumps the block directly below it. Not 2 blocks or 3 blocks.
And not to the side either.

**Comment by proxima812** [comment]
> @proxima812 the ic2c pump only pumps the block directly below it. Not 2 blocks or 3 blocks. And not to the side either.

he was pumping water, but I have to transfer it to the farm. How to do it?

**Comment by proxima812** [comment]
> @proxima812 the ic2c pump only pumps the block directly below it. Not 2 blocks or 3 blocks. And not to the side either.

I also put it directly, the water does not come in.

**Comment by CrossVas** [comment]
> > @proxima812 the ic2c pump only pumps the block directly below it. Not 2 blocks or 3 blocks. And not to the side either.
> 
> I also put it directly, the water does not come in.

1. Make an infinite source of water. Place the pump right above it.
![image](https://github.com/user-attachments/assets/b9575eba-6179-4cd8-9c97-406343be07a7)

2. Provide some power.
![image](https://github.com/user-attachments/assets/7afb11f8-3b3f-432d-8669-fe73f5d2c603)

3. Connect.
![image](https://github.com/user-attachments/assets/8f21b544-c414-4565-b16c-b703df2c67c0)

4. Profit.

**Comment by proxima812** [comment]
> > > @proxima812насос ic2c качает только блок, который находится прямо под ним. Не 2 блока или 3 блока. И не сбоку.
> > 
> > 
> > Я же говорю прямо, вода не поступает.
> 
> 1. Создайте бесконечный источник воды. Поставьте насос прямо над ним.
>    ![изображение](https://private-user-images.githubusercontent.com/25727222/393473980-b9575eba-6179-4cd8-9c97-406343be07a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDk5NTgsIm5iZiI6MTczMzU0OTY1OCwicGF0aCI6Ii8yNTcyNzIyMi8zOTM0NzM5ODAtYjk1NzVlYmEtNjE3OS00Y2Q4LTljOTctNDA2MzQzYmUwN2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA1MzQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMmEyMmQ2ZTRmNTZjZDllNjJhNDI4OTgyYjM0NTYwODE1NzQxYjY2ZGJlMWQxYTk4ZTI3ZWQyNjFmZWY5Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O0wdL4o73LfydZjg2UDxVU6856OSDxgCP6TLIA5gsnA)
> 2. Дайте немного мощности.
>    ![изображение](https://private-user-images.githubusercontent.com/25727222/393474044-7afb11f8-3b3f-432d-8669-fe73f5d2c603.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDk5NTgsIm5iZiI6MTczMzU0OTY1OCwicGF0aCI6Ii8yNTcyNzIyMi8zOTM0NzQwNDQtN2FmYjExZjgtM2IzZi00MzJkLTg2NjktZmU3M2Y1ZDJjNjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA1MzQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MzBjZTkyOTkxYmViYTlhNGVmN2Q4MzUxMjg1Zjc2MWQ4NzM5MmQyZDY4NTJlMzcxYmQyZTQxMjJhYzU3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oUyX-REd23KfOVKOngIgcJ7q1lmGD7IIgAp2X3wLxRY)
> 3. Соединять.
>    ![изображение](https://private-user-images.githubusercontent.com/25727222/393474070-8f21b544-c414-4565-b16c-b703df2c67c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDk5NTgsIm5iZiI6MTczMzU0OTY1OCwicGF0aCI6Ii8yNTcyNzIyMi8zOTM0NzQwNzAtOGYyMWI1NDQtYzQxNC00NTY1LWIxNmMtYjcwM2RmMmM2N2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA1MzQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNGVkNDE2MDM0N2E0YzEzMjFmYjc2OGFhZWFmZjFjMWMzYzE0ZWNiMzAxZTRlOTlhYzM2YjgxZmY4MjU0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YVAWtl6A3DIcMCkimnIQvau7Mhr9tiQz_ovexvUF1dU)
> 4. Выгода.

Спасибо. Попробую. Очень выручили!
