### ISSUE TITLE
[1.19.2] Cfoam bug or some strange feature.

### ISSUE THREAD

**Issue by VladBandos** [TinyModularThings/IC2Classic#1234]
IC2Classic-1.19.2-2.1.1
1.19.2-forge-43.4.5
I dont know if its a bug or not but cfoam doesnt conduct redstone at all.
![image](https://github.com/user-attachments/assets/261a4c82-a8bd-4c5f-8358-92551c67ab94)

**Comment by Speiger** [comment]
One is a Texture copy block, and the other one is CFoam.

Texture Copy block has different properties because it kinda needs to have that.
CFoam is working as intended here IIRC

**Comment by VladBandos** [comment]
sorry then

**Comment by Speiger** [comment]
no needed to apologize that was just a question and i answered it.
