### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by Vertix8** [TinyModularThings/IC2Classic#1237]
When the steam tunnel is close to each other there is such a bug. If there is a distance between them, the fan is displayed normally.
![Снимок экрана (118)](https://github.com/user-attachments/assets/2647d49f-16bf-4051-ac09-05c3f2bd1a1f)

**Comment by Speiger** [comment]
Yeah sadly this isn't fixable without effectively breaking every single steam turbine block out there.

And outside of this small limitation it is fine to use.
So not going to fix that.
Sorry.
