### ISSUE TITLE
Broken Extractor Recipe

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#124]
Apparently you can extract fire into 3 rubber...
![2015-10-04_15 46 58](https://cloud.githubusercontent.com/assets/4021725/10268396/3dc9dbb2-6aaf-11e5-8073-704097f8265b.png)

**Comment by Speiger** [comment]
Its only Visual

**Comment by Chocohead** [comment]
Still shouldn't happen though, but it might well be another mod adding an invalid recipe as I saw that in Tekkit Legends.

**Comment by Speiger** [comment]
FIxed
