### ISSUE TITLE
Compact Recycler and Regular Recycler STILL produces scrap on modded blacklisted items on 1.1.1.5

### ISSUE THREAD

**Issue by VenomFrog** [TinyModularThings/IC2Classic#125]
Hello, you might remember my issue with recyclers, well ive updated and noticed that issue with recyclers is fixed, well non vanilla blacklisted items still produce scrap. Im not sure if this an issue on MY part, an issue on mod compatibility or what. But its frusterating because players on servers can turn a single block into 32 pieces, all usable in making scrap.

http://imgur.com/a/VXrGZ

http://pastebin.com/yg3hHRWf Here is my config folder, please look at it. I want to wish this is a user error :/

**Comment by Speiger** [comment]
Yeah. Problem was that i did format the detection wrong. The new and only format is simply Block/Itemname and meta. No longer ModID then MC can not find the Object. Also the Init of the Config was to early so most mods did not have registered their stuff. That is also fixed. I will do a hotfix in a couple days. (this week for sure!)

**Comment by Speiger** [comment]
Ok forget what i just said. The System is like before. I managed it now to make the loading from a text to work... If it can not find someting it will throw a text that starts with: "Recycler Error:" so you can easy find it.

Fixed
