### ISSUE TITLE
Geothermal Genarator Bug

### ISSUE THREAD

**Issue by gruenebanane** [TinyModularThings/IC2Classic#126]
Durch Pipes unten werden auch Lavazellen in den oberen Slot getan, wo sie ja nicht hin sollen.

**Comment by Speiger** [comment]
Es war nicht geplannt das man zellen Automatisch importieren kann. Deswegen habe ich den Slot Blockiert. Wenn du lava reinfüllen möchtest solltest du am besten FluidPipes nehmen...
Aber da ich trotzdem irgendwann alle machinen und ihre Slots ändern muss (auch generatoren)
kann das eine Option fürs nächste update werden. Aber das kann noch lange dauern. Ich mach mindestens pro Update (außer durch wichtige fehler) 2 wochen pause. Um fehler sammeln zu lassen. Damit sich eine bessere Version entwickeln lassen kann.
Also lass dich überraschen.

Just for the Heck here is a short Explaining what he suggests:

Fuel slots for geothermal Generator should be accessable through the ISidedInventory

**Comment by gruenebanane** [comment]
It works, but Lava Cells are also landing in the Top Slot.

**Comment by Speiger** [comment]
Closing

**Comment by Ivar418** [comment]
@spieger so were not able to import lava cells into geothermal generator? i was possible in tekkit classic

**Comment by Speiger** [comment]
@Ivar418 i think it should be possible.

**Comment by Ivar418** [comment]
@Speiger are you going to change it? i think people like it more than not having the option at all. and if you dont like it you could just not do it right. please open it up for cells.
