### ISSUE TITLE
Cables are not connecting after leaving the Server run for a half day

### ISSUE THREAD

**Issue by gruenebanane** [TinyModularThings/IC2Classic#127]
Die Kabel sehen einzeln aus, und es fließt kein Strom mehr.
![2015-10-08_21 45 35](https://cloud.githubusercontent.com/assets/9641709/10377873/00d58c7e-6e06-11e5-8ab3-d51195182965.png) Server neustart behebt das Problem.

**Comment by gruenebanane** [comment]
Auch ein abbauen und wieder hinsetzen bringt nichts,

**Comment by Speiger** [comment]
Version of IC2 Classic?
Is that the latest? Because the Hotfix version should fix that...

**Comment by gruenebanane** [comment]
Sorry, old version.

**Comment by Speiger** [comment]
Did it work with the latest version @gruenebanane?

**Comment by gruenebanane** [comment]
No

**Comment by gruenebanane** [comment]
But now it is only client view, the machine still works.

**Comment by gruenebanane** [comment]
But after lefting and joining again, it is away.

**Comment by Chocohead** [comment]
People are complaining about this with Tekkit Legends too: http://forums.technicpack.net/topic/193310-copper-wires-keep-disconnecting-when-the-map-loads/

**Comment by Speiger** [comment]
@Chocohead i can not fix that alone.
I need help because it seems to be still there

**Comment by Speiger** [comment]
Ok i asked now now gigabit101 and he said the latest version fixes it. And Tekkit legends 1.0.8 has the latest version. So it should be fixed with updating the pack

**Comment by Speiger** [comment]
Fixed
