### ISSUE TITLE
Steam Reactor & Components

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#13]
IC2 Has an option for Steam Creation for reactors.

The idea of it is really cool.
For explaining how that will work for people that want to know it.

The Difference between the Electric and the Steam Reactor is, that components are now way more important then before.
The Uran Creates heat. The Heat get transfered into the Steam Vents. Those will use the Heat and draw out of the Reactor water to create Steam. (how that will work is not sure yet... only 2 ways are possible. More heat more Steam produced, or static steam production and there is no dependcy on heat to create more steam).

IC2 Reactors will change at that spot also.
They are no longer Electric parts, they have differend types of Chambers. (Input & Output & Closed),
The Reactor itself outputs steam on the outpu Chambers.
If there is no chamber he will aviode the sides where he waters get

The Steam must be outputed else it will not create steam and also the components will not cool down.
The steam tank will be much bigger than the water tank. The sizes are not set yet...

**Comment by SynfulChaot** [comment]
Suggestion:

When steam reactors get implement, have config options so people can choose to disable EU-direct reactors.  I find separating the steam production from the energy creation to be more fun and complex and I'd kinda like to force myself (and others playing my modpacks) to have to create the 'turbines' as well as the reactor itself.

Also, perhaps allow the input of certain types of cooler-than-water fluids (crushed ice, etc ...) to boost efficiency ... if you can create them fast enough to keep up with the reactor's consumption rate.

**Comment by Speiger** [comment]
@SynfulChaot i will add config that dissables the recipes. So that if someone want to force one mode they can but the other one is still there if they are in creative/op mode...
Removing the blocks from the game could be effecting addons..
I hope that is a solution that is ok.

**Comment by SynfulChaot** [comment]
True.  I didn't consider the add-on side.  That is a solution that would work perfectly.

**Comment by Speiger** [comment]
@SynfulChaot if you have any other suggestions, feature reqests, modsupport requests, just ask, i am always open for new pictures

**Comment by SynfulChaot** [comment]
As I play around with it more in my test world I'll be sure to.  ^.^

**Comment by Speiger** [comment]
@SynfulChaot just that you nodest that.
Steam reactor is in progress/testing. The block exisst and is fully funcitonal.
The Logic of the reactor is ok. Has way faster tickrate (instead of 20 delay ticks before the next it is no delay)
The Steam vents are at the moment way to OP... They produce at half productivity (1mb water = 80 Steam (normal is 1mb = 160mb Steam)) 320 Steam per Uranium cell which is equivalent with 200 EU per tick... So the caluclation of that is still in progress ^^.

So far i enjoy that it is running so good and smooth...

**Comment by Carbon-Ghost** [comment]
@Speiger : We need to follow RC convention on water to steam, so keep 1mb of water = 160mb of steam and instead lower the output of the steam vents, because this looks chaotic atm xD

Also, cryotheum support pwease ;P

**Comment by Speiger** [comment]
@Carbon-Ghoest
did you read the Latest changelog?
It is at the moment: 40 heat = 1mB Water = 160 steam = 100 EU
(Not sure if i changed the code from 40 to 80)

No Other fluid Support because only water/waterkind things can turn into steam... Also the logic would be way more complex because i would require a way more detailed information of the fluid then just static info about water....

**Comment by Carbon-Ghost** [comment]
Nvm got confused, so 1mb of water is 160 steam from RC standard right ? Well ok ^^

**Comment by Speiger** [comment]
Jup... So how far is the balancing?

**Comment by Carbon-Ghost** [comment]
I tried reactor but it seems I can't pump out steam... Used emerald pipes with autarchic gates ;c

**Comment by Speiger** [comment]
Try using a fluid Pipe that is not a emerald one...

**Comment by Carbon-Ghost** [comment]
Yes, a fluid emerald pipe :/

**Comment by Speiger** [comment]
Try it out with other things... I can not test with bc thanks @asiekierka that you do only provide release version and none Dev versions...

**Comment by Speiger** [comment]
Tested with bc and it worked fine... But i did not use Autartic gates i did use a engine... (The old and cool engine)

**Comment by Carbon-Ghost** [comment]
weird... Gonna retest that ^^

Also, post steam reactor, do you have any play for integrating an end game to IC2 classic ?

**Comment by Speiger** [comment]
@Carbon-Ghost that is a question for later...
I was thinking of something which could fit... But nothing telling yet. Secrets Baby Secrets xD

**Comment by Carbon-Ghost** [comment]
:D

**Comment by Carbon-Ghost** [comment]
I don't really have anything else except mekanism pipes, but gonna try...

**Comment by Speiger** [comment]
Done ^^" Next update will be a balancing update...
Depends on what i hear and see...
