### ISSUE TITLE
Reinforced Glass: Black textures

### ISSUE THREAD

**Issue by steveowashere** [TinyModularThings/IC2Classic#130]
See screenshot: 
![2015-10-11_09 05 56](https://cloud.githubusercontent.com/assets/13194819/10415390/467f24e4-6ff8-11e5-82a2-d00aa5860825.png)

Using latest version 1.1.2.1. Tested with/without optifine. Testing without/without texture packs. Problem persists. Most likely not an issue with the texture itself.

**Comment by Carbon-Ghost** [comment]
Small question, are you using Immibis connected texture mod ? I had problem with both glass and IC2 glass before when I used it...

**Comment by steveowashere** [comment]
Yes, for this test world I had Immibis' connected glass mod. Removing/disabling the mod seems to fix the problem.

**Comment by Carbon-Ghost** [comment]
Then problem solved, you can yell at Immibis to fix this xD  I had the same problem before though since he is only here once a year now, you might have some trouble to yell at him xD, not from our side at least xD may you close this ?

**Comment by steveowashere** [comment]
I'll go let him know. For now i'll just used Optifine. Speiger beat me to closing the issue :P

**Comment by Carbon-Ghost** [comment]
Go ninja'd :3

**Comment by Speiger** [comment]
XD just saw: close this thing and i was at home for about 2 minutes. So i closed it
