### ISSUE TITLE
Add IC2 Experimental Recipe Control.

### ISSUE THREAD

**Issue by Zilacon** [TinyModularThings/IC2Classic#131]
On IC2 Experimental there is a file "IC2.ini" which allows control of server recipes. This is extremely useful for server owners to ban crafting of items such as Nova Catalysts from ProjectE instead of using a very resource demanding banning plugin like TekkitCustomizer to scan every block for banned items.

Also banning plugins dont stop crafting of items they take the items AFTER its been crafted. So it will prevent players from wasting resources as well.

**Comment by Speiger** [comment]
That is a interesting thing...
Ok there is a lot of points to this:
- Much much work for moving all recipies
- Even more work for adding new recipes
- harder ways to test recipes

What i am maybe doing is making a File (maybe gson or properties) 
which allows you to throw in a veto to remove recipes, but then there is already ModTweaker which allows you to modifiy recipes (not sure how big that range of it is).

Just a couple questions: What are you want to dissable? Uumatter? That would be for me the only thing what i would remove... Maybe even scrapboxes but you could do suddenly hoes which makes hoes a 1500% chance...

**Comment by Zilacon** [comment]
We have tried minetweaker or modtweaker to no success it seems it only supports specific mods. So on my modpack TRPG we used IC2 to ban recipes instead and it worked flawlessly.

For Tekkit Legends there is A LOT of stuff from Project E that a lot of servers ban to stop people from doing the same exact thing on Tekkit Classic. Destroying the worlds and spawn and bypassing any type of plugin that protects anything.

At the moment we do this by using tekkit customizer which sucks. Because it adds another 2000% load to the server (timings report prove this).

**Comment by Zilacon** [comment]
Also your mod seems to conflict with MCMMO when Tekkit Legends updated to 1.0.7 MCMMO which was working before on 1.0.6 no longer works on 1.0.7 or 1.0.8. The same thing happens on IC2 Experimental on my TRPG modpack. But thats always been without MCMMO.

On Tekkit Legends a lot of players were using MCMMO and now it just dont work because of the addition to your mod. Anyway you could look into this and fix it? And possibly throw a pull request to IC2 Experimental as well with the fix? Because I made a issue report to MCMMO ages ago. Even after PAYING THEM for their plugin they just shrug their shoulders.

**Comment by Speiger** [comment]
@Zilacon ok about the recipes we can talk a little bit. The thing is i want a 1 time solution that make for users and me not much work. What you suggest is for me alone to much work and i do not want to do that.. I can ask the dev of ModTweaker to add support there and make special code for him that he can access the recipes from me really easy and create IC2 Recipes easy too.

About your MCMMO mod lol i heared about that today the first time in my life... What does this mod do (checking it a little bit but not sure how much i know), now the thing is what crashes with it. Explain it to me. Give me details.

Anyway thanks to your answer.

**Comment by Zilacon** [comment]
MCMMO is a bukkit plugin not a mod. It basically gives people experience towards skills based on their actions and activity on the server. When their skills level up higher it unlocks abilities like dropping extra stuff from dirt when dug, more ores drop when mined, more loot drops when you kill mobs, etc.

The errors for it are the exact same from IC2-E to IC2-C here is my issue post about it:
https://github.com/mcMMO-Dev/mcMMO/issues/2672

**Comment by Speiger** [comment]
Hmmm thats interesting. I readed that thing and do not understand that^^"

**Comment by Speiger** [comment]
Closing... Outdated...
