### ISSUE TITLE
Electrolyzer draining energy storage blocks

### ISSUE THREAD

**Issue by Alleluid** [TinyModularThings/IC2Classic#135]
Having a Electrolyzer next to any energy storage with a stack of water cells in them will totally drain the stored energy once it fills up.

**Comment by Speiger** [comment]
ok thanks :3

**Comment by Speiger** [comment]
I could reproduce that only on the BatteryBox. But i will fix the BatteryBox which still has bugs.

**Comment by bpeeters** [comment]
Hey Speiger,

I'm seeing this same problem in Tekkit Legends with both the MFE and MFSU as well as the batbox.

**Comment by Speiger** [comment]
@bpeeters that was another bug which had nothing directly todo with the electorlyzer. (its how the energystorages handled the API)

**Comment by bpeeters** [comment]
Ok, thanks.

**Comment by phit** [comment]
this is not fixed in "1.1.2.1 (Hot Fix)", easy reproduction:
get a mfe, mfsu filled up over 70%
put an electrolyzer next to it and put one water cell in

result: the mfe/mfsu will be completely drained

**Comment by Speiger** [comment]
@phit as said: this bugreport was posted after the hotfix. So it can not be fixed in the hotfix
