### ISSUE TITLE
UU-matter recipes not showing in NEI

### ISSUE THREAD

**Issue by Zaflis** [TinyModularThings/IC2Classic#136]
As the title suggests. I can craft things with UU matter, but recipes are currently kept in secret. Is this on purpose, and should it change?

**Comment by Speiger** [comment]
They are secrets. Changesble in config.
Not a bug. It is a feature since IC2 Exsisted.

**Comment by Speiger** [comment]
They are secrets. Changesble in config.
Not a bug. It is a feature since IC2 Exsisted.
