### ISSUE TITLE
java.lang.NoSuchFieldError: noneClassicRegistry - IC2 Wrench Plugin

### ISSUE THREAD

**Issue by Tsyklop** [TinyModularThings/IC2Classic#137]
http://pastebin.com/FtdLfLjt

IC2Exp...

**Comment by Speiger** [comment]
API Confliction. Could you please show me your modpack (just make a list with all installed mods + versions)

**Comment by Speiger** [comment]
I will update the API with the next IC2 Classic version... just for now its impossible to fix that...

**Comment by Tsyklop** [comment]
@Speiger crash log has a full list of mods.
version 1.7.10

**Comment by Speiger** [comment]
@Tsyklop its my Nei Plugin. I need to update the API in there too^^" Will be done today...

**Comment by Speiger** [comment]
To fix it. Delete all IC2 API files out of the Nei Plugin. Since the other plugin is installed it will work fine^^

**Comment by Tsyklop** [comment]
@Speiger I do not install NEI Plugin.

**Comment by Speiger** [comment]
@Tsyklop you do. The CropPlugin i made is the Nei Plugin.
^^

**Comment by Tsyklop** [comment]
@Speiger Thx. Working

**Comment by Chocohead** [comment]
This is why Greg says to never include API files with mod releases ;)

**Comment by Speiger** [comment]
@Chocohead yeah the reason here is that i need Classic API classes which Exp does not provide...
So i have to do that. (Problem is that i made that change after releasing the API for the CropPlugin)

**Comment by Speiger** [comment]
Fixing with the Classic API Update anyway...
