### ISSUE TITLE
Crash when stating game.

### ISSUE THREAD

**Issue by modmuss50** [TinyModularThings/IC2Classic#138]
Crash log:
https://gist.github.com/modmuss50/f77e10a52428cc8f4300

How to Reproduce:
Start the game

I was running in my dev environment exploring this issue, https://github.com/TechReborn/TechReborn/issues/198 but then my game would not start.

I'm not sure if its TechReborn breaking it or something else.

**Comment by Speiger** [comment]
Yeah that is the recycler API... I am check that. Give me a min.

**Comment by Speiger** [comment]
Reset the Recycler String. You need to insert the ModID:Block/Item not Block/Item that does not work...
That should solve it...

To the Crash that Minesasha tells thats something differend. A mod (i think it is yours) is returning a null on the function "getItemStackDisplayName" that is a case which you never should let happen!
