### ISSUE TITLE
Kicked out to main menu

### ISSUE THREAD

**Issue by ThisisCanada98** [TinyModularThings/IC2Classic#141]
After Switching out IC2 Exp for IC2 Classic I get kicked back to the start menu of Minecraft when trying to start a previous world or even a new one. I put what the launcher gave me into a text document and put it into drop box because it was to large for pastebin. https://www.dropbox.com/s/ikkc1i03bf8wn99/LOGZ.txt?dl=0

**Comment by Carbon-Ghost** [comment]
Have you just out of curiosity reset your configs ? I remember loading an exp world upgraded to classic just fine ( though I removed all IC2 exp related stuff from mobs, containers, myself, block etc.. )

**Comment by ThisisCanada98** [comment]
I did try reseting configs and getting rid of all ic2 items from the world before hand. The problem is even present when I create a new world.

**Comment by Speiger** [comment]
Not enough Resources again. Just delete that mod and no longer a problem.

**Comment by Speiger** [comment]
@hilburn please use proper reflection to load your plugins else this happens... Not my fault!

**Comment by ThisisCanada98** [comment]
Thank you very much!

**Comment by Speiger** [comment]
why that?

**Comment by ThisisCanada98** [comment]
For helping me out. I really appreciate it.

**Comment by Speiger** [comment]
ok^^
