### ISSUE TITLE
Machines get "ghost" itemstack when full output stack is taken out

### ISSUE THREAD

**Issue by Barhandar** [TinyModularThings/IC2Classic#142]
Tested in singleplayer only so far.  For example, smelt 64 iron ingots into refined iron, take out the 64 refined iron ingots. A single "ghost" (will disappear if attempted to stack, but otherwise persists even in chests and over world unload, and _can be used for crafting_) refined iron ingot will appear in the output slot, and will interfere with processing anything else while it's there. Happens with _any_ full output stack and probably all machines (tested with macerator, furnace, compressor and extractor). I suspect it's an itemstack with '0' items in it, thus the behavior.

**Comment by Carbon-Ghost** [comment]
Oh that.. That is an important bug, may lead to dupe, like the old 1.5 dispenser diamond dupe...
Yeah I also think it's the 0 item stack ( why the hell mojang did even implement that... ), basically, it can go in your inventory though you can't hear it, won't stack, when is in your inventory, the in world version is still here, and the fake diamond will despawn in the world and in inventory after 5 minutes, but it's more than enough time to create actual diamond blocks...

**Comment by Speiger** [comment]
Fixed.
