### ISSUE TITLE
Electrolyzer not working

### ISSUE THREAD

**Issue by InterstellarFish** [TinyModularThings/IC2Classic#143]
Hey everyone,

today I want to report a bug with the Electrolyzer. This bug was found with the Tekkit Legends Modpack, but I also tried the mod "alone", so I was sure that there weren't any issues concerning configs and stuff like that. The problem is, that when the Electrolyzer containing a water cell, is connect to full Energy Storage Block, it does consume the Energy (almost empty), but doesn't give out the Electrolyzed Energy Cell. To make sure that make setup is not wrong, I did the same thing with the "original" IC2 and it worked. I hope you can look into this issue soon, so the modpack can be updated with a fixed version.

-InterstellarFish

**Comment by Speiger** [comment]
Was already posted and it is fixed. But thanks for reporting =3
