### ISSUE TITLE
Mine And Blade: Battlegear 2 crashing on at ic2.core.item.tool.ItemElectricToolChainsaw

### ISSUE THREAD

**Issue by Cloudioa9** [TinyModularThings/IC2Classic#145]
Mods:
   Mine and Blade: Battlegear2
   Latest IC2 Classic 1.1.2.1

re-create: Go into battle mode and right click any mob/entity
here's the crash log.
[crash-2015-11-14_22.40.49-server.txt](https://github.com/TinyModularThings/IC2Classic/files/34813/crash-2015-11-14_22.40.49-server.txt)

**Comment by Speiger** [comment]
i call that a close one. Because today is release/Update day so i am not sure if i am able to fix it. Wish me good luck to track that down.

**Comment by Speiger** [comment]
fixed
