### ISSUE TITLE
issue with CustomOreGen

### ISSUE THREAD

**Issue by Steampunkr** [TinyModularThings/IC2Classic#147]
[CustomOreGen Error.txt](https://github.com/TinyModularThings/IC2Classic/files/37031/CustomOreGen.Error.txt)
Adding this mod doesn't cause the game to crash, but it does make CustomOreGen stop working. The attached file is pretty much the only relevant section, when I try to open the CustomOreGen menu, which turns out blank. I've tried deleting the CustomOreGen config, thinking it might be related to switching to this mod from IC2Exp but that didn't work.

Even if this isn't on your end I would like to know if you have a fix please, because I really want to play with this mod.

**Comment by Speiger** [comment]
Hmmm not sure whats causing that. Let me research it. (if it requires a sourcecode fix then it will be not possible because i wait at least a week to find important bugs)

**Comment by Speiger** [comment]
ok. It is something. You simply have the wrong ItemName for IC2 Copper dust... That is causing Crashes...
So update your Config of that mod and there should be no problem.
If you do not know the names from IC2 Classic then give me a list of all Items you need and i give you the names you require...
(Note you need to tell me if you need the item name or if you need the name from the gameregistry)
@Steampunkr

**Comment by Steampunkr** [comment]
I think that ic2CopperDist is supposed to mean the distribution of IC2's copper ore, and that the default can't be "disabled"
Hmm... the fix might be entirely on CustomOreGen's side. Although it's .xml configs are a bit confusing

**Comment by Speiger** [comment]
well then i suggest ask the modauthor of this thing. I can do not much about it since he is doing it internally. @Steampunkr

**Comment by Steampunkr** [comment]
Yeah, I think I see the problem. There's 2 defaults, with disabled being the second one. I'm going to close this since it doesn't have to do with this mod

**Comment by Speiger** [comment]
ok. thanks^^
