### ISSUE TITLE
Error appearing in console a lot

### ISSUE THREAD

**Issue by Nentify** [TinyModularThings/IC2Classic#148]
http://pastebin.com/mX2S1RQV

Getting this error in the console a lot, but I'm pretty sure no cables exist in the world at the moment. It happened on 1.1.2 and is happening when I updated to 1.1.3.3 as well.

**Comment by Speiger** [comment]
Interesting. This crash would only happen when cables are loaded... Maybe a bug of not clearing data incorrectly. Please give me some more infos about how it happens (situation) that would help

**Comment by Nentify** [comment]
I'm not doing anything, it just appears in console exactly every 30 seconds.

**Comment by Speiger** [comment]
yeah. Cauldren modfies stuff with TileEntities... So thats why it can happen...

**Comment by Nentify** [comment]
It doesn't start occurring immediately on startup. I will try to test it a bit more, but not sure what else I can do.

**Comment by Speiger** [comment]
well the log says that a transformer calls this problem. Do you have a transformer placed? (that causes MC to foam a cable and causes this problem...) but i never had this problem with a transformer or something like that.... Weird...

**Comment by Nentify** [comment]
After looking at the logs, it seems to occur for the canner too and probably others. I will try it in a fresh world in a couple of hours and see if I can figure anything out.

**Comment by Speiger** [comment]
that would be great. At the moment i am really busy with real life stuff so this month you can not expect a update...^^" Just so you know

**Comment by Speiger** [comment]
Closing. If there is any problem left you can tell me.
