### ISSUE TITLE
NEI Broken

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#15]
Every IC2 shaped and shapeless recipe is missing when you try searching them in NEI. The recipes all seem to work, just not show up.

**Comment by Speiger** [comment]
Not a bug.
I did remove the NEI and Crafting Guide intigration.
Will be implemented soon. I Need to find the API/Dev files befor i can do that.

**Comment by Speiger** [comment]
Nei & Crafting guide support added again. Crafting guide was faster than nei (in terms of errors xD)
