### ISSUE TITLE
IC2 core?

### ISSUE THREAD

**Issue by Robotia** [TinyModularThings/IC2Classic#151]
Where is the IC2 core? I only see the api source on GitHub and the compiled core in the releases. Are you not making the core public?

**Comment by Speiger** [comment]
@Robotia you know that IC2 is closed source.. This github page is just there to show the API which classic has so people can support it and a bugtracker so i can get easy bugs and suggestions together...
If i would upload the IC2 Classic source i would go against the IC2 Licence....

**Comment by Robotia** [comment]
@Speiger I was not aware of that, my apologies. Thank you :)

**Comment by Speiger** [comment]
No Problem....
