### ISSUE TITLE
Geothermal generator

### ISSUE THREAD

**Issue by ebildude123** [TinyModularThings/IC2Classic#153]
Using any transport pipe going underneath the geothermal generator always places what's pumped (e.g. lava bucket) on to slot on top instead of the bottom slot even when pipe goes underneath the geothermal generator.

edit: not sure if it's a problem with ic2 or the pipe mod though (bc transport)

**Comment by Speiger** [comment]
@ebildude123 this is not a bug, i intendet it.
Since Fluid Pipes are a usual thing in MC (it was not before) i decided to keep the none accessable slot for lava buckets / cells... The simple reaon is you can already pump fluids in...

**Comment by Ivar418** [comment]
@Speiger is there a way for me to edit the mod and add an open slot for this?
