### ISSUE TITLE
DenseOre/PoorOre compatibility

### ISSUE THREAD

**Issue by bigstiffy** [TinyModularThings/IC2Classic#156]
This was a bit of an issue when trying to configure a couple other mods, but the fix was simple enough.
DenseOres and PoorOres try to look in a 'blocks' folder for base block textures for texturing new ores dynamically, making it an issue for adding copper/tin/uranium from ic2-classic since there is no such folder.
Fixed it by just extracting the copper/tin/uranium textures from textures/sprites/single/ in the jarfile, putting them in a folder labeled 'blocks' and merging that folder under textures in the jarfile.
Not a big issue, but does prevent compatibility with those two mods.

**Comment by Speiger** [comment]
@bigstiffy ok i will merge the Files with the next files... Should i add special Recipes for these mods? (getting macerating recipes or extractor recipes)

**Comment by bigstiffy** [comment]
I don't think it's necessary to add explicit recipes for it as it seems recipes are already registered, the dense ore when macerated yields 4x the (generated) ore blocks, and smelted yields 3 ingots. The poor ore yields 1/9th of 1 ore yield when smelted (1 nugget, 9 to craft a full ingot/dust). This seems to hold true for all manually added dense/poor ores.

**Comment by Speiger** [comment]
Fixed
