### ISSUE TITLE
FakePlayers?

### ISSUE THREAD

**Issue by Robotia** [TinyModularThings/IC2Classic#157]
Can IC2Classic implement something similar to @gamerForEA's [IC2-FakePlayers](https://github.com/gamerforEA/IC2-FakePlayers)?

I think his code can be adapted, but I have not tried it myself.

**Comment by Speiger** [comment]
Why does IC2 need fakeplayers @Robotia ? Terraformer do not need a player to place blocks...
And the miner uses already a FakePlayer...

**Comment by Robotia** [comment]
For the filler, which doesn't implement a fake player and bypass Bukkit style protection. @Speiger Also, the wrench automatically removes machines without checking if the player has the ability to do so.

**Comment by Speiger** [comment]
Well the Terraformer requires no Fake Player... @Robotia.... Or what do you need it for. give me a example? ItemNBTData is aviable in my API now and that is good enough...

**Comment by Speiger** [comment]
@Robotia did not watch everything from your comment:
* Wrench does send PlayerData over to the TileEntity so its the machines that store no the Player. Has nothing todo with the Items..
* Terraformer. True but terraformer exchange blocks and not distorying them... And when you have safty in the world then it does matter if the block get exchanged... (And nobody supports the terraformer so no worry about addons changing something extremly)

**Comment by Speiger** [comment]
Unnessesary
