### ISSUE TITLE
Splitter Cables

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#16]
They work now, but require a direct redstone signal (ie, a lever right next to them), and still ignore redstone wire, even if it is powered.

**Comment by Speiger** [comment]
Try redstone above a block or a repeater...
I need still to figure out how the new Redstone mechanic works.
Some functions are changed.. But it works at least.
And with Mod cables there should be no problems.

**Comment by Speiger** [comment]
Tested... That is a vanilla bug..
If redstone connects directly to it and the texture make a straight line...
I do not know how it will be handled with modded wires. But i can not fix the vanilla redstone.
Sry
