### ISSUE TITLE
IC2 Classic

### ISSUE THREAD

**Issue by FaresSpeed** [TinyModularThings/IC2Classic#160]
Hey,
I was trying to make a protection file for IC2 Classic in mytown
when I went to check the mod files it was missing the mcmod.info which it's important to track the mod entities 

please can you fix it?

**Comment by Speiger** [comment]
@FaresSpeed well MCMeta file is generated in code instead of via file...
what info do you need?

**Comment by FaresSpeed** [comment]
the mod id if you don't mind

**Comment by Speiger** [comment]
Well if it is not IC2 then addons will not load their recipes and co..

**Comment by FaresSpeed** [comment]
hmm, well I tried to search for the modid IC2
it didn't work, either from my bad coding or I missed up something

**Comment by FaresSpeed** [comment]
may I know where's the code located? in order to figure the problem

**Comment by Speiger** [comment]
Its in the IC2 Class, line 439...

**Comment by FaresSpeed** [comment]
okay thanks for the info :D
