### ISSUE TITLE
Lag on chunkunload after updating server to most recent version

### ISSUE THREAD

**Issue by Rubbertjuh** [TinyModularThings/IC2Classic#162]
Hello,
Yesterday I updated my server to the most recent version of IC2, this seems to have solved the main issues. But it also created a new issue, sometimes the server has these insane lag spikes. 
And its coming from IC2, please check the screenshot from WarmRoast below for more details.
https://gyazo.com/260fb24415401cea90b2c9d901f358b0
Is there anything I can do about this to fix the lag spikes ? 

Please get back to me :)

**Comment by Speiger** [comment]
@Rubbertjuh that does not help me really.
Here is the thing i improved the EnergyNet Drasticly that it will not calculate to much and also stacks calculation (simply combine 500 calculation to 1 calculation) which is a way to shrink down the time... Now the question is. Why do you get the lagspicks still? I can not tell it by that picture. Please show me your World... That would be helpfull (video or pictures i do not care but do not leave any IC2 Peace out)

**Comment by Rubbertjuh** [comment]
I would love to send a video but I'm running a productive server, it has a map of 5000x5000. 
And basically everyone uses ic2 in this modpack.
If you like you can join my server to take a look, the ip is play.toastcraft.info 
Running the latest version of Tekkit Legends.
If there is anything I can do to help you further, please tell me. 
I can even give you temp. access to my server to test some fixes.

**Comment by Speiger** [comment]
@Rubbertjuh could you join my IRC channel for a faster talk? #IC2-Classic (EsperNet)

**Comment by Rubbertjuh** [comment]
I will join the IRC when I'm home @Speiger , currently on school. Will be home in 2 hours. You can also add my Skype if you prefer thay :) 
Skype: brend72

**Comment by Speiger** [comment]
@Rubbertjuh oh ok. Skype is private use only so nope.

**Comment by Speiger** [comment]
@Rubbertjuh how is the testing?

**Comment by Rubbertjuh** [comment]
@Speiger haven't gotten to testing yet. Been really busy with my final school project. I do have a fixed jar for the calculations though! Meet me on IRC, I'll share and you can fix it :)

**Comment by Speiger** [comment]
@Rubbertjuh even if the lag is the not best thing it can happen to you. But the Version @Robotia gave you solves not the problem. Actually it creates a huge differend problem: If a Machine/Cable gets dissconnected it the generator/Power storage will continues send more Energy to these targets as long no new wires get added.... thats a huge problem...

**Comment by Speiger** [comment]
@Rubbertjuh i suggest to you that you try out the latest version i uploaded.

**Comment by Rubbertjuh** [comment]
@Speiger Thanks a lot for the latest update.
Seems to have fixed 99% off the problems ^_^
Awesome stuff! Keep up the good work!

**Comment by Speiger** [comment]
@Rubbertjuh yeah but there is 1 big bug in it which i will fix in a minute

**Comment by Rubbertjuh** [comment]
@Speiger What is it if I may ask?

**Comment by Speiger** [comment]
Well lets say. If a Explosion acurs why ever your server wont like it....

**Comment by Rubbertjuh** [comment]
@Speiger wow darn.. I know what you're talking about ^^ 
How's the fix coming along?

**Comment by Speiger** [comment]
@Rubbertjuh its release 1.1.3.7.2 Has it fixed.

**Comment by Rubbertjuh** [comment]
@Speiger https://gyazo.com/9169c192a3ed382ceb1fa463fcc3653f
It's 1000 times better, still getting the occasional lag spike though. 
This is only with 17 people online and 67k tiles loaded.
Started out of the blue. 
Lag Spike will stay here for like 5 min and then it will be gone.

**Comment by Speiger** [comment]
Yeah that is not really fixable... Simply because: All the Paths have to be builded... And that is laggy... After they are done they are fine... That is the problem...
Also thats not only EnergyNet....

**Comment by Rubbertjuh** [comment]
Everything is fixable in my opinion. 
Why is it not only EnergyNet? 
These things might indeed slow down the progress, but keep in mind that many modpacks will not update for a long time. And this will be a solution for a lot of servers having this issue.

**Comment by Speiger** [comment]
@Rubbertjuh no not everything... The vector part is fixable but the lag that is created by constructing a path is limited fixeable... At a special range of targets i can do nothing...
Networking takes also a long time because of the way how it creates packets for TileEntities... (Is fixed but not in the hotfix version)
And yeah thats why in the next couple days (until this weekend) there will be nothing for the Hotfix version made... (It provides me with time for testing and also improving the source and get progress done. After that is done at least a bit i can bring the improvements to the hotfix version)

**Comment by Robotia** [comment]
Lambdas! :sunglasses: (just kidding)

**Comment by Speiger** [comment]
o.o whatever that means

**Comment by Robotia** [comment]
http://www.oracle.com/technetwork/articles/java/architect-lambdas-part1-2080972.html

**Comment by Speiger** [comment]
Should be solved by now....

**Comment by Rubbertjuh** [comment]
@Speiger Did you add anything for it to be fixed or?

**Comment by Speiger** [comment]
jup... if more is needed then i did then i have to add a limiter or something... (means: Energy can be limited... Because else i have to drop features and i rather take a enet that is laggy at high usage then having some core features removed)
