### ISSUE TITLE
Railcraft CESU cart causes crash

### ISSUE THREAD

**Issue by Nygmus** [TinyModularThings/IC2Classic#163]
IC2 Classic successfully triggers Railcraft's IC2 integration. However, IC2 Classic does not include the CESU, while Railcraft does have a CESU cart.

If the CESU cart is placed or spawned using creative mode, it causes a crash and will continue to crash any client which loads the chunk containing the cart.

**Comment by Speiger** [comment]
@Nygmus jup i am ware of that and belive me you have either remove the Entity or reset the world... I have to write a Semi Railcraft fix for that and i do not have really much the time. Simply: It tries to render the CESU Item and it will crash because its not a block in IC2 Classic...

**Comment by Speiger** [comment]
https://github.com/CovertJaguar/Railcraft/pull/784#event-595572622
@Nygmus update Railcraft as soon its getting its release
