### ISSUE TITLE
Client Crashes - Rendering Issues

### ISSUE THREAD

**Issue by Rubbertjuh** [TinyModularThings/IC2Classic#164]
Hello and thank you for the support.
A lot of people seem to have client crashes lately. I have had more than 12 reports of clients that crash when rendering a certain item. 
Here are 2 crash logs from 2 different people.
Hopefully this is something we can fix! 
http://hastebin.com/nenejojayu.cs
http://hastebin.com/cudofapona.cs
I would do anything to help you fix the issue.

**Comment by Speiger** [comment]
@Rubbertjuh best way. Distroy these block... That has nothing todo with IC2 Classic...
Its telling me that it tries to Render a Hopper... o.O Anyway distroy the cables...

**Comment by Rubbertjuh** [comment]
Easyer said then done. But if this isn't IC2 related, then I will close this issue

**Comment by Speiger** [comment]
@Rubbertjuh worldEdit or use tools that allow you to distroy stuff in positions...
