### ISSUE TITLE
Big Ranged OV Scanner works only on 5x5 tiles 

### ISSUE THREAD

**Issue by Eliri** [TinyModularThings/IC2Classic#167]
Hey :) 
The Big Ranged OV Scanner works only on 5x5 tiles, while the normal OV Scanner mines 9x9 as intended. 
Sadly I found nothing via google about this topic (or the item itself Oo )

**Comment by Speiger** [comment]
You are about 3 months to late...
https://github.com/TinyModularThings/IC2Classic/releases/tag/1.1.3.7.1
Also please check this version out (its not the latest) but there stays:
-Fixed: Scanner uses now right amount of Power in the miner. (Also Ranged is fixed...)
https://github.com/TinyModularThings/IC2Classic/releases
Here you find the latest one
