### ISSUE TITLE
Right clicking lava with 1 empty cell gives 8 full lava cells.

### ISSUE THREAD

**Issue by parcel31u** [TinyModularThings/IC2Classic#168]
Getting reports like these : http://minecraft.curseforge.com/projects/material-energy-natural-capital/issues/16

**Comment by Speiger** [comment]
Just a question do you modify anything on the LavaCell @parcel31u ? Because it copies the Item in the Registry which means that could be messed up? (The registry is supposed to have a stacksize of 1)

**Comment by parcel31u** [comment]
I did not, but I do have techreborn in the pack. The stacksize of lava cells are 64.

**Comment by Speiger** [comment]
@parcel31u no the stacksize in the registry is 1. The maxStacksize is 64... Someone must have changed it...

**Comment by Speiger** [comment]
Also techreborn does not access IC2 Core classes. It accesses the API...

**Comment by Speiger** [comment]
@parcel31u i tested it and it did not work... no matter how i tried it...

**Comment by Speiger** [comment]
@parcel31u version 1.2.0.1 has now a preventation methode in it which should prevent that bug... Unless someone messes in it while the world is loaded..
