### ISSUE TITLE
IC2 Classic 1.2.0.0 startup crash with Project E (?)

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [TinyModularThings/IC2Classic#169]
As soon as I update IC2 Classic to the latest version 1.2.0.0 it crashes on startup, I think with ProjectE. I tried deleting any IC2-related custom EMC value, but the crash still occurred. Doesn't occur with IC2C 1.1.3.7.3.
crash report: http://pastebin.com/yjidrkKG
Thanks for your help in advance.

**Comment by Speiger** [comment]
@SmokeyTheBandicoot the EMC plugin crashes. thanks for the bugreport. You can shut down the EMC plugin in the config. That will prevent it from loading. That will prevent the crash.

**Comment by SmokeyTheBandicoot** [comment]
Thank you, it worked!. But what does the ProjectE plugin do exactly? What features will be disabled now (just for curiosity)?

**Comment by Speiger** [comment]
It dissables the EMC support. The Fix for useless calls on generators and also preventation of the mininglaser can be pushed away...

**Comment by SmokeyTheBandicoot** [comment]
Well, thank you. Hope for a fix, I never enjoyed IC2 so much since 1.4.7. Keep up the good work!

**Comment by Speiger** [comment]
@SmokeyTheBandicoot you dissabled RubberTrees Right? Well thats causing it. I fix it right now.

**Comment by SmokeyTheBandicoot** [comment]
Thank you very much. Hope to see a new release soon ;P
