### ISSUE TITLE
Change Nuclear Fuel

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#17]
Thinking of an idea to make Nuclear reactor fuel.
Not sure yet. Get explained at the same time with the adding with the steam reactor..

**Comment by Carbon-Ghost** [comment]
Maybe keep Refined Uranium and add Plutonium and Thorium like the old GT ? It would also work like GT ^.^ Because it was balanced
:D

**Comment by Speiger** [comment]
Plutonium was anyway planned.
The thing is how the Uranium should be used.. (In terms of consumption)

**Comment by SynfulChaot** [comment]
I hope thorium gets added as well.  It could add for some interesting complexity.

**Comment by Speiger** [comment]
@SynfulChaot first you have to be fine with the Nuclear Jetpack ^^"

**Comment by ExDomino** [comment]
Don't forget that mod is IC2 Classic. If you make too many changes, the mod will lost its classic status.

**Comment by Speiger** [comment]
Yeah i know, but i learned also, there is always progress in something.
People wll yell at me if i do not work on that mod and show progress.
The Plan is only to adjust the DropRate from Depletet Uranium Cells because you can get a chance to get Depleted Uranium Cells which can give you Plutonium (for the Heat based Reactor Setups)
And a Steam Reactor will be joining too. But the BaseMechanic will stay thats sure.

**Comment by Carbon-Ghost** [comment]
It won't loose it's classic status, as it still follows IC2 classic rules ( old E-net and machinery ), classic doesn't mean it will be like old IC2 forever, but rather it means that it will be like the old IC2 with some additions from time to time like the old one, and we are trying to implement the features that we're planned on classic but then scrapped at exp ;)

**Comment by Carbon-Ghost** [comment]
Well during the upload of my post ( internet lag spike ) you ninja'd me ;P

**Comment by Speiger** [comment]
Yeah. But @ExDomino i am happy that you put your Opinien also in. It is always good to have people that say something to the planned additions.
Unlike the Exp Dev team (which throws things in how they want and do not really put the opinien of the Comunity (not all of them are but there are people of the Dev Team that do this)), i will try to keep as much throughput of the People and add on based on the ideas i have or get suggested and the opinien of a much people i can get and add the parts which fit most and are liked most^^"

**Comment by dustojnikhummer** [comment]
Yellorium Support?

**Comment by Speiger** [comment]
@dustojnikhummer
What do you mean?
Details please

**Comment by Carbon-Ghost** [comment]
Basically, Yellorium is a magic nuclear fuel which is infused uranium, and is OD as uranium and basically is just uranium, the infusion makes it simply change color and look like yellow xD It's 10x more common than normal IC2 uranium and comes into huge veins...

Also I don't why I said all of that, because normally it should already work... ( yellorium is OD as uranium so you can already use it for crafting nuclear cells... )

**Comment by Sicken009** [comment]
I have a suggestion for Nuclear Reactor fuel using redstone, glowstone, blaze rods, ender pearls, etc. to change or enrich uranium into something else to make it produce more heat/energy. or maybe even enchanting the fuel cells to create strange new effects. also another thing is the nether star could be use as a fuel source as well. I just hoping to give you some ideas. nothing more.

**Comment by Speiger** [comment]
@Sicken009 that is a interesting idea... It would be a really new idea for sure. But i think instead of using a reactor to infuse the uranium there should be a special block...
^^"

**Comment by Sicken009** [comment]
Just the name **Uranium Infuser** makes me excited.

**Comment by Speiger** [comment]
Hehe. If you have IRC @Sicken009 on EsperNet join the Channe #IC2-Classic

**Comment by Carbon-Ghost** [comment]
I like the idea of nether star rods...
