### ISSUE TITLE
Server Crash on startup (NEI module?)

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [TinyModularThings/IC2Classic#170]
It's me again, this time with a server crash on startup. Forge 1614 (latest), IC2 1.2.0.1

Crash log: http://pastebin.com/UJbNthM8

Thanks for your help in advance

**Comment by Speiger** [comment]
@SmokeyTheBandicoot you try to load the IC2 Nei Plugin on the server... It has nothing todo with IC2 Classic itself... Remove that mod from your server list.
Also you run the first version of curse on it... Check curse for newer versions. It could be possible (i could not test it really) that the latest version is useable on a server (it just prevent the loading)

**Comment by SmokeyTheBandicoot** [comment]
Oh, my mistake. I actually forgot the IC2 NEI Plugin being  a separate mod. I confused it with the NEI module in IC2 classic. Sorry for that. Easy fix. Thank you
