### ISSUE TITLE
No class found of Ic2 core

### ISSUE THREAD

**Issue by Fortist** [TinyModularThings/IC2Classic#176]
http://pastebin.com/VGM7GP99
What am I missing?

**Comment by Fortist** [comment]
Something is wrong with the curseforge version, because I downloaded the version on here and it works fine I guess.

**Comment by Speiger** [comment]
@Fortist what version did you try to run?

**Comment by Fortist** [comment]
The latest, 1.2.0.2.

**Comment by Speiger** [comment]
Thanks i will validate that.

**Comment by Speiger** [comment]
Interesting. But the versions are 100% Equal... xD I took those from the same place... Maybe bug on the file transfer on curse?

**Comment by Fortist** [comment]
Just double checked to make sure It wasnt my shenanigans on the side.
Ill download it again and try it again, to triple check it wasnt shenanigans.

**Comment by Speiger** [comment]
o.o ok let me check it with the curse file. Did you only have the ic2 mod in the curse download?

**Comment by Fortist** [comment]
I should clarify, a curse_forge_ download fuck up*
You were correct, it was something with the download, because I redownloaded (from curseforge) and it works just fine. Thanks for replying, however.

**Comment by Speiger** [comment]
Hahaha. No problem.
