### ISSUE TITLE
Converter Blocks

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#182]
- [ ] RF - EU Converter needs to be added
     - [ ] LV
     - [ ] MV
     - [ ] HV
- [ ] EU - RF Converter needs to be added
     - [ ] LV
     - [ ] MV
     - [ ] HV
- [x] Basic Steam Turbine needs to be added

**Comment by Speiger** [comment]
Cancelled RF generators. Not going to be in 1.10.2 Because of COTH RF API Beeing dead...

**Comment by Reoseah** [comment]
COTH? I thought it is CoFH's )

**Comment by Speiger** [comment]
ty @Reoseah xDD
