### ISSUE TITLE
Mining laser hotfix request

### ISSUE THREAD

**Issue by soulgriever** [TinyModularThings/IC2Classic#194]
when using the mining laser on a kcauldron server it works flawless with res thanks to your fake player, however explosive mode can still bypass the res, in the past there was a simple fix that just allowed you to disable explosive mode in the mod config could you incorporate that for 1.7.10?

**Comment by Speiger** [comment]
Ok. I researched a bit and found out that i missed a explosion Event which forge did add. (that allows people to dissable it)... IC2 has actually a Event for that too but forgeplugins of any kind do not really support that...
I add a event check on that too... (I think its time for another update on 1.7.10)

**Comment by Speiger** [comment]
Fixed it
