### ISSUE TITLE
Jetpack does not fly in IC2 Classic Test Version 1.5.9 in Minecraft 1.6.4, but it works in IC2 Classic Test Version 1.5.5

### ISSUE THREAD

**Issue by gruenebanane** [TinyModularThings/IC2Classic#196]
The noise and power consumption while trying to fly is like flying, but you can't get into the air. In IC2 Classic Test Version 1.5.5 everything works fine.

**Comment by Speiger** [comment]
Em yeah @gruenebanane i can not fix a 1.6.4 version anymore because i can not make a workspace for 1.6.4 anymore... Sadly...
Sry...

**Comment by Speiger** [comment]
To explain this: Since 1.6.4 the New MC launcher came out and if you try to make a workspace in 1.6.4 (where gradlew was not a thing (i checkt it multible times)) you needed the MC Jars + Libary Jars in a special folder & order... I can no longer make that order... So yeah its unfixable...
