### ISSUE TITLE
IC2Classic 1.7.10 Bug collection for 1.2.0.4

### ISSUE THREAD

**Issue by yaroslav4167** [TinyModularThings/IC2Classic#198]
Furance Exp-dupe and Cropnalizer-dupe.
Principle - [YouTube](https://www.youtube.com/watch?v=-Usf3rvMauw) 
Please, fix this bugs =)

**Comment by Speiger** [comment]
@yaroslav4167 which ic2c version is that?

**Comment by yaroslav4167** [comment]
@Speiger 1.2.0.3

**Comment by Speiger** [comment]
ok. So these are 2 bugs.
- [ ] Furnace not allowing to add Items too (even so who when a player ha the time to do this then he should be allowed to get exp xD)
- [ ] ItemInventories should close the inventory when thrown...

**Comment by Speiger** [comment]
@yaroslav4167 both fixed.
If you have anything else just point it out. (I am still collecting bugs to make a proper version)

**Comment by yaroslav4167** [comment]
Thank @Speiger 
I don't know more bugs and duplications.
Tell me about when will 1.2.0.4?

**Comment by Speiger** [comment]
well if nothing else joines and i do not get my feature done until that then it will be start of next week
@yaroslav4167 ^^"

**Comment by yaroslav4167** [comment]
I found another bug. When you open the safe on the server - client crash.
http://pastebin.com/BzTWpfP9

**Comment by Speiger** [comment]
- [ ] Personal Safes Causing Client crash on servers when opend.

Ok one question: Are you the owner of the personal Safe or are you just trying to open a safe from someone else? (thats important)

**Comment by Speiger** [comment]
@yaroslav4167

**Comment by yaroslav4167** [comment]
@Speiger I am alone on the server, so that a safe mine =)

**Comment by Speiger** [comment]
@yaroslav4167 fixed it. (I hope it, because i can not test it (i can not run a server in my dev invioment)

**Comment by yaroslav4167** [comment]
Many thanks @Speiger ! I hope everything will be good =)

**Comment by yaroslav4167** [comment]
Cropnalizer bug remains =с
Version: 1.2.0.4.

**Comment by Speiger** [comment]
@yaroslav4167 well normally you would not drop these items like that....
I open a new list soon... But for this week = no work on ic2c i have another project which gets high priortiy.
Test all the other stuff you found. (All Hendheld inventories have that too)
Also your suggestion = very laggy... I dissagree... (i have already a soultion)

**Comment by Speiger** [comment]
Closed i am opening soon the new list for the 1.2.0.5 update but this is going to still wait a couple weeks xD
