### ISSUE TITLE
items disappearing after exiting the macerator GUI with ic2 classic 1.2.0.4

### ISSUE THREAD

**Issue by escman1999** [TinyModularThings/IC2Classic#202]
here's a screenshot before i exit the macerator's GUI https://imgur.com/a/NZE4B

and here's one after i exit the gui and come back in a second later https://imgur.com/a/OjZJk notice how the obsidian dust isn't in my inventory or the macerator's gui

EDIT: the same thing is happening with the compressor

**Comment by Speiger** [comment]
Interesting.... i found no code at all that would cause a senario...
Also this is not a client bug only. Because even if the Item gets desynced the progressbar needs to be updated...
Just as proof make a video of it. Without any cuts when you can recause it... Because this seems strange...
(I did already take a look at the code and i try it out as soon i do 1.7.10 coding)

**Comment by escman1999** [comment]
i forgot to mention that i'm using other mods as well, so i'll test it with just ic2 classic and see if the bug still happens

**Comment by Speiger** [comment]
@escman1999 did it happen with ic2classic only?

**Comment by Speiger** [comment]
if not then i am going to close this

**Comment by escman1999** [comment]
testing now, it seems to be caused by another mod, you can close the issue

**Comment by Speiger** [comment]
Thanks :3
1.2.0.5 development starts soon maybe the changes fixes it

**Comment by escman1999** [comment]
just letting you know, the issue seems to happen with the FTB inventions modpack and a combination of some other moods, but i changed my modpack so that it uses the crackpack as a base, and the issue seems to be gone now

**Comment by Speiger** [comment]
Yay :3

**Comment by Fortist** [comment]
This is happening to me as well. Custom Modpack. So Im trying to figure out which mod causes the bug, but I dont know where to start, since it also affects another mod I have.

**Comment by escman1999** [comment]
please let me know if you find anything, fortist, so spiger can hopefully fix it for the 1.2.0.5 release :D

**Comment by Fortist** [comment]
I may have found something, but the mod in question doesnt actually show up in the FTB Inventions modpack.
VTweaks.
After removing it completely, the problem doesnt occur as far as Ive noticed.
Adding it back in and changing a few config options also 'fixes' it.
Im thinking it may be the "right click harvest crops" option. Im completely unsure.

**Comment by Speiger** [comment]
thanks @Fortist. Well mine is done by the block. Their could be done by an event...

**Comment by BBoldt** [comment]
```# Allows for right-click-to-harvest on nearly any (including mod) crop. No seeds will be dropped - intended
    B:"Easy Crop Harvesting"=false
