### ISSUE TITLE
Gravitation Suit for IC2 Classic?

### ISSUE THREAD

**Issue by fcpwiz** [TinyModularThings/IC2Classic#203]
Hi,

I noticed that the Gravisuit doesn't charge from the MFSU. I looked into it and saw that you mentioned that it's not properly set up for IC2 Classic and will only charge in a BatBox.

I found a fork of the Gravitation Suit mod which claims to be comparable with IC2 Classic: http://forum.industrial-craft.net/index.php?page=Thread&postID=195059. Though this mod was a no-go due to the fact that it didn't have the Gravisuite in the mod.

I was wondering- are there any Gravitation Suit forks/alternitves that are comparable with IC2 Classic?

**Comment by Speiger** [comment]
Well as far as i know not...

**Comment by Speiger** [comment]
@fcpwiz

**Comment by fcpwiz** [comment]
@Speiger Is there a way for you to update the mod to shift the power tiers down so the GraviSuit could be charged in a MFSU?

**Comment by Speiger** [comment]
@fcpwiz the problem is that the Graivity Suit Item has a To High tier... MFSUs can charge even weaker items then they are but stronger items are not possible...
Try out the BatteryBox (not the Batbox) that simply ignores tiers and charges almost everything that can be charged.
