### ISSUE TITLE
Texture for top of Nuke uses the ITNT texture.

### ISSUE THREAD

**Issue by CyanideX** [TinyModularThings/IC2Classic#206]
![Image](http://i.imgur.com/VWuvhb2.png)

**Comment by Speiger** [comment]
hehehe ^^" Yeah it does... do you want a special case only for nuke?

**Comment by Speiger** [comment]
@CyanideX prepaire a second texture for the Nuke i make a place for it...

**Comment by CyanideX** [comment]
Thanks. 😁
