### ISSUE TITLE
Waila settings do not work

### ISSUE THREAD

**Issue by artubi** [TinyModularThings/IC2Classic#208]
Hello,
Waila module doesn't seems to be working properly. When ingame, turning off everything in Waila settings makes no difference at all. All Waila info is still shown.  However, disabling it via config works.

Tested with:
IC2Classic Version 1.2.1.2.3
Waila-1.5.10_1.7.10

Also, rightclicking with crop analyzer on weed says "uknowen cop". Typo?

**Comment by Speiger** [comment]
This is not a bug. The config has a total Override for everything so you can enable everything if Waila fucks up. (I had often issues where the waila config dissabled everything that i wanted to see and could not enable it.) This is a feature. Also Pressing Hud Key is also a Override if you want to. (But you have to look at a EUUsing/Producing/Transfering block for that)

**Comment by artubi** [comment]
I just tried it. That config, isn't it reversed? because:
"Ignore Waila Config"=false - turning everything off in waila makes no difference, all info is still shown
"Ignore Waila Config"=tue - turning everything off in waila makes difference and all info is hidden

Also, I didn't knew that there is hud override. I thought it was for Quantumsuit Helmet. I mainly wanted to hide that "Require EU-reader in Hotbar to get Data" text.

Thanks for explanation.

**Comment by Speiger** [comment]
Oh sry i did not know you didnt wanted to see that. ^^" Well... I see what i can do...
