### ISSUE TITLE
[Bug] Galacticraft Sealable cables do not transfer IC2C power.

### ISSUE THREAD

**Issue by MaDmaxwell311** [TinyModularThings/IC2Classic#211]
Description of bug:
Galacticraft Sealable Cables ( Copper, Gold, Glass Fibre, ect... ) do not transfer power, the cables will connect, but no power will transfer through the cable.

**Comment by Speiger** [comment]
yeah thats galactric craft. They support that stuff not.
Here is my proof: https://github.com/micdoodle8/Galacticraft/blob/MC1.7/src/main/java/micdoodle8/mods/galacticraft/core/energy/tile/TileBaseUniversalConductor.java#L283

Its asking: Hey are you a IC2Cable if yes: We do not accept energy....
