### ISSUE TITLE
Carbon Boat turns into Electric Boat after quitting and starting

### ISSUE THREAD

**Issue by RdJNL** [TinyModularThings/IC2Classic#215]
Like the title says, every time I load my save, my carbon boat has changed into an electric one (without electricity, so I can't use it).

On a side note, the controls of the carbon boat are terrible compared to the vanilla boat.

Using version 1.2.1.4, Minecraft 1.7.10

**Comment by Speiger** [comment]
you are really lucky that i wanted to work on a patch for 1.7.10 today xD
(Not joking)
will be fixed with the next patch (which will be hopefully tomorrow)

**Comment by Speiger** [comment]
@RdJNL fixed. Thanks for the report

**Comment by RdJNL** [comment]
Thanks a lot for fixing this and for maintaining the mod in general :)

I'll be looking forward to the patch.
