### ISSUE TITLE
1.7.10 Bugs

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#216]
Got a bugreport so i mark it here so i dont forget. If you find new ones just add to here.

- Nano Saber (active i think) spams nei [Fixed]
- Config has Some misspelling: (Bronze Tools Disabled & UpgradeKit) [Fixed]

**Comment by yaroslav4167** [comment]
Exchange device crash the game (except TradeOMat)
TradeOMat - no checks at NBT items.

**Comment by Speiger** [comment]
@yaroslav4167 i know its 2 months ago but could you give me a crashlog with these trade o mat issues.
I push out tomorrow a fix and i kind want to have that problem solved.

**Comment by yaroslav4167** [comment]
1) Principe: https://youtu.be/LlcfULVsP4Y
    CrashLog: https://pastebin.com/whXtSHJT
2) Principe: https://www.youtube.com/watch?v=13_S1yy3VAQ
    CrashLog: https://pastebin.com/XuN4FMP3

And the name FluidOMat and EnergyOMat are confused.

**Comment by Speiger** [comment]
wow i didnt expect something that detailed and that fast ty.

**Comment by Speiger** [comment]
ok these issues are fixed now. Ty.

**Comment by yaroslav4167** [comment]
Thanks! =D
I will wait for the update to 1.10.
I gradually turn to this version.

**Comment by Speiger** [comment]
no problem. this version will be out in 1-2 days i wait on anoter bugreport that started this fixfest xD
(1.7.10 release)

1.10.2 might still need a while. ^^" next week we go hopefully into the final test which should be 2 weeks minium.

**Comment by yaroslav4167** [comment]
Oh ... I just decided to check out one long-standing mistake.
Principle: https://youtu.be/N-NSpCSKZdA

**Comment by Speiger** [comment]
xD thats not a bug xDD

**Comment by yaroslav4167** [comment]
Clearly, I will call this a "feature" x)

**Comment by Speiger** [comment]
Version released.
