### ISSUE TITLE
Crash on launch with DragonAPI/RotaryCraft - v17a

### ISSUE THREAD

**Issue by AbieTheFishman** [TinyModularThings/IC2Classic#219]
It would seem - IC2 Classic causes/doesn't play well with new updated version of Dragon API and RotaryCraft v17a of v17b. 

As per comment on reporting issue to Reika site.

> C2-Classic-Spmod{0.0.0.0} [IC2 Classic Detection Helper] (IC2Classic Version 1.2.1.5.1.jar)
> It certainly seems so - the cause lies within the fact that the entire ISemiFluidFuelManager is an always-empty dummy (returns null and an empty HashMap respectively).
> For my own setup I wrote a small Patch to overwrite it with an actually working one.

**Comment by Speiger** [comment]
Fixed on Reikas Side:
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1446

**Comment by AbieTheFishman** [comment]
Thanks - I really appreciate your work. I really couldn't use IC2 prior to finding you mod - just too much grind.

I'm playing and your working - thanks
