### ISSUE TITLE
More Upgrades

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#22]
I was thinking of those kind of upgrades:

Efficeny Upgrade: Less EU cost slower Process. (Opposite of Overclocker Upgrade).
Basic Item Ejector Upgrade: Eject 1 Item when a progress is done. (For free)
Item Ejector Upgrade: Ejects everything when a progress is done, (1 EU Per 8 Items)
Redstone Upgrade: Allows to shutdown machines with Redstone signals.

There will be more upgrades maybe. But those were my plans...

**Comment by Carbon-Ghost** [comment]
Efficiency upgrade is a bad idea imo, the rest of the upgrades seems ok ^.^

**Comment by Speiger** [comment]
@Carbon-Ghost efficeny upgrade is is only to a limited factor useable.

**Comment by Carbon-Ghost** [comment]
Well maybe a general effeciency upgrade, but requires a constant energy input ?

**Comment by Speiger** [comment]
Would be a thing when you put in Efficeny Modules then it resets the progress if you do not provide enough power. But then the powercost will be lower. But then the Progress speed would be the same (Just for the beeing nice).

**Comment by Speiger** [comment]
Also an idea to make a Muffler Upgrade that you can dissable 1 machine manually if you want (from sounds)

Also adding for some machines that have no Slots for upgrades extra upgrade slots.

**Comment by Carbon-Ghost** [comment]
+ 1 for the developped idea of effiency upgrade so it's not just an inverted overclocker :P 
Also, small request, can you add your own rotary macerator, singularity compressor and centrifuging extractor ? All of them + induction furnace would have 2 upgrades slots, being slower than their original counterpart if you don't apply a redstone signal and constant energy, 128 eu/tick packets and new/tweaked energy buffer to have 2x more energy buffer than their counterparts ^.^

**Comment by Speiger** [comment]
I know that efficency is the opposite. But there is only faster in ic2 no controll.

To the other thing. I have already a suggestion on that. I was thinking with 1 upgrade slot... But that requires a new Upgrade system. For both: Items & Machines. API files will be there also :D

**Comment by Speiger** [comment]
Got Implemented... So Closed
