### ISSUE TITLE
GregTech 5 Support

### ISSUE THREAD

**Issue by TsavyPrince** [TinyModularThings/IC2Classic#220]
Is there support for GregTech 5? Specifically this version : https://forum.industrial-craft.net/thread/11488-gregtech-5-1-7-10-forge-1355-unofficial-but-approved-port-stable-even-gt5-experi/

**Comment by Speiger** [comment]
Yes it should run. But recipes needs to be tweaked manually. That was the last info from @Blood-Asp when i asked.
If there is any issues then call @Blood-Asp and me so we can fix these issues.

**Comment by Speiger** [comment]
@TsavyPrince

**Comment by Speiger** [comment]
Closed because no answer and also no solution on my side.
