### ISSUE TITLE
Same MOD_ID as IC2 Exp

### ISSUE THREAD

**Issue by BloodWorkXGaming** [TinyModularThings/IC2Classic#221]
With having the same modid as IC2Exp a lot of issues come up when trying to run it together with a mod that adds support for it.

Most notably i am struggling with is Steves Carts Reborn and Unidict.
This is affecting the 1.10 version

**Comment by Speiger** [comment]
@BloodWorkXGaming Unidict waited on classics release.
And for Steves Carts Reborn. Read the known issues on curse... There is a fix.. Basically @modmuss50 needs to start get working on his thing. He knew this issue on his side for a week or two.

I have to have the same modID to get the Energy Compat loaded and also allow addons who support both to work easier... Its a compat that will stay.

**Comment by BloodWorkXGaming** [comment]
Ah cool, Thanks for the REALLY quick answer!

**Comment by Speiger** [comment]
no problem.
