### ISSUE TITLE
Crafting Recipes with multiple Items not updating correctly

### ISSUE THREAD

**Issue by BloodWorkXGaming** [TinyModularThings/IC2Classic#222]
Like seen in [this gif](https://puu.sh/wntcx/2ffb20b3f3.gif) a recipe with multiple items doesn't update correctly when changing the amount of the item of an existing ItemStack.

This is an issue for the normal crafting table and AE2 table, not for the Tinkers Construct table.
Opening and closing the AE2 terminal fixed this bug.

**Comment by Speiger** [comment]
Thats a Minecraft Bug, which tinkers construct has included too.
Minecraft doesnt check for recipes when you update the stacksize of a Item.
It requires that the item gets exchanged or removed or added not upgraded.

**Comment by BloodWorkXGaming** [comment]
Ah okey, thanks for the info, so you would have to write a coremod to fix it if I understand it correctly?

**Comment by Speiger** [comment]
@BloodWorkXGaming Yes which i would not do since i have no knowledge about asm. It would also not help mcs performance to do that. Just place the stacked items in first or use my crafting table that supports the stacking in the shiftclick with JEI

**Comment by BloodWorkXGaming** [comment]
totally see the reason behind not using ASM, just wanted to know as I started with modding recently
