### ISSUE TITLE
[1.10.2] Electric Circuit recipe uses steel not refined iron

### ISSUE THREAD

**Issue by ShneekeyTheLost** [TinyModularThings/IC2Classic#225]
I don't know if this is an oredict problem or recipe registration problem or what, but in my ModernRetro pack I am building, when Thermal Foundation and Immersive Engineering are present, the recipe for the Electric Circuit calls for Steel from one of these two mods and not Refined Iron. 

When I mouse over the recipe in JEI, it says 'Accepts any ingotSteel' but doesn't list Refined Iron as an option.

Mind you, I don't really mind this, all things considered. It means I need to get a coking oven and blast furnace up and running in order to get into IC2C tech which won't really kill me, but I'm curious if this is 'as intended' or some sort of bug.

**Comment by Speiger** [comment]
@ShneekeyTheLost you activated the SteelRecipes config option which replaces Refined Iron with steel recipes. Making steel the only possible way. Refined iron becomes useless.  
That can be turned off. Make sure you do that.
