### ISSUE TITLE
[ru_RU] Translation (1.10)

### ISSUE THREAD

**Issue by yaroslav4167** [TinyModularThings/IC2Classic#226]
Hi!
I again translated this mod (now for version 1.10) =3
If you want, you can use it.
There may be errors.
[ru_RU.lang](https://1drv.ms/u/s!Aqpxs79I3Zgd9TAHtxAy4pGCUWif)

Yes i know [Speiger]

**Comment by Speiger** [comment]
thanks i implement that with the next patch.

**Comment by Speiger** [comment]
Added for a todolist
