### ISSUE TITLE
List of current issues in the 1.7.10 stable version

### ISSUE THREAD

**Issue by Carbon-Ghost** [TinyModularThings/IC2Classic#23]
-Mekanism batteries cannot be used in SU !
-Tool enchanting system is for now broken. 
-Steel mode is missing in config.

Gonna provide you with textures if you need so Speiger, otherwise good work :D

**Comment by Speiger** [comment]
@Carbon-Ghost thanks.
Steel mode is from Railcraft.
But everything else i will check.

**Comment by Carbon-Ghost** [comment]
They removed steel mode in version 9.2.x iirc, worst case, I will release the Minetweaker script for steel mode ^.^ ( replace most of the refined iron, used in important recipes, such as machine blocks and drills ).

**Comment by Speiger** [comment]
I can implement that thing without trouble. I just need to make some prepair some thing for it... But the comming release will not contain it. The one after that. (Feature request you know)

**Comment by Speiger** [comment]
The Mecanism part is a problem by themselves if they do not implement the proper Exp classes then it will not work for them...

**Comment by Speiger** [comment]
Steel Mode Finished.
The Enchantment system waits.... I close that now because there is nothing in it that is important.
