### ISSUE TITLE
Ranged Pump only does 4 Blocks per level

### ISSUE THREAD

**Issue by Gamogamer** [TinyModularThings/IC2Classic#231]
It only pumps the 4 Blocks right around the mining pipe. It has a filtered scanner set up for the fluid (lava).
![2017-08-20_12 13 16](https://user-images.githubusercontent.com/7470667/29494271-be6445e6-85a6-11e7-95a7-e4f52fc4b76e.png)

**Comment by Speiger** [comment]
Closing. because its at a compressed todolist
