### ISSUE TITLE
Quark chests don't work in toolbox recipe

### ISSUE THREAD

**Issue by abculatter2** [TinyModularThings/IC2Classic#236]
I don't know if there are any other recipes that are the same way. Since Quark is a commonly used secondary mod, and I assume its chests use some kind of oredict, it probably will be worth adding compat for it.

**Comment by Speiger** [comment]
I don't know any oredictionary entry regarding chests. I could have forgotten it but we never used quark in the main game even so it was havyly requested.

Doesn't oak chest work since these should still be using the vanilla ID? Or can't you create normal chests anymore? I think vazzki would have thought about that possibility.

**Comment by abculatter2** [comment]
Yes, oak chests work, but you can't craft oak chests with Quark unless you have oak wood, or two different kinds of wood, as it defaults to oak chest when you do that. And I assume Vazkii would have thought of this as well, hence why I assume that his chests have some kind of oredict. I would check myself, but I'd have to install Crafttweaker, which I'm trying to avoid so that I don't get into my usual cycle of spending half my play time turning the game into a total conversion just because I don't like a couple recipes...

**Comment by Speiger** [comment]
well my proposal: Right now no idea how to fix it. But i will check it out as soon i work on the next patch.
Until now i suggest to use a sawmill with a Sawblade upgrade and then you get more wood out of your logs. Making 1 log to 1 chest at least. So you don't need as much wood... Sry no other idea...

**Comment by abculatter2** [comment]
Well I mean, right now I'm playing SP, so I can just cheat in oak chests and delete the other types of chests whenever I need to. It'd just be nice to not have to do that.

**Comment by Speiger** [comment]
well got a oak sapling and put it into a IC2 farm. Then you have your little tree farm. So and they grow so quickly (once fully grown) that you never run out of oak so quickly anymore.

**Comment by abculatter2** [comment]
I caved and got minetweaker, and went ahead an checked, and quark chests are indeed registered to the following oredict entries;
<ore:chestWood>
<ore:chest>

**Comment by Speiger** [comment]
why not add a recipe for the oak chest from all chests? because other mods could have the same potential issue

**Comment by abculatter2** [comment]
I dunno why Vazkii didn't add that. I figure he considered the oreDict registration to be 'good enough' for cross-mod compat, and put the onus on other mods to add that support.

**Comment by Speiger** [comment]
Well i know there are a lot of mods that use chests and not all think of using a oredict entry.

**Comment by Speiger** [comment]
closing because added to a todolist
