### ISSUE TITLE
Wood gas cells are not registered as wood gas containers

### ISSUE THREAD

**Issue by abculatter2** [TinyModularThings/IC2Classic#237]
Specifically, I tried setting the wood gas fluid type in a Refined Storage exporter, and the wood gas cell won't work. I assume this is because it's not registered as a fluid container?

**Comment by Speiger** [comment]
It is registered as one.
```
IC2Fluid.createFluid("woodgas", new IC2Fluid("woodgas").setDensity(-1000).setViscosity(500));
FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("woodgas", 1000), Ic2Items.woodGasCell.copy(), Ic2Items.emptyCell.copy());
```

**Comment by abculatter2** [comment]
Yup, water and lava cells don't work, either

**Comment by Speiger** [comment]
Yeah basically RS forcing in the new system. Which has a lot of issues on its own thats why i dropped it.
I wonder why it doesnt support it since forge has a backport for that kind of system.

**Comment by Speiger** [comment]
closing because added to a todolist
