### ISSUE TITLE
Miner deletes one mining pipe after completion

### ISSUE THREAD

**Issue by abculatter2** [TinyModularThings/IC2Classic#238]
I've done four complete operations so far, putting in one stack of mining pipes, and each time exactly one pipe has been deleted.

**Comment by Speiger** [comment]
believe me i fixed that 20 times already its a bug that doesnt want to leave

**Comment by abculatter2** [comment]
lol, at this point maybe just consider it a feature? I wouldn't mind having to spend a small amount of iron to keep the miners running.

**Comment by Speiger** [comment]
well it would be per dig and you waste 0.75/0.8 Iron per dig. And it depends how much that is per mining.
Because this happens after you dug up the pipes.
But yeah lets call it a feature with all these options its not a worse miner and it can dig as big of a hole as a bc quarry or rftools miner...

**Comment by Speiger** [comment]
closed because added for a todolist
