### ISSUE TITLE
IMPORTANT ISSUE : Nuclear reactors pipe compatibility

### ISSUE THREAD

**Issue by Carbon-Ghost** [TinyModularThings/IC2Classic#24]
You cannot, no I repeat myself, YOU CANNOT pipe, anything in nuclear reactors, and by anything I also mean there is nothing that can pipe stuff in without causing a crash and a permanent world corruption, attaching BC pipes/mekanism/AE2 buses makes instant crash, using hoppers or BC chutes only crashes if you insert an item. 

This is an important bug, another minor bug is that reactor chambers doesn't accept redstone signals, forcing you to have a lever/redstone passing wall current, which is annoying in compact builds. 

Tested with the latest version of the mod.

**Comment by Speiger** [comment]
I was so close to make a release xDD Waiting paid off.

**Comment by Speiger** [comment]
Next time please send the FMLLog with it. Now i have to track everything down before i fix it.
(It is now to late to upload it since i am already simulating the crash)
@Carbon-Ghost. Also look sometimes if i answer because i may have some questions...

**Comment by Speiger** [comment]
Maybe its already fixed. but i did not had any crash.
The Redstone bug is a vanilla bug. Redstone wire works if it connects only to the reactor (not in a curve). Try modded wire also.

**Comment by Carbon-Ghost** [comment]
Sorry for not answering back to you ^^', was at school/college :/ 

You sure you aren't getting any crashes ? Also, gonna test w new version ( like I said in the forum ).

**Comment by Speiger** [comment]
Nope nothing. I tried with Vannilla hopper (BC does not work in my dev invioment with IC2 Classic),
but if you have another crash with the new version send me the log and i can fix that stuff. Because the log give enough information for me.

**Comment by Carbon-Ghost** [comment]
Kk, already send one before on forums, but here is a copy http://paste.ee/p/HNs3b

**Comment by Speiger** [comment]
@Carbon-Ghost ^^" Yeah sadly that there is no crash in that report..
I mean normally there are informations why the game stops running or something.
Yours is just shuting down and thats it...

**Comment by Speiger** [comment]
Found ad fixed....
