### ISSUE TITLE
1.4.0.0 : Broken Recipe

### ISSUE THREAD

**Issue by prettyflyforapyguy** [TinyModularThings/IC2Classic#240]
Hi, I noticed the HV Solar Panel uses an IV-Transformer instead of an HV-Transformer. This is not like the rest of the panels, and I assume it is a bug.

**Comment by Speiger** [comment]
@prettyflyforapyguy thats not broken. That is balancment. The only gain you get from a HV solar panel is compression placing down 8 MV solar panels produces the same amount as 1 HV Solar panel.
On top of that it is also there to prevent the solar rush as early as i saw it comming on the testserver.
Once that was implemented people started looking at other viable options which produce more power then compacted solar panels for less resources.

**Comment by prettyflyforapyguy** [comment]
Makes sense, I did the same thing in prior versions and never considered another source of power due to how good HV solars were.
