### ISSUE TITLE
1.7.10 Dynamite projectile render glitch

### ISSUE THREAD

**Issue by Ghostlyr** [TinyModularThings/IC2Classic#242]
![default](https://user-images.githubusercontent.com/8511068/33240753-68f104a0-d2e5-11e7-9e05-42743a0e7f84.png)

IC2Classic version: 1.2.1.5.1
Forge: 10.13.4.1614
No any other mods installed

**Comment by Speiger** [comment]
Wow. Just wow.

**Comment by Speiger** [comment]
you are lucky that i made a mistake and need to export my mod again xD

**Comment by Speiger** [comment]
Fixed.
