### ISSUE TITLE
[Urgent] Server will crash after it finishes loading // 1.10.2

### ISSUE THREAD

**Issue by SebaSphere** [TinyModularThings/IC2Classic#249]
FML Log Every Crash
https://zerobin.net/?3040b5b7833334c6#rlKtwPQJChX3dtvYPI1lMdboL/B2Ua3KRb1MJcIIryI=

Server Log Every Crash
https://pastebin.com/ptPF7qHn

One of my players on my server was messing around with logistical transporters and IC2 machines and crashed the server every time it loads.

On the servers discord, he said

SebaSphere - Yesterday at 2:39 PM
What exactly did u do. Reporting this on github

warr - Yesterday at 2:40 PM
i made alot of IC2 machines connected to mekanism pipes and sorters
my main imput chest gets glitched by the sorters
so whenever i put in a stack and the items get taken out sometimes there are negative items there and it makes it insta crash

Server has been down for several days already

**Comment by SebaSphere** [comment]
https://github.com/aidancbrady/Mekanism/issues/4923

Mekanism Github

**Comment by Speiger** [comment]
You are using IC2Exp not IC2Classic
[15:33:58] [ic2-poolthread-1/DEBUG] [IC2.Uu/IC2]: UU graph built with 4310 nodes after 467 ms.
at ic2.core.block.invslot.InvSlotProcessableGeneric.accepts(InvSlotProcessableGeneric.java:27) ~[InvSlotProcessableGeneric.class:?]
Both of those classes dont exist in classic.

**Comment by SebaSphere** [comment]
can you redirect me to the github. Cant find it. Thanks

**Comment by SebaSphere** [comment]
nvm Found it

**Comment by Speiger** [comment]
@SebaSphere they dont have a github they have a IC2Forum where they do link to their thing.

**Comment by SebaSphere** [comment]
Ok
