### ISSUE TITLE
1.7.10 Fluidstack issue

### ISSUE THREAD

**Issue by TsavyPrince** [TinyModularThings/IC2Classic#250]
`java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid`
So apparently this exception happened and the game crashed when I ran IC2 Classic and Gregtech5 Unofficial together.
https://pastebin.com/3AzR09Zm
Here is the entire output log.

**Comment by Speiger** [comment]
@TsavyPrince yeah sry about that but GT5U has to fix that. 
Basically GT5U is designed to work only with IC2Exp and make  full use  of their code,
and classic is only patched on to by the very basic support you can expect.
If you want GT + IC2C try gt6 or bother the GT team to make the IC2Classic Compat working properly or at least dedicate time to make it happen.
