### ISSUE TITLE
1.7.10 - Instant re-enriched uranium cell

### ISSUE THREAD

**Issue by borisfps** [TinyModularThings/IC2Classic#251]
I dont know if it's a bug or it's not implemented yet.
But if i put an depleted isotope cell in a rector it becomes instant an re-enriched uranium cell. But it should take  a while. And it should be enriched faster on high temperature like in the original mod.

I used the 1.2.1.5.2 version
(https://wiki.industrial-craft.net/index.php/Depleted_Isotope_Cell)

**Comment by Speiger** [comment]
Did you get it from Creative?

**Comment by borisfps** [comment]
yes i cheated it for testing

**Comment by borisfps** [comment]
Now i tried to craft it and put it in the reactor, it works. Idk why i didnt come to this on my own, but thanks for the help!

Btw great mod! IC2 is now for me playable again, with that old ic2 Feeling. Thanks <3
