### ISSUE TITLE
Macerator Double Processing Result

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#252]
First recipe: 1xLead Ore = 1xLead Dust
![image](https://user-images.githubusercontent.com/25727222/39405240-7ddeb6c6-4baa-11e8-9bbd-741ffe325aaa.png)

Second recipe: 1xLead Ore = 2xLead Dust
![image](https://user-images.githubusercontent.com/25727222/39405225-3c49b35a-4baa-11e8-8857-a6f712fb19ef.png)

Minecraft 1.7.10
IC2Classic Version 1.2.1.6

**Comment by Speiger** [comment]
thanks i found the issue. As soon a new ic2c 1.7.10 version comes out the recipe will be fixed.

**Comment by CrossVas** [comment]
Got it! 
Thanks!!

**Comment by Speiger** [comment]
Might take a bit i just started a break from mc and ic2c isnt easy to setup a dev envioment for it. (and this is more of a low priority thing)

**Comment by CrossVas** [comment]
I really appreciate that, big thanks to you.
