### ISSUE TITLE
Automatic item insertion is screwed up

### ISSUE THREAD

**Issue by esotericdesign** [TinyModularThings/IC2Classic#255]
1.7.10, version 1.2.1.5.1: if a Lava Cell goes from a hopper into a Geothermal Generator, it clogs up the slot for empty containers, while the actual Lava Cells and lava buckets slot remains empty. Also, Iron Furnace collects neither fuel nor raw materials from hoppers.
1.7.10, version 1.2.1.7: just checked out, same

**Comment by Speiger** [comment]
You need to fill it from the bottom @esotericdesign

**Comment by Speiger** [comment]
same thing.

**Comment by esotericdesign** [comment]
Double-checked everything.
Iron Furnace works with Hopper Ducts just fine, thanks. But the Geoth. Generator...
Directly connected pump works as expected, but you have to power it up, haven't you? What I'm trying to say is that I want lava to be my main source of energy, and I can't see what's the profit of pumps. Of course, I may misunderstand something.
Still, neither tubes nor ducts solve the problem, even if they go to the bottom side (see screenshots)
). More than that, I had burnt down a lava bucket before cells went into, in order for the bucket to go in the top slot, and for cells - in the other one, which is where they should go from the very beginning. But the bucket remained where it was....
Which raises an important question: what's the top slot even for?
![2018-07-04_07 24 47](https://user-images.githubusercontent.com/40729240/42258643-51e7f142-7f4c-11e8-9b85-06a6724f9b20.png)
![2018-07-04_07 09 26](https://user-images.githubusercontent.com/40729240/42258653-5925f74c-7f4c-11e8-8c2a-ac88af049b0d.png)
![2018-07-04_07 09 30](https://user-images.githubusercontent.com/40729240/42258676-6f920002-7f4c-11e8-9c2b-56857dae1e77.png)
![2018-07-04_07 09 37](https://user-images.githubusercontent.com/40729240/42258677-6fb7535c-7f4c-11e8-8d8a-c44a5201bb57.png)
![2018-07-04_07 24 34](https://user-images.githubusercontent.com/40729240/42258678-6fdb7d72-7f4c-11e8-9a13-6b9eb5b66b02.png)
![2018-07-04_07 24 44](https://user-images.githubusercontent.com/40729240/42258679-6fff5418-7f4c-11e8-821f-344e9b2cfee9.png)

**Comment by Speiger** [comment]
ok i lookt up the code and yes geo gen is only manually fillable or liquid fillable.
And thats intendet behavior in 1.7.10.
