### ISSUE TITLE
1.12 version crash

### ISSUE THREAD

**Issue by Intipablo** [TinyModularThings/IC2Classic#258]
https://hastebin.com/nubobahehi.sql

Crashing on startup. Thanks for updating the mod :+1:

**Comment by laz2727** [comment]
Either you have like half Forestry disabled or the mod loading order is incorrect. Second one is probably on IC2C though.

**Comment by Intipablo** [comment]
That worked, thanks. Yeah I have a lot of Forestry disabled.

**Comment by Speiger** [comment]
@Intipablo yeah then disable the IC2 config the Forestry modul since it requires a lot of forestry and it cant check for the mod to have the submoduls loaded.
