### ISSUE TITLE
Crash with Defiled Lands

### ISSUE THREAD

**Issue by NormanNormalington** [TinyModularThings/IC2Classic#259]
Using IC2 Classic 1.12-1.5.3.1, Defiled Lands 1.12.2-1.4.2 and Forge 2758. Reported both here and on the Defiled Lands issue tracker, as I'm not really sure on whose end the issue is. 
https://gist.github.com/NormanNormalington/f8abc6de6d688910cd646af65d075364

**Comment by NormanNormalington** [comment]
Lykrast/DefiledLands#19

**Comment by Speiger** [comment]
Seriously i just updated IC2 Classic i could have patched this like now in 5 mins...

**Comment by Speiger** [comment]
Anyway @NormanNormalington as soon i get back to coding on it (maybe today if not then tomorrow) you have your patch.

**Comment by Speiger** [comment]
fixed yesterday @NormanNormalington
