### ISSUE TITLE
Dynamite / ITNT dupe glitch

### ISSUE THREAD

**Issue by coderbot16** [TinyModularThings/IC2Classic#261]
When trying to place dynamite sticks with shift / right-click, I discovered that instead of placing a dynamite stick into the world, the dynamite instead places a full ITNT block. This makes it possible to perform an 8x dupe by crafting the ITNT back into dynamite with string, which effectively grants the player unlimited explosives. This seems to be 2 bugs resulting from one issue: I would expect that there would be an in-world block for dynamite, which would be the one placed by the dynamite item.

Steps to reproduce:

1. Obtain a stick of dynamite.
2. Place this stick with shift + right-click, which results in an ITNT block in the world.
3. Break the ITNT block to get back an ITNT item.
4. Craft the ITNT with string to get back 8 sticks of dynamite - 8x dupe.

[Here](https://imgur.com/a/oY3s9CG) is an imgur album that explains the issue concisely.

**Comment by Speiger** [comment]
thanks will be fixed with the next patch.

**Comment by Speiger** [comment]
Patch is uploaded to curse.
