### ISSUE TITLE
Nuclear jetpack explosions crash the game

### ISSUE THREAD

**Issue by AdmiralPancakes1** [TinyModularThings/IC2Classic#262]
[Log here](https://paste.dimdev.org/ebipugigaf.mccrash)

To replicate:
1. Create new world
2. Obtain nuclear jetpack (Make sure it has no EU in it)
3. Load components that will cause it to explode (2 quad blaze cells is enough)
4. Equip jetpack
5. Wait for it to heat up
6. Crash

**Comment by Speiger** [comment]
will be fixed in the next patch. thanks

**Comment by Speiger** [comment]
Patch is uploaded to curse.
