### ISSUE TITLE
Falling electric boats crash the game and corrupt worlds

### ISSUE THREAD

**Issue by coderbot16** [TinyModularThings/IC2Classic#263]
While testing the boats, I found that when they get pushed off of a tall ledge it causes the game to crash and corrupt the world.

Steps to reproduce:

1. Build a tower of any block. I used one that was 20 blocks high.
2. Make a small ditch around the tower so that when you place water on the top, it does not spread on the ground.
3. Place an electric boat. The water stream with push it off the top, and it will fall to the ground.
4. The game crashes, and the world is now corrupted since trying to reopen the world leads to the same crash.

[Crash Report](https://pastebin.com/KjpPVaHu)

![2018-09-08_23 00 40](https://user-images.githubusercontent.com/22420959/45261701-fa568d80-b3bc-11e8-9de4-5a9623c82952.png)

**Comment by Speiger** [comment]
Patch is uploaded to curse.
