### ISSUE TITLE
[Request] Ability to configure recipes for remaining machines that show up in JEI

### ISSUE THREAD

**Issue by coderbot16** [TinyModularThings/IC2Classic#267]
It would be nice if the Canning Machine, Rare Earth Extractor, and Liquid Fuel Generator had entries in ic2machineRecipes.json or an equivalent file that allowed some recipes to be disabled. Most of the other machines are present in this file, so this just seems like a minor inconsistency. It would also be nice if there was a way to edit scrapbox drops in a similar way. My purpose for this is allowing me to remove certain unused recipes. For example, I've changed all of the recipes to not use Plasma Cores, meaning that magnets and therefore the rare earth extractor is redundant, yet it still shows up in JEI. Other examples include moving the fluids that can be burned in the Liquid Fuel Generator to more specialized TechReborn fluid generators, such as making Wood Gas burn in the Gas Turbine. Disabling these machines is not the problem, it's just that I don't want to clutter up JEI with recipes for these disabled machines.

**Comment by Speiger** [comment]
No problem. 
There might be other ways to cheat, still.

Also about addons. I would suggest you to wait 1-2 more days then the new addon API comes out.

**Comment by Speiger** [comment]
closing because release is now out.
