### ISSUE TITLE
Some machines eat buckets

### ISSUE THREAD

**Issue by coderbot16** [TinyModularThings/IC2Classic#268]
Some machines consume buckets when extracting fluids from them. This occurs with cells as well, but this is expected due to their disposable nature. I would assume, however, that buckets would retain their normally reusable nature in the context of these machines. I have confirmed this issue with the following machines, but it may exist in other ones too.

* Geothermal Generator
* Solar Turbine
* Fuel Boiler

**Comment by Speiger** [comment]
thanks.

**Comment by Speiger** [comment]
Fixed. Will be in the next patch.
