### ISSUE TITLE
Reinforced glass has inside textures, weird lighting

### ISSUE THREAD

**Issue by AdmiralPancakes1** [TinyModularThings/IC2Classic#269]
Reinforced glass doesn't get rid of its inside textures like regular glass, and has a weird darkening effect on the blocks next to it. This happens with the clear variant too.

![image](https://user-images.githubusercontent.com/19880843/45929635-8373d580-bf22-11e8-9b90-305a4dc0f04b.png)

To replicate: Place down some reinforced glass

**Comment by Speiger** [comment]
Fixed. Will be in the next patch.
