### ISSUE TITLE
Crash from placing reactors next to each other

### ISSUE THREAD

**Issue by AdmiralPancakes1** [TinyModularThings/IC2Classic#270]
[Log here](https://paste.dimdev.org/wivarituwa.mccrash)

To replicate:
1. Place down a reactor.
2. Attach a chamber to the reactor.
3. Place a reactor component inside the new inventory slots added by the chamber.
4. Place another reactor next to the chamber.
5. The chamber should pop off, and then after a moment the game will crash.

Interestingly enough, this also dupes any items that were inside the reactor chamber.

**Comment by Speiger** [comment]
Yeah its a null item. Its going to be patched next version. Like all the other things that were queued up.

**Comment by Speiger** [comment]
Fixed. Next patch has that fixed.
