### ISSUE TITLE
Mysterious Tea

### ISSUE THREAD

**Issue by esotericdesign** [TinyModularThings/IC2Classic#272]
I can see items as Tea Leaf and Tea Crop Seed in NEI, and it shows that I can make tea, but how do I get leaves or crop seeds? I've looked up several guides, and there were all the crops but Tea, even coffee.
Is it hard to get?

**Comment by Speiger** [comment]
Tea crop is a IC2Crop only, you can get it through breeding or planting the seed bag in there.
The chance can be seen with the CropAnalyzer in breeding mode (where you can see all the chances of your crop setup)
