### ISSUE TITLE
Electric hoe works (and fail) on everything (massive energy lost)

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#273]
Hello,

When trying to using the Electric  Hoe on dirt, I noticed that the Electric Hoe trys to work on every blocks, and lost energy. The vanilla hoe only work on dirt.

**Comment by Speiger** [comment]
thanks will be fixed in the next patch.

**Comment by Speiger** [comment]
Fixed in the latest patch.
