### ISSUE TITLE
A cable inside a foam block makes painters shift colours

### ISSUE THREAD

**Issue by esotericdesign** [TinyModularThings/IC2Classic#276]
Found out the feature of hiding cables in a construction foam block, cool idea IMHO. Oddly enough, when I right-click the hardened block with a painter, it gets dyed some other colour (i.e. magenta painter dyes the block green, yellow makes gray, white gives blue etc.), probably a texture bug? In the texture assets, though, there's only one set of painted foam blocks, which works as supposed for foam-only blocks.
P.S. obscurators work well on both foam block types

**Comment by Speiger** [comment]
not a texture bug but a "MC Color conversion" bug, will be fixed with the next patch.
We still work on stuff right now.

**Comment by Speiger** [comment]
@esotericdesign ok after testing, it turns out thats your modpack because when i used that it didnt cause that at all.
