### ISSUE TITLE
[Suggestion] Add examples of each input type to the wiki examples section under "How to add custom Recipes"

### ISSUE THREAD

**Issue by Electrofried** [TinyModularThings/IC2Classic#280]
It would be extremely helpful to people with little experience with JSON to have examples of the formatting of each of the input types supported by custom machine recipes in the wiki. While the guide does explain that the inputs are handled the same way as the input section of shapeless recipes, the shapeless recipe examples are not directly applicable to how the machine recipes are formulated.  
An extra few lines demonstrating each machine input type would be helpful for inexperienced users to get a grasp on the unique JSON layout required.
eg:
`"recipeType": "extractor",
  			"outputs":
  			[
  				{
  					"item": "ic2:itemmisc",
  					"meta": 3,
  					"amount": 2
  				}
  			],        
  			"input":
  			{
                                "inputType": "item",
                                "item": "minecraft:gravel",
  				"meta": 0,
  				"amount": 1
  			}`

**Comment by Speiger** [comment]
> Machine Recipes
> This category assumes you read the Crafting recipes at least a bit.

You did not do that else you would have noticed that it provides for each input type an example + a description (below the examples) of what parameters are needed etc.
