### ISSUE TITLE
Canning Machine Not Accepting items

### ISSUE THREAD

**Issue by AtomicWaffle14** [TinyModularThings/IC2Classic#283]
The Canning Machines (both regular and vacuum) won't accept items from outside sources, including hoppers, pipes, and other machines trying to export to them. Is this a problem with the machine having two input slots? 

I tried designating the slots using the inventory/slot upgrades but they are a little confusing (including the simple Automation Upgrade), and it still wouldn't take in items.

Here's are some screenshots:
![2018-11-20_15 00 56](https://user-images.githubusercontent.com/39530149/48799711-e0e39300-ecd5-11e8-8e10-83b7ad7a760b.png)
![2018-11-20_15 01 00](https://user-images.githubusercontent.com/39530149/48799712-e0e39300-ecd5-11e8-8ae5-087bf572e9ae.png)
![2018-11-20_15 01 03](https://user-images.githubusercontent.com/39530149/48799713-e0e39300-ecd5-11e8-9399-4a7115928639.png)

**Comment by AtomicWaffle14** [comment]
The strange this is that this is not happening with any other multi-slot machines, such as the Uranium Enricher.

**Comment by e99999** [comment]
Trying putting the food in from the top and the secondary into the EAST side. automation is designated per side

**Comment by AtomicWaffle14** [comment]
Tried it, doesn't work.

**Comment by e99999** [comment]
ok tried it, yeah its weird. it wouldnt start "hoppering" apples in until I placed a tin can in the bottom slot. and wont accept input for the cans into any side.

**Comment by Speiger** [comment]
@AtomicWaffle14 the slot is by default only accessible from the East. (It rotates also with the machine so its the right side when you look at the "Front" face. Cells come into there by default.

**Comment by Speiger** [comment]
Also i assume you placed the "Inventory Upgrade" (Automation Upgrade) into the "Machine Upgrade" Slots (where overclockers can go)
If thats the case then thats the reason why it didnt work. Because Inventory Upgrades have their own 5 Upgrade slots that can't be viewed normally.
They have to be accessed with the machine tool.

**Comment by AtomicWaffle14** [comment]
> @AtomicWaffle14 the slot is by default only accessible from the East. (It rotates also with the machine so its the right side when you look at the "Front" face. Cells come into there by default.

This is actually not true. It is  only accepting cells/cans from the back, and other ingredients from the top, without the automation upgrade. With the automation upgrade installed it works from any side, as you described.

(I hadn't tried the automation upgrade all by itself. It also doesn't go into the machine upgrade slots, so no worries there.)

**Comment by AtomicWaffle14** [comment]
So basically it was just me being oblivious.

**Comment by Speiger** [comment]
@AtomicWaffle14 it was added for the Apply and dont think. Just to get things running. The advanced upgrades are a lot more complex and allow a lot more.
