### ISSUE TITLE
IC2Classic disabling the Vanilla shield sound and also disabling Vanilla shield durability use

### ISSUE THREAD

**Issue by AtomicWaffle14** [TinyModularThings/IC2Classic#286]
With IC2C 1.12.2 installed, Shields won't make any noise when successfully blocking an attack. Usually you hear a "thud". Taking out IC2C and reloading the game brings the sounds back. This applies for both the Vanilla shield and the IC2C Shields.

**Comment by Speiger** [comment]
@AtomicWaffle14 IC2 shields have no sound, unless you want a wooden sound for a metal shield?
If thats the case do it yourself.
I changed the topic since that other part is a bug, that will be patched in the next version
