### ISSUE TITLE
A couple bugs

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#287]
When testing for my mod I noticed a couple bugs:

1. the basic steam turbine can accept any fluid, not just steam:
https://gfycat.com/DefinitiveCheapGrebe
I used wood gas as an example there but it can accept any fluid, which means that one could use water, which means they don't have to create steam.

2. the plasmafier shows as having a max limit of 512 eu/t but it can actually accept 2048 eu/t: 
https://gfycat.com/JitteryImpartialDartfrog
I mentioned this in your discord server under bugreports but I've decided to post it hear so you can keep track of it.

**Comment by Speiger** [comment]
Yeah second bug you already reported. I just forgot to fix it. And honestly that isnt much of a problem since the "Top" tooltip is accurate.

Other bug with the steam turbine i love it. Best bug ever!

**Comment by Speiger** [comment]
Fixed
