### ISSUE TITLE
Jetpack 3d model ?

### ISSUE THREAD

**Issue by Carbon-Ghost** [TinyModularThings/IC2Classic#29]
If I give you a 3d model of both jetpacks with Techne, could you try to integrate it in IC2 classic ( like SimplyJetpacks 3d models ).

**Comment by Speiger** [comment]
^^" Do not know, if it fits into IC2 Classic and do not know where to get the models.

**Comment by Carbon-Ghost** [comment]
It will still respect the 16x16 IC2 classic texture style, but just in 3d :dancer: 
Mmmh, perhaps, ask Grag how to add models ^.^ ?

**Comment by Speiger** [comment]
Its not a question how to implement the models. Look at TinyModularThings there are enough.
I simply can not design good models. You would then have to use a ugly one which i do not want.
By the way new idea just look into it

**Comment by Carbon-Ghost** [comment]
^.^

**Comment by Speiger** [comment]
not happening anymore... this was 1.7.10. Closing it with this version.
