### ISSUE TITLE
Auto ore to dust function doesn't add ingots to dust

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#290]
I noticed it as I based my crushed ore and purified crushed ore auto add function of it.
I got mine to completely work after I changed it from an if.. else if statement to 2 if statements

**Comment by Speiger** [comment]
Thats because i only allow "dust" and not "crushed" or "purified".

Also could you show examples?

**Comment by Trinsdar** [comment]
I think you misunderstood. Let's just ignore the crushed stuff as it's not actually related. I was saying that the ore to dust method is supposed to add ingot to dust recipes as well as the ore to dust recipes but only adds ore to dust recipes. I'll show an example later when I'm back at my computer

**Comment by Trinsdar** [comment]
Here are six pics showing to the contuary:
![2018-12-28_17 42 27](https://user-images.githubusercontent.com/30245301/50530086-830e4c00-0ac8-11e9-86d5-6d19d415ad60.png)
![2018-12-28_17 42 29](https://user-images.githubusercontent.com/30245301/50530087-8570a600-0ac8-11e9-9136-2ed2147955ec.png)
![2018-12-28_17 42 38](https://user-images.githubusercontent.com/30245301/50530088-873a6980-0ac8-11e9-9d72-b85b8a6bb5fa.png)
![2018-12-28_17 46 03](https://user-images.githubusercontent.com/30245301/50530090-89042d00-0ac8-11e9-99c9-338436767614.png)
![2018-12-28_17 46 15](https://user-images.githubusercontent.com/30245301/50530091-8b668700-0ac8-11e9-82f2-7f867df05b9a.png)
![2018-12-28_17 46 22](https://user-images.githubusercontent.com/30245301/50530094-8dc8e100-0ac8-11e9-9226-17c253a8db74.png)

as you can see in the pics they are under the right oredict entries. I pressed r on both of those dust but it only showed an ore recipe, not an ingot recipe. and those are two different mods by the way, so it's not one mod. I also have base metal's ic2 integration turned off in that example so there can be no conflicts there. and I clicked on both aluminum dusts I had available in that instance so it's not that.

**Comment by Speiger** [comment]
the issue is that i dont extract the name properly.
I found it after checking again.

**Comment by Speiger** [comment]
i only remove 3 chars instead of the required 5 chars.

**Comment by Trinsdar** [comment]
Also on the topic of auto recipes could you add a config option for turning it off if someone wanted to for whatever reason?

**Comment by Speiger** [comment]
why?

**Comment by Trinsdar** [comment]
because maybe for example someone wants to disab;e ore doubling recipes in the macerator, although I guess it can be disabled in the ic2machinesRecipes.json. it's just easier i guess

**Comment by Speiger** [comment]
fixed both
