### ISSUE TITLE
Auto oredict doesn't detect IC2Classic Addon Additions

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#291]
I am aware that you may have added them to the oredict on purpose but honestly any mods that add recipes that use plates also add plates of their own. and I don't think their are really any ic2 addons that are compatible with ic2 classic that also call for plates. any other mods that have compatibility to ic2 classic are bigger mods with their own plates such as thermal series, immersive engineering, railcraft, base metals, ect. it's really breaking more recipes then it adds recipe compat to.ic2 addons
here's an example of how it breaks other mod recipes:
![plates](https://user-images.githubusercontent.com/30245301/50542617-224a4680-0b90-11e9-95f3-d1aaa0bd2e06.gif)
and how it relates to me is I've added a config option that makes casings require plates, which also adds plate recipes using the first item under the respective oredict, but because ic2c ingots are under plate ore dict, it results in situations like this:
![casings1](https://user-images.githubusercontent.com/30245301/50542612-13fc2a80-0b90-11e9-8e65-3778b00b656f.gif)
and this:
![2018-12-29_15 27 11](https://user-images.githubusercontent.com/30245301/50542611-09419580-0b90-11e9-8d27-72b124c31823.png)

granted refined iron may be a bit of an exception as you have to smelt iron to get it but that doesn't account for copper, tin, bronze, and gold

**Comment by Speiger** [comment]
Not a bug, that only happens if it can not find the oredict entries within preinit stage (which is done between the 2 preinit options)
That is only a loading order issue but  can be fixed for you.
PreInit without the IOverrideObject is once ic2c has fully loaded. Preinit with the IOverrideObject is before ic2c is loaded. So you have to apply it early enough.

**Comment by Trinsdar** [comment]
so I would need to do those recipes in preInit is what you are saying?

**Comment by Trinsdar** [comment]
So let me understand this correctly: you are saying that if it cannot find plates that are under plateIron, plateCopper, plateTin, plateBronze, or plateGold then it will add ic2c ingots to those respective ore ducts. If so then there is an issue that it's not detecting that railcraft, thermal foundation, and base metals all add plates under those entries

**Comment by Trinsdar** [comment]
and by the way I tested removing my recipes that required plates but it still registered the ingots under the plate oredicts

**Comment by Trinsdar** [comment]
With all that said, why do you need to even register them as plate entries at all? almost every mod that adds recipes that use plates also add their own plates so that the player doesn't have to add another mod to get plates.

**Comment by Speiger** [comment]
Because there is some addons in older versions that used exp plates and didnt add them so i had to add  replacements.

**Comment by Trinsdar** [comment]
is it even still relevant in 1.12?

**Comment by Speiger** [comment]
as long ic2c is compatible to ic2 addons? Yes

**Comment by Trinsdar** [comment]
Ok. Well then there still us the problem that it doesn't detect other iron plate, gold plate, ect. entries.

**Comment by Speiger** [comment]
nah i just fix the issue thats easier and also better for backup.

**Comment by Speiger** [comment]
done
