### ISSUE TITLE
Stacking full batteries shows them as having zero charge

### ISSUE THREAD

**Issue by AtomicWaffle14** [TinyModularThings/IC2Classic#292]
When stacking together two full batteries, they display as having zero EU. Separating the stack brings them to full charge again, but it's a weird visual bug.

**Comment by AtomicWaffle14** [comment]
Yep, 1.12.2. It seems like a bug then. They stack and display as empty once stacked.

**Comment by Speiger** [comment]
The "Empty part" is right, just the rest is not.
