### ISSUE TITLE
Sound problems 1.12.2

### ISSUE THREAD

**Issue by AtomicWaffle14** [TinyModularThings/IC2Classic#294]
In the Dec 3 build there's a lot of sound weirdness:

1) Jetpacks don't make a consistent sound when in hover modes, instead the sound flickers on and off, which sounds really weird.
2) stone macerator has no sounds
3) machine sounds all turn off when the game is paused and unpaused in singleplayer. Sounds resume as normal when the machine changes states.
4) when walking, nearby machine sounds fluctuate up and down in volume with each step.
5) handheld drills make no sound when mining. Not sure if intentional?

Not sure if the last update was supposed to fix some of these, but it seems not to have shipped properly. I'll place these here just in case.

**Comment by Speiger** [comment]
Yeah, still no bugs here. I could go into further detail but everything runs as intendet.

Also stone macerator, i can only have 1 sound. I am not an audio artist, and second its hard to make a "good" stone macerator sound, i can not use a soft sound like a macerator for such a havy machine.

Anyway this is finished.

**Comment by AtomicWaffle14** [comment]
Just thought I'd bring it to your attention. Machines not having sounds is not too good. The sawmill also doesn't have sound. Guess it's not important enough...

**Comment by Speiger** [comment]
@AtomicWaffle14 do you know a audioengineer that makes sounds for free?
Or if it is not free do you take over the cost?

**Comment by AtomicWaffle14** [comment]
No need to get snappy at me, I'm just trying to be helpful. If you don't like me, just say it... 

Anyways, if you need a looping sound file it's pretty simple to do. I could do it myself in about an hour if you gave me the length the sound clip needs to be. Please don't assume that people don't know what they're talking about.

**Comment by AtomicWaffle14** [comment]
I could make you a couple of sound files for free if you'd like. I have some experience with sound editing from a course I took last year. I would get free sound samples from freesound.org and modify them.
