### ISSUE TITLE
IC2 Localisation is broken

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#3]
Todo: Fix the Following Localisations.
Beer
Coffee
Brewing barrel item
The upgrades
Active nanosabres
All coloured painters
Charged RE-Batteries

**Comment by Chocohead** [comment]
The debug item is broken too, it's called item.null.name

**Comment by Speiger** [comment]
Fixed. Debug item is not possible at the moment. Also not nessesairy since its only a debug item and everyone see that. Also creative only..
