### ISSUE TITLE
Nuclear Jetpack

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#30]
I like the idea.
Logic is still breeding (like a breeder xD) in my head but i think i will implement that to classic.
It has its good a bad side, for sure.
But it will be fun. 
(Worst case: Nuclear explosion at the air because overheated xD)

**Comment by Carbon-Ghost** [comment]
Perhaps nuclear fueled RTG pellet jetpack ( which last very long, but is slow due to using heavy elements, overheating is impossible due to low energy, just a nice way to be more agile almost forever ^.^ ).

**Comment by Speiger** [comment]
RTG pellets will not join the Classic area, even Plutonium is only as Extension for the Uranium cells there...
What you have todo is to make a reactor setup into your Jetpack, How? not sure yet, but you have a gui like a nuclear reactor (little bit smaler maybe), and there you make your setup, and that will run and fill the Jetpack with Electricity, Only thing you have to keep in mind it will start producing energy if a special amount of energy use did happen. (if it is lower then 50%) and it stops when it is almost full (99%).

The jetpack is simply a really extended version and i think nuclear reactor fans will love it^^"
Only a texture is needed.

**Comment by Carbon-Ghost** [comment]
I can provide you with that ;D

But by RTG, I didn't wanted the IC2 exp infinite RTG, but a plutonium fuel jetpack that last very long ^.^

But your idea seems better ^.^

**Comment by Speiger** [comment]
Well thinking of i know that stays for 100-500 Years (lets say 100),
well 1 day in MC is 20 minutes, means 3 days in 1 hour, means 72 days in 1 day, means 26280 days in 1 Year, simply means 72 years in one real life year... ^^" Everything close to that is really OP.. Even if it only sends 5 EU, its infinite EU that you throw anywhere and it provides you a really long time...
^^" To make it not that op i need to drain its power Providing part to about 1/100, which means that it runs about 3,72 days (in real life) which is for server playing or real playing some thing as you would use 10 buckets of Fuel... (Only at the time it lasts, not energy production)

And yeah i just wanted to throw that thinking about what you meant out.^^"

**Comment by Carbon-Ghost** [comment]
Again, no IC2 exp RTG, as we both now that is OP, you idea is better ^.^

I am ok with verryyyyyyyyyyyyyyy long nuclear fuels but not infinite xD

**Comment by Speiger** [comment]
xD Jup^^"

**Comment by Carbon-Ghost** [comment]
^^

**Comment by Speiger** [comment]
Is implemented so do not need  to be open. But still textures needed @Carbon-Ghost @Chocohead is just a note so if anyone has a idea or something ^^"

**Comment by Carbon-Ghost** [comment]
Kk, gonna make them, add the textures for the next update with jetpack inworld better textures ;)
