### ISSUE TITLE
Missing JEI recipe catalyst registration

### ISSUE THREAD

**Issue by e99999** [TinyModularThings/IC2Classic#300]
keeps slipping through the cracks on each update so Ill make an issue 😄. 

Missing recipe catalyst registries for:

- Industrial Workbench --> minecraft.crafting;
- Stone Macerator --> macerator;

**Comment by DrakusorU** [comment]
I also noticed just there a bunch of things missing from JEI.. like recipes for UU-Matter, Enriched ingots and a lot of other stuff.. whats happening more exactly?

**Comment by Speiger** [comment]
@DrakusorU UU-Matter is intentional, but you can enable these recipes via a config setting. (And reloading textures afterwards).
Uranium Enricher Recipes will come soon too. I am waiting for addons to be ported to the newest patch since it breaks basically every addon.

Also what else could be missing.

**Comment by DrakusorU** [comment]
Gotcha.

After checking the IC2 exp I don't know which is intentionally missing or not, for example -- plasmafier - plasma cell, ales, brews ( as I haven't played minecraft that much in a long time especially with ic2 stuff i have no clue how these are made without JEI )

**Comment by Speiger** [comment]
Plasmafire yeah thats a bit unqiue... Its hardcoded and not a recipe list machine.
Maybe a tooltip might help.
Brewing is so modular that i can not create the recipes since it uses almost the full 16bit Integer that it has. (16k recipes)

So that has to be done via the wiki.

**Comment by Speiger** [comment]
Fixed also @DrakusorU Plasma cell has now a tooltip to ensure people get it.
