### ISSUE TITLE
[Bug] 10k Coolant Cell Recipe

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#302]
The recipe for 10k Coolant Cell seems to be broken.
It uses only water from Water Cell and returns empty one back.
![recipe](https://user-images.githubusercontent.com/25727222/52731969-b9941d80-2fc7-11e9-88a0-dff330cb67db.gif)

**Comment by Speiger** [comment]
That is actually intentional. Since it is a "WaterInput" and not a TinCell alone.

**Comment by CrossVas** [comment]
@Speiger if I understood correctly, this recipe wasn't planned to be similar with recipe from IC2>1.5.2.
It's a little bit strange. 
Nevermind then.

**Comment by Speiger** [comment]
i decided for it because what does a double layered tin cell do?
It does not transfer heat better. Also this is based on 1.4.7 IC2 not 1.5.2 IC2.

But when we made the change in 1.10.2 it was decided to be better.

**Comment by e99999** [comment]
why would anyone ever advocate adding more recipes that eat tin cells 😆 this is one of the few that dont!
