### ISSUE TITLE
Electrolyzer not working release 1.7.10 version 1.1.3.5

### ISSUE THREAD

**Issue by MrMrRubic** [TinyModularThings/IC2Classic#305]
trying to electrolyze, but nothing works. it wont accept power. is it posible to release a hot fix like 1.1.3.5.1?

**Comment by e99999** [comment]
are you using an energy storage tile to power it or trying with cables? you cannot use cables.

**Comment by MrMrRubic** [comment]
placed on top of a MFE, tried rotating it with power-out side facing up, no difference

**Comment by Speiger** [comment]
@MrMrRubic why are you running on a legacy supported patch that was only created for technic pack once and then dropped because it was only for a couple servers.

1.2.1.7 is the latest 1.7.10 version. And i do not even own the 1.1.3.5 version anymore.

**Comment by MrMrRubic** [comment]
dont ask me, i dont run the server lol, im goint to ask if they can swap the files :)

**Comment by Speiger** [comment]
there is even 1.1.3.7.4.3 version. So you are even on a outdated technic pack patch.

**Comment by MrMrRubic** [comment]
difference between 1.2.1.7 and 1.2.1.8?

**Comment by Speiger** [comment]
fixes? Changelogs are present in my files so you see exactly what was changed.

**Comment by Speiger** [comment]
(scroll down)
https://minecraft.curseforge.com/projects/ic2-classic/files/2615057

**Comment by Speiger** [comment]
ok now leaving the version issue behind.
The electrolyzer isnt a machine that can accpet power. Its a block that you put next to a power storage and it will draw power from it. The power storage needs to be at 75% or fuller. If it is below 30% it will drain from itself to charge the power storage.

The power storage tier also affects the speed at what the electrolyzer is working at.

that should solve your issue.

**Comment by Speiger** [comment]
I hope that helps @MrMrRubic

**Comment by MrMrRubic** [comment]
yeah, its weird. it fixed itself after a we added thermal, might be the server restart that did it
thanks for the help :)

**Comment by Speiger** [comment]
@MrMrRubic the version you are using has a completly broken EnergyNet that can selfdestruct at any given time, also it keeps chunks loaded, i highly suggest that you update to either branches latest version to get the fixes.
