### ISSUE TITLE
Hemp seeds cannot be planted

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#306]
Hello,

I tryed everything to plant a hemp seed, nothing worked. Cannot found anything on google either, except about the same seed from Immersive Engineering.

Tryed on farmland, dry or wet, like normal vanilla seeds;
Tryed on grass and farmland at the side of water, like sugar cans;
Tryed on sand like cactus.

Nothing worked. How to plant this seed please?

Minecraft Version: 1.12.2
Forge Version: 2815
IC2 Version: 1.5.4.2

**Comment by e99999** [comment]
try crop sticks

**Comment by Speiger** [comment]
IC2C crop sticks only (its growing faster on there anyway)

Thats a intendet mechanic and not a bug.
