### ISSUE TITLE
[Enhancement] If it doesn't already exist, consider adding OpenComputers support to the reactors.

### ISSUE THREAD

**Issue by levicc00123** [TinyModularThings/IC2Classic#308]
Some example methods:

getHeat()
getMaxHeat()
getEUOutput() (Nuclear reactor only)
getSteamOutput() (Steam reactor only)

Thank you for making my favorite tech mod and have a great day!

**Comment by Speiger** [comment]
@levicc00123 no it does not exist, and right now there is no plans to add that feature.
Though it could be that addon makers might write that.
