### ISSUE TITLE
Unknown Crash reason

### ISSUE THREAD

**Issue by Spenny519** [TinyModularThings/IC2Classic#309]
I keep crashing on startup and don't know why

[crash-2019-04-07_22.53.47-client.txt](https://github.com/TinyModularThings/IC2Classic/files/3052964/crash-2019-04-07_22.53.47-client.txt)

**Comment by Speiger** [comment]
Do you have a mod that changes the vanilla furnace?
Because thats the issue. The Vanilla Minecraft Furnace lost its ItemBlock and can no longer be used in crafting recipes. Thats why it is happening.
Not an issue of ic2c since i can not fix that without making the mod unplayable.

**Comment by Spenny519** [comment]
I have the Fast Furnace mod installed. I will check to see if that was the problem when I get home

**Comment by Spenny519** [comment]
I removed fast furnace and still crashing

[crash-2019-04-08_11.45.33-client.txt](https://github.com/TinyModularThings/IC2Classic/files/3055832/crash-2019-04-08_11.45.33-client.txt)

**Comment by Spenny519** [comment]
I got it to load without crashing. idk what mod it was but it is working now

**Comment by Speiger** [comment]
ok, i have no idea which mod causes the furnace to have no itemblock.

**Comment by Spenny519** [comment]
I will try to find what mod it is tonight and let you know and also report the issue that that mod's github

**Comment by Spenny519** [comment]
Completely unable to find the mod causing the crash. no idea why. am completely baffled

**Comment by Speiger** [comment]
good to know.
