### ISSUE TITLE
Intigrate Advanced Machines

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#31]
The idea of intigrating Advanced Machines into IC2 Classic.
Because Immibis version is good but his mods getting more unstable as i go in my world...
(Nothing against him)

**Comment by Speiger** [comment]
Did implement 90% of the nessesary machines already.
Recipes i have already ideas for some replacements.
(Only the Adv Macerrator Recipe will be differend),
it requires something from classic only ^^"

Also Immibis version does not run with classic so it is almost a have to...

**Comment by Speiger** [comment]
Finished.

**Comment by Carbon-Ghost** [comment]
:D
