### ISSUE TITLE
Crash with Forestry (disabled apiculture)

### ISSUE THREAD

**Issue by MasterEnderman** [TinyModularThings/IC2Classic#311]
If you disable the "apiculture" module in forestry the game crashes while starting.
Crash-Report: https://paste.dimdev.org/ujonohojom.mccrash
Forge: 14.23.5.2836
IC2C: 1.5.4.2
Forestry: 5.8.2.387

**Comment by laz2727** [comment]
It does. If you want to disable Forestry modules you need to disable Forestry compat altogether.

**Comment by Speiger** [comment]
@MasterEnderman what laz2727 said, the modul is required for the forestry addon.
