### ISSUE TITLE
Missing list error client side

### ISSUE THREAD

**Issue by TheTWDestroyer** [TinyModularThings/IC2Classic#314]
Im trying to connect to my server and it kicks me for missing mods when i look at the client logs i see IC2 is missing blocks or items. How would i fix this? (IC2Classic+Version+1.2.1.8)
https://pastebin.com/wfrNHi0g

**Comment by Speiger** [comment]
@TheTWDestroyer you disabled the ores on the client thats the issue.
Just ensure that the server & client config match. That is a unique 1.7.10 system that was back then implemented (in 1.4.7) by the IC2 Devs which was not the smartest idea (thats why its gone in later versions)
