### ISSUE TITLE
BC fluid shards allow you to basically dupe fluids when right clicked on liquid fuel generator

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#315]
![fluid bug](https://user-images.githubusercontent.com/30245301/57815356-17f6a680-7745-11e9-8ea0-2e2471779315.gif)

**Comment by Speiger** [comment]
Fixed in next patch. (Close on patch release)

**Comment by Speiger** [comment]
Patch is out.
