### ISSUE TITLE
Terra Wart not consumed

### ISSUE THREAD

**Issue by gamefreq0** [TinyModularThings/IC2Classic#316]
Running in a modpack I've been putting together myself (Gregtech 6 focused), I ran into an issue where eating a terra wart will remove debuffs, but doesn't actually get removed from my inventory, allowing me to reuse it as much as I'd like. Prior to "eating" it, shift+clicking it around inventory works fine, but afterwards it needs to be manually moved with the mouse. Additionally, after "eating" it, throwing it makes it disappear. No errors are being thrown in the log. I'm using IC2 Classic 1.2.1.8 (according to the filename, but according to the Forge mods list, it reports 2.2.999). Forge version 10.13.4.1614, and I can list all the mods I'm using if you need it.

EDIT: It appears to actually use 2 at a time, which may be causing a stack of 1 to underflow and do strange things...

**Comment by Speiger** [comment]
fixed.
