### ISSUE TITLE
Multi-input recipes.

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#317]
Hey, 
I'm trying to find a way to autocraft Plasma Core -> PESD -> PESU.

Currently I'm stucked at Plasma Core item which use multi-input recipe.
I've tried to use:
- Sequential Fabricator from Thermal Expansion = game crashed 
- Refined Storage - regular crafting pattern = system get stucked without any reactions.
- Formulaic Assemblicator = it recognises the recipe as being OK, but I can't encode this
- Industrial Workbench = It is not able to do crafts by himself (?). I'm not quite sure how does this "machine" work (no info on wiki)

Any help with autocrafting setup would be useful.
Thanks!

**Comment by Speiger** [comment]
You can solve that with the "Crafting Upgrade" and the ["Item/Stack Limiter Upgrade"](https://github.com/TinyModularThings/IC2Classic/wiki/Inventory-Upgrades#stack-limiter-upgrade) in the Machine Buffer.
The Crafting Upgrade exports the crafting result into the decided direction inventory and the machine Buffer contains the contens while the Limiter allows you to control how many items are allowed to be in that inventory.
This should be completely automateable within Vanilla IC2C

**Comment by CrossVas** [comment]
My bad
Formulaic Assemblicator is from Mekanism 

Just tried Machine Buffer. Thanks for help!

**Comment by Speiger** [comment]
oh ok.
