### ISSUE TITLE
[Enhancement] way to monitor the heat buildup of an ic2 classic reactor automatically

### ISSUE THREAD

**Issue by escman1999** [TinyModularThings/IC2Classic#319]
in the current build of ic2 classic, there seems to be no way to do this; maybe you could add something similar to the nuclear control thermal monitor?

**Comment by Speiger** [comment]
@escman1999 Machine Tool to set the Comparator Output, and then a comparator or adv comparator to get the output you want.

**Comment by escman1999** [comment]
hmm, i was thinking like, a way to shut off a reactor when it reaches say, 5000 heat. world control can do this, but it's extremely buggy and crash prone

**Comment by Speiger** [comment]
You have 15 stages based between 0-15 no heat to max heat. I assume with a bit of work you can easily make a redstone signal hit the heat you want to. Get creative.
