### ISSUE TITLE
Intigrating Compact Solars

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#32]
Would be cool to have Intigrated Compact Solar Pannels :D

**Comment by Carbon-Ghost** [comment]
Maybe a special solar panel that recharges re enriched uranium cells, with +1 cycle life every minecraft days ? That would be quite fun :D

**Comment by Speiger** [comment]
I am now sorry for that but you have to accept that i write that now.

Really? Am i on drugs or did you write that now really?
You know that you require Uranium to reinrich uranium. Else it would not work...
What would work would be a Solar Reactor/Heat reactor that absorbes the heat to make the Process faster, but belive me you can make a reactor that can prodouce 16 cells per uranium Cell, and it is automatable xD At least with my custom BC version or CC, if you can write CC

**Comment by Carbon-Ghost** [comment]
Lol, yes, you are not on drugs, I wrote that, it was originally a suggestion made by SpwnX in the Advanced Solar panels thread ^.^ I know it's not realistic ( like the Nucler jetpack btw :P ) but it's a fun slow alternative for re-enriching uranium ^^

I can write CC but I would prefer having your BC version with slot detection merged via pull-request on BC 1.7.10 ^.^

Well, theoretically, if you can get back uranium from cells, you can have an infinite loop breeder reactor, using 1 uran creating 8 depleted cells, and at the end giving you 8 reenriched cells, then coal dust it, then get back 8 uran cells, then decraft them for uranium, -> ??? -> repeat -> profit :D

**Comment by Speiger** [comment]
Nope i am not on drugs, just to say i do not need drugs to be high, i am always high from nature.

Yeah it is a slow alternative to reinrich uran but then you coud simply throw 1 uranium cell into a reactor with 4 reinriched (forgot the name sry) cells and a lot of Reactor vents then you have the same result and it is even faster...

Cool because i can not write CC, thats why i made in 1.6.4 my custom BC version with slot detection... Sadly Asie (the maintainer of BC), did say that the slot detection will not be implemented by BC in 1.7.10. TMT is also not even close to be ready for an update... (We will see maybe i make a bunch of subaddons for stuff),

To your last thing, Technicle you can x16 your Uranium Ore, into cells, (drops = x8), but you can not make infinite uranium, in the Old IC2 (or in a really old version of my 1.6.4 version) it was that you had a 20-15% chance that you get your uranium cell back, so that you simply were able to reduce the amount of uranium loss, Well with the current 1.7.10 Version, its a 50% chance, i increased it by accedent because i wanted to change the uranium consum and production, well fail, but its still there.
So your uranium consum is really low but not infinite, and with a really high uranium processing you gain even more Uranium cells. And yeah i will not implement UU -> Uran. I was thinking of doing it because of Ultimative Solar pannels but then i understood why the original other did it not. (infinite Powerloop)

**Comment by Carbon-Ghost** [comment]
Lol yeah uu uran is OP, but also, can we have a chance config option for depleted rods ? Also, with minetweaker I managed to do what I said, you loose cell in the process, but I think you can get it back with transform output something, but it was just for testing + it's bugged xD

**Comment by Speiger** [comment]
Em i can make a Minetweaker/generalconfig that allows to maniuplate the chance of gaining Depleted rods. And if you need Uranium use the MFR mining laser drills they can also produce Uranium and its a infinite powerloop but that one is not really OP because if you are really unlucky then your loop breaks...
We will see what will happen next week.. i started last week the battery box and it is almost done...
^^" But updating it will wait a little bit. (You know mod compatiblity and co goes first)

**Comment by Carbon-Ghost** [comment]
Meh, I don't care about mining lasers, I want a reactor before mining laser eras and condenser + collectors infinite uranium, as in my modpack these requires quite a lot of rare and complex ressources :P

**Comment by Speiger** [comment]
Use a custom recipe adder mod since UU Matter is an Item you can make your own recipes.^^"
That solves your trouble...

**Comment by Carbon-Ghost** [comment]
Maybe... Still would prefer you adding it ;P

Meh it's ok for now ;)

**Comment by Speiger** [comment]
Because of the infinite power loop nope...

**Comment by Carbon-Ghost** [comment]
Yup, that's why I said we needed to balance it out, anyaway, it's ok ;)

**Comment by ExDomino** [comment]
I'm not agree with that. If you really want compac solars, there is an addon for that.

**Comment by Carbon-Ghost** [comment]
There IS a reason why we are integrating it in classic, this is due to the fact that the addon is for experimental IC2, and might have problems with classic as it ignores the e-net

**Comment by Carbon-Ghost** [comment]
+ have different textures from Classic

**Comment by Speiger** [comment]
@ExDomino, agreed.
What i would do anyways is a config that allow Dissableing it.
And also the Idea is to remove the lag from the EnergyNet (because i know a lot of people that do not know these addons and Places millions of SolarPannels, which the Old EnergyNet can not handle so easy then the new one)
^^"
But i am open for a talk anyway. And i nodest your opinien and will keep it in mind.

@Carbon-Ghost nope it is totally Stable and can not do anything bad in the EnergyNet...

**Comment by Carbon-Ghost** [comment]
Different textures from classic ;P

At this point, this is the only thing I have to say : 
- If addons adds classic version for us, then ok, else we fork it if we need to ;D
Still textures ;P

**Comment by Speiger** [comment]
Yeah. Would be a possebility.

**Comment by Speiger** [comment]
Just added the Compact solars to the Game. Simply are stacked versions of Solarpannels (NO OP in that term)
If there are suggestions i can add them but for now its added.

**Comment by Carbon-Ghost** [comment]
Suggestion number 1 ; disable them by default please, an HV compact solar is like having a reactor in one block that works during the day xD

Also, make the a-solar helmet ouput 8 eu since it's using an LV panel, right ?
But anyway, I would rather had integrated advanced solar panels...

another suggestion would be to give them a very small generation of EU during night and rain, but by very small I mean the generation during the day / 32

**Comment by Speiger** [comment]
@Carbon-Ghost 
suggestions answer:
1: requires 512 times more resources... No config at the moment.
2: Nope. Adv solar helmet produces 5 eu  thats enough... Even during the night..
3: Maybe with an upgrade... Not now at least...

**Comment by Carbon-Ghost** [comment]
Kk ^^
