### ISSUE TITLE
MFE OR MFSU won't drain power if its MJ power from BC.  (using flux generator) 

### ISSUE THREAD

**Issue by trilexcom** [TinyModularThings/IC2Classic#322]
MFE OR MFSU won't drain power if its MJ power from BC is connected for example their lasers..  (using flux generator) 

Forge Version : 2823
IC2 Classic Version : 1.12-15.4.2
BC : Buildcraft-all-7.99.24.1
IC2C Extras : ic2cextra-1.2.3
Gregtech Classic : 0.0.1-pre-alpha-26

Thanks 

Mat

**Comment by Speiger** [comment]
@trilexcom could you provide some pictures/video/gif or something that shows the issue?

**Comment by trilexcom** [comment]
sure brother one sec https://imgur.com/a/Eppg9b3

**Comment by Speiger** [comment]
![opera_2019-05-27_22-02-48](https://user-images.githubusercontent.com/2556269/58437654-3193d880-80cb-11e9-90ef-e8f8b32eb350.png)
(I am going to try in a minute again if you still upload  things.)

**Comment by trilexcom** [comment]
ok try again sorry https://imgur.com/a/Eppg9b3

**Comment by Speiger** [comment]
could you show me the side that is connecting to the pipes?
Also the pipes have power stored so it could be that there isnt any request. (Assuming)

**Comment by trilexcom** [comment]
i uploaded another picture while lasers are running, plus that

**Comment by Speiger** [comment]
ok i have to fix another bug i am going to test that again with these versions. If this is reproduceable then i will fix that if not then sry. 
Thanks for the report.

**Comment by trilexcom** [comment]
anytime brother thank you for supporting BC man i always appreciate it

**Comment by Speiger** [comment]
ok issues was bc inverted the logic for giving power.
Instead of saying how much got consumed it told how much was left.

**Comment by trilexcom** [comment]
So its on BC end or ic2c end ?

**Comment by Speiger** [comment]
I can fix it on my side. Patch is ready.

**Comment by trilexcom** [comment]
thank you for the quick fix my friend.

**Comment by Speiger** [comment]
Patch is out.

**Comment by trilexcom** [comment]
thank you again
