### ISSUE TITLE
[Bug] Missing recipes 

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#323]
After updating IC2C to the latest version, some shaped recipe just disappeared.

Those recipes are for blocks/items which have two shaped recipes. I.e.:
Advanced Circuit recipe;
Copper Cable;
Bronze Cable;
Advanced Machine Block;
Solar Panel (using only 1 type of dust (Charcoal Dust))

If this is intended, let me know.

**Comment by Speiger** [comment]
nope that is not intendet I am trying to make a config that is predictable sadly that isnt as easy to do.
(Trying to find a unique name system that can be implemented so that repeats can not happen and also is automatic).

**Comment by Speiger** [comment]
Could you please validate if that is also affected by machine recipes. Macerator etc. (I can not do that right now because IRL stuff and if I have that info it would help fixing that issue pretty quickly)

**Comment by CrossVas** [comment]
The Block and items which are affected by this are:
Reinforced Glass;
Industrial TNT;
Construction Foam;
Solar Panel;
Advanced Machine Block;
Copper Cable (Horizontal)
Bronze Cable (Horizontal)
Glass Fible Cable (using redstone)

As for machine recipes it seems to be okay.

**Comment by Speiger** [comment]
Nope it was around 50 recipes. I made a simple check. 
I changed how the recipehashes for crafting recipes are generated now and that should fix that problem.
(Patch is building as of the message)

**Comment by Speiger** [comment]
Patch is released

**Comment by CrossVas** [comment]
Wow, thank you!!
