### ISSUE TITLE
[Bug] Electric Hoe

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#327]
Heyo, 

Can you make Electric Hoe to work like vanilla hoe and not try to do infinite R-Clicks?

Thanks!

Attachment:

[Imgur](https://i.imgur.com/GESw4Ke.gifv)

EDIT: Electric Hoe also does R-Click on any block (whether from mods or from vanilla)

**Comment by Speiger** [comment]
Fixed.

**Comment by CrossVas** [comment]
Thank you!!
