### ISSUE TITLE
Fuel Boiler eats Fuel Cans when using vanilla hoppers

### ISSUE THREAD

**Issue by Froggy800** [TinyModularThings/IC2Classic#328]
The Fuel Boiler destroys Filled Fuel Cans when inserted with a vanilla hopper from any side; the items simply disappear, without providing anything to the device. The issue isn't present when the insertion is done with modded means (AE2's export bus, Immersive Engineering's Conveyor belts). Placing a hopper below the machine works as intended.

Tested with IC2Classic 1.12 1.5.4.3.2 on Forge 14.23.5.2838

**Comment by Froggy800** [comment]
I also found a dupe bug: I placed a Vacuum Canner machine with a Basic Import Upgrade set in the direction of the boiler: when the boiler finishes emptying the Fuel Can the Canner imports it in its own inventory, but the one in the boiler's inventory doesn't get removed. I can remove the fuel cans from the canner as many times as I want, they simply keep getting duped.

**Comment by Speiger** [comment]
cool will be fixed in the next patch.

**Comment by Froggy800** [comment]
The same issues is present with the PESU, MFSU, MFE, all four Water Mills and the Battery Station. Simply place a hopper above them to test it. The machines don't accept items they would not normally accept, but the ones they do accept end up getting voided. The Water Mills (all four tiers) accept and don't void RE-Batteries, but still void Water Buckets; the PESU appears to void everything but RE-Batteries; there's no issue with the BatBox.

**Comment by Speiger** [comment]
Yeah its the "Single Items" that get voided. I found the bug and it was a "<" that needed be changed to a "<=". That fixed all the issues.

**Comment by Speiger** [comment]
Will be in next patch. But that still needs a couple days because i want to add a couple other ideas.
