### ISSUE TITLE
Export upgrades & possibly other upgrades acting weird

### ISSUE THREAD

**Issue by e99999** [TinyModularThings/IC2Classic#329]
I dont know if its related to the recipe check logic being updated, but using export upgrades in machines seems to work only for a short while. Over the course of a few minutes it will just stop exporting, i thought it was related to the chunk unloading/loading but enabling chunk loading has no effect. I have not tried with import or other upgrades yet. 

Latest version ofc.

**Comment by Speiger** [comment]
Fixed.
