### ISSUE TITLE
Induction Furnace Dupe

### ISSUE THREAD

**Issue by abculatter2** [TinyModularThings/IC2Classic#331]
If an Induction Furnace smelts an odd number of items that isn't the first in a batch, it will produce an extra item on the last smelt

**Comment by Speiger** [comment]
@abculatter2 could you provide a video example Because if this was a thing then i would have gotten that report months/a year ago.

**Comment by abculatter2** [comment]
I'm not able to record video, unfortunately. I did download the latest version from a few days ago on Curseforge,  so it should be latest or close to it.
I didn't test it extensively, but literally all I had to do to replicate it was place a stack of any odd number of items 3 or above into the furnace and let it run until it finished the stack. It then produces an extra item on the final operation.
I can do some more testing tomorrow, if you'd like, and also take pictures of the set-up.

**Comment by Speiger** [comment]
Yeah found the issue. Thats patched now.
