### ISSUE TITLE
Toolbox dupes items while trying to drop them

### ISSUE THREAD

**Issue by gab111** [TinyModularThings/IC2Classic#332]
Upon hovering over an item in a toolbox (any toolbox will do) and clicking 'Q' or 'Ctrl + Q', inventory will close and the item will be dupped. 

![ezgif-5-55d25a7e3bee](https://user-images.githubusercontent.com/51998940/59771219-96e18080-92a9-11e9-86e7-159a6c49dd4b.gif)

**Comment by Speiger** [comment]
interesting i thought i prevented every dupe bug. Thanks.

**Comment by Speiger** [comment]
(oops closed it accedentily)

**Comment by Speiger** [comment]
Fixed.
