### ISSUE TITLE
Hazmat suit protection levels

### ISSUE THREAD

**Issue by urhen25** [TinyModularThings/IC2Classic#334]
The Hazmat Suit, Hazmat Suit Leggings, Scuba Helmet and Rubber Boots provide the same protection and toughness as their diamond armor counterparts. Considering how dirt cheap the armor is, I'm pretty sure this is unintended. 
On a maybe related note, I noticed that the same armor levels apply to the nano suit, quantum armor and bronze armor (except the bronze armor doesn't provide any armor toughness). This may be intended, but I thought it was worth mentioning.

**Comment by Speiger** [comment]
Hazmat suit, does only show these stats but when its actually applied it has barely any protection against these kind of things.
Bronze armor is just a default implementation of a armor types no special logic in damage calculation.
Electric Armor has a custom protection where it can absorb up to a certain damage and then they just let it through completly. If they run out of energy they have 0 protection unlike normal armor.
Sadly thats a "Material Only" thing and is not easy to do.
