### ISSUE TITLE
Won't Launch in Tekxit 3 with Hacked Clients

### ISSUE THREAD

**Issue by GamerGuyD3** [TinyModularThings/IC2Classic#335]
I downloaded Tekxit 3 and took out the following mods:

- RandomPatches
- (maybe others I forgot)

And added the following mods:

- Impact
- KAMI
- (maybe others I forgot)

I don't plan on hacking on official servers so please don't just overlook this request (not like i can play on Tekxit 3 servers without RandomPatches anyways). I plan on making my own anarchy server for some friends with the mods but am having this issue. Here's the link to the crash report, thanks <3: https://paste.dimdev.org/uzolahalek.mccrash

**Comment by CrossVas** [comment]
The version of IC2C is outdated.
Try to uptade it to the latest one.

**Comment by Speiger** [comment]
@CrossVas its barely out of date.

@GamerGuyD3 Two things.
1: Out of Legal issues I do not support Hacked Clients at all.
2: The crashlog shows that the crash comes from the Hacked Client itself.
```
net.minecraft.block.Block.handler$isFullBlock$zei000(Block.java:3183)
```
Block.handler$isFullBlock$zei000 does not exist and its at the bottom of the code so it was injected by hacks. So this is not a IC2C issue.

Sorry but this is on you.
