### ISSUE TITLE
IC2C Unknown Crash (About 65 Other Mods Installed; Modpacks Works Fine Without IC2C)

### ISSUE THREAD

**Issue by GreyMatterist7** [TinyModularThings/IC2Classic#339]
I've been working on essentially a revamped version of an old FTB pack to play around with, and decided to include IC2C as it keeps the old recipes, however every time I try to launch my pack with it, it crashes in stage 5/7 (post-initialization). If I take the mod out, the modpack launches fine. I can't seem to figure out what the issue is, though I concede I'm not super knowledgable about these things so I may be missing something obvious. I've been troubleshooting for about 2 hours now and can't figure it out. Crash Report attached below. Thanks!

[crash-2019-07-03_00.51.46-client.txt](https://github.com/TinyModularThings/IC2Classic/files/3353357/crash-2019-07-03_00.51.46-client.txt)

**Comment by Speiger** [comment]
the mod from KitzuneAlex is causing the crash. Because it puts a "OreDict" entry in that it wont support on its own.
Not IC2cs Bug. (KitzuneAlex is aware of that bug)

**Comment by Trinsdar** [comment]
@GreyMatterist7 I wouldn't use projext x as this bug has been around for quite a while and it's still not fixed. The mod also has other bugs too. Use this instead:https://www.curseforge.com/minecraft/mc-mods/quartzium

**Comment by GreyMatterist7** [comment]
Thanks so much!!!
