### ISSUE TITLE
[Bug] 1.7.10 - Additive Depleted Isotope Cells becoming normal Uranium Re-Enriched Cells.

### ISSUE THREAD

**Issue by Skyler-Altol** [TinyModularThings/IC2Classic#340]
Hi all,

First off I'll say that this is a bit of a stretch considering 1.7's age at this point, but it never hurts to ask. Essentially I'm playing with the last version of 1.7.10 I can find, which is 1.2.1.8, and I'm trying to breed the additive enhanced cells in a breeder reactor. But the depleted isotope cells end up becoming regular re-enriched uranium cells, as per the title. 

Is there any hope for a hotfix on that? I haven't found any other major issues with the 1.7 version. There are some minor things with Nuclear Control printing strange values and/or not showing some things, eg the remaining time for additive uranium cells is always 0:00:00 on the information panels. Using ComputerCraft to debug that results in finding that the dmg value does not increase for these cells, but it does increase for normal uranium. 

Side note: I'm loving this mod. It's seriously taking me back to the Tekkit Lite days xD All I need now is the Reactor Coolant Injector to auto recharge my LZH/RSH condensators, and I'll be able to perfectly replicate Tekkit Lite in 1.7. But I won't request that from IC2 Classic as Speiger has already ruled that out in the past haha. Thanks for making this mod, you've brought back some great memories :)

Cheers,
Skyler

**Comment by Speiger** [comment]
fixed.

**Comment by Skyler-Altol** [comment]
Is there any sort of timeline as to when the 1.7 jar file containing the fix will be pushed out? Cheers for the fast fix :D

**Comment by Speiger** [comment]
I am waiting for 1.12.2 to be ready for addons. (I am doing batch releases) which should be done at wednesday or thursday.
Also if other things show up go ahead and  tell because right now I am just on waiting for others.

**Comment by Skyler-Altol** [comment]
I'll do a full sweep for anything else in that case. Will update when I finish that.
