### ISSUE TITLE
1.14?

### ISSUE THREAD

**Issue by BigCasper** [TinyModularThings/IC2Classic#342]
Do you plan on doing a 1.14 port?

**Comment by Speiger** [comment]
yep but 1.14 is not fully released yet and forge is in alpha. Not the best conditions to port stuff.

**Comment by Trinsdar** [comment]
Well actually forge is the only thing that's not ready. Vanilla 1.14 itself just had its last version.

**Comment by Speiger** [comment]
Yeah but I bet they find another sub version.

**Comment by Trinsdar** [comment]
Well we'll see
