### ISSUE TITLE
Can't craft some stuff with TechReborn

### ISSUE THREAD

**Issue by JCDenton64** [TinyModularThings/IC2Classic#343]
With installed IC2Classic+1.12-1.5.4.4, TechReborn-1.12.2-2.22.1.979-universal and RebornCore-1.12.2-3.13.12.447-universal over Minecraft 1.12.2 and forge 14.23.5.2780 i cannot create Electric jetpack (and maybe some other mashines) due to messing up basic chip recpie.
Instead of crafting ic2 components i give TR component (copper wire, battery box, basic and advanced chip etc.)
Can you alter input resources for jetpack and probably other stuff to allowing use of TechReborn components? Or add some stub recpie (e.g. 1 TechReborn component shapeless => 1 IC2c component/mashine)?
Best regards. You work are really awesome!

**Comment by Speiger** [comment]
Yeah use the IC2C json recipes. Outside of that you are out of luck since TR isn't supported by IC2C

**Comment by JCDenton64** [comment]
Problem was resolved by editing config of TechReborn (.../config/teamreborn/techreborn/recipes.cfg, option "deduplicate=false" to "deduplicate=true")
Sorry about that!
