### ISSUE TITLE
[1.7.10] Backport the Crop Cloning Feature.

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#344]
A way to allow cloning crops if there is a single crop stick. Making the keeping of crops less of a hassle if you make it properly.

**Comment by OvermindDL1** [comment]
So you mean to take a snipping from a plant and planting it elsewhere?  ^.^

Technically can only do that with some plants, but wouldn't be bad to just have them all do it here.

**Comment by Speiger** [comment]
@OvermindDL1 nah the feature: If a Breeding crop is only  connected to a single fully grown crop (and no other crops) it creates a duplicate.

**Comment by Speiger** [comment]
done
