### ISSUE TITLE
Pumps should autoOutput to BC Pipes.

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#346]

**Comment by e99999** [comment]
does it have to be just BC pipes, or can it be any valid fluid container above the pump?

**Comment by Speiger** [comment]
It just does not notice BC Pipes because BC Pipes rely on the fact that the other tileEntity has to have a Fluid Capability to connect. Else they won't accept liquid.

Any other TileEntityContainer should be fully supported.

**Comment by Speiger** [comment]
done
