### ISSUE TITLE
[1.12]why does Flux Generator use FE instead of RF?

### ISSUE THREAD

**Issue by CrystalCurtain** [TinyModularThings/IC2Classic#347]
On my server,a group of players try using the wire from MEK to connect to the ic2 classic machines... but because the config of mek about it(the support of eu) was turned off by me(because it will crash the server when a plenty of energy through the wire of mek.)
And I see it,so I just said that you can use the Flux Generator to transform the energy.
But it didn't work.... By using the waila,I noticed the Flux Generator used FE instead of RF.... So I searched the FE on the mcbbs.And someone told me to install the hammer core, it will transform FE to RF automatically,and FE comes from Ex Compressum. So what caused it ?(and I 
 want to know why a plenty of energy will crash the server if I don't ban the mek's supporting of eu).

**Comment by Speiger** [comment]
Because at the time RF was a mess where each mod had its own Implementation and I personally didn't want to support 5 different RF APIs just at the risk of reworking everything because 1 API decided we are not supported anymore. And FE started getting popular I decided that thats the only API i am going to support because its forge integrated.

**Comment by CrystalCurtain** [comment]
but... when I installed the hammer core to try transform the energy... It still doesn't work.... In the matter of other mods,the transforming goes frequently,But when I try the Flux Generator... I used alot of wires ,but there is still no power in the Flux Generator...

**Comment by CrystalCurtain** [comment]
Okay I think I have got it... The flux generator is to generator RF and does not produce the Eu....
Hmmm... So How could I Transform other energy to Eu?

**Comment by laz2727** [comment]
You can't because it breaks the balance in half. The best you can do is use the real Universal Energy - steam.

**Comment by CrystalCurtain** [comment]
@laz2727
sorry but I can't stand what you discribed....
steam?
I'm a server owner so I can't change mod easily...

**Comment by Speiger** [comment]
ic2c has a steam generator that is what he means.
@CrystalCurtain

**Comment by CrystalCurtain** [comment]
hmmm...
So I should use steam to generate energy to transform other mods' energy?

**Comment by Speiger** [comment]
well you can generate EU out of railcraft steam if you want to.
But you need a lot of the steam turbines because each produces 40EU/t

Outside of that there isn't going to be a RF/FE => EU compat at all.

**Comment by CrystalCurtain** [comment]
but when I translate your mod(1.7.10) six months ago, I noticed there were some block can transform rf to eu or eu to rf, why they disappeared in the 1.12?

**Comment by Speiger** [comment]
Yes but they were dropped because they are not easy to balance the other way. The balance back then was 1 EU => 4 RF and 40RF => 1EU managing that without complaints was not worth it so i dropped the RF=>EU way, since if players played with IC2 they didnt want the unbalance in teh first place.
