### ISSUE TITLE
Rubber Wood in IC2Classic Sawmill outputs 6 Jungle Logs, instead of planks

### ISSUE THREAD

**Issue by TeetoKaziim** [TinyModularThings/IC2Classic#348]
![image](https://user-images.githubusercontent.com/25490944/62068011-c49bdc80-b1fa-11e9-97fc-09edbc20ab6e.png)

Everything about the sawmill and the other things the rubber wood log crafts into seems to indicate that these should be planks and not logs.

**Comment by Speiger** [comment]
Not a bug.
A rubber log when smelted produces a jungle log that's why it produces 6.

**Comment by GregoriusT** [comment]
So what you are saying (and confirmed on IRC while i wrote this) with this is, Jungle Wood is so ugly, that you would not even wanna farm Rubber Trees to get it unless you use it for Charcoal or something, and that 6 is the amount that makes this worth it and not 2 3 4 or 5. XD

**Comment by Speiger** [comment]
Yes because rubber is more worth then charcoal.
