### ISSUE TITLE
[Bug] Unable to remove recipes added by different mods

### ISSUE THREAD

**Issue by PapierZylinder** [TinyModularThings/IC2Classic#351]
Mods like Mekanism or Galacticcraft are adding recipes for the macerator. But in the ic2machineRecipes.json there is no way to disable those recipes and those mods don't have a option to disable the recipes either.

**Comment by Speiger** [comment]
Yeah not a bug.
If I do it any later this will track stuff like CraftTweaker.
Sry I  can't change that.
