### ISSUE TITLE
Nice Greg can give a 64 stack of UU for 1 emerald.

### ISSUE THREAD

**Issue by Slayer5934** [TinyModularThings/IC2Classic#354]
![ono](https://user-images.githubusercontent.com/20819543/63214926-ec40df00-c0ec-11e9-8894-297a78d340b9.PNG)

**Comment by Speiger** [comment]
Yeah I coded that in manually. (Config for the gregs exist)

**Comment by Speiger** [comment]
Not a bug @Slayer5934

**Comment by SuperCoder7979** [comment]
that means 1 emerald is only 9 iridium, it should really be 30 stacks of iridium per emerald /s

**Comment by Slayer5934** [comment]
Where is the config for the gregs, I cant seem to find it @Speiger o.o

Also personally I don't think that should be a thing, it takes 7 million EU to make a single uu matter and trading a single emerald for a 64 stack (which is basically half a million EU) seems really OP.. Unless I'm missing something o.o

**Comment by Speiger** [comment]
"enableVillagers" is the config.
About the other one its a joke that we had with greg when we were testing.

Greg sold 300k UUMatter for 1 Dragon Egg. And you were able to get 3 of them really easily.
He even sold power for way less.

If you dont like it. Don't use it. Or just enjoy the gag.

**Comment by Slayer5934** [comment]
Would it be possible to add a simple toggle for this trade? It isn't really a gag if it breaks a portion of the mod you guys worked hard on :/

**Comment by Speiger** [comment]
turn of villagers from ic2c thats your only option.

**Comment by Slayer5934** [comment]
If the source is updated I can add this config myself if you'd like?

**Comment by clienthax** [comment]
Is this config option meant to prevent trading existing gregs who spawned before the option was disabled?

**Comment by Speiger** [comment]
@Slayer5934 sourcecode is closed source because of legal rights.
@clienthax once a villager has trades loaded (aka a player interacted with a villager) the mod loses control over the Trades because they are strored in the Entity. So you have to kill the loaded trades villagers.
