### ISSUE TITLE
Canning Machine not accepting water

### ISSUE THREAD

**Issue by Silsec** [TinyModularThings/IC2Classic#356]
I trying to pump water into the canning machine (from all sides) from the ic2c pump, refined storage, and other mods with fluid transfer but cant get water into it.  Even tried fluid import upgrade. Is there something Im missing?

**Comment by Speiger** [comment]
Because the canning machine has no fluid tank?

**Comment by Silsec** [comment]
I just tried with a tank but nothing happened. Can show/explain a set-up that works.

**Comment by Speiger** [comment]
Open the UI or do it in JEI and look up the recipes. Or there is a wiki here too. Enough info to selfresearch.

**Comment by Silsec** [comment]
Wasnt looking for recipes and wiki doesnt explain enough unless its a bug.

**Comment by Speiger** [comment]
> The Canning Machine is used to fill Tin Cans with food, fill Electric Sprayers, CF Backpacks, Jetpacks, and Fuel Cans with Construction Foam and Fuel.

This cutted line from the first 2 lines of the documentation should tell you exactly what it is used for. If you then opened up the recipe list to check what recipes it has then you would have noticed nothing has to do with "Fluids" of any kind.
So again. Its not a Bug.
