### ISSUE TITLE
Is this intended not to burn out?

### ISSUE THREAD

**Issue by Slayer5934** [TinyModularThings/IC2Classic#357]
Sorry if it's a stupid question :P I just noticed in my house "Hey wait a minute, why didn't they poof?" So I tested in creative mode with 34k+ eu going to a mass fab and no burn.. 
![Capture](https://user-images.githubusercontent.com/20819543/63230475-0d7ff900-c1db-11e9-8280-0b8eb9c8c889.PNG)

**Comment by Speiger** [comment]
512EU/Packet. Not 512EU/Tick A cable can only handle infinite packets but the max is 512EU per packet.

**Comment by Slayer5934** [comment]
<3 Thank you sorry for wasting your time :c
