### ISSUE TITLE
Vacuum Canner (tin can) duplication glitch

### ISSUE THREAD

**Issue by Ad-Blokker** [TinyModularThings/IC2Classic#358]
It dupes tin cans using the Vacuum Canner with a Import Upgrade. The video says it all:
[Link to YouTube ](https://youtu.be/zSJEdzVy_fU)

I also tried it in a new world in SP and it did the same duplication glitch

p.s. Also tried it with the regular Canning Machine but when it has the Import upgrade installed it just ignores it and doesn't import anything. But the export upgrade works just fine. The import upgrade is set to the correct side.

**Comment by Speiger** [comment]
Fixed.
