### ISSUE TITLE
Quantum and Nano armor behave different in MP

### ISSUE THREAD

**Issue by Ad-Blokker** [TinyModularThings/IC2Classic#359]
In single-player you will be insta killed when hit by lighting when you are not on the ground at the time of impact. But when we switch over to a Multiplayer server this doesn't happen. You are just immune to lighting when flying with a nano or quantum suit. This seems like a bug to me

Multiplayer video of getting struck by lighting while flying:
[https://youtu.be/tD4DAzfCVxI](https://youtu.be/tD4DAzfCVxI)

**Comment by Speiger** [comment]
fixed
