### ISSUE TITLE
No scrap metal from metal tools in Recycler 

### ISSUE THREAD

**Issue by Ad-Blokker** [TinyModularThings/IC2Classic#360]
The title says it all. When recycling metal tools the recycler gives iron/gold ingots instead of scrap metal.

**Comment by Speiger** [comment]
Damaged tools give ScrapMetal. Normal give metal.

**Comment by Ad-Blokker** [comment]
I also tried broken tools and they just make normal scrap
Video: [https://youtu.be/y7M6HkexW_0](https://youtu.be/y7M6HkexW_0)

**Comment by Speiger** [comment]
ahh a recipe sorting issue.
