### ISSUE TITLE
[Feature Request] Solar Energy at Night

### ISSUE THREAD

**Issue by Slayer5934** [TinyModularThings/IC2Classic#361]
Would you be able to make the top 2 tier solar panels able to produce a tiny amount of energy at night?

Like maybe HV producing 48 EU at night and MV doing 16? This is purely a feature request :3

**Comment by Speiger** [comment]
AdvSolars in 1.7.10 is compatible & 1.12 has the Classic Edition of AdvSolars on Curse that do exactly that. https://www.curseforge.com/minecraft/mc-mods/advanced-solars-classic

I am not going to implement that addon but its there for those who want it.
