### ISSUE TITLE
[1.7.10] Solar Panels do not charge items inside them

### ISSUE THREAD

**Issue by Skyler-Altol** [TinyModularThings/IC2Classic#362]
See title. Attempting to place a piece of nano suit armour into the slot in the solar panels (assuming the solar panel is the appropriate voltage level, in this case a medium voltage panel) results in no charge being added to the armour.

**Comment by Speiger** [comment]
I just tested it and the MV or higher solar panel charges the nano armor fine.
And yes the Energy tier matters in the source. Thats why a nano armor cant be charged in a generator either.

**Comment by Skyler-Altol** [comment]
@Speiger did you test in SSP or SMP?

**Comment by Speiger** [comment]
Nvm i missed the 1.7.10 and after rechecking yes you are right. Will be patched with the next 1.7.10 release.

**Comment by Speiger** [comment]
fixed for all generators.
