### ISSUE TITLE
Vacuum canner (output duplication)

### ISSUE THREAD

**Issue by Ad-Blokker** [TinyModularThings/IC2Classic#364]
When putting in 1 stack of toast (which gives 4 filled tin cans out per 1 toast) it gives 4 stacks of filled tin cans out, this is correct.

BUT, when putting in 3 stacks of toast it is supposed to give 12 stacks out, because math.
> 3X 64 Bread = 192 bread total
> 192 x 4 = 768 filled tin cans = 12 stacks of filled tin cans

But the actual output is 19+ stacks

It seems to do some weird duplication when there are multiple stacks in the input slots

**Comment by Ad-Blokker** [comment]
This also happend with vanilla Minecraft food by the way

**Comment by Speiger** [comment]
fixed.
