### ISSUE TITLE
Can't find a way to add recipes for fluid generator

### ISSUE THREAD

**Issue by flyingperson23** [TinyModularThings/IC2Classic#366]
I've looked through all the recipe handling code I can find and it seems to me that all the recipes for the semifluid generator are hard-coded, and I can't find a way to add any more of them

**Comment by Trinsdar** [comment]
This has a method of doing it: https://www.curseforge.com/minecraft/mc-mods/ic2-classic-tweaker
https://github.com/Trinsdar/IC2ClassicTweaker/blob/master/doc/LiquidFuelGenerator.md

**Comment by Speiger** [comment]
@flyingperson23 the only way to do is how @Trinsdar showed it.
