### ISSUE TITLE
[1.12.2] Nano Helmet HUD Impossible to Activate

### ISSUE THREAD

**Issue by Walkop** [TinyModularThings/IC2Classic#368]
This has been tested by multiple users on different computers.

Just as in title. Does ANYONE know how to enable the HUD for the Cropnalyzer on the Nano helmet? Same with the EU-Reader or Thermometer. The EU Reader, when equipped, gives tool tip information, but nothing visible. The Thermometer doesn't work at all. From what I can tell at least. The Cropnalyzer has no HUD, and cannot be toggled on or off no matter what i set the key binds to.

Making all Nano Helmet equipment functionally useless.

**Comment by Speiger** [comment]
the one probe is needed.

**Comment by Walkop** [comment]
One probe? Sorry, I'm not sure what you mean. I've been fighting this issue for hours and if it's a simple lack of information on my part, I'd love to learn how to activate the HUD. I've checked many videos and every wiki I could find, nothing explains how to activate the suits integrated tools.

**Comment by Speiger** [comment]
https://www.curseforge.com/minecraft/mc-mods/the-one-probe

**Comment by Speiger** [comment]
To give more information: 
The one probe is a hud mod that provides huds based on what the mod provides them.
IC2Classic has a the one probe integration to show the data to the player.
Since I didnt want to implement my own system using that mod made it a lot easier.

**Comment by Walkop** [comment]
That's fantastic! Thank you. I'll edit any Wikis I find to include this information.

**Comment by Walkop** [comment]
Sorry to bother again. Installed The One Probe to client and server. Still can't get the HUD to show up, no matter what key combo is used. Any ideas?

**Comment by CrossVas** [comment]
Try to combine Helmet with Probe in Crafting table

**Comment by Speiger** [comment]
@Walkop that or use the "Probe" Bauble. Since IC2C has baubles support that would players to make a lot of things easier.

**Comment by Walkop** [comment]
Combining the OneProbe with the helmet doesn't work...the bauble should, I
would think, but it breaks immersion to have the option to combine the
readers into the helmet but they just don't work (and also, that OneProbe
isn't mentioned anywhere in the material).

Is there any chance of this getting fixed, maybe coding the crafted helmet
to hook in directly? Or is that outside of IC2c?

**Comment by Speiger** [comment]
honestly. I am not changing anything. You have all tools needed. I suggest you look into the Baubles mod on CurseForge that should help. Or set the config not to need the things. I can not do your job in that regard to read configs or look for potential solutions.
This is done for me now.
