### ISSUE TITLE
Delete Me

### ISSUE THREAD

**Issue by Walkop** [TinyModularThings/IC2Classic#369]
Hello Speiger;

I wrote this out immediately after your last reply to my issue with the Nano Helm, but didn't realize you'd blocked the thread. I felt awful when I read that, as my intention was never to bother you and what I had already sent you (but was never received) was designed to clear that up.

It's pasted below.

"That's no problem! I wasn't trying to be difficult. I appreciate your help, and all the work you've done into IC2c. I just wanted to ask some questions. I wasn't sure how it worked. I've also prodded around in all the config files and modified things to work as best I can. I just wanted to know if there was anything I was missing as to how it works to make it work properly. Honestly, IC2c has been the highlight of PC gaming for me for the past month! You've done some incredible work :)

Baubles I have, I put the OneProbe there and it's worked fine. Thank you for all your responses and super prompt replies. It's been a breath of fresh air from what I'm used to online!"

Thanks again, for everything. You've been an awesome help. :)

**Comment by Speiger** [comment]
No problem. Just busy with a lot of stuff. And at some point it got a bit annoying so thats why the closing.
Asking for help is fine. But overdoing it (and you were close enough) is a point where I dont want to deal with it anymore.

So no worry as long you stay reasonable.
