### ISSUE TITLE
EU bug with Exp addons.

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#37]
Some machines have a 0 EU request.
The problem here is that i made a fix that prevent that you overload a machine because IC2 Exp is not using his own functions properly...
My fix simply preventing energy to flow into the machine when it is not requesting something...

That causes problems because of their system that does not really help...

**Comment by Speiger** [comment]
Fixed... Very dirty... Well it works...

**Comment by Chocohead** [comment]
Should this still have the inprogress tag?

**Comment by Speiger** [comment]
Yeah is still in progress because i do not want to have it in the EnergyNet (this stupid fix)
thats why i still keep in progress in so that i can remind myself with that yelling at other dev mods/ic2 itself...
