### ISSUE TITLE
[Suggestion] Add Immersive Petroleum fuels to Fluid Generator

### ISSUE THREAD

**Issue by abculatter2** [TinyModularThings/IC2Classic#374]
Not sure if you guys are open to these sorts of minor compatibility suggestions, though I figured adding two values wouldn't be too big a deal.

Based on what I looked up on the wiki, Gasoline produces 51,200 RF per bucket, so using the Flux Generator's 1 EU = 8 RF ratio that's 6,400 EU per bucket.

Diesel I haven't been able to really find good numbers for, though I'm pretty sure it's about 45,000 EU per bucket.

**Comment by Speiger** [comment]
Diesel is already supported through BC from what I remember.
Right now there are no plans to add IE Fuel support but there is an API. Maybe the minetweaker addon that @Trinsdar is making can help you out there.

**Comment by abculatter2** [comment]
Unfortuntaely, Immersive Petroleum's diesel seems to not just be oredict fuel. I don't know why, tbh.

IE's biodiesel is already supported, from what I can tell.

**Comment by Speiger** [comment]
Then this is your only hope. From what I know it supports LiquidGenerator too.
https://github.com/Trinsdar/IC2ClassicTweaker

Anyways issue from this side is closed.
