### ISSUE TITLE
Export Upgrade doesn't work with Extractor

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#376]
Export Upgrade doesn't work with Extractor. It works with the macerator.
It is set to "up". Both Extractor and Macerator has a chest upside.

Minecraft: 1.12.2
Forge: 14.23.5.2847
IC2C: 1.5.4.4

**Comment by Speiger** [comment]
Because the up side is disabled for the extractor in terms of exports. You need a machine tool to enable the up side to be exported from (also automation or side upgrade)
