### ISSUE TITLE
Can't add custom machine recipe

### ISSUE THREAD

**Issue by JungleJ0n** [TinyModularThings/IC2Classic#378]
I'm trying to add a machine recipe that takes 9 Iridium nuggets and gives one iridium ore.
Im not sure if there is an user error or because it's different mod packs
`{ "recipes": [ { "recipeType": "compressor", "hidden": false, "output": { "item":"ic2:itemmisc", "meta": 181, "amount": 1 }, "recipeMetadata": '{}', "recipeExperience": 0, "input": { "inputType": "ore", "oreID": "nuggetIridium", "amount": 9 } } ] }`

**Comment by Speiger** [comment]
eh cant see an issue right out of the gate.
Just look for this text in the startup log:
```
Custom Recipe Loader Start
```
If errors show up you find them there.
