### ISSUE TITLE
CF Sprayer

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#38]
It seems it doesn't work, or at the very least you can't fill it with CF Pellets.

**Comment by Speiger** [comment]
Try canning machine, crafting recipe also exsist. Compressed forma pellets + the Sprayer.
If that not work post please here again.

**Comment by Chocohead** [comment]
Ok, so the canning machine doesn't work but I managed to get the crafting recipe working (turns out the NEI spawned one is full). The sprayer itself doesn't work however, either on a cable or just on the ground.

**Comment by Speiger** [comment]
kk

**Comment by Speiger** [comment]
Fixed. Still some other Problems with the Networking but the spraying works. Also the Foam blocks working.
