### ISSUE TITLE
Composite and Bronze armor repair crash

### ISSUE THREAD

**Issue by zHawky** [TinyModularThings/IC2Classic#380]
[crash-2019-11-23_16.43.31-client.txt](https://github.com/TinyModularThings/IC2Classic/files/3882346/crash-2019-11-23_16.43.31-client.txt)
[crash-2019-11-23_16.42.25-client.txt](https://github.com/TinyModularThings/IC2Classic/files/3882347/crash-2019-11-23_16.42.25-client.txt)

**Comment by Speiger** [comment]
will be patched in the next patch.
