### ISSUE TITLE
Couple crafting tables bug out with stacked crafting.

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#382]
So far, after testingthese bug out:
the sequential fabricator from thermal can craft stacked recipes but only using 1 item, and it doesn't even require the recipe to be showing up as stacked, though you have to set the recipe using jei. It led to this crash though: https://paste.dimdev.org/ucuhiwolew.makefile.
the formulaic assembler will do the same, but the difference is the slots are actual crafting slots, so the items get reduced by one, and it doesn't crash.

The arcane workbench can craft stacked recipes, but seems to only consume the non stacked items when it is stacked.

Ic2 classic version 1.5.4.5
Thermal Expansion 5.5.4.43
Thaumcraft 6.1.BETA26

mekanism 9.8.2.389
jei 4.15.0.292
tested using the upcoming atm3 expert pack, but I don't think any of the other mods are relevant at all.

I haven't posted on any other trackers yet as I don't know how fixable this even is.

thaumcraft table:
![thaumcic table](https://user-images.githubusercontent.com/30245301/69497669-ab0b5880-0ead-11ea-8790-1ff0e9b83999.gif)

sequential fabricator:
![thermal](https://user-images.githubusercontent.com/30245301/69497716-181eee00-0eae-11ea-8bd3-207a2afaeef8.gif)
formulaic assembler:
![mek](https://user-images.githubusercontent.com/30245301/69497737-52888b00-0eae-11ea-9ca1-6c9e2e9ca4c6.gif)

**Comment by Speiger** [comment]
Please report to the crafters directly because they might be hardcoding a couple things.
Ask for info if they support all functions that a crafting table does?
(Because else a lot of different mods would have issues too)

**Comment by Trinsdar** [comment]
ok

**Comment by MachiavelliSeraphim** [comment]
Just ran into this same problem.
AE2 cant do it either with the patterns since it wont allow stacked crafting.

Sequential Fabricator works, but causes intermittent server crashes....

**Comment by MachiavelliSeraphim** [comment]
Out of curiosity, what ever happened to the batch crafter?
Wasn't it originally in IC2?

**Comment by Speiger** [comment]
@MachiavelliSeraphim ic2c only has the crafting upgrade & the industrialworkbench which both support stackcrafting.
Anything else is IC2Experimental. That is not ic2classic

**Comment by e99999** [comment]
GTC Electric Craftingtable can support stack crafting, just sayin 😎 ✌️

**Comment by MachiavelliSeraphim** [comment]
I assume there is an undocumented way to automate with the crafting upgrade or the table, since the Wiki is blank in that regard.

**Comment by Speiger** [comment]
@MachiavelliSeraphim its a ic2c upgrade so it can go anywhere where ic2c upgrades can go.
You set the recipe via opening the crafting menu. And it grabs the items out of the machine and puts it into the direction the export side is facing.
Machine Buffers are full crafting grid and with inventory upgrades you can set which items are allowed to be where and how many of them max.
Its a powerful system that barely anyone uses because its not thrown into their faces.

**Comment by Speiger** [comment]
also @e99999 claim is wrong there is other mods that support stackcrafting.
RFTools for sure, Buildcraft (maybe), RefinedStorage supports it too.
There should be more.

**Comment by MachiavelliSeraphim** [comment]
Huh, ill hafta try tinkering with it.  I figured there had to be a way to make everything work.

Only complaint is I cant put batteries in the buffer :(

Galacticraft makes it nice with the Venus atomic batteries....

**Comment by Speiger** [comment]
@MachiavelliSeraphim energy in a buffer is only needed if the upgrade itself needs power. Which only "Export & Import (Item & Fluid)" upgrades need. (The adv version).
It only has a energy buffer so if you need power then it would drain it from there.

**Comment by MachiavelliSeraphim** [comment]
Thanks.
Ill try it when I get a chance.
Always assumed the crafting upgrade would need power.  
Guess not.

**Comment by MachiavelliSeraphim** [comment]
Seems to work at an odd pace, but works.

**Comment by Speiger** [comment]
@MachiavelliSeraphim it runs up to 2-4 times a second, but it adjusts its crafting speed based on how frequently the items are present.
In other words: The more successful crafts it has the faster it runs. With a cap.
It ranges i think between (5-10)-(120-240) ticks of delay between ticks (i dont remember properly right now)

**Comment by MachiavelliSeraphim** [comment]
Interesting.  
I noticed if you shuffle 4 of them in and out of the machine itll race till it runs out of materials, then go back to slow.
Awesome thst it works though.

Thanks again.

**Comment by Speiger** [comment]
all sides either fixed or disable the issue. so closing now.
