### ISSUE TITLE
Custom Recipe format

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [TinyModularThings/IC2Classic#383]
I cant use the 4 tin ingot recipe to make cells because thermal expansion uses that recipe for making gears.

How do I define a new recipe that would put the 4 ingots in the corners instead?

Is it MineTweaker format, or a different context?

Sorry to keep bugging you.
Thanks.

**Comment by Speiger** [comment]
https://github.com/TinyModularThings/IC2Classic/wiki/How-to-add-custom-Recipes
Examples are present

**Comment by MachiavelliSeraphim** [comment]
{
	"recipes":
	[
		{
			"recipeType": "shaped",
			"hidden": false,
			"output":
			{
				"item": "ic2:itemcellempty",
				"meta": 0,
				"amount": 1,
				"nbt": '{"display":{"Name": "TestingName"}}'
			},
			"pattern": ["O O", "   ", "O O"],
			"inputs":
			[
				{
					"patternID": "O",
					"inputType": "forge:ore_dict",
					"oreID": "ingotTin",
					"amount": 1
				},
				
			]
		}
	]
}

Apparently Ive got something wrong here.....

I hate not having learned newer languages....

**Comment by Speiger** [comment]
@MachiavelliSeraphim there is a Minetweaker addon for IC2Classic. (Could have told that right out of the gate)
It should be called IC2CTweaker @Trinsdar

**Comment by MachiavelliSeraphim** [comment]
Thanks.  
I usually try my hand at writing it if I've got a good syntax example to work with.  
I just created the recipe in CraftTweaker for the moment.
I will lookup the Minetweaker addon for IC2C.

Thanks again.

**Comment by Trinsdar** [comment]
yah: https://www.curseforge.com/minecraft/mc-mods/ic2-classic-tweaker

**Comment by CrossVas** [comment]
Or you can change the recipe of gears to use iron in the middle via TE config.

**Comment by MachiavelliSeraphim** [comment]
Thank you everyone for all the help.
