### ISSUE TITLE
Multipart Limunator doesnt seem to work.

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [TinyModularThings/IC2Classic#384]
Is there a problem with the Multi-part Luminators?

The normal ones work perfectly but the multi-parts wont draw power or turn on.
Am I missing something?

Thanks.

**Comment by Speiger** [comment]
Eh yeah tried to patch this. But the reason this does not work is some underlying big foundation issue.
Will be moved to a later try of patching. (Already invested a hour to patch this bug. And patched other things but this seems right now not solvable)

**Comment by Speiger** [comment]
Fixed and released
