### ISSUE TITLE
Suggestion: make miner check tools based off ic2 experimental's new interface IMiningDrill

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#385]
Basically it would allow other mods to add valid drills to the miner by implenenting the interface, like how tech reborn does here: https://github.com/TechReborn/TechReborn/commit/a452e694e9b61decb42fdd7a46ca0095da5c4f12

**Comment by Speiger** [comment]
The IC2Exp MiningDrill API works in reverse of Classics.
I mean its not impossible but its basically reworking the Miner Class quite a bit.
Since IC2Exps API says the tool how long the max progress is while mine allows to speed up the fixed speed.

**Comment by Trinsdar** [comment]
ah ok
