### ISSUE TITLE
Regular luminator does not have a proper hitbox

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#386]
Currently it takes up the whole block, when it should only take up the 1 pixel wide face it is on
![2019-12-29_23 20 01](https://user-images.githubusercontent.com/30245301/71568091-5a7db100-2a92-11ea-9fb6-d2acee35f032.png)
![2019-12-29_23 24 33](https://user-images.githubusercontent.com/30245301/71568106-87ca5f00-2a92-11ea-8598-8f3c82b33ac9.png)
Seems to be a reoccurrence of #79
Also if you've noticed they have a render bug, but I don't expect you  to be able to fix that

**Comment by Speiger** [comment]
Fixed
