### ISSUE TITLE
IC2 breaks Botania Pylon rendering

### ISSUE THREAD

**Issue by PapierZylinder** [TinyModularThings/IC2Classic#387]
When having Botania and IC2C installed, it seems that ic2s breaks the render of the botania pylons. They are invisible in the inventory.
When i remove ic2c the pylons in the inventory are visible again.

The version of the mods i have installed:
Baubles-1.12-1.5.2
Botania r1.10-363
IC2Classic 1.12-1.5.4.5

![2020-01-02_23 14 26](https://user-images.githubusercontent.com/45166325/71696740-10f4d500-2db6-11ea-83ff-f59d73cd5f9b.png)

**Comment by Speiger** [comment]
@PapierZylinder could you provide me the startup log of the game?

**Comment by PapierZylinder** [comment]
Not 100% sure what you mean with startup log, but i guess this should be what you want.
https://pastebin.com/GdEZviLQ

**Comment by Speiger** [comment]
The log between GameStart and main menu. That should be really long.

**Comment by PapierZylinder** [comment]
oh okay, took me a while to find it. Thats the only other file i found. I hope its the correct one this time.
https://pastebin.com/VCZw3MUj

**Comment by Tim2162286** [comment]
The same thing is occurring with Astral Sorcery collector crystals.
![InvisibleCrystals](https://user-images.githubusercontent.com/15058004/77271467-0be44b00-6c6c-11ea-9c94-ad86b3dd54c0.PNG)

**Comment by DAmNRelentless** [comment]
Is this still being worked on?

**Comment by Speiger** [comment]
Yes

**Comment by Speiger** [comment]
Fixed.
