### ISSUE TITLE
Jetpack toggle mode doesn't work

### ISSUE THREAD

**Issue by dKenez** [TinyModularThings/IC2Classic#388]
The default m key doesn't change jetpack mode. I even tried changing the key to "P" but is till didn't work.

**Comment by Trinsdar** [comment]
did you make sure to be holding space when you press it?

**Comment by dKenez** [comment]
I did not, thank you for the reply@

**Comment by Speiger** [comment]
Thanks @Trinsdar i just became to busy to even answer that.
