### ISSUE TITLE
Machines can export newly created items to disabled sides

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#389]
Scenario: Compacting Recycler with a Basic Export Upgrade set to "up", and a chest above it, but without doing anything to enable that side.

Bug: Newly created scrap (not scrap that's already in the export slot) will be exported to the top.

I noticed that my Compacting Recycler wasn't exporting the scrap in its output slot, only the newly created scrap. Then I saw #376 and realized that the top must be disabled by default, so I tried other sides and it worked there, which means the bug must be that the newly created scrap does get exported. I tried the Extractor mentioned in that issue, and the same thing happened, so I think it happens on all machines (with their disabled sides, not necessarily the top), but I didn't test any others.

As a side note, are disabled sides listed anywhere? I can't find any way to see what they are (or even that they exist) other than trial and error.

Minecraft: 1.12.2
Forge: 14.23.5.2847
IC2C: 1.5.4.5

**Comment by Speiger** [comment]
Ok sorry I was very busy,
You can control input & output settings via the Machine Tool and Inventory Upgrades.
https://github.com/TinyModularThings/IC2Classic/wiki/Inventory-Upgrades

Ofc some upgrades can bypass this system entirely do to performance optimizations, and a change would require rethinking the entire idea of it.
So not a bug but a feature.

**Comment by dwentz89** [comment]
Hmm, well, I don't think it's good design for the export upgrades to work halfway in situations like this, especially without mentioning it either in game or in the wiki. I can understand not wanting to redo the whole system over this though, and as you said, workarounds already exist, so I guess it's not a big deal.

**Comment by Speiger** [comment]
If you really think about it, most mods have side control & auto export/import, and that is linked to side  control. Mine is a bit more dynamic but horrible at telling the user how it works. Not denying that.

Enough selfjustification. This feature among a lot of others are on my personal "want to fix" list. Though it is to big of a change for the next update

**Comment by dwentz89** [comment]
I don't have a problem with side control (especially when you have an upgrade that disables it). I was surprised that it exists since it's not documented very well, but I'm mainly complaining about how the export upgrades partially bypass the side control without fully bypassing it.

If the upgrades didn't export newly created items, it'd make sense because they're obeying the side control. If they exported all items (both new and old), it'd make sense because they're overriding the side control. The current situation is partially obeying it and partially overriding it, which just confuses me. It's not at all intuitive that new and old items should have different export rules.
