### ISSUE TITLE
Nutrient Storage display issue

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#391]
When scanning unknown crops with the Cropnalyzer, the Nutrient Storage is displayed as x/100, but it still lets you go up to 200 like with known crops, and going past 100 still keeps increasing the Crop Nutrients.

Minecraft: 1.12.2
Forge: 14.23.5.2847
IC2C: 1.5.4.5

**Comment by Speiger** [comment]
Thanks will be checked and fixed in the next patch.

**Comment by Speiger** [comment]
Fixed
