### ISSUE TITLE
Weed-Ex Storage save issue

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#392]
When saving and loading the game, all crops reset to 0 Weed-Ex Storage. I suspect this would also happen if you unload and reload the chunk, but I haven't tested that.

Minecraft: 1.12.2
Forge: 14.23.5.2847
IC2C: 1.5.4.5

**Comment by Speiger** [comment]
Yep i forgot to save that value. Will be patched in the next version.

**Comment by Speiger** [comment]
Fixed
