### ISSUE TITLE
Metal crops don't look deep enough for ore

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#393]
Normal crops get humidity/nutrients from the farmland block directly below them and from the 3 dirt blocks below that, for a total of 4 blocks below the crop itself. The metal crops (Ferru, Aurelia, etc.) only look 3 blocks down for their ore, so you have to do the farmland, then a single dirt, then the ore, and it doesn't check for another dirt after the ore. I think they should look up to 4 blocks down for the ore to be consistent, or at least still check for dirt after the ore. As it is now, you have to give up the bonuses from 2 dirt blocks to place the ore.

Oh, and I think Nether Wart and Terra Wart are also affected when they check for Soul Sand or Snow, but that's harder to test.

Minecraft: 1.12.2
Forge: 14.23.5.2847
IC2C: 1.5.4.5

**Comment by Speiger** [comment]
Yep this is intentionally. You still can put the ore as deep as the lowest possible dirt.

**Comment by dwentz89** [comment]
Well I can't. If I replace the lowest dirt with an ore they don't grow at all. I have to replace the lowest 2.

**Comment by Speiger** [comment]
Yeah because its not inclusive.

**Comment by dwentz89** [comment]
Then it's not looking 3 below the farmland. It's only looking at the one directly below the farmland and the one directly below that, which is 2 below the farmland.

**Comment by dwentz89** [comment]
Maybe this will clarify.

**Normal crop:**
Level 0: Crop
Level -1: Farmland (gives stats)
Level -2: Dirt (gives stats)
Level -3: Dirt (gives stats)
Level -4: Dirt (gives stats)
Level -5: Dirt (does not give stats)

**Metal crop:** (grows)
Level 0: Crop
Level -1: Farmland (gives stats)
Level -2: Dirt (gives stats)
Level -3: Ore (is checked)
Level -4: Dirt (does not give stats)
Level -5: Dirt (does not give stats)

**Metal crop:** (does not grow, but I think it should)
Level 0: Crop
Level -1: Farmland (gives stats)
Level -2: Dirt (gives stats)
Level -3: Dirt (gives stats)
Level -4: Ore (is not checked, but I think it should be)
Level -5: Dirt (does not give stats)

**Comment by Speiger** [comment]
Yep i know. The dirt part is intendet behavior. That is not going to change.
The root part is not part of intendet behavior. It should be inclusive.
I just made it inclusive so the next patch will have this fixed.

**Comment by dwentz89** [comment]
This issue still exists as originally reported, in `IC2Classic-1.12-1.5.8.jar` with `1.12.2-forge-14.23.5.2859.jar`
