### ISSUE TITLE
Nutrient Storage suggestion

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#394]
Currently, Nutrient Storage maxes out at 200, which gives +10 Crop Nutrients, but it can't be refilled until you drop down to 100, and at 101 you only get +6 Crop Nutrients, so the stat will keep fluctuating no matter how diligent you are at maintaining your crops.

Water Storage doesn't have this problem because it can be refilled whenever you're below the max instead of needing to wait until half the max, and Weed-Ex Storage doesn't either because high Weed-Ex Storage doesn't help any more than low Weed-Ex Storage does.

I propose capping the Crop Nutrients bonus from Nutrient Storage at +10 (to match the +10 from max Water Storage), but increasing the maximum Crop Nutrients to 300 so that you'll be able to refill it before the bonus drops below +10

**Comment by Speiger** [comment]
Water does not have this issue because it takes durability to refill it. So it can take partical amounts. While fertilizer only can consume 1 item fully. So it wont allow another fertilization if the item does not fit in the crop. (So you dont lose something)

And this is intendet behavior without making fertilizer unstackable.

**Comment by dwentz89** [comment]
I know, that's why my proposal is to increase the max storage instead of making fertilizer have durability. The result is effectively the same, but my way is (probably) easier to implement and without negative side effects like making fertilizer unstackable.

**Comment by Speiger** [comment]
The result would be still the same, fertilizer effect does not get capped so increasing would just create the same result. And that behavior won't change
What you can do is 2 things: Choose a biome that has a high nutrient count.
Or use soulsand as farmland that has a high nutrient count but a negative water effect.

**Comment by dwentz89** [comment]
It looks like I wrote it wrong it in my first post, but I'm proposing adding a cap to the Crop Nutrients bonus, and also increasing the Nutrient Storage cap.
> I propose capping the Crop Nutrients bonus from Nutrient Storage at +10 (to match the +10 from max Water Storage), but increasing the maximum Nutrient Storage to 300 so that you'll be able to refill it before the bonus drops below +10.

Because of the new cap to the Crop Nutrients bonus, it would not create the same result.

Nutrient Storage | Crop Nutrients in current version | Crop Nutrients in my proposed version
------------ | ------------- | -------------
50 | +3 | +3
100 | +5 | +5
150 | +8 | +8
200 | +10 | +10
250 | N/A | +10
300 | N/A | +10

Whenever it drops down to 200, you'd be able to fill it back up to 300, and the bonus would stay at +10 the entire time.

**Comment by OvermindDL1** [comment]
What @dwentz89 says makes sense, I'm +1 on it, it's bugged me as well.

**Comment by Speiger** [comment]
Changed in the way that it can be now used until the value is 200 or more. But the effect will be capped and the value above 200 will be now hidden for progressbars or cropanalyzer info. (TL:DR caps at 200 and even if it is at 254 it will only show 200)

**Comment by Speiger** [comment]
@OvermindDL1

**Comment by OvermindDL1** [comment]
Cool, that makes sense.
