### ISSUE TITLE
Custom crafting recipes don't work

### ISSUE THREAD

**Issue by Erik3003** [TinyModularThings/IC2Classic#396]
https://pastebin.com/XZdTAvHS

This is trying to load the custom recipes on the wiki page, so the recipe is definitively correct.

**Comment by Speiger** [comment]
Sorry IRL went busy, I saw it in discord, I wanted to answer it later. 
(Sorry i look at it later right now really busy, just wanted to tell you that i saw it)

**Comment by Speiger** [comment]
@Erik3003 the issue is that the amount is missing in the input.

**Comment by Speiger** [comment]
oh @Erik3003 item is not a Object
item & meta go into the same object as input type.

**Comment by Erik3003** [comment]
Works now, the tutorial on the wiki was incorrect.
