### ISSUE TITLE
I can't craft Flux Generators

### ISSUE THREAD

**Issue by Bitek1993** [TinyModularThings/IC2Classic#397]
I use some mods, that require energy conversion, rf to eu, but i can only find Electric Flux Generators, thera are no flux generators available in the game, and  i don't know why, and how to make it appear, please help me
![no flux](https://user-images.githubusercontent.com/41382874/74611887-67b53480-5100-11ea-9cb8-43ad1ec74f7e.png)

**Comment by Speiger** [comment]
Were removed do to impossiblity to balance RF to EU. 
Back then it was 40RF => 1EU and 1EU => 4RF, I am not planning to read RF => EU support again.
