### ISSUE TITLE
Question : Install with ic2exp (1.7.10)

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#398]
Hello, it is possible, in 1.7.10, to install your mod togheter with ic2exp ?
Thank you in advance.

**Comment by CrossVas** [comment]
No, or IC2 Classic, or IC2 Exp.

**Comment by Speiger** [comment]
Nope they share a modid do to compat  reasons. So they can not coexist

**Comment by ExDomino** [comment]
In 1.7.10 can I replace ic2exp by ic2classic in a modpack without problem?

**Comment by OvermindDL1** [comment]
IC2C and IC2ex have the same public API's except for some reactor thing in IC2ex that IC2ex broke from the old IC2 standard API, so if the mods don't touch that (I can't think of any off hand that don't already support both styles?) then you don't have an issue swapping between them.

**Comment by Speiger** [comment]
In 1.7.10 you still can replace the mod without any real issues. @ExDomino 
the worst that can happen is that some addons may not play nice with that.
But they are very rare. (Like only 1-2) At least in 1.7.10
