### ISSUE TITLE
Wrong recipe for Filtered Fluid Export Upgrade

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#399]
One of the recipes for the Filtered Fluid Export Upgrade requires 2 Advanced Circuits, an RE-Battery, ... and a Filtered Fluid Export Upgrade, which is the same thing you're trying to craft.

Both upgrades have the same damage value (28), and neither has any NBT data, so all you're doing by crafting that is clearing the settings on the upgrade so it's stackable again, but that shouldn't cost 2 circuits and a battery.

There's a corresponding Filtered Fluid Import Upgrade recipe that requires a Filtered **Basic** Fluid Import Upgrade in that spot, so I'm pretty sure that Filtered Fluid Export Upgrade recipe is supposed to require a Filtered Basic Fluid Export Upgrade.

**Comment by Speiger** [comment]
@dwentz89 please provide pictures

**Comment by dwentz89** [comment]
![FilteredFluidExport](https://user-images.githubusercontent.com/4080989/75612933-dbd2dd80-5aed-11ea-859e-ec594ed5c038.png)

It's the same item in both the input and output.

**Comment by Speiger** [comment]
yeah i think you are right. Thanks

**Comment by Speiger** [comment]
fixed
