### ISSUE TITLE
Im not sure if this is your issue or not but its happening...

### ISSUE THREAD

**Issue by AvulcanLogic** [TinyModularThings/IC2Classic#401]
... and idk if its even your issue or not but idk who to submit these reports to
(i already sent the evilcraft people a report)

Here is an edited crash report
https://paste.dimdev.org/iwununevuj.rb

Here is the whole thing
https://paste.dimdev.org/iqitovixoz.mccrash

**Comment by Speiger** [comment]
Evilcraft has a harddependency on IC2Experimental. Not IC2Cs fault

**Comment by Speiger** [comment]
Basically instead of using core classes they should use the API. Because then you get compat to both automatically.
