### ISSUE TITLE
[1.12.2] IC2 Classic (all versions) breaks Astral Sorcery's "Floating Crystals" rendering

### ISSUE THREAD

**Issue by fkrisi11** [TinyModularThings/IC2Classic#402]
Loading any version of IC2 Classic in Minecraft 1.12.2 alongside Astral Sorcery breaks the rendering of Astral Sorcery's "Floating Crystals". 
I already talked to the guys at Astral Sorcery, and they said they were using some kind of "model rendering" to render the "Floating Crystals"... I don't know if that helps or not.

I also tried to change crop rendering in the ic2 config, but no value works to fix the rendering in Astral Sorcery.

I also tried renaming Astral Sorcery to load it later than IC2, but that didn't help either.
My issue is probably related to this as well: #387 IC2 breaks Botania Pylon rendering

The issue affects the items in the GUI and also when they are held in hand. It does not affect the rendering of the "Floating Crystals" when they are placed in the world.

Here is a picture of the issue:
![fc](https://user-images.githubusercontent.com/26310365/77271612-710d6000-6caf-11ea-9241-c23f9dcfa867.jpg)

**Comment by Speiger** [comment]
Jep simple bug i forget to call the super renderer i actually "store" to prevent these bugs. But a simple fix. Will be patched in the next version

**Comment by fkrisi11** [comment]
Thank you ^^

**Comment by Speiger** [comment]
Just to be fair, there is no eta on next version right now. But honestly its time to make another patch. I am just really out of mc modding (or programming in general) so i have to get back in somehow ^^"

**Comment by fkrisi11** [comment]
And that is perfectly fine with me. Programming goes well when you feel like programming... when you feel creative.

If you are forced then... not so much. At least that is how it is for me.

In any case, even without an ETA, I'm glad that you even decided to take on this task ^^

**Comment by DAmNRelentless** [comment]
Would be nice if this patch is still a thing. No one forces you but it seems like this also breaks the item rendering of all of Botania's Pylons.

**Comment by DAmNRelentless** [comment]
Is this still being worked on?

**Comment by Speiger** [comment]
The mod didnt have a development cycle yet, but this stays open because its my active todolist once i am working on it again.

**Comment by Speiger** [comment]
Fixed
