### ISSUE TITLE
Water mill inventory cannot be accessed by other blocks on world reload.

### ISSUE THREAD

**Issue by TheMuso** [TinyModularThings/IC2Classic#404]
Minecraft Forge version: 1.12.2-14.23.5.2847
IC2 Classic version: 1.12-1.5.4.5

When setting up a water mill of any voltage, I am using other mods to push in water containers to be used, and pulling them out again when empty. On first set up all works ok, however once I reload my world, fluid containers are not able to be removed and put back in until the water mill is picked up and replaced.

I am using EnderIO pressurized fluid tanks as the container, and have tried using EnderIO pressurized fluid tanks on top of the water mill configured to push and pull to and from the water mill, as well as XNet.

Steps to reproduce:
1. Open up a world, creative mode likely the easiest here.
2. Place down a water mill. Tested with medium and high voltage water mill, but I am pretty sure it affects them all.
3. Connect the water mill up to an item system for inserting and removing fluid containers. My testing has involved placing an EnderIO pressurized fluid tank on top of the water mill, and then using another pressurized fluid tank as the container. The tank on top is configured to push and pull from the bottom, inserting the full tank into the water mill, and then pulling out the tank when it is empty. The tank on top of the water mill is connected via super-laminar fluiducts from Thermal Expansion to a bank of aqueous accumulators to keep it full of water.
4. Place a battery of some kind next to the water mill, I have used an MFSU in my testing.
5. Notice that fluid containers are inserted and removed from the water mill with your item management system.
6. Close the world, and reload it.
7. Notice that if there is any container in the water mill that it gets emptied if it still has water in it, but cannot be removed from the water mill.
8. Removing the fluid container, picking up/breaking the water mill and replacing it restores original functionality, and fluid containers are insertable and removable again.

Please let me know if you need any more info.

**Comment by Speiger** [comment]
Yeah this sounds weird but the bug is the opposite.
It actually fixes itself on world reload.
Watermills shouldn't be accessible by default with item insertion (yes thats intended)
what you have to do to gain item insertion is get a machinetool and put a inventory upgrade (slot access upgrade or automation upgrade) into it. That grants you access.

**Comment by TheMuso** [comment]
Thank you. I'll put this down to me not really doing my research. :) Will close.
