### ISSUE TITLE
Nuclear Reactor, no sound?

### ISSUE THREAD

**Issue by delta4873** [TinyModularThings/IC2Classic#407]
The reactor doesn't make any sound, other machines sound seems to stop randomly. Also, is radiation sickness a thing? Because I don't get sick holding fuel cells.

**Comment by Speiger** [comment]
It should, maybe there is a bug in there, other machines stop when the game is paused.
And no I decided against that because Reactors are already painful enough to deal with (inventory constraints and existing complexity) so that feature is cut out for making it more accessible.
