### ISSUE TITLE
Quantum Dyeing Recipe Duplication Glitch

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [TinyModularThings/IC2Classic#409]
When i try to dye Quantum armor in multiplayer (tested on a clean server with only IC2C installed), server generates [an error](https://gist.github.com/YuRaNnNzZZ/466428f7f1d8bb7c58c64a6bee944c4e) and crafting table (or player inventory crafting grid) sometimes drops duplicate items (be it armor piece or dyes) on GUI closing.

https://yurie.thigh-high.club/pz91x1jy.mp4

IC2Classic 1.12-1.5.4.5, Forge 14.23.5.2847

**Comment by Speiger** [comment]
Fixed.
