### ISSUE TITLE
Steam reactors can not be balance tweaked using configs

### ISSUE THREAD

**Issue by DBotThePony** [TinyModularThings/IC2Classic#414]
Pretty self explanatory.

In config file there is `I:energyGeneratorNuclear=` option, but none options for steam reactor/turbine output/input values/ratios.

*I want such config options since steam reactor in IC2C is way underpowered*

**Comment by Speiger** [comment]
You know why?
Because the steam reactor does not produce anything.
Its the steam vents

**Comment by DBotThePony** [comment]
This doesn't justify that steam reactor and it's components can't be balance tweaked using configs.

![https://cdn.discordapp.com/emojis/695247900363718656.png?v=1](https://cdn.discordapp.com/emojis/695247900363718656.png?v=1)

**Comment by Speiger** [comment]
Oh yeah this justifies why there is no "steam reactor" config modifier. Because there is nothing you can modify in the steam reactor itself.

**Comment by DBotThePony** [comment]
No, reactor itself got water buffer and steam buffer volume, which might get balance values in config.

**Comment by Speiger** [comment]
the reactor is only a data storage. It does not even get called when the steam vents produce stuff

**Comment by Speiger** [comment]
TL:DR i leave this open if i add something next patch to this then i will tell you.
Though no promises.

**Comment by Speiger** [comment]
Decided against that because i am already patching enough for this patch.
Also right now I do not have the mind to find a good balacing way that can be synchronized with all players.
