### ISSUE TITLE
Vacuum Canner does not refill CF containers

### ISSUE THREAD

**Issue by DBotThePony** [TinyModularThings/IC2Classic#415]
![javaw_xwutyTUqnm](https://user-images.githubusercontent.com/6339511/83533865-4f83ec80-a51a-11ea-8e23-7c739123587e.png)
![javaw_gDHEtlBqPm](https://user-images.githubusercontent.com/6339511/83533889-57dc2780-a51a-11ea-8ab9-c0db24253168.png)
![javaw_XDlwyAejl0](https://user-images.githubusercontent.com/6339511/83533891-5874be00-a51a-11ea-8a85-dea972555db5.png)

**Comment by Speiger** [comment]
Fixed
