### ISSUE TITLE
Non-uniform heating of components in Nuclear Reactor

### ISSUE THREAD

**Issue by EchoingHell** [TinyModularThings/IC2Classic#416]
Hello,
I am using IC2 Classic in the Tekxit 3 modpack.

It seems that, when in use, the vents in the nuclear reactor respond non-uniformly to the Hull heat. Certain heat vents (seemingly the same position every time when the layout is unchanged) overheat when other heat vents (identical, Electric Overclocked Heat Vent) stand there idle.

I have isolated the Fuel Cells in a pack in the centre, using Reactor Heat Exchangers to move heat to the hull, but the EOHVs are not all sharing the load of hull heat as expected.

Please can you help me understand how the heating calculations work?

Thanks

**Comment by EchoingHell** [comment]
![image](https://user-images.githubusercontent.com/66575879/83982358-1d112f80-a91e-11ea-9af7-bde757e08bbc.png)

As an example

**Comment by Speiger** [comment]
Yes that is correct behavior.
The reactor goes from top left to bottom right (horizontal then vertical) and items are updated as they are in the spot. Heating gets applied/removed as the item is called. That means first serve first get.
Not a bug. Thats why all these components exist
