### ISSUE TITLE
Wrong HV solar panel recipe

### ISSUE THREAD

**Issue by DBotThePony** [TinyModularThings/IC2Classic#418]
![javaw_bqYUxsvIaD](https://user-images.githubusercontent.com/6339511/84600611-c4eda680-aea4-11ea-9a6a-0042867e51f7.png)
![firefox_UigQRObG77](https://user-images.githubusercontent.com/6339511/84600691-6b39ac00-aea5-11ea-905a-f6b0ff93fab4.png)

*ok, shall bug report war begin*

**Comment by Speiger** [comment]
That was intended to get people of the HV Solar Spam.

**Comment by Trinsdar** [comment]
It's iv om purpose, not a bug

**Comment by DBotThePony** [comment]
Stopping people from reducing tick lag by themselves, huh? How interesting.

**Comment by Speiger** [comment]
@DBotThePony the solar panels are so much optimized that you can have a couple hundred without even causing a 0.1ms of lag. 
And you know 64EU Panels still exist. So compression isn't lost. But the first thing people look at: How expensive is a HV Solar panel and then decide to use the branch or not.

**Comment by DBotThePony** [comment]
Sampling over 6 seconds on empty server
![Xming_g1PRa8Tk18](https://user-images.githubusercontent.com/6339511/84600941-3f1f2a80-aea7-11ea-852f-4b52b0c0ae39.png)
I hear you.

**Comment by Speiger** [comment]
-.-"
Simple last warning. I done arguing with you @DBotThePony. 
To Simply that. No you are wrong for the reason of "Cost" in the first place.
Yes the numbers game is a thing but you are exactly the type of player why this recipe change was made in the first place.

And to make my warning clear. I am done arguing with you. If you stop right now you are at least able to make bugreports if you find actual bugs. (Like the canning machine)
