### ISSUE TITLE
Coolant cell crafting recipe produce empty cells regardless liquid container utilized

### ISSUE THREAD

**Issue by DBotThePony** [TinyModularThings/IC2Classic#419]
![M5b3uOidLi](https://user-images.githubusercontent.com/6339511/85270322-51025e00-b4a3-11ea-9a37-c8d15df93b6c.gif)
![xqspTpSpA0](https://user-images.githubusercontent.com/6339511/85270407-74c5a400-b4a3-11ea-82f6-0e2635c14696.gif)
![lZTN9fxJSn](https://user-images.githubusercontent.com/6339511/85270473-89a23780-b4a3-11ea-9a52-b8bbedf2d9e2.gif)

**Comment by Speiger** [comment]
Will be fixed in the next patch. No ETA though.

**Comment by Speiger** [comment]
Fixed. Though you might not get a container back in some recipes because the liquid containers do not provide any emptying by themselves. (Not fixable, an example is forestry tincans)

**Comment by Speiger** [comment]
Fixed and released
