### ISSUE TITLE
Crash with Overlord IC2 compatibility 

### ISSUE THREAD

**Issue by jbdigel** [TinyModularThings/IC2Classic#420]
Crash when loading IC2 classic and Overlord mod together. No config in Overlord to turn the IC2 compatibility off, that mod hasn't been updated in a while, but seems to work with most recent version of IC2 experimental.

https://pastebin.com/TBZnXzKf

**Comment by Speiger** [comment]
@jbdigel Overlord mod checks for IC2 Experimental Core classes.
Not a IC2 Classic bug. Overlord should use the IC2API instead of core classes.
