### ISSUE TITLE
Extractor recipe for gravel to flint does not use ore dict

### ISSUE THREAD

**Issue by netmc** [TinyModularThings/IC2Classic#426]
Extractor recipe for gravel to flint does not use the ore dictionary.  This prevents gravel from other mods like Underground Biomes from being used to create flint.

**Comment by Speiger** [comment]
@netmc ic2c barely uses oredict in general.
There is a "gravel" oredict but i am not planning to add oredict to everything because it has overhead.

If you have this issue please use the provided way to add custom recipes to resolve that issue. (And you can disable existing recipes too)
