### ISSUE TITLE
customMachineRecipes problem 

### ISSUE THREAD

**Issue by BioTech21** [TinyModularThings/IC2Classic#427]
I need to add quartz dust crafting to AE2.
The problem is that the name of the item is written with two colons(appliedenergistics2:material:2), and because of this, it is impossible to add material.
This problem could be solved by writing the oreID to "outputs" and entering the ore id, but I didn't make it...

Here is the recipe code: 
{
	"recipes":
	[
		{
			"recipeType": "macerator",
			"outputs":
			[
				{
					"item": "appliedenergistics2:material:2",
					"meta": 0,
					"amount": 1
				}
			],
			"recipeMetadata": '{}',
			"recipeExperience": 0,
			"input":
			{
				"inputType": "ore",
				"oreID": "crystalCertusQuartz"
			}
        }
    ]
}

**Comment by MIDORIINKO** [comment]
Hi BioTech21.
I'm struggling with the same problem.
May I ask you that?

**Comment by BioTech21** [comment]
@MIDORIINKO Yes of course. What are you interested in?

**Comment by Speiger** [comment]
@BioTech21 can you tell me what the issue was and what the fix was?
So i can make edits or something so other people who run into the same issue can have a potential solution.

Also sorry for the late response, hadn't had the time to responde.

**Comment by BioTech21** [comment]
@Speiger 
The problem was that I could not add craft for the AE2 mod (and not only), since the item ID was written with two colons.
I was able to solve this problem using the CraftTweaker + ModTweaker + IC2 Tweaker mods (exactly a tweaker for experimental industrial, not classic).

Sample code:
`{
	"recipes":
	[
		{
			"recipeType": "macerator",
			"outputs":
			[
				{
					"item": "appliedenergistics2:material:2", //Not working recipe due to two colons.
					"meta": 0,
					"amount": 1,
				}
			],
			"recipeMetadata": '{}',
			"recipeExperience": 0,
			"input":
			{
				"inputType": "ore",
				"oreID": "crystalCertusQuartz"
			}
		}
	]
}`

**Comment by Speiger** [comment]
Oh Ok. Maybe i can fix that issue on my side too.

**Comment by BioTech21** [comment]
@Speiger Thanks for your responsiveness and for bringing this great Industrial Mod to version 1.12.2! Good evening!

**Comment by MIDORIINKO** [comment]
Thank you two!
