### ISSUE TITLE
Ore Scanners cant scan for very rare Ores

### ISSUE THREAD

**Issue by GregoriusT** [TinyModularThings/IC2Classic#429]
Make Ore Scanners scan Chat Output for 100000 instead of 1000, and add a fixed point dot to the resulting Chat message.

Or literally just dont make it round down to ZERO.

As of right now you cannot scan for "Single Block of Ore in Chunk"-Ores.

**Comment by Speiger** [comment]
lets ignore that there is a "OreScanner" Block that actually gives you values instead of basic outputs xD
And lets ignore that in 1.12 this thing i think is not working.

**Comment by GregoriusT** [comment]
Hey, you said its a rounding Issue, so how about never round down to ZERO if something is there, so that it at least tells you there is SOMETHING down there, instead of failing to scan for those Ores alltogether. Rounding Up is literally the most easy fix for this kinda thing, and doesn't even require changing the Chat Message.

**Comment by Speiger** [comment]
Fixed. Solution works fine in both ways. Also fixed another bug.
