### ISSUE TITLE
reactor planner fails to import rods from addons

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#430]
![reactorplanner](https://user-images.githubusercontent.com/30245301/94464468-84344780-018c-11eb-9a29-28b304121717.gif)

**Comment by Speiger** [comment]
Can not reproduce since no IC2Extras isnt installabel with drag and drop lib install.
Added Loggers for repoduction tests.

**Comment by Speiger** [comment]
Assuming the Bit Limit is reached, that means a custom one has to be installed.
