### ISSUE TITLE
one probe shows incorrect stats with crops when player has crop analyzer, like 0 growth points

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#431]
![crop-probe](https://user-images.githubusercontent.com/30245301/94743896-1c296100-0346-11eb-82a5-adc049e25e7a.gif)
ic2 classic 1.5.5.1
the one probe 1.12-1.4.28

**Comment by Speiger** [comment]
already found will be patched in the next patch. You know the eta.

**Comment by Speiger** [comment]
fixed
