### ISSUE TITLE
binnies dna sequences won't fit in industion furnace, and I assume the electric one too

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#433]
![sequences](https://user-images.githubusercontent.com/30245301/94890198-a52ac000-044c-11eb-841a-0e7cdf69a987.gif)

**Comment by Speiger** [comment]
Hopefully fixed without breaking something else.

**Comment by Trinsdar** [comment]
Um sorry to say, but looks like not only is this not fixed, now we can't put sand in a furnace either
