### ISSUE TITLE
automatable slots that have had their max stacksize set to something lower then what's in the super call cause deletion of

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#434]
![deleting](https://user-images.githubusercontent.com/30245301/95006806-3f6a3f80-05d6-11eb-9476-e786da96b0fc.gif)
basically what I did is set the max stack size of my ore washer to 16, and it caused it to start deleting the items, I found this when testing out a new block I was making. I can confirm it's an ic2c bug, because I tried it with my roller, which litterly just has gui and recipe stuff, and a couple other misc stuff, no addSlots or anything.

**Comment by Speiger** [comment]
Since Inventory Insertion is done by IC2C if you use InventoryHandler and do not override the capability then this is a ic2c bug.
Will be coming in the next patch.
