### ISSUE TITLE
dupe bug with rubber wood

### ISSUE THREAD

**Issue by bear989** [TinyModularThings/IC2Classic#442]
you can keep getting sticky resin from rubber wood if you break it and replace it, when i did it i was using a chainsaw

**Comment by Speiger** [comment]
Not a bug this has been a feature since the start of IC2, it is a way to grind the way to get sticky resin.

**Comment by GregoriusT** [comment]
Does the Log at least disappear, like it does for Gravel to Flint conversion?

**Comment by bear989** [comment]
no you can just break and replace infinitely

**Comment by Speiger** [comment]
It is a 16% chance that you get one though. Have fun grinding yourself through. But it has been at least since 1.8.3 (Beta) like that.
