### ISSUE TITLE
[1.12.2] Electric Furnace doesn't accept any item

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#446]
Hello,

The Electric Furnace in IndustrialCraft Classic doesn't accept any items.
I tryed with Sand, Wood and Potatoes, but none of these items are accepted into the furnace in order to smelt.

Thank you in advance.

Minecraft : 1.12.2
Forge : 14.23.5.2854
IndustrialCraft Classic : 1.5.5.2
IndustrialCraft Extras : 1.4.8.2
GregTech Classic : 1.1.6

**Comment by Speiger** [comment]
@ExDomino try replicating in 1.5.5.2.1

**Comment by Speiger** [comment]
@ExDomino and is 1.5.5.2.1 having the same issue?
