### ISSUE TITLE
Can't get redstone signal from nuclear reactor based on heat.

### ISSUE THREAD

**Issue by AustinHaugerud** [TinyModularThings/IC2Classic#447]
It seems like according to issue #319 there should be an ability to configure reactors to output a redstone signal (from 0-15) based on their heat state.

I set the machine tool to comparator mode, right clicked a reactor chamber, then set multiple sides to "reactor heat" and saved. I then heated the reactor to over 25% capacity, but no redstone signal was ever emitted at any level. Hopefully I'm misusing this somehow, but I'm at a loss as to how this is supposed to work if it's not a bug.

Version according to Forge: 2.2.999 (2.8.1001)

**Comment by Speiger** [comment]
Null/Non Value is vanilla comparator only, Side values are IC2Cs Advanced Comparator so you have more options if you want to.
Why? Because in 1.7.10 MC had a Directional support in the Comparator API that was gone in 1.10.2 and I implemented it back with a seperate API  thats why 2 comparators. If the Machine does not support the API then it defaults to the MC API.

**Comment by AustinHaugerud** [comment]
Did you actually read what I said @Speiger ? The reactor does not emit any form of redstone signal on heat mode no matter what, there is never any input for the vanilla or advanced comparator to use anyway. In other words, this mode allegedly supported does not seem to work at all. 
![image](https://user-images.githubusercontent.com/5608551/102697403-66560c00-41ea-11eb-8abb-323d862f26de.png)

**Comment by Speiger** [comment]
@AustinHaugerud please provide a video/gif/movingimage of how you setup everything.
Because I have people using that feature just fine on latest version.

**Comment by bear989** [comment]
from the way i am reading this he is trying to get the redstone out of the reactor chamber itself @Speiger, he needs to connect the advanced comparitor to that side of the reactor chamber.

**Comment by Speiger** [comment]
@AustinHaugerud bears comment.

**Comment by bear989** [comment]
https://youtu.be/rvLn73mP7GE

**Comment by AustinHaugerud** [comment]
Apologies, was indeed misuse then. Thank you both, especially for taking the time to upload the example video. I didn't realize the comparator was mandatory to get a signal. Best to you both.
