### ISSUE TITLE
Recycler Blacklist is not functional for modded items.

### ISSUE THREAD

**Issue by Slayer5934** [TinyModularThings/IC2Classic#452]
It has been said here https://github.com/TinyModularThings/IC2Classic/issues/125 that this issue is fixed, but I listed 2 modded items and the blacklist did not prevent recycling; I then tried this on IC2Cs own item scaffold and it also did not block it, in the original issue he said it would output a recycler error in the log but no such error was found.

**Comment by Speiger** [comment]
@Slayer5934 could you show how the config entry looks like?

**Comment by Slayer5934** [comment]
S:recyclerBlacklist=minecraft:glass_pane, minecraft:stick, minecraft:snowball, IC2:scaffold, galacticraftcore:oil_canister_partial

**Comment by Slayer5934** [comment]
I pulled the id straight from craft tweaker but I'll try lowercasing it to see if that works, appreciate the response, will report back in a few minutes.

**Comment by Slayer5934** [comment]
Yep it still didnt work S:recyclerBlacklist=minecraft:glass_pane, minecraft:stick, minecraft:snowball, ic2:blockscaffold, ic2:blockironscaffold

**Comment by Slayer5934** [comment]
It's worth noting that vanilla things are blacklisted correctly.

**Comment by Speiger** [comment]
Ughhhh i think i know why that is happening... Yeah this will take time but i have at least a idea why thats a thing.
Simple answer: The Recycler blacklist config load to early and mods for whatever reason haven't registered their items yet. I bet this is due to how forge tried to enforce a new system and it loads really late...

Thanks for the report. I will deal with it (leave it open as reminder) the next time ic2c gets its patch this is dealt with.

**Comment by Slayer5934** [comment]
I appreciate your time and responses, hopefully it's not too hard to fix. You could check the quark source or backtools if you wanted to see how those mods do it to maybe.

**Comment by Speiger** [comment]
Its not hard just need to setup a lot of things since a lot of my projects are right now not on my pc so that will take time and i am jammed right now.

**Comment by Speiger** [comment]
Sorry this took so long, but this should be patched with the next release.

**Comment by Slayer5934** [comment]
> Sorry this took so long, but this should be patched with the next release.

A little late reply but thank you very much for fixing this :)
