### ISSUE TITLE
Crash on 1.12.2 with Baubles installed

### ISSUE THREAD

**Issue by DenEgg** [TinyModularThings/IC2Classic#458]
I'm always playing with Baubles, so it is really necessary for me. But today I wanted to use IC2C too and it causes Crashes on startup. Reason for this is obviously the Nuclear Jetpack for Baubles.

I'm using
forge-1.12.2-14.23.5.2860
Baubles-1.12-1.5.2
IC2Classic+1.12-1.5.5.2.1

All other data is provided in the Crash Log.

CRASH LOG
[crash-2022-02-06_10.03.15-client.txt](https://github.com/TinyModularThings/IC2Classic/files/8009823/crash-2022-02-06_10.03.15-client.txt)

**Comment by Speiger** [comment]
As Stupid as it sounds.
Your jar corrupted during the download.
That is sadly happening sometimes.
Just redownload the mod and try again. I can tell you for sure this is the problem (had this thousands of times already and that is the only fix)

**Comment by DenEgg** [comment]
Actually, I just found out that it's not IC2C what is causing the crashes, after trying your solution. The Crashes came from IC2C Extras, which is broken with the last Updates. Don't know, why it says IC2C in the Log.

Now without IC2C Extras everything is working fine.

Thanks anyway for your Help.

**Comment by Speiger** [comment]
@Trinsdar
Might want to look at this.
