### ISSUE TITLE
CropHarvester not getting full crop drops when harvesting crops with high Gain stat

### ISSUE THREAD

**Issue by Big-D-In-Action** [TinyModularThings/IC2Classic#459]
I have Malachite crop with 20/31/10 stats, and when harvested by Crop Harvester it results in 1-2 copper dust dropped. When harvesting by hand it yields 15-16 dust.
Version is IC2Classic+1.12-1.5.5.
Is it an intended behaviour?

**Comment by PrincessOfEvil** [comment]
Yes, auto-harvesting is *massively* weaker than manual. Very intended.

**Comment by Speiger** [comment]
Yep. Very intended.

**Comment by Speiger** [comment]
To give some lore:
The player carefully picks the crop drops while the machine just mashes down the crop and gets as much as it can. 
Since the machine is very crude there is a LOT of waste.
