### ISSUE TITLE
No info about EU in NEI

### ISSUE THREAD

**Issue by R0MaNbI4** [TinyModularThings/IC2Classic#460]
I'm not sure if this is a bug or just not implemented yet

The description on CurseForge says that there is integration with NEI, but in NEI no any info about EU. I mean conductivity of wires and loss per block, production of generators, how much energy storage is output, how much the device consumes.

Now I have only installed (all other mods deleted):
- NEI ([Not Enough Items 1.12.2-2.4.3.245-universal](https://www.curseforge.com/minecraft/mc-mods/not-enough-items-1-8/files/2755792))
- JEI ([jei_1.12.2-4.16.1.302.jar](https://www.curseforge.com/minecraft/mc-mods/jei/files/3043174)) (dependency for NEI)
- IC2C ([IC2Classic 1.12-1.5.5.2.1](https://www.curseforge.com/minecraft/mc-mods/ic2-classic/files/3093607))

Here is a comparison with IC2 Experimental. Is this how it should be?
Or did I not install some mod? Maybe I need to fix something in the configs or press some hotkey for NEI.
If it's just not implemented yet, is it planned?

![image](https://user-images.githubusercontent.com/23138330/176995967-f703379e-c836-470b-9087-f5c14b80f77c.png)
![image](https://user-images.githubusercontent.com/23138330/176996152-b490dbbe-3dfc-4d1a-8788-d10563762d8e.png)
![image](https://user-images.githubusercontent.com/23138330/176996308-e5a9b08c-c83a-4251-ac83-6550490066b6.png)
![image](https://user-images.githubusercontent.com/23138330/176996181-b4a4ec8d-2520-4f95-b69f-e5fcbe3732c0.png)
![image](https://user-images.githubusercontent.com/23138330/176996348-eddd1f83-3069-46f4-a98f-cad42d444492.png)
![image](https://user-images.githubusercontent.com/23138330/176996387-984333c7-2e78-481f-8110-efd8712382b3.png)

**Comment by Speiger** [comment]
Equipp a EU reader.

**Comment by R0MaNbI4** [comment]
Oh, I really like this approach. Thanks for the quick response.
