### ISSUE TITLE
Bug with pump and pump attachments, ticking tile entity issue

### ISSUE THREAD

**Issue by Ismael-V** [TinyModularThings/IC2Classic#461]
When an IC2 pump faces in the direction of a pipe attachment, the game crashes with a ticking tile entity bug and the world becomes completly inaccesible until you delete with some external tools the pipe or the pump from the world

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/14/22 7:34 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at java.util.Objects.requireNonNull(Objects.java:203)
	at ic2.core.block.transport.TileEntityFluidPipe$PipeFluidHandler.drain(TileEntityFluidPipe.java:356)
	at ic2.core.util.LiquidUtil.drainTile(LiquidUtil.java:332)
	at ic2.core.util.LiquidUtil.drainTile(LiquidUtil.java:323)
	at ic2.core.block.machine.tileentity.TileEntityPump.pump(TileEntityPump.java:202)
	at ic2.core.block.machine.tileentity.TileEntityPump.operate(TileEntityPump.java:175)
	at ic2.core.block.machine.tileentity.TileEntityPump.canoperate(TileEntityPump.java:144)
	at ic2.core.block.machine.tileentity.TileEntityPump.updateEntityServer(TileEntityPump.java:121)
	at ic2.core.block.TileEntityBlock.func_73660_a(TileEntityBlock.java:326)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:203)
	at ic2.core.block.transport.TileEntityFluidPipe$PipeFluidHandler.drain(TileEntityFluidPipe.java:356)
	at ic2.core.util.LiquidUtil.drainTile(LiquidUtil.java:332)
	at ic2.core.util.LiquidUtil.drainTile(LiquidUtil.java:323)
	at ic2.core.block.machine.tileentity.TileEntityPump.pump(TileEntityPump.java:202)
	at ic2.core.block.machine.tileentity.TileEntityPump.operate(TileEntityPump.java:175)
	at ic2.core.block.machine.tileentity.TileEntityPump.canoperate(TileEntityPump.java:144)
	at ic2.core.block.machine.tileentity.TileEntityPump.updateEntityServer(TileEntityPump.java:121)
	at ic2.core.block.TileEntityBlock.func_73660_a(TileEntityBlock.java:326)

-- Block entity being ticked --
Details:
	Name: ic2:pump // ic2.core.block.machine.tileentity.TileEntityPump
	Block type: ID #253 (ic2.te // ic2.core.block.BlockTileEntity // ic2:te)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (324,56,-986), Chunk: (at 4,3,6 in 20,-62; contains blocks 320,0,-992 to 335,255,-977), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Actual block type: ID #253 (ic2.te // ic2.core.block.BlockTileEntity // ic2:te)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Bug
	All players: 1 total; [EntityPlayerMP['IsmPG'/122016, l='Bug', x=326.21, y=56.00, z=-987.30]]
	Chunk stats: ServerChunkCache: 1089 Drop: 0
	Level seed: -7177085000905220743
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,3*minecraft:stone,52*minecraft:sandstone;2;
	Level spawn location: World: (320,4,-984), Chunk: (at 0,0,8 in 20,-62; contains blocks 320,0,-992 to 335,255,-977), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Level time: 703 game time, 703 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 171652 (now: false), thunder time: 42229 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1651935648 bytes (1575 MB) / 3355443200 bytes (3200 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 1, allocated: 15, tallocated: 99
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version       | Source                                         | Signature                                |
	|:------ |:------------------- |:------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2        | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                 | 9.42          | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                 | 8.0.99.99     | forge-1.12.2-14.23.5.2859.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2859  | forge-1.12.2-14.23.5.2859.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | appliedenergistics2 | rv6-stable-7  | appliedenergistics2-rv6-stable-7.jar           | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | buildcraftlib       | 7.99.24.8     | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.8     | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.8     | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.8     | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.8     | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | ic2                 | 2.8.186-ex112 | Industrial-Craft-2-Mod-Experimental-1.12.2.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | buildcraftcompat    | 7.99.24.8     | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.8     | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.8     | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.8     | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358     | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | waila               | 1.8.26        | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LCHIJA | jei                 | 4.15.0.291    | jei_1.12.2-4.15.0.291.jar                      | None                                     |
	| LCHIJA | nei                 | 2.4.3         | NotEnoughItems-1.12.2-2.4.3.245-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['IsmPG'/122016, l='Bug', x=326.21, y=56.00, z=-987.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

https://user-images.githubusercontent.com/67332010/184548586-f2b3b746-d912-4a9d-bbae-a8c2221c0f86.mov

![image](https://user-images.githubusercontent.com/67332010/184548596-442f52e1-44dd-42ee-a100-0d2834da8c88.png)

.

**Comment by Speiger** [comment]
Industrial-Craft-2-Mod-Experimental
That error is with IC2 Experimental, this is IC2 Classic. Totally different mods

**Comment by Ismael-V** [comment]
I'm sorry, I just wanted to contribute to the experimental version...

**Comment by Speiger** [comment]
@Ismael-V here you can find the IC2 Exp bugtracker:
https://bt.industrial-craft.net/my_view_page.php
