### ISSUE TITLE
Grammar issues with advancement descriptions and titles

### ISSUE THREAD

**Issue by PawnixHere** [TinyModularThings/IC2Classic#462]
**Describe the issue**

The IndustrialCraft2 advancement descriptions for "Storage Upgrade" & "Just Too Much". The noun "Build" is followed up by vowel sounds; "MFE" & "MFS", not a consonant sound. The correct spelling is "an" not "a" for both advancements.

The IndustrialCraft2 advancement "Better than Iron" suggests that the player smelts refined iron, which is impossible and the advancement should probably read "Smelt An Iron Ingot".

**Comment by Speiger** [comment]
"Build an MFE" instead of "Build a MFE".
I am pretty sure the first one, which you suggest, sounds and is wrong.

"Better than Iron", is most likely more of a joke since you can "upgrade iron just by resmelting it" which realistically does nothing.

Don't take everything to seriously.

**Comment by PawnixHere** [comment]
Grammar would beg to differ. Even Grammarly begs to differ. 
MFE is a vowel in the context of Build __ MFE/MFS, which should be followed up by "an" instead of "a"

In order to pronounce "A MFE/MFS" a person must pronounce the hard A and quickly follow it up with a continuation of the A sound which doesn't work, resulting in an abrupt and awkward stop in the sentence as "MFE/MFS" continues. By writing "an" you transition from a noun to a vowel seamlessly. My worries come from a place of love for the modpack. Seeing such unprofessional and simple mistakes makes me think that the mod isn't cared for properly. Besides, a simple name change doesn't involve hours of programming. I really do hope you will find the heart to fix this as it just looks weird when spoken in proper English.


As for the "Better than Iron" advancement, the description suggests the player smelts refined iron to unlock the advancement. The title is perfectly fine. Apologies for not making it clear that I was talking about the description.

Writing you this example of "A MFE/MFS" causes professional software such as Grammarly to correct me in my own example of how the advancement description is spelt wrong.

![Skärmbild 2022-09-13 113515](https://user-images.githubusercontent.com/60940047/189879974-f15f9d4a-a349-44a9-9dd7-1c03bd39cc33.jpg)

**Comment by Speiger** [comment]
Grammar sees the "MFE" as a word itself, yet its a acronym.
"Build an Multi-functional energy storage" vs "Build a Multi-functional energy storage"

Anyhow if you want to be picky, go head be picky.
But this is not going to change.

Thanks bye

**Comment by PawnixHere** [comment]
If a word in its acronym form is a _vowel_ which we have now made clear, it will still **always** be written with "an" beforehand. It would be different if you were to write out the whole name. Give me a moment and I'll send over my favourite sources for quick learning of more intricate grammatical constructs. They're quite useful for things like these where you might be unsure or unaware of the intricacies of the language. I've myself been caught off-guard a few times in my life and this helped me understand better.
