### ISSUE TITLE
IItemHandler violation

### ISSUE THREAD

**Issue by bziemons** [TinyModularThings/IC2Classic#463]
Logistics Pipes had an issue inserting into empty machines https://github.com/RS485/LogisticsPipes/issues/1663

I debugged into the code and it seems like the `BasicHandlerInstance` implementation of the `net.minecraftforge.items.IItemHandler` modifies the item stack that is passed to `insertItem`. The documentation of that function, however, states:

> stack – ItemStack to insert. This must not be modified by the item handler.

**Comment by Speiger** [comment]
Oh i forgot to copy the stack...

**Comment by Speiger** [comment]
@bziemons addressing this now. (Patch might take a few days, but now patch work starts)
