### ISSUE TITLE
Storage explodes when reaching full if connected to flux generator

### ISSUE THREAD

**Issue by michael-hart** [TinyModularThings/IC2Classic#464]
Environment: tekkit 2 v1.0.5

Situation:
Connect MFSU to HV flux generator with glass fibre cable. Connect HV flux generator to some load using HV flux cable - I've been using a still with some biomass in it. Charge the MFSU to full.

Expected: MFSU stays full and power stays supplied to still.
Actual: MFSU explodes as soon as it reaches full.

To reproduce quickly, stick an MFSU down, charge it to nearly full with a bunch of hybrid solar panels, then break the panels. Attach an RF load to the output. Attach 2 bio generators to the input, and fill them with ethanol. The MFSU explodes when it reaches full.

I was having this issue with a batbox, and kept thinking it was from drawing too much power, so kept upgrading. In creative, I tested using the top tier stuff, and it still exploded.

It's worth noting that using the same still with a batbox and fully charging the batbox before connecting it to an lv generator + lv cables means there's no explosion. I guess there's some issue when the box reaches full and checks if it should explode?

**Comment by Speiger** [comment]
@michael-hart please provide a clip that shows the setup so its reproduceable.
