### ISSUE TITLE
[Question] Adjustable Transformer vs IV Transformer

### ISSUE THREAD

**Issue by nathanrsfba** [TinyModularThings/IC2Classic#467]
So I've noticed that the Adjustable Transformer seems to be quite a bit cheaper to craft than the IV transformer; yet it seems to be able to transform the same voltages that the IV transformer can (or, can be configured to do so.)

Other than crafting the HV solar panel, is there a need to craft the IV transformer at all, rather than the adjustable?

**Comment by Speiger** [comment]
Adustable Transformer is only to downstep power, while the IV Transformer is to down/upstep power.
Meaning you lose half of its functionality.

But yes it is kind of useless to some degree.
But honestly, that really doesn't matter in the end.
