### ISSUE TITLE
Unexpected Behavior - Plethora Inventory Wrapping & IC2 Classic

### ISSUE THREAD

**Issue by RugRite** [TinyModularThings/IC2Classic#468]
ENVIRONMENT:

openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-8u342-b07-0ubuntu1~22.04-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)

ERROR LOG:

https://mclo.gs/tsmKlVh

TO REPRODUCE:

-- 1x Computer
-- 2x Modem
-- Network cable
-- 1x Any IC2 Machine
-- Compatible Item for IC2 Machine Inventory

Connect Modem to IC2 Machine & Computer --> Wire modems --> Activate network
Place the compatible item in Slot 1 of the IC2 machine inventory

   IN COMPUTER LUA --> 
  
   machine = peripheral.wrap('ic2:nuclear reactor_0')
   machine.drop(1, 1, "any_direction")

  ||

  machine = peripheral.wrap('ic2:nuclear reactor_0')
  cooler = peripheral.wrap('ic2:nuclear reactor_1')
  machine.pushItems(peripheral.getName(cooler), 1) or ..., 1, 1, 1)

  EXPECTED BEHAVIOUR 

  The machine drops 1 of the item in slot 1 out of the selected face

  ||

  The machine transfers 1 item from slot 1 to slot 1 of the other machine

  ACTUAL BEHAVIOUR

  CC Spits back a null pointer error and server-side prints https://mclo.gs/tsmKlVh
    It's only with IC2 machines that this is happening, I'm able to do the above with machines/blocks from any other mod pack I've tried.

I asked about this over on the CC tweaked side and it looks like one of the devs for plethora responded with this -->
https://github.com/cc-tweaked/CC-Tweaked/issues/1187#issuecomment-1285927720

Is there a chance this is still supported for a fix? <3

**Comment by Speiger** [comment]
I can't fix this, that needs to be fixed by the computer mod, because they most likely supported IC2Exp but not classic.
Or something like this.

**Comment by Speiger** [comment]
Mod is still supported and there will be a patch next week.
Not sure if i can fix this since the log doesn't include ic2c code itself...

**Comment by Speiger** [comment]
Fixed.

**Comment by Speiger** [comment]
1.12.2
