### ISSUE TITLE
[1.19.2] Guidebook changes the GUI size

### ISSUE THREAD

**Issue by Vapaman** [TinyModularThings/IC2Classic#469]
### Issue
When using opening the guide book, GUI size goes to a bigger size. It goes back to normal after closing the book.

GUI doesn't scale back to the preferred size when using the "show multiblock" functionality

Steps:
1) Set GUI scale to smaller than the max
2) Open guidebook and pick any multiblock
3) Click Show multiblock, this should make you exit the book, but not change the GUI scale back to normal. If not, do this again. It should change the GUI size **after** the first try

### **Pictures for clarification:**

![kuva](https://user-images.githubusercontent.com/77460466/197387152-1cc05bb0-cdca-46e1-88b7-e927d917e5e3.png)
![kuva](https://user-images.githubusercontent.com/77460466/197387169-e4d89895-538b-4369-9740-a1fd6010610c.png)

**Notice the GUI scale is changed from 1 to 2**

![kuva](https://user-images.githubusercontent.com/77460466/197387180-f3ace254-387d-4235-aba4-b869e557b898.png)
![kuva](https://user-images.githubusercontent.com/77460466/197387196-51466f71-3c46-4849-aab6-3c635ed0e717.png)

### Installed mods
Minecraft 1.19.2
Forge 43.1.47
IC2C 2.0.0

**Comment by Speiger** [comment]
Thank you I will address that with the first patch.

But unless there is a crash bug this will be delayed a few days so i can do the first bulk patch addressing everything at once.
Also giving me time to do other things since a lot of other things had been delayed because of ic2c 1.19

**Comment by Vapaman** [comment]
Thank you for a swift reply!

And awesome work on the mod. Feels really polished, with good performance and all bugs I found so far were only visual. Good work, make sure to take a good rest!
