### ISSUE TITLE
CFoam config requests + moar bugs

### ISSUE THREAD

**Issue by Carbon-Ghost** [TinyModularThings/IC2Classic#47]
Can we have a config for blast resistance please ? I feel CFoam is way too owerpowered for that imo, especially because I use CFoam to create expensive railcraft concrete ;/

Also, although it's nice to be able to collect CFoam now, there is a problem, dry Cfoam drops a dev item, which is uncreafteable, looks black instead of gray, and places black Cfoam. 

Can you fix it please ^.^
Thx.

**Comment by Speiger** [comment]
^^" for now i say no:
It can create server/client sync issus when you have differend numbers on the resistance...
Later maybe when i found a better solution to make that not happen.

The bug will be fixed.

**Comment by Carbon-Ghost** [comment]
Thanks ^.^
