### ISSUE TITLE
[1.19.2] Mining Laser is held incorrectly on the player model

### ISSUE THREAD

**Issue by Vapaman** [TinyModularThings/IC2Classic#470]
### Issue
Mining laser is held like a normal item. It should probably be held like the CF sprayer or like the bow

**Mining laser** 
![kuva](https://user-images.githubusercontent.com/77460466/197387880-644f17dd-e6b1-4385-a78a-d7d1727223a9.png)
The laser uses the default held item model

**Vanilla Bow**
![kuva](https://user-images.githubusercontent.com/77460466/197387899-f2e83a29-ff21-46c9-9f97-8d1e78f71151.png)

**CFoam sprayer**
![kuva](https://user-images.githubusercontent.com/77460466/197387967-f9e67378-4416-4054-a121-9e07f0672650.png)
CFoam sprayer is floating
### Mods
Minecraft 1.19.2
Forge 43.1.47
IC2C 2.0.0

**Comment by Speiger** [comment]
Yeah the item transforms are broken for a lot of things. Offhand included if you are using lefthandedness...
This might take a few patches to be addressed since this is a foundation issue and honestly nobody used the F5 keys, IIRC.

Thank you for the report this will be addressed at some point.
