### ISSUE TITLE
[1.19.2][Forge][Localization] Spaces and commas between numbers show as NBSP-sign when using non-english localization on your OS

### ISSUE THREAD

**Issue by Vapaman** [TinyModularThings/IC2Classic#471]
### Issue:
The Non-Breaking Space ( ) character is used in place of the comma or space while using some non-english localization on your OS. This character is not supported correctly by Minecraft.

Workaround for the user is to use some compatible english regional format for your OS

### Pictures:
**While using US localization on OS:**
![kuva](https://user-images.githubusercontent.com/77460466/197390869-deb88dfb-383d-4818-afa4-fda49cf98dd2.png)

**While using Non-english localization on OS:**
![kuva](https://user-images.githubusercontent.com/77460466/197391396-fbf1b24d-6ca4-409a-86b4-0af7f0587208.png)
Finnish is used for this examble. Seems to happen with any localization which uses a space instead of comma as separator between digits

### Related issues:

https://bugs.mojang.com/browse/MC-2595

https://github.com/SlimeKnights/TinkersConstruct/issues/2608

https://github.com/MinecraftForge/MinecraftForge/issues/3521

https://github.com/SleepyTrousers/EnderIO-Rewrite/pull/72#discussion_r946971485
### 
### **Mod version:**
Minecraft 1.19.2
Forge 43.1.47
IC2C 2.0.0

**Comment by Speiger** [comment]
Wow. Ok this should be addressed in the next patch.
We know english and german work fine since these were the development languages.

This will be addressed in the next patch.

Thank you for the report.
