### ISSUE TITLE
[1.19.2] Localization missing for Show Recipes in wiki

### ISSUE THREAD

**Issue by Vapaman** [TinyModularThings/IC2Classic#472]
### Issue
Localization missing for "Show recipes"
![kuva](https://user-images.githubusercontent.com/77460466/197392955-7db9a799-1990-4342-b7c0-3c5938dc21ba.png)

Note that the localization is there when there are multiple options shown
![kuva](https://user-images.githubusercontent.com/77460466/197392965-eb0e9bd6-2ebd-4449-95e7-91877d8505ce.png)

### Mods

Minecraft 1.19.2
Forge 43.1.47
IC2C 2.0.0

**Comment by Speiger** [comment]
GAHHHHH a typo sneaked in... Thank you.

Will be address with the next patch.
