### ISSUE TITLE
[Suggestion] [Compatibility] Make flux generators compatible with AE2 energy acceptors

### ISSUE THREAD

**Issue by Vapaman** [TinyModularThings/IC2Classic#473]
AE2 energy acceptors do not pull energy out of a block, so there needs to be an another mod to act as a bridge or use AE2s own enegy generation.

Potential fix to this would be to make the flux generators push FE automatically to adjacent blocks.

**Comment by Speiger** [comment]
Flux Generators automatically emit power on the "Red" Dot.
and we used them with AE.

And i tested that it works.

**Comment by Vapaman** [comment]
Sorry, I cannot get it to work on my end. I'll try to see if its some conflict with another mod

**Comment by Speiger** [comment]
Does it work with the Controller?

**Comment by Vapaman** [comment]
I'll try with just AE2 and IC2, and test it with just the controller

**Comment by Vapaman** [comment]
Yes, it works if you plug it directly to a controller, but doesn't seem to work if you try to power an energy acceptor

![kuva](https://user-images.githubusercontent.com/77460466/197396427-879dff66-c4c2-4f86-8eb3-eb011cf04822.png)

**Comment by Speiger** [comment]
@shartte and @Technici4n would you care to explain why the Energy Acceptor isn't working?

oh yeah @Vapaman small warning from a bug that ME is aware of but choose to ignore.
If you break and replace the controller after it attached to a Flux generator the second controller won't receive power.
(Due to them not supporting a essential forge feature)

**Comment by Vapaman** [comment]
> If you break and replace the controller after it attached to a Flux generator the second controller won't receive power.
Can replicate

**Comment by Speiger** [comment]
Yes that will happen due ic2c using a new forge feature that allows caching. This is a major performance increase, and while there are mods out there not supporting it, so far outside of AE everyone fixed it the moment i reported it.

Simple fix is: break and replace the ic2c block to reset the cache.
