### ISSUE TITLE
[1.19.2] Resin spits out on the wrong side of the tree

### ISSUE THREAD

**Issue by Erik3003** [TinyModularThings/IC2Classic#475]
### Issue:

When using the tree tap on a resin spot, the resin will drop behind the resin spot, i.e. on the other side of the tree.

### Mod version:

Minecraft 1.19.2
Forge 43.1.47
IC2C 2.0.0

**Comment by Speiger** [comment]
It shoots out randomly. 
The issue is the drop spawns in the block itself...

I am not sure if i make this a feature or fix it...
