### ISSUE TITLE
[Bug] Miscellaneous bugs with Rubberwood

### ISSUE THREAD

**Issue by Vapaman** [TinyModularThings/IC2Classic#478]
Rubber trees have some bugs and inconsistensies with vanilla trees

### Rubberwood saplings are always fully grown with 1 bonemeal

Rubberwood saplings grow with the first bonemeal. 
Inconsistent with vanilla saplings as vanilla saplings it usually takes several pieces of bonemeal.
It also seems that the Rubberwood Sapling doesn't have the "stage" tag that vanilla saplings have.

### No charcoal recipe
![kuva](https://user-images.githubusercontent.com/77460466/197842291-71065b20-96e8-4e45-b64e-3de0190444f8.png)
Rubberwood logs cannot be used for charcoal. Don't know if this is an oversight or intended. Seems to be missing as Rubberwood seems to be missing the tag "minecraft:logs_that_burn"

### Rubberwood leaves damage entities that are inside them'
Rubberwood leaves seem to be semi-opaque, and damage entities that are inside them.
This is inconsistent with vanilla leaves. Makes it annoying to go through when riding horses.
![2022-10-25_20 32 47](https://user-images.githubusercontent.com/77460466/197842872-03352bd6-2c61-4e6f-b999-532bb694ed79.png)

### Rubberwood Leaves are not flammable
Rubberwood leaves cannot catch fire or be destroyed by fire. Most likely relates to how it is semi-opaque.

### Mod versions
Minecraft 1.19.2
Forge 43.1.47
IC2C 2.0.0

If I find more bugs relating to rubberwood I'll add them here

**Comment by Speiger** [comment]
> Rubberwood saplings are always fully grown with 1 bonemeal

That is intended and stays that way. Yes it is inconsistent with vanilla, but honestly i don't care.

> Rubberwood leaves damage entities that are inside them

This is a bug since leaves shouldn't deal damage and will be addressed.

**Comment by Vapaman** [comment]
Just added that the rubberwood leaves are not flammable

**Comment by Speiger** [comment]
will be also addressed
