### ISSUE TITLE
[1.19.2-2.0.20/1166] GL Errors upon setting keybinds from this mod to Not Bound

### ISSUE THREAD

**Issue by FyreAlchemage** [TinyModularThings/IC2Classic#480]
When setting some of this mod's key bindings to Not Bound, the game spams a GL error about it, resulting in huge log sizes. Specifically, the error is: "65539: Invalid key -1".

This happens with the following bindings:
- Alt Key
- Mode Switch Key
- Side Inventory Key
The others don't mind being unbound.

**Comment by Speiger** [comment]
Thank you that will be addressed in the next patch. (Next monday)

I should have fixed this when it was found in UE...
