### ISSUE TITLE
[1.19.2] Stripped Rubberwood does not give Resin

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [TinyModularThings/IC2Classic#481]
I am unable to use Tree Tap or place Treetap & Bucket on stripped Rubberwood log with visible Resin on it (with both `resin` and `collectable` block states set to true)
![2022-10-28_12-08-50_ef51c838-6c69-48b5-a737-1b701b87dfdf](https://user-images.githubusercontent.com/5104603/198550657-986eed0d-749e-4e17-a083-36e16ce6aecc.png)

EDIT: Bucket placed before stripping continues to generate resin properly.

**Comment by Speiger** [comment]
Jikes... Yeah nobody did that during testing so yeah it never came up. Will be addressed in the next patch.

Thank you for the report
