### ISSUE TITLE
[1.19.2] Can use jetpack while riding entity

### ISSUE THREAD

**Issue by Vapaman** [TinyModularThings/IC2Classic#482]
### Issue
While mounting any entity you can use the jetpack to rise. This produces rather humorous results:
![2022-10-28_21 27 15](https://user-images.githubusercontent.com/77460466/198707023-31fc3d04-ce7b-4be3-b4cc-d9be55dcdb3f.png)
![2022-10-28_21 29 37](https://user-images.githubusercontent.com/77460466/198707176-11c03ce5-9f99-4374-949a-0e39bec9af31.png)

### Mod versions
Minecraft 1.19.2
Forge 43.1.47
IC2C 2.0.0

**Comment by Speiger** [comment]
Not a bug that is actually a intended feature since 1.12.2 xD

**Comment by Vapaman** [comment]
Lul
