### ISSUE TITLE
No possible way to get aluminium

### ISSUE THREAD

**Issue by Voidrunner42** [TinyModularThings/IC2Classic#483]
Title explains itself, no way to get aluminium ore, or in anyway

**Comment by Speiger** [comment]
@Voidrunner42 read the wiki, or look in JEI,
both have explained how you get it.

"Progression Tutorials"

**Comment by Voidrunner42** [comment]
Can you please refer me to a link? Since I cannot find it in the wiki.

**Comment by Speiger** [comment]
@Voidrunner42 in 1.19.2 there is a "Ingame" wiki item.
That you get when you spawn in a world.
And that item is the wiki.
