### ISSUE TITLE
Jetpack bug

### ISSUE THREAD

**Issue by Mauladen** [TinyModularThings/IC2Classic#485]
Good afternoon, I have discovered a strange bug that is related to jetpack and possibly something else.
When I play with my girlfriend together, when she presses the space bar, I just take off, that is, she controls my flight, but on the contrary it does not happen

**Comment by Speiger** [comment]
What Context were you playing in?
Multiplayer? Lan?

Also a small clip would help immensely @Mauladen

**Comment by Mauladen** [comment]
Let me describe the situation in more detail 

1. LAN 
2. I am the creator of the world 
3. When I use JetPack (any that is in fashion), when I press the space bar of another player, even if there is no jetpack on it, I start to take off, that is, he controls my flight, but my actions do not affect his flight

**Comment by Mauladen** [comment]
> What Context were you playing in?
> Multiplayer? Lan?
> 
> Also a small clip would help immensely @Mauladen

Let me describe the situation in more detail 

1. LAN 
2. I am the creator of the world 
3. When I use JetPack (any that is in fashion), when I press the space bar of another player, even if there is no jetpack on it, I start to take off, that is, he controls my flight, but my actions do not affect his flight
