### ISSUE TITLE
Jetpack hover mode does not prevent falling damage when riding a mount

### ISSUE THREAD

**Issue by Maoman1** [TinyModularThings/IC2Classic#488]
I flew up very high on my horse and then glided down with hover mode, and as soon as I touched the ground, I and my horse both took full fall damage as if we'd fallen that entire height without hover mode, killing my horse instantly and leaving me with 1 heart left. That horse had amazing stats too :(

**Comment by Speiger** [comment]
Thank you that is now fixed.

**Comment by Speiger** [comment]
Could reproduce it, not sure if that is so easily fixable...
