### ISSUE TITLE
feature request: brew time configs 

### ISSUE THREAD

**Issue by linkhidalgogato** [TinyModularThings/IC2Classic#491]
i would really really appreciate a config to multiply the amount of time it takes to brew stuff by a factor. Or some kind of single player mode which rebalances the times. 

Its clearly designed to take a while and i get that and it would be fine for servers, but these times just don't work in single player like at all, most worlds (specially moded) dont even last 1680 hours of playtime and that's the MINIMUM amount of time to make whisky, even some of the other times a pushing it at 13 to 40 hours but doable whisky tho its just impossible to get in single player. Having it be idk 1 hour per year would still be an extremely long time in single player but it would at least be doable

**Comment by Speiger** [comment]
@linkhidalgogato I didn't ignore your message, I am just waiting on a few backend answers, or if they don't come I will answer for them. But since the next patch is a few weeks away it is fine if this process takes a bit longer.
