### ISSUE TITLE
[1.12.2] Furnace recipes broken in latest update

### ISSUE THREAD

**Issue by xJon** [TinyModularThings/IC2Classic#493]
The latest release (`1.5.6.0`) introduced an issue with IC2C furnace recipes - they no longer accept most recipes, e.g. you can no longer smelt cobblestone or sand or vanilla ores in IC2C furnace machines.
This is reproducible with IC2C only and by reverting a version the issue goes away.

**Comment by Speiger** [comment]
Took a while but fixed

**Comment by xJon** [comment]
Update: Issue is back with version `1.5.7`.
