### ISSUE TITLE
[1.19.2] After 10/18 Overclockers / Quantum Overclockers machine stops working.

### ISSUE THREAD

**Issue by Kanzaji** [TinyModularThings/IC2Classic#495]
## Description
After some amount of overclockers in a machine, the process just stops / even goes backwards >.>

## How to reproduce
1. Place any machine in the world with transformer upgrades and 10 overclockers / 18 Quantum overclockers*
2. Power it up
3. Add one more overclocker / quantum overclocker
4. Watch progress stopping / going backwards

*Note: I actually tested this just with electric furnace at the moment of reporting this ^^"
Edit: It seems that amount of overclockers is different for other machines, but for all of them at some point machine just stops.
## Screenshots / videos
https://user-images.githubusercontent.com/60540476/199271774-f0407167-f4da-4d50-930b-42e99e11e479.mp4

## Other mods:
I use Enigmatica 9 Develop version of 1.0.3 (Between 1.0.2 and not released yet 1.0.3) with IC2C added
https://github.com/EnigmaticaModpacks/Enigmatica9

PS: Also not sure about those, so gonna ask here ^^":
- iirc Fluid cells were able to place fluids in world >.> But they can't now.
- Also unisolated cables doesn't seems to do damage to a player when EU is transfered. 
- Another thing, that is probably intentional actually, is that batteries doesn't output any power if it has stored less than its output rate.

**Comment by Speiger** [comment]
Not a bug. The EU/t consumption exceeds the internal Energy Buffers capacity.
The machine should continue to work if you insert a Energy Storage Upgrade.

**Comment by Kanzaji** [comment]
Woops, I completely forgot about this ^^" Yea that raised the limit.
But I will ask few more things, as I don't want to create another issues for those things if they are intentional >.>

- iirc Fluid cells were able to place fluids in world >.> But they can't now.
- Unisolated cables doesn't seem to do damage to a player when EU is transfered.
- Batteries doesn't output any power if it has stored less than its output rate. I'm guessing that one is intentional, as I think that how it worked in the old versions as well ^^" But it feels weird to see 30k of EU in PESU and not being able to "extract" it for use.
- You can't actually see how much power machine can have / has. Tooltip is just missing when you hover over energy icon.
- Thermal gen doesn't actually react to lava to increase heat generation, only if you input it, what makes it kinda more expensive fancy geothermal gen.

Also yup, some of them I've copied over ^^"

**Comment by Speiger** [comment]
> iirc Fluid cells were able to place fluids in world >.> But they can't now.

IC2Exp thing. Never was a classic thing.

> Also unisolated cables doesn't seems to do damage to a player when EU is transfered.

only happens if 32 EU/t is exceeded iirc... Though might be a bug... Need to test.

> Another thing, that is probably intentional actually, is that batteries doesn't output any power if it has stored less than its output rate.

Performance optimization. Batteries are only drained if the machine is at 90% power. This makes a machine 80% less laggy.

> You can't actually see how much power machine can have / has. Tooltip is just missing when you hover over energy icon.

This has some lore actually. EU Reader in the hotbar (or in the modular armor Hud slot)
Why? How the f would steve know it without a tool to do it?

> Thermal gen doesn't actually react to lava to increase heat generation, only if you input it, what makes it kinda more expensive fancy geothermal gen.

Thermal Generator passive generation only works if there is no lava used. Also it updates very slowly (like IIRC every 1024 ticks) due to performance. Because it checks 3.375 Blocks (15x15x15 area).

If you have more questions. Keep asking. As long this isn't in the wiki I will explain it. (EUReader is explained in there though)
Also i suggest TheOneProbe since it has special compat with ic2c with a lot of info.

**Comment by Kanzaji** [comment]
> only happens if 32 EU/t is exceeded iirc... Though might be a bug... Need to test.

I've tested this on aluminium wire with ISU charging another ISU, so it is for sure over 32EU/t 😅

> Another thing, that is probably intentional actually, is that batteries doesn't output any power if it has stored less than its output rate.

I think there was a little missunderstooding 😅 I was talking about blocks ones, like MFSU, PESU output rates. Also good to know that this optimization is a thing 😋

> Thermal Generator passive generation only works if there is no lava used in the internal tank. Also it updates very slowly (like IIRC every 1024 ticks) due to performance. Because it checks 3.375 Blocks (15x15x15 area).

Well, I do have it for long time surrounded by lava, and EU generation like... jumped a tiny bit ^^" Maybe 0.1 EU. Let me try to just put it in nether lava lake and wait like 10 minutes.

**Comment by Speiger** [comment]
> I think there was a little missunderstooding 😅 I was talking about blocks ones, like MFSU, PESU output rates. Also good to know that this optimization is a thing 😋

Oh yeah this is intentional. 😅

> Well, I do have it for long time surrounded by lava, and EU generation like... jumped a tiny bit ^^" Maybe 0.1 EU. Let me try to just put it in nether lava lake and wait like 10 minutes.

The max output of passive gen is 16EU/t. While that doesn't sound like a lot you can place a lot of them into a giant lava pool.

> I've tested this on aluminium wire with ISU charging another ISU, so it is for sure over 32EU/t 😅

Yeah then please make a issue for that so i remember when i make the next patch.
