### ISSUE TITLE
[1.19.2] Unisolated cables don't hurt player anymore

### ISSUE THREAD

**Issue by Kanzaji** [TinyModularThings/IC2Classic#496]
*Relayed from #495*
## Description
Unisolated cables doesn't hurt player while EU is transfered

## How to reproduce
1. Place charged ISU and uncharged ISU
2. Connect them with unisolated aluminum cable
3. Literally stand on the cable in survival mode

## Screenshots / videos
https://user-images.githubusercontent.com/60540476/199280674-1c9d4510-a74e-4361-b01b-14c983b5fcb4.mp4

## Other mods:
I use Enigmatica 9 Develop version of 1.0.3 (Between 1.0.2 and not released yet 1.0.3) with IC2C added
https://github.com/EnigmaticaModpacks/Enigmatica9

~~Also another question ^^" What information OneProbe should give player? As E9 does have OneProbe installed, and only thing I get is for some machines the drop chance and inventory content~~
Okay ignore that, I see you need actual item for OneProbe to show more info 😅

**Comment by Speiger** [comment]
@Kanzaji ty.
Also TOP can be configured that you don't need the item. (The config is a bit annoying, but it works)
I might make a patch to the mod that makes it easier for the user.
