### ISSUE TITLE
[Suggestion] Support for ExtremeReactors and Refined Storage energy

### ISSUE THREAD

**Issue by drenough** [TinyModularThings/IC2Classic#499]
Hi, sorry to bother you, just wanted to ask if you could add some block or support for FE energy mods like ExtremeReactors or Refined Storage mod, so I could use FE power from Extreme Reactors for EU power if possible please ?

**Comment by Speiger** [comment]
FE support is already a thing with the FluxGenerator. Which also automatically emits power.

And more then that i am not willing to do.
If that is fine with you please close the issue.

**Comment by drenough** [comment]
Thanks a lot!

**Comment by drenough** [comment]
Sorry for re-opening this, I tried flux generators but if I put them directly on output from Extreme Reactor, they just dont get power, If I use some solar panels with flux generators, I can power Refined Storage controller but I can not get power from Extreme Reactor to flux generator or maybe I'm doing it wrong :(.

**Comment by drenough** [comment]
I asked on https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/103 and they said that if you're ok with them making it compatible with your EU power system they would do it ?

**Comment by Speiger** [comment]
Flux Generators are only "producing" not "Accepting" Forge Energy.
Meaning they are EU => FE and not FE => EU

**Comment by Speiger** [comment]
Also small extra note.
Extreme reactors were one of the reason RF/FE => EU support was cut.
