### ISSUE TITLE
Nightvision Goggles Missing Texture

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#5]
They did have one, which is this:
![nightvision_1](https://cloud.githubusercontent.com/assets/4021725/7031693/580bc5a8-dd65-11e4-8306-d78b93d73409.png)

**Comment by Speiger** [comment]
Thanks i will add that when the Item gets its recipe

**Comment by Chocohead** [comment]
![2015-06-06_15 25 02](https://cloud.githubusercontent.com/assets/4021725/8019992/3c5db04e-0c60-11e5-846f-6d18b61d877e.png)

Was the old recipe in case you were wondering ;)

**Comment by Speiger** [comment]
Ok. I think i take it... Better then nothing ^^" (I had no idea how i should make a recipe)

Also done when i am back.

**Comment by Speiger** [comment]
added
