### ISSUE TITLE
How can I translate the mod into my native language?

### ISSUE THREAD

**Issue by Mauladen** [TinyModularThings/IC2Classic#504]
As I see your development is not being done here, and therefore I want to know how I can participate in translating the mod into Russian?

**Comment by Speiger** [comment]
Oh crap i forgot the ruissan translation someone send me...
Will be included with the next patch...

**Comment by Mauladen** [comment]
> Oh crap i forgot the ruissan translation someone send me...
> 
> Will be included with the next patch...


Thanks for your work, it's very cool

**Comment by Speiger** [comment]
Made by: [grustno_kataem](https://www.curseforge.com/members/grustno_kataem)
[ru_ru_translations.zip](https://github.com/TinyModularThings/IC2Classic/files/9935009/ru_ru_translations.zip)

If you want to check them and fix issues that is fine.
A friend of mine said they are fine, but the more confirmations the better!

**Comment by Mauladen** [comment]
> Made by: [grustno_kataem](https://www.curseforge.com/members/grustno_kataem) [ru_ru_translations.zip](https://github.com/TinyModularThings/IC2Classic/files/9935009/ru_ru_translations.zip)
> 
> If you want to check them and fix issues that is fine. A friend of mine said they are fine, but the more confirmations the better!

The translation itself looks good, but I noticed my VS Code shows a lot of errors in ru_ru.json and wiki_ru_ru.json, I think it needs to be checked

**Comment by Mauladen** [comment]
I have created my own repository where I am currently correcting translation design errors
[ic2classic-ru)](https://github.com/Mauladen/ic2classic-ru)

**Comment by Speiger** [comment]
I might open source translations too.
Ill think about it. But that is a good idea.

**Comment by Speiger** [comment]
@Mauladen I will link him this issue.
Just a small warning. Make sure you create a datapack and test the translations.
The wiki is really picky on what it displays and what not.
- The "preview" entries for example cut of everything that doesn't fit on a page.
- The "subpage/page" is made with style in mind. Where you have to make sure everything looks good.

So please keep that in mind.

**Comment by Mauladen** [comment]
> @Mauladen I will link him this issue. Just a small warning. Make sure you create a datapack and test the translations. The wiki is really picky on what it displays and what not.
> 
> * The "preview" entries for example cut of everything that doesn't fit on a page.
> * The "subpage/page" is made with style in mind. Where you have to make sure everything looks good.
> 
> So please keep that in mind.

I would be very glad if you could help me make or at least suggest how to make a datapack with translation

**Comment by Mauladen** [comment]
> @Mauladen I will link him this issue. Just a small warning. Make sure you create a datapack and test the translations. The wiki is really picky on what it displays and what not.
> 
> * The "preview" entries for example cut of everything that doesn't fit on a page.
> * The "subpage/page" is made with style in mind. Where you have to make sure everything looks good.
> 
> So please keep that in mind.

I understand what you are talking about, but at the moment the translation is at this stage

1. Different translation of some items in different parts of the mod
2. There are many problems that you described above
3. There are places that are not translated or are not translated accurately

**Comment by Speiger** [comment]
@Mauladen translations are now open source.
