### ISSUE TITLE
[1.19.2] Fluid pipes don't connect to cauldrons

### ISSUE THREAD

**Issue by Vapaman** [TinyModularThings/IC2Classic#505]
### Issue
Fluid pipes cannot connect to and extract from vanilla cauldrons. This makes lava farms harder to make. 
![2022-11-04_19 45 27](https://user-images.githubusercontent.com/77460466/200041704-e0855137-8b10-41c3-89f5-c1d7ac1d5586.png)

### Versions:
IC2C 1.19.2 2.0.1
Forge 43.1.47

**Comment by Speiger** [comment]
Cauldrens arent fluid containers in code.
not a bug.

**Comment by Speiger** [comment]
If you want a good relyable lava source, "Fusion Reactor" is your target.
It will be able to produce as much as you need.
Otherwise pump a lava cave lake or nether?
