### ISSUE TITLE
[1.19.2] Suggestion, add Config to disable Wiki

### ISSUE THREAD

**Issue by Saereth** [TinyModularThings/IC2Classic#506]
How do you disable the wiki book on first spawn in 1.19.2, I'm not seeing anything for it in the config. Someway via datapacks perhaps?

**Comment by Speiger** [comment]
@Saereth Throw it away, and you are fine. Just prooving my point right xD
But no. I will enforce the wiki book on initial spawn because IC2C is complicated enough where you need guidance.

**Comment by Saereth** [comment]
This is a bad policy frankly, things like akashic tome and quests exist. This is the responsibility of a pack dev if they disable your book to convey the information to the player. You have the book spawn, on by default, you've provided the information well and if `ther` is valid reason beyond that to not initially spawn with it then a config is elementary. Imagine if every mod enforced their book on spawn with the same logic, players in mod packs would login to full inventories.

**Comment by Speiger** [comment]
Frankly, this mod is fresh and so different from the original that at this point the wiki is necessary.
Also I doubt that someone is willing to write over 600 pages of documentation into their quest for every single thing.

On top of this. To be honest I am not expecting a single questing packdev to use this mod. (Sorry @Geekerandy)
Ignoring that FFS right now my main focus is to provide people who play the mod the best experience possible.
Meaning if i give a option to skip the wiki and not force it on to them they will get stuck on every single thing or use outdated info.

I might include a config later but for now NO.
If you don't like that then please play with different mods, i made this mod for my friends and me and the release was nice to have on the side.

**Comment by Saereth** [comment]
Gotcha, will remove from the modpack. Thanks for your reply

**Comment by Speiger** [comment]
Opening because keeping the suggestion anyways.

**Comment by Speiger** [comment]
@Saereth  and for everyone else.
i might not add a config right now but there is a way to disable it with CraftTweaker.
IC2c checks for the "ic2_wiki" boolean tag inside of the Entities Persistent data to be set false.
It uses the [PlayerLoggedInEvent](https://docs.blamejared.com/1.12/es/Vanilla/Events/Events/PlayerLoggedIn)
At a normal priority.
Just set the flag early enough and the book won't spawn.

```java
	@SubscribeEvent
	public void onPlayerLoggedIn(PlayerLoggedInEvent handler)
	{
		CompoundTag nbt = handler.getPlayer().getPersistentData().getCompound(Player.PERSISTED_NBT_TAG);
		if(!nbt.getBoolean("ic2_wiki")) {
			//Give Wiki
		}
	}
```

Now I gave you the tools to do it yourself.

**Comment by Saereth** [comment]
That's perfectly fine, and appreciated. Basically in this use case the players will still be provided the book just in the form of the akashic tome which contains several starting books they can switch between, so this will work great for that.
