### ISSUE TITLE
[1.19.2] Misc bugs with the advancements

### ISSUE THREAD

**Issue by Vapaman** [TinyModularThings/IC2Classic#508]
### New ore miner is not triggered by picking up raw ore

This makes it so it isn't possible to obtain this advancement without first getting silk touch.

The advancement is also calling for mining copper, which isn't added by IC2C

### The wither nuking advancement is missing localization
![2022-11-06_02 30 03](https://user-images.githubusercontent.com/77460466/200148615-e983863b-7c45-400a-88a9-3183e72b33a4.png)

### Mod versions:
IC2C: 2.0.1
Forge: 43.1.47

**Comment by Speiger** [comment]
Ty will be addressed in the next patch.
(Milestone has a ETA attached when i try to get it out)
