### ISSUE TITLE
Scaffold inflict damage

### ISSUE THREAD

**Issue by Dr0n1k** [TinyModularThings/IC2Classic#51]
There is another bug. If you put scaffolding and try to climb on them, then either fall into the texture and takes damage, or you start to climb on them and still take damage.

**Comment by Chocohead** [comment]
Yeah, walking into scaffold gives you damage. It also doesn't stack when you left click on more scaffold to the bottom of a tower.

**Comment by Speiger** [comment]
I am testing the left clicking and it works fine for me. You also have to know when he can  not place it then it has something todo with that the weight is bad on that side (they act a little bit realistic)

**Comment by Speiger** [comment]
By the way the damage thing is now fixed.
Also added that you climb on Iron Scaffoldings 50% faster. (from 0.2 up to 0.3)

**Comment by Speiger** [comment]
By the way did you know that you can increase the strenght of the Scaffolding (Iron ones with Iron Fences and wooden ones with sticks)?

**Comment by Chocohead** [comment]
Indeed I did. Only works when they have a block under them however.
