### ISSUE TITLE
[1.19.2] Fusion reactor not forming, am I being an idiot?

### ISSUE THREAD

**Issue by levicc00123** [TinyModularThings/IC2Classic#512]
I'm using regular reinforced stone, clear reinforced glass, and regular valves in my setup. I've taken two screenshots to show how I have the fusion reactor set up in my creative test world.
![2022-11-08_07 18 30](https://user-images.githubusercontent.com/4361838/200590323-70cacce9-9d90-4e05-aece-2c0eaa332c9f.png)
![2022-11-08_07 18 36](https://user-images.githubusercontent.com/4361838/200590330-23372333-8e85-4751-8ca7-648256eb265a.png)

IC2 Classic 2.0.1
Forge 43.1.47

Am I being an idiot, am I supposed to be using some other valve block, or is there something ese I need to do before the fusion reactor works properly?

Thank you for your time, and I'm sorry if this is the wrong place to ask this.

**Comment by Speiger** [comment]
Top Left of of the Side you place it on. the wiki says that. But its a general rule

**Comment by levicc00123** [comment]
Yeah, I'm an idiot. Thank you for your help, and thank you for making an amazing mod!

**Comment by Speiger** [comment]
No Problem @levicc00123
