### ISSUE TITLE
IC2 Classic for 1.19.2 incompatible with OptiFine

### ISSUE THREAD

**Issue by JasonS05** [TinyModularThings/IC2Classic#513]
While using MultiMC to load IC2 Classic I found that it crashed on launch. I tried disabling IC2 Classic (preventing forge from loading it) and then it worked. I re-enabled IC2 classic and disabled all my other mods. Again, it worked. I then started enabling mods one by one until it stopped working. When I got to OptiFine, it started crashing again. To be sure it was the culprit, I disabled all the other mods so I only had IC2 classic and OptiFine and it kept crashing. The specific versions I am using are:

Operating system: Ubuntu 22.04 LTS
Java: openjdk 17.0.5 2022-10-18
Minecraft: 1.19.2
Forge: 43.1.1
IC2 Classic: IC2Classic-1.19.2-2.0.1.jar
OptiFine: OptiFine_1.19.2_HD_U_H9.jar

Crash report here: [crash.txt](https://github.com/TinyModularThings/IC2Classic/files/9977311/crash.txt)

**Comment by Speiger** [comment]
@JasonS05 sorry but there is 0 optifine support from me.
For all its worth the dev can fix it himself or it will never be fixed.

I actually tried working with him once and found a bug in his code with chunk pregen.
Where he didn't do certain checks.

And yes he fixed that rather quick, but i kept getting bugreports about the same crash.
Now i was lazy, but after almost 1 year of constant reports i found out he never offically released the patch he made.
Not only that he skipped releases with a CRASH FIXING BUG.
I had to hound him for long, Community backlashing and him being a dick,
So yeah after that I said 0 Optifine support. Even if i am the cause.

I won't go out of my way to break optifine support, but i won't check if it works.

So yeah @sp614x FUCK YOU!

@JasonS05 Use Radium/Rubidium instead, they provide a lot more performance in comparason and I support these two mods actually.

**Comment by Speiger** [comment]
Pinning this so people can see that I don't care if optifine works with it or not.

**Comment by JasonS05** [comment]
@Speiger thanks for letting me know you won't support OptiFine (and why). I'll look into Rubidium/Radium then.

**Comment by Speiger** [comment]
@JasonS05 sorry. Touchy subject...
No attacks go to you only to you know who.
If you felt attacked i am sorry.

**Comment by JasonS05** [comment]
@Speiger no I didn't feel attacked or otherwise insulted. Sometimes it's a bit hard to convey subtle feeling over text (lack of intonation and such) so I understand why you might've thought I was unhappy. Now that I read my comment again I realize the first sentence comes across as sarcastic, but I didn't mean it that way.

**Comment by Speiger** [comment]
@JasonS05 no worry, i just wanted to make sure 💯

**Comment by snowstarlfy** [comment]
So, if you dont support OptiFine, how can i play ic2c with shaders?

**Comment by Speiger** [comment]
@snowstarlfy there are other alternatives out there.

**Comment by HeroxeT** [comment]
I use a lot of resources to make minecraft look nicer (for example, flash animation) and almost all of these resource packs use the optifine function to work properly. There are no alternatives in this case for forge. What can be done in this case?

**Comment by Speiger** [comment]
@HeroxeT yeah then you are out of luck.

**Comment by xJon** [comment]
@HeroxeT Use [Entity Model Features](https://www.curseforge.com/minecraft/mc-mods/entity-model-features) + [Entity Texture Features](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric).

**Comment by HoopaDeez** [comment]
@Speiger I cant find any alts for optifine that support shaders on 1.19.2 Forge other than Oculus and that causes crashing just like optifine

**Comment by CrossVas** [comment]
> [@Speiger](https://github.com/Speiger) I cant find any alts for optifine that support shaders on 1.19.2 Forge other than Oculus and that causes crashing just like optifine

embeddium and oculus should be enough to provide you the ability to use shaders afaik. And they both work just fine with IC2Classic.
