### ISSUE TITLE
[1.19.2] - Crash using hopper to feed dirt into rare earth extractor

### ISSUE THREAD

**Issue by ToxinZangoose** [TinyModularThings/IC2Classic#514]
Forge version: 43.1.52
Minecraft version: 1.19.2
IC2:C version: 2.0.1

Hello, first time using IC2. 
I ran into an issue with a vanilla hopper crashing the game when placing it by a rare earth extractor and filling it with dirt.

The error log said something about ticking block entity for the rare earth extractor, here is the crash log.
[crash-2022-11-10_19.09.04-server.txt](https://github.com/TinyModularThings/IC2Classic/files/9985653/crash-2022-11-10_19.09.04-server.txt)

**Comment by Speiger** [comment]
This looks like a canary issue.
please use Radium or Rubidium (which one is the lithium port)

**Comment by ToxinZangoose** [comment]
Will do, thank you!
