### ISSUE TITLE
[1.12.2] Electric Furnace cooks dusts as the last one cooked

### ISSUE THREAD

**Issue by ArthurHetem** [TinyModularThings/IC2Classic#518]
Basic details

```
Are you using a legitimate Minecraft acount?: Yes
Are you using Java 8, 64-bits?: Yes
Did you add any additional mods: Tekkit 2 modpack
Crash/latest log link (if applicable): Not a crash
Describe the issue

```
When there is a inventory attached to the electric furnace for example a hopper and there are different ore types, the next type of ore dust will be cooked as the previous one for example:
Cooking iron dust into iron ingot and in the hopper are tin dust
After the iron dust is cooked, the tin dust will start to go down to the furnace, and the furnace will start to cook tin dust into iron ingot:
![image](https://user-images.githubusercontent.com/7545272/202833208-ac181527-baf6-40ba-9b75-b82b7565f834.png)

**Comment by Speiger** [comment]
HUH, good to know... I will address this in the next patch which is scheduled for next year.

**Comment by Speiger** [comment]
Fixed
