### ISSUE TITLE
IC2 and Mekanism energy compatability

### ISSUE THREAD

**Issue by E-daw** [TinyModularThings/IC2Classic#519]
Universal cables from mekanim aren't connecting to IC2 machinery and vice versa (latest version of both mods on 1.19.2). Is there any way to fix this or any compatibility mods that exist? I have compatibility turned on through config and it still doesn't work.

**Comment by Speiger** [comment]
@E-daw for EU => FE/RF generation the Flux Generator exists.
For RF/FE => EU, no there is nothing.
And that is intentional, since RF/FE production is really unbalanced.

You can produce EU with Steam though. Steam Turbine (64EU) or the Steam Tunnel (between 512-2048EU) is an option.
