### ISSUE TITLE
Rubber wood and Bone meal

### ISSUE THREAD

**Issue by Dr0n1k** [TinyModularThings/IC2Classic#52]
If I use bone meal in the Sapling of a rubber tree, the oak tree grows normal.

**Comment by Chocohead** [comment]
Confirmed, bone mealing a rubber tree sapling makes it grow an oak tree.

Also, it should only take 1 bone meal to make it grow, it always used to and still does in experimental. Thunderdark said the industrial-ness of them makes it only take 1.

**Comment by Speiger** [comment]
Was not only the Sappling that were broken. Nope the generating of the Tree was intirely dead...
Fixed anyways.
