### ISSUE TITLE
[1.19.2] Mining Laser Tracking Mode will Crash against Endermen when Mo' Enchants is also installed

### ISSUE THREAD

**Issue by Geekerandy** [TinyModularThings/IC2Classic#520]
A modpack containing
IC2 Classic 2.0.2
and Mo' Enchants 1.5
https://www.curseforge.com/minecraft/mc-mods/mo-enchants

Will result in a crash if the Mining Laser from IC2 Classic hits a Tracking Mode shot onto an Enderman. Removing Mo' Enchants prevents a crash.
It is ONLY enderman. Other mobs will NOT cause a crash.

[crash-2022-11-23_23.42.32-server.txt](https://github.com/TinyModularThings/IC2Classic/files/10081780/crash-2022-11-23_23.42.32-server.txt)

**Comment by Speiger** [comment]
Yeah Mo Enchants expect the attacker always to be alive.
Which fun fact arrows (if they could hit the darn thing) aren't either.
Sooo Not a bug of ic2c.
Unless you want mining Laser Beams to become sentient.
And before you ask. NO!

**Comment by Speiger** [comment]
Reported to the Mo Enchants dev

**Comment by LDMGamingYT** [comment]
Hey - Mo' Enchants dev here,
This seems like an easy fix, and I can try to implement it in the next update.
Does the attacking weapon have enchantments, and if so, what?

**Comment by Speiger** [comment]
o/ @LDMGamingYT 
Unbreaking/Efficiency, nothing else is allowed.
Unbreaking => reduces power cost
Efficiency => Unrelated to combat but also increases energy costs.
My suggestion is: If the Entity isn't living assume its a Projectile or something like that and check the "true source".
Or skip it. But always double check.
