### ISSUE TITLE
Russian Wiki does not work

### ISSUE THREAD

**Issue by StaryPartisan** [TinyModularThings/IC2Classic#522]
Despite the presence of the localization file, the Russian wiki does not work.

**Comment by Speiger** [comment]
Thank you I will address it in the next patch.
Though this will wait a bit because I want to work on other projects a bit december with very little time i actually get.
I hope you don't mind :)

January is the next patch planned (unless critical issues)

**Comment by Speiger** [comment]
Tested it, now it works.
