### ISSUE TITLE
Wrong word?

### ISSUE THREAD

**Issue by rentommy** [TinyModularThings/IC2Classic#523]
Lapatron Crystal--->Lapotron Crystal  ?
![图片我1](https://user-images.githubusercontent.com/98695146/206400764-66f9bddc-1df4-45d6-a155-baa6d3a24684.png)

adamantum--->adamantium  ?
![屏幕截图 2022-12-08 165111](https://user-images.githubusercontent.com/98695146/206401560-58301dc8-dcce-4b60-b47c-fb1c314f2469.png)

**Comment by Speiger** [comment]
Good catch.

**Comment by rentommy** [comment]
Electric Wood Gassifier-->Electric Wood Gasifier?
![屏幕截wwwwww图 2022-12-08 174447](https://user-images.githubusercontent.com/98695146/206414542-96f2bda6-b010-4ba7-b49c-ae6b35cd7210.png)

**Comment by rentommy** [comment]
What does Crystalizer mean in the Crystalizer Upgrade Kit?
![屏幕截图 2022-12-09 120245](https://user-images.githubusercontent.com/98695146/206621405-85fc9655-cc82-437e-a84d-de2655592ae4.png)

**Comment by Speiger** [comment]
Ok please don't constantly spam closing and opening.
If you leave it open I will not forget it, I will check github and make sure I looked at everything and marked it as "fixed" when it is fixed.

Spamming the opening and closing will only cause the issue getting locked and if you continue resulting in a ban.

Just update it if it matches.
If you have questions, there is a discord or open a separate issue.

**Comment by Speiger** [comment]
Crystalizer is a reference that the Batbox uses "Batteries", while a MFE uses "Energy Crystals", the "Crystalizing" means the conversion from "Batteries" to "Energy Crystals"

**Comment by Speiger** [comment]
Added Release ETA.

**Comment by Speiger** [comment]
@rentommy adamantum is correct, its not based on a fictional metal like Adamantium.
Its more based on [Adamantan](https://de.wikipedia.org/wiki/Adamantan) Which is more diamond like name.

WoodGassifier is also correct, since its based on the Woodgasser.

The Lapatron was wrong on my side so thank you on that.
