### ISSUE TITLE
Some machines not working in 1.19.2

### ISSUE THREAD

**Issue by Foggias113** [TinyModularThings/IC2Classic#524]
The mod has some issues with some machines like the fuel boiler or the steam tunnels, where, not matter what, does not open the gui, not allowing for steam productions and other things. How can i fix it? Is it a compatibilty issue with a newer version of forge maybe?

**Comment by Speiger** [comment]
For others.
Fuel boiler only gets a gui if you have it a formed multiblock while the steam tunnel doesn't have a gui.
