### ISSUE TITLE
Colossal Machines not working?

### ISSUE THREAD

**Issue by NavedNoor** [TinyModularThings/IC2Classic#526]
I have a Problem with a Colossal Recycler. I build a 2x2x2 machine but it doesn't connect properly. It doesn't connect to any kind of cable or pipe.
![2022-12-11_20 04 08](https://user-images.githubusercontent.com/47759894/206923800-f0e80f84-19e9-4500-a0ab-0a3f8b6948fd.png)
![2022-12-11_20 04 15](https://user-images.githubusercontent.com/47759894/206923813-a5aae29b-d0de-4f00-bd3c-5ec396fefdda.png)

I can't find any information in the in-game wiki or the online wiki about maybe connecting those blocks with a tool to one? 
I tried it out in Single-Player and I can access the menu of the colossal Recycler with just one Block. But it is still unusable.
![2022-12-11_20 04 50](https://user-images.githubusercontent.com/47759894/206923845-a2426ea0-2417-46f4-93e0-a2b7a15a9588.png)
![2022-12-11_20 04 22](https://user-images.githubusercontent.com/47759894/206923839-57bbbc60-ed5e-4b57-9716-479175c07756.png)

I can't tell if this is a bug or if I forgot a step. My problem is: there is no information in the internet or in-game wiki about connecting the single blocks into one multiblock.

**Comment by Speiger** [comment]
You only use 1 Colossal machine and then the rest is Colossal machine structures.
You can disable the "Formed view" in the book and that shows it too.

The Master goes to the top left of the machine based on which facing you look at.

Also the bug is that you are even capable of opening the gui when its not formed correctly.

**Comment by NavedNoor** [comment]
Thank you so much :D and thanks for your great work Speiger!
