### ISSUE TITLE
Wet CFoam should have an entry in the wiki book

### ISSUE THREAD

**Issue by Geekerandy** [TinyModularThings/IC2Classic#527]
At the moment it isn't clear how to make CFoam initially because all you see is how to recolor CFoam.
And as such, there was no entry on making Wet CFoam itself, and if there is, it was not easily seen.

**Comment by Speiger** [comment]
I think there should be a "Cfoam" tutorial page in general.

**Comment by Speiger** [comment]
Finally done. Took me a while!
