### ISSUE TITLE
Electric tools

### ISSUE THREAD

**Issue by Dr0n1k** [TinyModularThings/IC2Classic#53]
When using Electric Wrench machines are not removed, and the use Electric Hoe of the land is not  digs. 

P.S. Sorry for my bad english. I`m using google translate ((((
I really want to help you in the development of this mod.

**Comment by Chocohead** [comment]
Electric Wrenches don't wrench
Electric Hoes don't hoe
Electric Tree-taps don't tree-tap resin
Electric Drills do however work.

**Comment by Speiger** [comment]
First as long it makes any sence to me i can read it.
So it is fine. When i can not read it i tell that.
From which language do you translating?

**Comment by Speiger** [comment]
Fixed.

**Comment by Dr0n1k** [comment]
I translate from Russian

**Comment by Speiger** [comment]
Ok i can not speak that language

**Comment by Chocohead** [comment]
Remove the inprogress tag silly :P

**Comment by Speiger** [comment]
^^" Thanks
