### ISSUE TITLE
[1.19.2] Alloy furnace gets stuck

### ISSUE THREAD

**Issue by KennysDaywalker** [TinyModularThings/IC2Classic#534]
It can be reproduced by inserting the second recipe immediately after the first recipe.
For example with two hoppers or AE2 automation.
![2022-11-17_14 59 57](https://user-images.githubusercontent.com/40204217/207943980-1b17a57f-5e6a-43ea-aa62-57ffe78d5866.png)

**Comment by KennysDaywalker** [comment]
![2022-12-15_18 59 36](https://user-images.githubusercontent.com/40204217/207944994-0dfbccdf-d3ba-47ac-aff7-262622a41960.png)

**Comment by Speiger** [comment]
FFS finally found the bug. Easy fix.
Thank you so much for giving me such a reliable test setup that made it actually easy to reproduce.
And sorry that it took so long.
