### ISSUE TITLE
[1.19.2] Export Upgrade does not always export everything in Refinery

### ISSUE THREAD

**Issue by KennysDaywalker** [TinyModularThings/IC2Classic#535]
This happens only with Bio Fuel in combination with Silver or Gold.
It doesn't matter what type of silver ore or gold ore it is.
![2022-11-30_15 55 09](https://user-images.githubusercontent.com/40204217/207982328-a449a123-b6a9-4ae5-a474-a7294941dd6d.png)

![2022-12-15_22 27 00](https://user-images.githubusercontent.com/40204217/207982387-a3b55276-a859-4a41-ac99-c0ec8696fb0c.png)

**Comment by Speiger** [comment]
I figured it out. The bug is actually that it automatically outputs stuff when its supposed not to. Thank you.
