### ISSUE TITLE
[1.19.2] Whiskey does not mature as quickly as described in the wiki

### ISSUE THREAD

**Issue by KennysDaywalker** [TinyModularThings/IC2Classic#537]
here Daenara whiskey. Because with hers it's pretty obvious to see:
![2022-12-17_20 54 51](https://user-images.githubusercontent.com/40204217/208270943-7a65282c-4331-497e-8e8b-992f56d7800d.png)

More than 7 days have passed but the whiskey has not matured for 10 years.

**Comment by Speiger** [comment]
@KennysDaywalker her power system is mostly based on solar.
I know she has wavegens, but if it constantly rains or is night she might have ran out of power for a few days.

**Comment by Speiger** [comment]
ok @KennysDaywalker did a amazing job and figured out the bug.
My math was completely off...
While this is not perfect either but this is way closer and within my acceptable range this is the value that @KennysDaywalker found that the brew time should take.
```
1.209.600
```
Which is a difference of roughly 520k ticks or (7 hours)

**Comment by Ar4ibald2115** [comment]
@KennysDaywalker out off topic, which mod add this HUD on the left?

**Comment by Speiger** [comment]
@Ar4ibald2115 The One Probe
Which is the mod ic2c also suggests in the first 2-3 wiki pages.

**Comment by Ar4ibald2115** [comment]
@KennysDaywalker Thanks.
