### ISSUE TITLE
[Suggestion] Nuke Jetpack

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#54]
It should really provide some armour points, as you do have a lump of metal attached to your back (the reactor).

**Comment by Speiger** [comment]
Yeah idea is cool. How many points do you think are fair?

**Comment by Carbon-Ghost** [comment]
Iron level seems fair, although it contains diamonds, it's mainly steel-copper-tin making up the armor, but I am not against "nano" armour level ( I only mean armor points wise, so it's close to diamond, yet not quite as good ).

**Comment by Speiger** [comment]
I set it now that it show 1 full shild, 50% damage absorbtion and max 3 damage absorbtion.
That is fair for free (a constant shield that do not take damage) when i make it higher then i will make downside effects (like that the reactor can explode through damage)

**Comment by Carbon-Ghost** [comment]
Oh, kk, nice :D

**Comment by Speiger** [comment]
Got implemented
