### ISSUE TITLE
[1.19.2] Rocket Miner pumps up all Liquid no matter what scanner

### ISSUE THREAD

**Issue by KennysDaywalker** [TinyModularThings/IC2Classic#540]
Tested with this construct:
![2022-12-17_15 02 02](https://user-images.githubusercontent.com/40204217/208559912-231fabc8-4705-488c-a8f5-bf2667048982.png)
![2022-12-17_15 03 14](https://user-images.githubusercontent.com/40204217/208559965-c1688929-d294-4c45-b57b-3b93545555af.png)

The Result for OD and OV Scanner was that:
![2022-12-17_15 18 07](https://user-images.githubusercontent.com/40204217/208561609-0384e978-6aa8-4aac-be0c-63d44ca27b6f.png)
Although the liquids were not in the way on two sides, they were pumped out anyway.

With Filtered Fluid Scanners, the ores were not touched but the fluid filter settings were ignored:
![2022-12-17_16 43 53](https://user-images.githubusercontent.com/40204217/208560782-40fdbbd4-1d4b-47c5-80e2-8ca91e820c80.png)
The filter was tested once with only water, then only lava and a completely empty filter.
The result was always the same.

By the way, these are the Ores that were not mined (beta Server):
![2022-12-17_15 18 20](https://user-images.githubusercontent.com/40204217/208561194-7cff7bcb-06ee-42b5-9d92-88128c0ecab0.png)

**Comment by Speiger** [comment]
Done. The miner will now only target fluids if they are in a way and if a pump is attached. (Rocket miner comes with cells so that is included)
Though it will still target flowing fluids by default because it causes other problems otherwise.
