### ISSUE TITLE
Bronze ore don't spawn on 1.19.2 big caves

### ISSUE THREAD

**Issue by CaVAL-EMR54** [TinyModularThings/IC2Classic#545]
The Bronze ore don't spawn on the new in big caves of 1.19.2,help

**Comment by Pollema** [comment]
It's not supposed to spawn.
Bronze, both in IC2C and real life, is an alloy made out of copper and tin.

**Comment by Speiger** [comment]
Yeah bronze ore isn't a thing. Please mix dust or use an Alloy Smelter
