### ISSUE TITLE
[1.19.2] Suggestion: Enable Rocket Miner to pump up all liquids

### ISSUE THREAD

**Issue by KennysDaywalker** [TinyModularThings/IC2Classic#548]
Many mods add liquids to the dimensions.
But Rocket Miner can currently only pump out lava and water.
It's a shame about the lost resources. It would therefore be advantageous if the Rocket Miner could pump out liquids like the Ranged Pump.
If you need the imeges for the different cells I would gladly volunteer.

**Comment by Speiger** [comment]
I do have an idea @KennysDaywalker but you will hate me  for it.
And before you asked, we didn't even mention said idea so its blind for you.

Note that any problems this causes with your setup will be solely blamed on you.
Keep that in mind >:)

**Comment by Speiger** [comment]
And done... Took a lot longer then expected, but implemented
