### ISSUE TITLE
the version 1.19.2 add 'optfine' mod will report error 'bootstraplauncher targets' and go bad

### ISSUE THREAD

**Issue by Eustiya** [TinyModularThings/IC2Classic#553]
many people also have this problem. I will tell you on their behalf

**Comment by Speiger** [comment]
@Eustiya i am sorry but the asshole of optifine dev has burned every single bridge to gain support from my side years ago.
If you use optifine and it works that is fine by me but if it doesn't work I don't really care anymore.

Report it to him and hope he fixes his mod and makes a public release in a year.

Anyways closing

**Comment by Speiger** [comment]
Small note for everyone else.
If you need performance mods use the "lithium/sodium" ports of forge these work fine with ic2classic and I use them personally too.
There is alternatives out there that don't suck like optifine.
