### ISSUE TITLE
Rocket Miner

### ISSUE THREAD

**Issue by OzzyFox** [TinyModularThings/IC2Classic#554]
I have place Rocket miner at ocean's surface on the block with career scanner, it dig some of my blocks that i have placed under it, show me with red one of water blocks (i didn't put in it any cells) and it flew away. 6 hours and it still doesn't get at home location. It was fully charger 7,5m EU crystal. It have chunk loader too and i have checked all my small dynmap, there is no new halls in my world (in world dimention). How i can find it and bring it back? It has Remote with right coordinates of home location.

**Comment by Speiger** [comment]
Sorry for the long delay.
@OzzyFox the rocket miner can only mine fluids if cells are provided. That is intentional.
Before this coming patch it would mine all fluids in its targeting range.
Now it will no longer do that and use Cells more efficiently.
