### ISSUE TITLE
[1.19.2] Diamond dust has no tag

### ISSUE THREAD

**Issue by SuperPypok** [TinyModularThings/IC2Classic#558]
Diamond dust from IC2C has no forge:dusts/diamond tag, which leads to incompatibilities in crafting recipes with other mods that have the same item.
And people creating modpacks need to fix this bug themselves through CraftTweaker. By doing some ridiculous lines of code in the ZS file.
(Sorry if I sounded rude to you.)
(DeepL translate)

**Comment by Speiger** [comment]
@SuperPypok that is intentional.
Not a bug.

The reason being: IC2Crops can mass produce diamond dust, if that was compatible it would break a balance like crazy.
If they want to add compat just make a datapack that adds them to said tag.
But by default this won't be a thing.

**Comment by SuperPypok** [comment]
@Speiger
I get it, I'm just very bad at IC2 and didn't know that.
By the way, why in that recipe can not be prescribed: ic2:diamond_dust, and do not add a tag? So that the machine can only produce dust from ic2, not affecting the same dust from other mods, but there was a tag.
These actions can still untie the hands of people who create modpack. CraftTweaker code will become less, and people will choose: to leave the production of dust only from ic2 or prescribe a tag and complicate the crafts, thereby making modpacks more interesting. (By "CraftTweaker code will become less" I meant the code that writes the user himself using CT in the ZS file).
And if all that I described earlier, it is still impossible to implement. Then can you please advise: how to make such datapack? 
(DeepL translate)

**Comment by Speiger** [comment]
@SuperPypok 
> I get it, I'm just very bad at IC2 and didn't know that.

That is fine. You don't have to know that. Crops are a bit obscure to some.


> By the way, why in that recipe can not be prescribed: ic2:diamond_dust, and do not add a tag? So that the machine can only produce dust from ic2, not affecting the same dust from other mods, but there was a tag.

Outputs have to be predefined. In other words: You are supposed to be specific and not provide a List of the same thing.

> These actions can still untie the hands of people who create modpack. CraftTweaker code will become less, and people will choose: to leave the production of dust only from ic2 or prescribe a tag and complicate the crafts, thereby making modpacks more interesting. (By "CraftTweaker code will become less" I meant the code that writes the user himself using CT in the ZS file).

For outputs you need to provide "Specific" elements. But for inputs you can say "any of these items" and that is what a "Tag" is.
For example: You can say: "Any Log" or "Any Plank" and if you add ic2c's diamond dust to said tag you can say "Any Diamond Dust" as a "input"

If you want to know how to do it in DataPacks, here is minecrafts wiki [Article](https://minecraft.fandom.com/wiki/Tag)

**Comment by SuperPypok** [comment]
Okay. Thanks for the explanation! And thanks for the link to the guide!
