### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by suiheng** [TinyModularThings/IC2Classic#560]
![image](https://user-images.githubusercontent.com/81475218/211250153-4b2187de-ce5f-4c64-b376-f0d1497e72f7.png)
log:
client:
[debug.log](https://github.com/TinyModularThings/IC2Classic/files/10370746/debug.log)
server:

[debug.log](https://github.com/TinyModularThings/IC2Classic/files/10370748/debug.log)

I made sure I checked everything，if only add ic2c it will be like this.

**Comment by Speiger** [comment]
@suiheng Looks like your client/server is viewed as a vanilla instance and rejecting the connection.
I am using the standard forge tutorial for any mod that has networking. This isn't a ic2c bug.
