### ISSUE TITLE
Incompatability with Crayfish Gun Mod

### ISSUE THREAD

**Issue by rrusciguy** [TinyModularThings/IC2Classic#562]
After updating CGM to 1.3.1, the client begins crashing with an error mentioning IC2C very early in the stacktrace, not sure if this is on their end or an effect of the "PackHack" mentioned.
MC 1.19.2
Forge 43.2.3

IC2C 2.0.2
[crash-2023-01-11_09.08.42-client.txt](https://github.com/TinyModularThings/IC2Classic/files/10393134/crash-2023-01-11_09.08.42-client.txt)

**Comment by Speiger** [comment]
Fixed in the latest update that comes in a couple days.
