### ISSUE TITLE
[1.12.2] Can't create path blocks with drill on grass blocks

### ISSUE THREAD

**Issue by xJon** [TinyModularThings/IC2Classic#564]
Unlike a normal shovel; not sure why not :P

**Comment by Speiger** [comment]
Duplicate to #479 .
I get why people think it's a good idea.
But it won't be happening.
So please don't take this offensively.

@xJon I hope you don't mind.

Tldr: doesn't really make sense to use that drill for this kind of thing and the accident potential is imo to big.

**Comment by xJon** [comment]
Oh I see, if it's by design then no worries. But are you aware it can make path blocks on dirt (not grass)?

**Comment by Speiger** [comment]
@xJon i looked into the code and its not implemented by me.
This could be due to another mod.
