### ISSUE TITLE
[1.12.2] Sound system crashes

### ISSUE THREAD

**Issue by xJon** [TinyModularThings/IC2Classic#565]
Have been experiencing crashes when changing output device:
https://mclo.gs/eCR4oAm
https://mclo.gs/Id8ezKt
https://mclo.gs/nPPJKDf

**Comment by Speiger** [comment]
thank you will be addressed in the next patch.
Though might take a few weeks since a few other projects take priority at the moment or are pending a high priority very soon.

**Comment by Speiger** [comment]
should be fixed
