### ISSUE TITLE
[1.12.2] Fighting with nano saber + nano shield?

### ISSUE THREAD

**Issue by xJon** [TinyModularThings/IC2Classic#566]
I might be misusing it, but it seems impossible to use this combo, because when holding a nano saber right click toggles it rather than block with a shield.

**Comment by Speiger** [comment]
Ok going to port the 1.19 change to 1.12
Right click to activate, and alt + Right click to deactivate.
Activation should be Trivial because if you are in a surprise combat section you don't want to remember the key combo, right click should just work.

Again a few weeks before this comes though.

**Comment by xJon** [comment]
@Speiger Could you add the alt + right click to deactivate to the shift tooltip? Right now it's unclear
