### ISSUE TITLE
Slowness upgrade not accepted by every machine?

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#567]
So i tried to use the slowness upgrade for my induction furnace and rotary macerator, but it won't go into the slot.
Non of my machines accept the upgrade, except the refinery.

Edit: Seems to affect the advanced machines only. The overclocker isn't accepted either.

**Comment by Speiger** [comment]
Advanced machines do not accept speed modifiers in general.
You get a crazy efficient speedup but lose the ability to over/underclock.
