### ISSUE TITLE
[1.18.2/1.19.2] PackHack$CustomResourcePack assumes resource is ".json" in `hasResource`

### ISSUE THREAD

**Issue by MrCrayfish** [TinyModularThings/IC2Classic#569]
I've had a report that mentioned this mod is causing a load issue.
https://github.com/MrCrayfish/MrCrayfishGunMod/issues/419

From some quick investiagting, it seems any file that is not a `.json` in `"models/item"` will cause an IndexOutOfBounds exception.

**Comment by Speiger** [comment]
Already fixed in the latest patch that is being tested atm.

**Comment by Speiger** [comment]
@MrCrayfish i am closing the issues when a patch is out. So leaving this open.

Patch should come out in a couple days.
Just giving a bit of time for testing if everything was properly fixed and give translators the time to self credit.
