### ISSUE TITLE
Painters

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#57]
They work, and do split the cables EU wise, but once painted they require a block update to update the cable that's just been painted.
![2015-06-06_14 22 33](https://cloud.githubusercontent.com/assets/4021725/8019780/17ae0e22-0c58-11e5-87b6-7d772eba8b88.png)
![2015-06-06_14 22 43](https://cloud.githubusercontent.com/assets/4021725/8019781/18a711ca-0c58-11e5-9f9c-e35cbc113c2a.png)

**Comment by Speiger** [comment]
Missing blockUpdates from the Painters. Ok Will be processed when i am back..

**Comment by Speiger** [comment]
Fixed. Now when the EnergyNet Changes it causes now blockupdates on the changing block and the sorounding ones too..
