### ISSUE TITLE
Shift+Alt+X turn on mob visor for all players

### ISSUE THREAD

**Issue by OzzyFox** [TinyModularThings/IC2Classic#571]
Shift+Alt+X turn on mob visor for all players
I manually turn on this at my player (quantum armor + head HUD update)  but my friend visor is turn on/off too
We both have same HUD upgrades at helmets

**Comment by Speiger** [comment]
@OzzyFox yes that is intentional.
Even the large scale stuff is visible for everyone.
So not a bug.

**Comment by Speiger** [comment]
yes
