### ISSUE TITLE
Pumps Still Need Work

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#58]
Even with the latest version, they replicate fluids from flowing blocks, and don't fill buckets :(
![2015-06-06_15 07 47](https://cloud.githubusercontent.com/assets/4021725/8019906/0f136860-0c5e-11e5-9268-43e4bc734555.png)
![2015-06-06_15 07 49](https://cloud.githubusercontent.com/assets/4021725/8019907/0fb5f31e-0c5e-11e5-9c0d-20e9009d7cea.png)

**Comment by Speiger** [comment]
Ok. Todo list, when i am back.

**Comment by Speiger** [comment]
@Chocohead tested. And you are partly right and wrong. First he drains only fluids that are full blocks.
Flowing blocks are no longer counting and it also only drains the block on the bottom. I will add later a flowing searching mechanic with a little range... But for now its invalid. (With sourceBlocks it only works)
