### ISSUE TITLE
when using IC2 clasic book looking up recipes and pressing R or U will crash you 1.19.2

### ISSUE THREAD

**Issue by IchigoGames** [TinyModularThings/IC2Classic#580]
Crashing when looking up recipe in IC2 Clasic book using jei pressing r or u when looking at any recipe will crash your clint both in server and singleplayer but will not crash server. i dont know if this is a jei issue or just a ic2 clasic issue.

Minecraft 1.19.2
Forge 43.2.3
jei-1.19.2-forge-11.5.2.1000
IC2Classic-1.19.2-2.0.2

https://gist.github.com/IchigoGames/7eae0cd7d6a8343de0cc481434ac9c65 crash report

**Comment by Speiger** [comment]
Fixed in 2.0.3 which released 7h ago

**Comment by IchigoGames** [comment]
saw that thanks i forgot your the ic2 clasic dev lol

**Comment by Speiger** [comment]
No worry I hope you guys are doing well.
