### ISSUE TITLE
Tube configurator and request tube

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#584]
I am trying to automate some stuff and noticed something.

Tube configurator with extraction tube redstone control setting:
Right clicking on extraction tubes (and filtered) works, they also work like intended.
It shows which setting is applied in chat (enabled/disabled).

Then i noticed i can click with the same mode on request tubes.
When clicked with configurator, it always says redstone control enabled in chat, no disable message.
When the request tube is activated that way, it won't request if redstone is on.
The problem is, when redstone is turned off again it won't start requesting again.
It will only start requesting again, if i click it with the tube configurator again.
Kind of like a "single use turn requesting off forever" :D

Another fun fact: If you play around to much with it (clicking on request tube with tube configurator and randomly applying redstone), it will stop requesting some stuff that it has in it's list (in my case 2 out of 5 items). That's the moment i had to destroy the tube and set it up again.

My test setup is very simple:
chest---provider tube---tube---request tube---chest

I don't know if the request tube should even react to the tube configurator/redstone, but it would be a cool feature.

**Comment by Speiger** [comment]
Yeah this sounds like a bug that you can't disable stuff.

I will address it in the next patch.
But that eta is weeks away since I do love to do bulk patches.
Leaving this open so I won't forget
