### ISSUE TITLE
*-O-Mats + Personal Safes

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#59]
Using a Trade, Energy or Fluid-O-Mat with a Personal Safe allows it to read what is in the inventory stock wise, so it can pull it out when it is sold. It does not however put the payment in, so it is voided. I tested to see if they were just generally broken, but they work fine with normal chests.

**Comment by Speiger** [comment]
ok, i know why it is happening. It is because of the IInventorySupport that IC2 Classic has now.
As said: fixing when i am back.

**Comment by Speiger** [comment]
Fixed. Dirty but it is fixed...
