### ISSUE TITLE
[1.19.2] Wearing jetpacks reducing MC perfomance 

### ISSUE THREAD

**Issue by JohnnyAnakonda** [TinyModularThings/IC2Classic#590]
Every single active item, which have mini GUI [e.g jetpacks] on Bottom Left screen, is reducing my own FPS from 140-180 to 54-65 FPS. On my screenshots you can see my FPS with wearing jetpack and without jetpack. Also, if you gonna hiding your GUI by pressing F1, your FPS is gonna be stable until u return GUI back
![2023-01-22_11 28 05](https://user-images.githubusercontent.com/64531380/213907398-a8d923d5-604c-466c-be39-88d0df60dc16.png)
![Inked2023-01-22_11 27 54](https://user-images.githubusercontent.com/64531380/213907404-e74f8e44-4e40-4623-9b68-4829440ed2d7.jpg)

**Comment by CrossVas** [comment]
Check this one: 
https://github.com/Trins-mods/Gravisuit-Classic-Edition/issues/26
Should have less impact on mc performance (I hope 👀)

**Comment by CrossVas** [comment]
Maybe it was a bad idea to check for IC2Classic's armor when displaying info 🤔
I feel sorry about that.

**Comment by Speiger** [comment]
@JohnnyAnakonda not IC2Classic issue.
Also if you open and close issues like that again i am issuing a perma ban.

**Comment by Speiger** [comment]
@CrossVas thank you for solving this one for me.
Hope you are doing well.
