### ISSUE TITLE
Water/Lava Cell crafting recipe

### ISSUE THREAD

**Issue by Christofmeg** [TinyModularThings/IC2Classic#596]
Add back these crafting recipes?

Suggest using ic2:empty_cell and forge:buckets/water
![image](https://user-images.githubusercontent.com/4357405/215182066-d9fcf467-9e7e-42d2-acdd-e00d8285feda.png)

Suggest using ic2:empty_cell and forge:buckets/lava
![image](https://user-images.githubusercontent.com/4357405/215182248-584d5553-20ff-42e3-bb20-36310cc962cb.png)

**Comment by Speiger** [comment]
why? You can fill and drain cells with any fluid container if so wished.
These recipes were only there for modcompat.

**Comment by Christofmeg** [comment]
It would be nice to have, when other mods adds custom buckets.  Also the reversed recipe, with water cell and empty bucket = water bucket.

You can close this issue, if you see no further action needed :)
