### ISSUE TITLE
[1.19.2] Block tags added to all items

### ISSUE THREAD

**Issue by Christofmeg** [TinyModularThings/IC2Classic#598]
IC2Classic-1.19.2-2.0.3

All items seem to be added to these block tags:

minecrat:bee_growables
ic2:flowers
minecraft:crops
minecraft:parrots_spawnable_on
ic2:flat

Could be another mod. Don't know for sure yet.

![2023-01-28_09 10 48](https://user-images.githubusercontent.com/4357405/215254990-439bab97-8fb3-443b-aabc-cb3e69173e7a.png)

**Comment by Meduris** [comment]
I just checked with the same IC2 Clasic version, using the modpack we had for beta testing, and the only tags I get on e.g. the Diamond sword are:

forge:tools
forge:tools/swords

![grafik](https://user-images.githubusercontent.com/15174539/215271458-f44b9502-39f1-43d1-a429-c19d4395a4d0.png)

**Comment by Meduris** [comment]
could you provide an actual mod list, considering you seem to have quite some mods installed judging by the amount of pages in jei

**Comment by Meduris** [comment]
ok, I just checked, but the only thing we do is as following:

everything that already has a vanilla minecraft:flowers or minecraft:crops tag gets the ic2:flowers tag
ic2:flat has similar conditions, so the main culprit should be whichever mod adds the minecraft:crops tag to those items.

If it bothers you, I would suggest trying to reduce the number of mods to figure out which one actually adds the minecraft:crops tag etc to items and check wether removing that also gets rid of the ic2:flowers and ic2:flat tags on those items

**Comment by Christofmeg** [comment]
I tested myself and confirmed with a fresh install, and as you said ic2 is not guilty. Closing issue here, I will find the perpetrator
