### ISSUE TITLE
Can't turn a monitor so that the screen faces the top side.

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#599]
I can manually place the monitor to face up, but not rotate it with a wrench to the top (not even with wrench+shift).
When placed facing up, the text is only readable when the player is looking south (not invisible, just upside down text wise)

**Comment by Speiger** [comment]
@Shizz00 not a bug.
The Upwards facing would be limited to 1 direction and you would not be able to change it.
If that facing isn't compatible I would have to implement a 24 axis rotation which I am not interested in and causes a lot of problems in the back end.

This is a intentional limitation.
