### ISSUE TITLE
How do you get the steam out of the colossal Recycler?

### ISSUE THREAD

**Issue by Grievous7** [TinyModularThings/IC2Classic#603]
I know this isnt a wiki, but i dont know where else to ask. 

I am able to get water into the Recycler, but cant get the steam out of it. I dont knwo what tubes/pipes to use, and where to put/use the steam. what i tried didnt work and i dont know what to do. 
Help would be appreciated :)

Game version: 1.19.2
Mod version: 2.0.2

**Comment by Speiger** [comment]
@CrossVas @Grievous7 fluid pipes can also be set to "extract" fluids.
You don't require a electric fluid pump to do so.
(Just click on the Fluid Pipe when it is connected to a fluidtank of any form and then select the "extract" button, make sure the right block is selected)

But basically Fluid Pipes and or Electric Fluid Pump.
