### ISSUE TITLE
Small optical feature for super cable possible, maybe?

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#604]
When the super cable goes vertical the texture stays horizontal. Would it be possible that the lines look the same as in horizontal placing, or is that intended? [cable](https://i.imgur.com/9V10Fbd.png)

**Comment by Speiger** [comment]
This intended. This is how it looked in Minecraft 1.1 (this is a lot earlier then 1.7.10)
![image](https://user-images.githubusercontent.com/2556269/215838308-e66d629e-a77b-42d4-b394-a51c0e6fdfc5.png)

Yes this is a different texture pack but the cable is the same and a texture pack didn't have the control how the texture was rotated back then.
