### ISSUE TITLE
java.lang.VerifyError: Bad local variable type

### ISSUE THREAD

**Issue by SuperPypok** [TinyModularThings/IC2Classic#605]
While my modpack was with Rubidium, everything was fine. But when I switched to Optifine the game crashed.
By not complicated machinations I found out that the culprit for the crash is IC2.
(What exactly was I doing? I chose 10 mods and removed them from the folder mods. In one of these selections was the IC2 and after a few more tests, it turned out that this is the fault.)

Logs and CR: https://github.com/SuperPypok/fcr

(DeepL translate)

**Comment by Speiger** [comment]
Optifine isn't supported by any of my mods anymore.
I don't care if ic2c breaks optifine or if optifine fucked up.
For more info #513

**Comment by SuperPypok** [comment]
@Speiger oh, okay, got it. Sorry about that.
Some weird developer at Optifine... I mean, Twilight Forest has about the same problem.
