### ISSUE TITLE
Cropmatron with request tube won't request weedex (fertilizer works)

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#608]
[screenshot](https://i.imgur.com/DmxC1ek.png)

There are two weedex in the barrel, if the cropmatron is replaced with a chest/bulk crafter/other storage container it works.

**Comment by Speiger** [comment]
@Shizz00 most likely it can not insert the item into the required slot from the side you have picked.
Please check the "UI settings" and check if the slot is accessible from said side.

**Comment by Shizz00** [comment]
Hm, i selected the weedex slot and every side is accepted for input. Still no request.i

**Comment by Speiger** [comment]
ok ill look into it when the next update patch comes.

**Comment by Speiger** [comment]
Fixed... Yeah dumb bug...
```java
		handler.registerInputFilter(filters[0], 0, 1, 2);
		handler.registerInputFilter(filters[1], 3, 4, 5);
		handler.registerInputFilter(filters[2], 6, 7, 8); //Filters was a 1 yeah no wonder it didn't work...
```
