### ISSUE TITLE
[1.19.2] Checking recipes using JEI while reading Wiki hides the UI

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#609]
Setup: 
- Forge: 43.2.3
- IC2C: 1.19.2-2.0.3
- JEI: checked with 11.4.0.274 and 11.5.2.1007

How to reproduce: 
 - Open the manual
 - Check a random recipe using JEI
Result: the UI is hidden (like after pressing F1), the JEI and Wiki "windows" are opened in the background, so hitting Esc two times, the UI appears back. 
Also, after pressing Esc one time and then clicking with your mouse anywhere on the screen causes severe lags.

Demo: https://imgur.com/a/A4jAXKy

EDIT: 
Additional content if needed (nothing is there tho)
[latest.log](https://github.com/TinyModularThings/IC2Classic/files/10608623/latest.log)
[debug.log](https://github.com/TinyModularThings/IC2Classic/files/10608626/debug.log)

**Comment by Speiger** [comment]
ok thank you ^^

**Comment by Speiger** [comment]
Hopefully fixed (it works in dev) in the next patch
