### ISSUE TITLE
Add an Electronic circuit + an RE battery to tinkers tools to give them the electric modifier

### ISSUE THREAD

**Issue by LuigiHutch** [TinyModularThings/IC2Classic#61]
Tinkers construct tools had the ability to put an electronic circuit and an RE battery onto the tools which would give them the 'elcectric' modifier which would allow you to charge up your tools with EU.
http://i.imgur.com/Gc2v4V6.png

This funtionality was removed in 1.7 and i feel the it would be suited to be readded in by IC2 Classic.
Im not sure if this can be done but it would be great if it could be added.

**Comment by Speiger** [comment]
I will talk to the newest dev of Tinkers construct maybe i can make it happen that they add it back again...

**Comment by Speiger** [comment]
If they wont i will try to the next update to implement something. Not sure if it works^^"

**Comment by LouisHutch** [comment]
They probably wont add it on there side as they removed it as they said they dont support ic2 anymore.

I know Ender IO added there capacitor banks support for tinkers tools on ender io's side so i assume it could be done on your side but im not for certain that it can be done for EU side of things

**Comment by Speiger** [comment]
EnderIO simply supports RF things thats it.
And yeah i know that i was talking to them after it got removed and they said the reason to...
It will be properly my side who will do that... I will look up if there is any possebility to add that...

**Comment by Speiger** [comment]
The answer was quick...
Simply nope... well no problem...
I can add it myself i checked that but before i can do that i need to make some prepairations...
Also would be kinda nice if you can make some kind of vote anywere (as long as i can see it and see the results) so that i can see that there is a demaind there...
Because i know not much people who want EU on tools back...
(Also need maybe textures for that)

**Comment by Speiger** [comment]
@LouisHutch i hope that solution is ok^^"

**Comment by Speiger** [comment]
@LuigiHutch plugin is working fine... Need to fix/adjust IC2 to the new System but that should be no longer a problem...
Added. Simply

**Comment by Speiger** [comment]
Added.

**Comment by Carbon-Ghost** [comment]
I don't really play with TiCon, but gonna test that on a one use world pack ^^
