### ISSUE TITLE
[1.12.2] Splash potion of harming on QuantumSuit?

### ISSUE THREAD

**Issue by xJon** [TinyModularThings/IC2Classic#612]
Hey!
Forwarding feedback from https://www.technicpack.net/modpack/tekkit-2/discuss:
> Hey is it possible to patch potions of instant damage and bee hives going straight through the best armors in the game?

Regarding Forestry bee hives, they seem to damage a player wearing a full set of QuantumSuit (+ using Gravitation Chestplate / Ultimate Hybrid Solar Helmet) similarly to as if they were wearing nothing. This is not the case with ProjectE's Gem armor which seems to regenerate health quickly enough.

This could also be changed from vanilla/Forestry's end. What do you think?

**Comment by Speiger** [comment]
Magic damage still can bypass this type of armor yes.
