### ISSUE TITLE
Issue #1:Flux Generators only supply flux to machines that are at the north facing side of the generator. Issue #2: Flux generators sometimes do not work if the power supplied to them goes through a transformer (proper wireing, proper type of transformer). Issue #3: Flux generator can still accept EU through the flux outputting side if rotated with a wrench.

### ISSUE THREAD

**Issue by OHOgameplay** [TinyModularThings/IC2Classic#613]
Issue#1: They only provide flux to the block facing to the north. It is also not affected by the actual generator output side.
Any of the 6 sides that faces towards north will supply the flux accepting block there
![2023-02-05_21 05 47](https://user-images.githubusercontent.com/124529188/216842163-4b65509c-c878-4ef5-8d61-9f8819fa3db9.png)
![2023-02-05_21 05 59](https://user-images.githubusercontent.com/124529188/216842164-afffbc63-7185-482e-adda-a2c7c7b1577b.png)

Issue#2: Tried to reproduce, but no luck. Maybe a one time local bug.

Issue#3: If i place a generator, and connect it to a grid (connected to any of the 5 EU inputs), after rotating the block with a wrench to a point, where the flux output is connected to the EU cable, it still accepts EU, and supplies flux to a block (if it is at the north facing side)

![2023-02-05_21 12 54](https://user-images.githubusercontent.com/124529188/216842471-91eb5e75-99e9-47b5-afdd-264fc5ed55a9.png)

Normally it should not connect, like this:

![2023-02-05_21 13 24](https://user-images.githubusercontent.com/124529188/216842516-1e838daf-1f6a-4e11-a0a6-175e28750000.png)

But it connects, like this:

![2023-02-05_21 14 03](https://user-images.githubusercontent.com/124529188/216842535-33ee0173-44f5-4a07-8916-0d240711164a.png)
To rotate, i used the Crescent Hammer from Thermal Series.
The IC2 Wrench does not rotate the generator to that stage if the cable is connected.

**Comment by Speiger** [comment]
Not a classic issue since the Flux Generator was rotated with a invalid tool.
