### ISSUE TITLE
New tube maybe? One that does not connect to anything, but itself.

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#614]
Right click with wrench would let it connect with other things. (maybe disable specific sides)
Reason: parallel tubing
Name ideas: isolation tube, loner tube

 Or is this already possible somehow and im blind? No, i will not stack directional tubes, doesn't look good^^

**Comment by Speiger** [comment]
Mining Pipes, work on cable/pipes/tubes and work like anchors that prevent connections.
So not nessesary since you can plug any side you want from connecting.
Pretty sure this was also shown in the tube tutorial or EU tutorial.
