### ISSUE TITLE
Mining laser in explosive mode destroys blocks in protected chunks (ftb chunks)

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#615]
The other modes won't destroy blocks in those protected chunks.
I posted the issue on the ftb mods [github](https://github.com/FTBTeam/FTB-Mods-Issues/issues/672) first since i thought it may be a permission thing with ftb chunks, but that does not seem to be the case. Is it possible to fix this on your side?

**Comment by Speiger** [comment]
Will address this, lets see if this blows up in their faces xD
