### ISSUE TITLE
Where to look for information about mod?

### ISSUE THREAD

**Issue by razriar** [TinyModularThings/IC2Classic#616]
Hello! I have read wiki on github and wiki in game from book but both lack information. Is there any other source?

**Comment by EnderVonSlayer** [comment]
Just those two sources, more specifically the online version is for 1.12.2 and the in-game wiki is  meant for 1.19.2.

What did you have issue with/questions about?

**Comment by razriar** [comment]
Thanks for answer. I don't understand some mechanics. 
I have found discord server. I'd rather ask there.
