### ISSUE TITLE
Suggestion: add more powerful weapons.

### ISSUE THREAD

**Issue by razriar** [TinyModularThings/IC2Classic#617]
When playing modpacks with strong mobs endgame quantum armor is enough efficient, whereas nano saber feels weak.

How about adding enchantments or upgrades for nano saber or new weapons like quantum saber?

**Comment by Speiger** [comment]
@razriar the Electric Enchanter works for electric tools and their buffs still work.
New tiers. I doubt it.
That is addon Material.
But a config to rebalance it might be a good idea.

**Comment by razriar** [comment]
@Speiger Isn't it possible to make sharpness enchantment increase damage of nano saber activated mode? I think it would feel more pleasant than changing values in config.

**Comment by Meduris** [comment]
I currently don't have any plans for new weapons, but I'll have to think about it. If I have the time, I still kinda want to add more content to IC2C Additions.
