### ISSUE TITLE
Suggestion: Chainsaw mode to destroy leaves vs shearing them.

### ISSUE THREAD

**Issue by TheCanadianDane** [TinyModularThings/IC2Classic#619]
It would also be beneficial (if not currently available) to have fortune as an enchant to give more saplings from leaves on this mode.

**Comment by EnderVonSlayer** [comment]
The mowing tool is fantastic for removing leaves, highly recommend giving it a shot

**Comment by Speiger** [comment]
@TheCanadianDane we can't increase chances. But the Mowing Tool at least does what you want.
