### ISSUE TITLE
[1.19.2] Slag Generator

### ISSUE THREAD

**Issue by burymesoftly** [TinyModularThings/IC2Classic#621]
I guess its not how it should work, wiki says that it just 25% more effective than default generator
![2023-02-12_14 37 46](https://user-images.githubusercontent.com/125179011/218299487-727aaab2-770b-4e0b-9268-6750c8ab192c.png)

**Comment by Speiger** [comment]
Pretty sure you are referencing the 1.12.2 wiki for the 1.19.2 version.
The Ingame wiki says (copy pasted out of it)
```
The Slag Generator is an advanced Generator, increasing its output to a whooping 60EU/t. On top of that, it randomly outputs scrap as a side product.
```

Please ignore the Github wiki when reporting 1.19.2 issues.
