### ISSUE TITLE
Filtered extraction tube only checking normal minecraft durability value?

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#622]
I tried filtering tools with different durability values.
Tested items: minecraft: bow, ic2c: drill, building gadgets: all gadgets (they use FE/RF)

Tube setting on all items: blacklist, durability: exact damage, 100% durability on item.

The minecraft bow works like intended: A bow with 100% durability will remain in the chest, a bow with less than that not.
The other items with energy as the durability bar ignore that and won't be extracted, regardless of the amount of energy stored.
Using NBT as filter doesn't work since each drill/gadget/whatever has many different settings on the item.

**Comment by Speiger** [comment]
@Shizz00 intended this way...
Because Energy != Durability.
If you run out of energy your tool just doesn't work but it still exists.
If you run out of Durability your tool disapears.

As simple as that.
