### ISSUE TITLE
Machine access control in reactor slots behaves weird

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#623]
First off, sorry for asking so many things recently (i really try to google before asking here).

Well here we go again :)

So the machine access control behaves weird in the reactor. Once a slot is selected you can only disable it.
For it to work again even reset does not work. I have to disassemble the reactor with a wrench and place it again,
otherwise i won't be able to use that slot with a tube again. The enable/disable button just flickers when clicking it.
[Short demonstration clip](https://i.imgur.com/7U1IBM0.mp4)

**Comment by Speiger** [comment]
I am not sure how much this is a bug and into what direction.

But here is the thought process:
Reactors are a dynamic inventory and thus don't really allow much configuration. (Would break to much)
This is why that isn't really configurable.

I have to check if slot access disabling is also intended to be changed or if that is the bug.

Thanks.
