### ISSUE TITLE
[1.19.2] Alloy furnace doesn't work.

### ISSUE THREAD

**Issue by TTomeczeK** [TinyModularThings/IC2Classic#624]
I cant open AF, Cables doesnt work with AF
![image](https://user-images.githubusercontent.com/125333490/218634680-f5c23f0a-9bd3-43e1-832a-934bba1f636a.png)

**Comment by CrossVas** [comment]
There are two types of Alloy Smelter.
Regular Alloy Smelter. Regular single-block.
Pressure Alloy Smelter. A 2x2 multiblock machine.

**Comment by CrossVas** [comment]
IC2 provides several tiers for almost every basic machine.
For Alloy Smelter you have two tiers: 
 - Alloy Smelter: a standard single-block machine;
 - Pressure Alloy Furnace: a 2x2 multiblock machine.  
 
 In-game image:
![image](https://user-images.githubusercontent.com/25727222/218636437-c7a1e335-e79f-491a-9ae2-46eb9e3811ea.png)

**Comment by Speiger** [comment]
@CrossVas thank you
@TTomeczeK yeah you build the multiblock version without the multiblocks.

**Comment by TTomeczeK** [comment]
@CrossVas @Speiger 
Thank you, everithing is fine :)
