### ISSUE TITLE
Wave Generator should be considered an LV Generator in the Wiki Book

### ISSUE THREAD

**Issue by Geekerandy** [TinyModularThings/IC2Classic#628]
Currently, it is listed in the MV Generators category despite producing less than 32EU/p.
![image](https://user-images.githubusercontent.com/14936715/219848748-50cf40a8-c717-413e-a0d9-908783e7fe1d.png)

**Comment by Meduris** [comment]
This is completely intentional as the wave gen gets a huge boost in eu production during rain (20%) and thunderstorms (400%)

**Comment by Speiger** [comment]
To append to it.
The tier system is based on the progression of the mod not the production.
