### ISSUE TITLE
Fuel can needs a Damage Bar

### ISSUE THREAD

**Issue by Erik3003** [TinyModularThings/IC2Classic#63]
When using a Filled Fuel Can to power a Generator, the can isn't used and stays in the slot.
It initially should put an empty can in the slot replacing the full one.

**Comment by Speiger** [comment]
@Erik3003 does the Generator run?
If Nope then it is a bug.
Else that is new Feature it uses not all of the Fuel from the FuelCan so you can be more efficent at furnaces and have simply more fuel with you and do not use everything up^^"

**Comment by Erik3003** [comment]
Ok, it isn't a bug :D 
Could you please add a damage bar to show its fuel level?

**Comment by Speiger** [comment]
added...
