### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by Christofmeg** [TinyModularThings/IC2Classic#630]
Have you considered uploading IC2Classic to [Modrinth](https://modrinth.com/) aswell?

**Comment by Speiger** [comment]
I considered a few of my mods for modrinth.
IC2Classic wasn't one of them since i have to get permission to release it somewhere else then curseforge.
Honestly not sure about it. 

At the moment this is a no from my side.
But this can change in the future.

**Comment by millennIumAMbiguity** [comment]
As long as it is not on Modrinth or not marked with won't fix, then I believe this issue should remain open.
