### ISSUE TITLE
[1.12.2] Shooting exploding ores from some mods with Mining Laser causes crash.

### ISSUE THREAD

**Issue by Slayer5934** [TinyModularThings/IC2Classic#631]
[crash-2023-02-15_17.07.49-server.txt](https://github.com/TinyModularThings/IC2Classic/files/10777700/crash-2023-02-15_17.07.49-server.txt)

In this example shoot a nether ore from Netherending Ores in survival mode with a mining laser, the ore tries to explode and the game crashes, this is because the laser removes the ore before the other mod gets to check if it's still there.

**Comment by Speiger** [comment]
@Slayer5934 please open an issue there since all i am doing is scaning the explosive resistance and nothing else.

**Comment by Slayer5934** [comment]
Their mod has stopped development a long time ago, I suppose I can disable explosions though to get around the issue.

**Comment by Speiger** [comment]
Yeah sorry but this is nothing i can fix. Because this is a normal resistance check that explosions would do.

**Comment by Slayer5934** [comment]
Thank you for your time though
