### ISSUE TITLE
1.12.2: HEI Bookmarks misplaced

### ISSUE THREAD

**Issue by grantonthenet** [TinyModularThings/IC2Classic#632]
When using a machine from this mod, the bookmarks area (left side of screen in screenshots) is moved down.
IC2C Machines:
![2023-02-19_14 56 57](https://user-images.githubusercontent.com/116581445/219974773-e4fc604a-2f8b-4ad2-a1d8-04d2f00e0873.png)
Expected:
![2023-02-19_14 58 19](https://user-images.githubusercontent.com/116581445/219974779-4ff7339a-7209-44bf-b2b1-ae4e7628cc26.png)

**Comment by Speiger** [comment]
Yeah no. Not a IC2C issue.
Different mods had the same issue with JEI and JEI did nothing to fix it.
These mods rewrote their entire UIs for everything to make it work.

Yes I am aware its an issue but i am not doing a giant rewrite to make everything work that isn't my bug to begin with.
I am sorry.
