### ISSUE TITLE
Opening IC2 Wiki book resets your Inventory GUI settings

### ISSUE THREAD

**Issue by JohnnyAnakonda** [TinyModularThings/IC2Classic#637]
By opening IC2 Wiki book, its gonna reset your inventory GUI size on default value
![2023-02-23_22 53 30](https://user-images.githubusercontent.com/64531380/221015773-19db21d1-bcf5-4311-a988-1f4ccf26aa3e.png)
![2023-02-23_22 53 32](https://user-images.githubusercontent.com/64531380/221015782-e5dbf6f6-e63f-4322-aac9-e26a722e4e82.png)

**Comment by Speiger** [comment]
already on the list and fixed too
