### ISSUE TITLE
Suggestion: Make it possible that Nuclear/Steam Reactor with 6-chambers  are able to be activated underwater

### ISSUE THREAD

**Issue by KennysDaywalker** [TinyModularThings/IC2Classic#638]
My suggestion would be to make the Chambers Redstone receptive or a redstone repeater that can be placed underwater like in Minecraft Bedrock.

**Comment by Speiger** [comment]
Sorry no, I will not implement Minecraft parity features.
It is already possible to power reactors underwater its just a bit more tricky.
