### ISSUE TITLE
Armor protection value configuration + visual bug

### ISSUE THREAD

**Issue by Carbon-Ghost** [TinyModularThings/IC2Classic#64]
For balancing purposes for modpack makers, can you make the armor values configurable ? In %, you would be able to set the protection value for all armors except bronze ( shouldn't be touched for OD reasons and because it's balanced ), you can set values from 10% to 100% for full set nanosuit and quantum armor, mainly for balancing them so I can make nanosuit 80% like diamond, so it's basically just the same except nanosuit is energy powered, and nerf quantum to protect you only from 95% of the damage so you aren't invincible. Just small request, if you don't want to do it, I am going to try to see if I can try to do it myself ( I am pretty sure I'm gonna fail though xD ), 

Also, small visual bug time : 
- Nanosuit armor bar is supposed to be full, because following minecraft logic, any armor with 80% protection or more gives you a full armor bar, IC2 dev thought it was a good idea to give it 18 armor points to represent the 90% dmg protection but it wasn't as it can be misinterpretated and doesn't follow logic minecraft convention ;P

**Comment by Speiger** [comment]
I will not make a Config for each suit... Sorry that is simply to much config. What i can do (only brainstorming now) is make a modifier config which allow you to modify the protection of the armors (1 config for all) simply rising it increase it and lowering it makes it less. Would be the same as the oredensity config.

The Bugreport is weird. Funny but weird...
I will take a look into that.

**Comment by Carbon-Ghost** [comment]
Lol, well thx ^.^

**Comment by Speiger** [comment]
Fixed. Added. But only Nano & Quantum... Everything else stays like it should be...

**Comment by Carbon-Ghost** [comment]
NICE :D
