### ISSUE TITLE
Items like Uranium Rods can be enchanted in Anvil

### ISSUE THREAD

**Issue by JohnnyAnakonda** [TinyModularThings/IC2Classic#640]
Some items which have durablity, like Isotopic Uranium Rods, Chips rolls, cakes can be enchanted with Mending and Unbreaking inside Anvil by using Enchanted books. In my opinion its too OP, especially when u using Chips
![2023-02-24_16 27 00](https://user-images.githubusercontent.com/64531380/221190751-9942dee2-b78d-4217-9b0d-cf0441ddad8e.png)
![2023-02-24_16 27 02](https://user-images.githubusercontent.com/64531380/221190762-4d8f5474-e5b7-4a6e-bf8b-2d0f95fb3329.png)
![2023-02-24_16 28 09](https://user-images.githubusercontent.com/64531380/221190783-22c57818-17db-4572-a40f-8bd54e63a4f4.png)

**Comment by Speiger** [comment]
Not a bug.
Though Unbreaking doesn't work with uranium in a reactor. Yes all intentional.
