### ISSUE TITLE
[Request] Config option to disable soil tooltip

### ISSUE THREAD

**Issue by aaronhowser1** [TinyModularThings/IC2Classic#644]
![image](https://user-images.githubusercontent.com/15698722/221416163-ea473546-0df5-4373-ba18-f6d6b82fb541.png)

I'd rather not see this every time I hover over Dirt or Prismarine or whatever, since soil stats are important like 0.5% of the time.

**Comment by Speiger** [comment]
@aaronhowser1 how would you like to have it disabled?
Since JEI also scans the Tooltips for search queues it means if i don't show it you can't even search for it.

A config would require a WorldReload/ServerRejoin.
Also the default would be enabled not disabled if it was a config.

**Comment by aaronhowser1** [comment]
Default being enabled is totally fine. My plan would be to just have a JEI info page or something, or even just a quest listing them.

If it's possible to have it clientside and not serverside, that would be a bonus, but I'd be shipping with it disabled either way in modpacks.

**Comment by Speiger** [comment]
@aaronhowser1 
In modpacks you can have it disabled, but the wiki mentiones the tooltips existing so people will try to do so.
So if you disable it make sure people to tell to enable it when they want to use it.
Or provide a list yourself. (Note addons can add their own blocks too and it basically shows that too thanks to the searchable tooltips)
