### ISSUE TITLE
Strange behavior of request/provider tube

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#645]
I have a request tube connected to a bulk crafter. The provider tube is connected to my storage system (through some color filter tubes).
Everything works fine, but after a few days (after serveral server restarts), sometimes the request tube stops requesting stuff. In this particular case today, the request tube stopped requesting 1 out of 9 items. It just says missing. I looked into my storage... well there's still like 90k of that item (refined iron in this case). So i took out another item (cobble stone) in the bulk crafter, the tube request like normal, but refuses to restock the refinded iron. Then i took out redstone dust. After i did that, it suddenly restocked refined iron again and the bug was gone. the last time this happened, it was the provider tube. No system in my base got items from that provider tube until i destroyed it and placed it again. This happens like once a week and is not that important (to me), but i just wanted to mention it.

**Comment by Speiger** [comment]
Most likely chunk loading/unloading caused a hickup.
The Requester tubes keep any excess requests cached so they won't pop out or get lost.
That way it may can get stuck...
