### ISSUE TITLE
Fluid Import/Export Upgrade should not have a slider but manual value input for customizing flow rate

### ISSUE THREAD

**Issue by Geekerandy** [TinyModularThings/IC2Classic#647]
![image](https://user-images.githubusercontent.com/14936715/221518854-e5c7ac3e-9b86-44b0-8fa3-f295390cc7a0.png)
Having a slider like this makes it impossible to fine-tune the flow rate of a fluid upgrade to a specific value.
I request to make it into a manual value we can just enter in.

**Comment by Speiger** [comment]
@Geekerandy The scrollwheel should solve this problem.
