### ISSUE TITLE
How to brew whisky 15 and above? It seems that my JEI can't find this formula.

### ISSUE THREAD

**Issue by BeryL12138** [TinyModularThings/IC2Classic#648]
I want to get the alcohol unit, but how can I get the alcoholic drink through the machine? JEI told me that I can only brew whisky or very light wine, but I found that only whisky 15 and above can brew alcoholic beverages. Is there a bug in my game?
@Speiger

**Comment by OzzyFox** [comment]
Sorry but i dont understand how to make a wisky? Can you  explain the recipe, please?
I have try a lot of combinations and waste a lot of time, but i got only trash...

**Comment by Speiger** [comment]
@BeryL12138 You need at least beer quality brew and you need to have them at least 2 brewing stages done. (Thermometer tells you progress data)

@OzzyFox Whisky => throw in whisky grist, then throw in water cells, and then wait IRL weeks to finish.
5 weeks to get the max quality possible (IRL weeks)

**Comment by BeryL12138** [comment]
Why can alcohol only be synthesized with whisky? I see more than one formula of synthetic alcohol in JEI, but only whisky is useful. Most importantly, whisky is really hard to brew! I can't count how much time and resources have been wasted to brew whisky, and there are a lot of bugs... For example, the use of a thermometer will crash the game..
@Speiger
