### ISSUE TITLE
How to get alcohol in the machine? 

### ISSUE THREAD

**Issue by BeryL12138** [TinyModularThings/IC2Classic#649]
Why can alcohol only be synthesized with whisky? I see more than one formula of synthetic alcohol in JEI, but only whisky is useful. Most importantly, whisky is really hard to brew! I can't count how much time and resources have been wasted to brew whisky, and there are a lot of bugs... For example, the use of a thermometer will crash the game..
  I love this mod very much.However, there are many bugs in this module. I hope the author can fix these problems in future versions. It is worth mentioning that the wiki has not been updated for a long time, and some formulas can not be found (such as the synthesis of wood and gas). I hope the wiki can explain what the hidden formula really means, and I hope this module can become better and better.
@Speiger

**Comment by Speiger** [comment]
It can also be created from beer mugs.
Beer mugs need at least some hops to be included and you need at least a decent beer / wheat ratio and let it brew for a an hour max and then you get a bit out.

> For example, the use of a thermometer will crash the game..

OK, WHY don't you report it the moment it happens.
Why wait until the hour after i released a patch?

> It is worth mentioning that the wiki has not been updated for a long time

The Github wiki is only for 1.12
for 1.19 you need the ingame wiki.

> and some formulas can not be found (such as the synthesis of wood and gas)

Hidden formulars? Where?
What about: Throwing 1 log in and then pumping out the woodgas into a tank.
Now you have the exact fluid amount you have produced.

Or even better: The EU Reader shows you more UI data when you have it in your helmet/hotbar.

Also there won't be a patch for a few weeks now or longer if no new reports come in.
You reported this a few hours AFTER i made the patch.

Thanks.
The question was answered.
