### ISSUE TITLE
There's no rubber tree nowhere.

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#65]
In the latest version (1.0.9.10), I searched while flying in creative mode above few forests and I dind't see any rubber tree. The config "enableWorldGenTreeRubber" is well set to "true" in the IC2.cfg.

**Comment by Speiger** [comment]
Ok i will check that as soon as i can.

**Comment by Speiger** [comment]
Fixed.
Also supports now FakeAirBlocks (like those from Railcraft)

**Comment by ExDomino** [comment]
Now, I'm just waiting the next upgrade to see this big bug corrected. Unable to play until.
