### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by BeryL12138** [TinyModularThings/IC2Classic#650]
![@I`I33@NKDB2X6M7JBT7%V5.png](https://user-images.githubusercontent.com/126538334/222765034-1ea9be55-8ea4-43bd-b361-4bf4800ea516.png)

**Comment by Speiger** [comment]
0 * 0.45 => 0

**Comment by BeryL12138** [comment]
> 0 * 0.3 => 0

？？？？？I don't understand.
I'm going to cry.

**Comment by Speiger** [comment]
Fuel Filling is a accumulative job.
Basically you start with 0 fuel, then the first item gets added. That adds fuel.
And after that you can use the % increasing ones because you need to start with a + one.
Because they are added after each other.

**Comment by BeryL12138** [comment]
> Fuel Filling is a accumulative job.
> Basically you start with 0 fuel, then the first item gets added. That adds fuel.
> And after that you can use the % increasing ones because you need to start with a + one not with a multiplier.
> Because they are added after each other.

In fact, I did as you said, but it still didn't work. The fuel tank can't be put into this machine (I'm sorry I asked a lot of questions recently, but I really like this mod)

**Comment by Speiger** [comment]
@BeryL12138 
https://user-images.githubusercontent.com/2556269/222790226-e71207a2-c433-40ec-86fe-0edd1deaddf8.mp4

**Comment by BeryL12138** [comment]
> @BeryL12138 
> https://user-images.githubusercontent.com/2556269/222790226-e71207a2-c433-40ec-86fe-0edd1deaddf8.mp4
> 
> 

thanks！（crying）

**Comment by Speiger** [comment]
@BeryL12138 no worry :)
