### ISSUE TITLE
Why is this recipe invalid?

### ISSUE THREAD

**Issue by BeryL12138** [TinyModularThings/IC2Classic#651]
![7485352d2661b39a.jpg](https://user-images.githubusercontent.com/126538334/222881166-e4f9719e-06db-43bf-ac91-2d0a4e6f5401.jpg)

![5bce96a7cec874e2.jpg](https://user-images.githubusercontent.com/126538334/222881169-716cc5be-6ca1-4486-9d71-58c129b63225.jpg)

@Speiger 
Suggestion:Make the formula of alcohol more diverse and easy to obtain  ：）

**Comment by Geekerandy** [comment]
What kind of alcohol is it?

**Comment by Speiger** [comment]
@BeryL12138 no need to ping me, opening an issue will ping me automatically.

About your question:
What is the brew named?

**Comment by BeryL12138** [comment]
> @BeryL12138 no need to ping me, opening an issue will ping me automatically.
> 
> About your question:
> What is the brew named?

It calls Watery Soup Brew.Strangely, there is a real recipe for alcohol in JEI

**Comment by BeryL12138** [comment]
> What kind of alcohol is it?
> 

Watery Soup Brew

**Comment by Speiger** [comment]
> Watery | Soup | Brew

Format: Alcohol Level | Solid Level | Brew

-  Watery: No Alcohol in it.
-  Soup: A bit of wheat in it.
- Brew: Quality is lowest quality.

What you need at minimum is: 
Normal | Any | Brew

I will fix the refinery soon so it lists all the "valid" inputs for beer.

**Comment by BeryL12138** [comment]
> > Watery | Soup | Brew
> 
> Format: Alcohol Level | Solid Level | Brew Quality/Time
> 
> -  Watery: No Alcohol in it.
> -  Soup: A bit of wheat in it.
> - Brew: Quality is lowest quality.
> 
> What you need at minimum is: 
> Normal | Any | Brew
> 
> I will fix the refinery soon so it lists all the "valid" inputs for beer.

It is worth mentioning that I have tried almost all kinds of brewing and can't extract alcohol, except whisky. Besides, when I drink whisky, there will be a lot of mistakes in the game.（upset）

**Comment by Speiger** [comment]
well since you don't throw in "HOPS" into the barrel ofc you can't have alcohol in it.
And the brew time you have to wait a few hours...
@BeryL12138

**Comment by BeryL12138** [comment]
> well since you don't throw in "HOPS" into the barrel ofc you can't have alcohol in it.
> And the brew time you have to wait a few hours...
> @BeryL12138 

Well, I just tested that some beer can extract alcohol, but JEI can't find it. The problem has probably been solved. Next is how to get hops. I really don't know anything about agriculture

**Comment by Speiger** [comment]
Read the wiki.
Its breed via crop breeding. Rest is up to you.
