### ISSUE TITLE
IC2 Classic-EU Reader-The One Probe viewing Machine Progress max time display issue

### ISSUE THREAD

**Issue by Geekerandy** [TinyModularThings/IC2Classic#653]
The maximum amount of Progress time an IC2 Classic machine can display in The One Probe seems to be capped at one million ticks (833 minutes)
Attached video demonstrates a macerator recipe added by a datapack with an energy_mod of 4320, then 2510 to be just above one million ticks, and 2400 to be right under one million ticks.

Datapack used with "energy_mod:4320":
[carbonfiber.zip](https://github.com/TinyModularThings/IC2Classic/files/10891003/carbonfiber.zip)

Video demonstration:
https://youtu.be/DZeqfaBjkkA

**Comment by Speiger** [comment]
OK so it is a one probe issue.
Good to know I will look into that.
