### ISSUE TITLE
[1.19.2] Thermometer crashes game/server upon using on a barrel

### ISSUE THREAD

**Issue by TakeyuTaken** [TinyModularThings/IC2Classic#657]
Since i stumbled upon this issue while dabbling into brewing and i could only find vague mentions of it:
Upon using the thermometer on a barrel, it crashes the whole game or server. Checking a reactor works fine.

Crash report: https://mclo.gs/kt8PerS

P.S. Really great job with this mod, we are having a blast. :)

**Comment by Speiger** [comment]
@TakeyuTaken manual hotfix for yourself:
Install "The One Probe" there is a unintentional Dependency to that mode with the right click action.
Will be addressed in the next patch.

**Comment by TakeyuTaken** [comment]
Crash is fixed, but no clear content display.

![2023-03-20_19 39 28](https://user-images.githubusercontent.com/127440647/226436267-2e4afe11-e62e-4fc5-a834-d113eba03f33.png)

Barrels still work with The One Probe installed, so it's just the resolving.
