### ISSUE TITLE
Please turn on and off the nano saber via the right mouse button without ALT

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#659]
Please turn on and off the nano saber via the right mouse button without ALT

**Comment by Meduris** [comment]
requiring ALT for turning it off is completely intentional as you would not be able to use it together with shields otherwise.

**Comment by MrJorman** [comment]
> requiring ALT for turning it off is completely intentional as you would not be able to use it together with shields otherwise.

hmmm, logical..

**Comment by Meduris** [comment]
we initially (I think even including the 1.10 and 1.12 version) did not require the ALT key for disabling it but later added that for exactly that reason

**Comment by MrJorman** [comment]
> we initially (I think even including the 1.10 and 1.12 version) did not require the ALT key for disabling it but later added that for exactly that reason

ok bro. good.
