### ISSUE TITLE
[Idea] Nuclear Generator (with uranium, no risk, generates low power)

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#66]
My idea is a new generator that works with uranium gem directly, produces low power, expansive to craft and without any risk of explosion. Usefull for new bases (* see below) that you can mine uranium directly and put them into the generator in order to produce a bit of energy. The production have to be really low, something like 5 EU/t, so you can use tin cables and later, the fact of making another source of energy in addtion is still useful. Of course, one uranium lasts for a long time. ^^ But the whole thing has to be less effcient than a true nuclear reactor, of course.

* * You have to craft the generator in your old base and bring it with you, because it would needs some tier 3 materials in the recipe, like an advanced electronic circuit, maybe a lapotron as well.

**Comment by Speiger** [comment]
@ExDomino i know it is not the same, but you are suggesting something like the RTG Generator from Exp right?
I do not really know what i should think about that idea. It reminds me of the really old Reactor mod^^.

**Comment by ExDomino** [comment]
The RTG Generator is too OP, because it produces 32 EU/t without any fuel, even if its composantes are long to obtain, but yes my idea is inspired from it.

**Comment by Speiger** [comment]
I know why they are op. So lets talk about details (because this is the reason why it does let me not know what to think about).
The Energy Production would be max 5 EU. How much fuel does it max have? How much fuel do you gain per Uranium (Maybe rod because it uses 1 cell which is easy to craft)? How fast should it produce (every tick or every second?)

**Comment by ExDomino** [comment]
This generator would produces the same kind of energy that if you put a single uranium rod into a nuclear generator, so according to IC2ReactorPlanner, an uranium will produces 5 EU/t and lasts 2 hours, 46 minutes and 40 seconds, so 1 000 000 EU will be produced from it. But explained like that, my idea is completely useless, you can bring a nuclear reactor with you and this config is without any danger I think. The important fact here is that unlike real nuclar reactor, you will not wast any energy if you don't have enough storage to store the whole 1 000 000 EU produced from one piece of uranium and the generator consumes uranium directly, not need of rod. ^^

That generator would have an option to prevent the waste of uranium, the same option I suggested for the coal generator that consumes an uranium only if its buffer is full. Of course, its buffer is 1 000 000 EU, so it needs a Lapotron crystal in the recipe.

**Comment by Speiger** [comment]
Well i would say the buffer is 100k EU and the total EnergyGain (5 EU production) is 100k EU. So that Nuclear Reactors are not useless and the Better way to use.
Because setting up a save 60 EU generator is realtivly easy....

**Comment by ExDomino** [comment]
I'm not agree with that because in a nuclear reactor, if you put 1 uranium only in the reactor, it will produce 1 000 000 EU in total, but it's the less efficient design. If you put 2 uranium side by side, they will produce 4 000 000 EU at 20 EU/t, so 2 000 000 per uranium. The datas I sent you (5 EU/t for 1 000 000 EU in total) are really from the worst ever possible reactor design that exists. If you decrease that to 100 000 EU only, nobody will use the generator, because you lost 90% the energy that an uranium can provide you, and when I say 90%.

**Comment by Speiger** [comment]
Ok. Good reason not to do it. But a downside have to be there if you use it. (Not critical but something that say i can not use that for infinite power gen (placing infinite of them))

**Comment by ExDomino** [comment]
The downside is that it needs uranium as fuel and it doesn't provide as much energy per uranium than a true nuclear reactor does, and it only produces 5 EU/t. A true reactor will always provide more energy thant this simple generator. And, I would say that solar panels are already a better way to produce a lot of energy. You put, for example, 40 of them and you have 40 EU/t during the day, without any fuel. ^^ Use a bed each night and it will almost never rain. XD With the mod Advanced Solar Panels, they produce as well during the night, it's a reason why I hate that mod.

**Comment by Speiger** [comment]
Maybe a cooldown or something? Or it sends only big packets?
Well a reactor produces 10. But that requires a little coolant...

**Comment by Speiger** [comment]
by the way anything that is now suggested will be implemented after the next update. (I do not have much time to make more then i did already plan)

**Comment by ExDomino** [comment]
If you at least fix the bug of rubber trees that don't be generated, it's good.
And you implemented all of my other ideas: EasyMode and BatteryBox.

**Comment by ExDomino** [comment]
Sorry, miss clicked.

**Comment by Speiger** [comment]
Yeah, the BatteryBox was a way to prevent me to implement a BatteryStation and a ChargingBench, because it is both...

**Comment by Speiger** [comment]
Accepted (from my side). Reason. If you need a smal but constant amount of power to keep something running (a solarpanel alternative) you can use that one. But you gain not 100% of the rod out of it.
You gain 90%. reason? You can put in uranium only but also Uranium rods and the multiplyer of the rods will change the Max Created Power... Other thing is that this generator will consume the fuel first before it generates (Nuke does uses it while it is producing).
That are my requirements...

Also it is joining the update after this one and then there is still a vote...

**Comment by ExDomino** [comment]
You have the last word, but remember that 90% is 900 000 EU, 100 000 EU is only 10%. And 1 000 000 EU produced by a true reactor is the worst reactor design that never exists. You will always produce minimum 2 000 000 EU or 4 000 000 EU from an uranium with a good reactor, so you already lost 50% to 75% of the uranium energy potential with only 1 000 000 EU. And don't forget that it only produce 5 EU/t. With a true reactor, you can easily produce up to 420 EU/t. (more powerful is possible but dangerous and good designs are hard to find)

**Comment by Carbon-Ghost** [comment]
Honestly, I really don't see any utilities to this micro RITEG, except if it will work with plutonium with a 100% rate, so it's actually worth it, and plutonium will only be able to be produced with a normal reactor.

**Comment by Speiger** [comment]
@Carbone-Ghoest,
maybe you do not know time build ideas,
but for example i builded a Scrap Box machine if you remember?
(I showed pictures of it),
and that eated only 1 Eu in idle mode and 15 EU in active mode.
So i made clockbased system so that i produced enough for myself and not overdone it with EU Production. And i did wanted to do it with Survivalist generators^^" did not work.
This generator would be ideal for it. You can build small things with it that do not eat that much power over time^^"

Example: Vaygrim Chance has a forgecraft base that did run on 40 RF per tick (passive power) and even stable xDD,
So in eu counted it would be 10 EU (1EU = 4RF) so he would needed two of these generators and everything would be fine xDD

The idea that you can put in plutonium for a longer powergen and 100% powergain is not so bad. That could be a addition to this generator.

**Comment by Carbon-Ghost** [comment]
Are you talking about Vaygrim's passive heat generators or RITEG ( which BTW if he builds some, I totally missed this episode ) ? xD

**Comment by Speiger** [comment]
He used these Pasive Thermal Generators from Imassive Engineering which produce each 20 RF per tick with a uran block and water block.. Its his ForgeCraft series...

**Comment by Carbon-Ghost** [comment]
Yeah that, wonder what would have happened if he used cryotheum and pyrotheum xD

**Comment by Speiger** [comment]
Well No clue but i like that his base is so efficent that it can run with 40 RF. Something that direwire can never achieve xD

**Comment by Speiger** [comment]
Decided against that for now...

**Comment by Speiger** [comment]
Closing
