### ISSUE TITLE
When using ic2c shields the Swing animation plays

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#661]
When I use shields from IC2, there is a click event, the shield does not work like in vanilla minecraft. Remove the click event, please.

**Comment by Speiger** [comment]
what is the "clickevent" you talk about?

**Comment by MrJorman** [comment]
When you activate the shield with the right mouse button, a click event occurs

**Comment by MrJorman** [comment]
https://youtu.be/yQeJ97gvyEg see video

**Comment by Speiger** [comment]
Fixed your issue so it represents what the actual issue is.

@MrJorman please talk to a random person before you report issues and try to explain to them what the issue is without showing them.
Because currently this is like really exhaustive to deal with you.

**Comment by MrJorman** [comment]
> 

Sorry, I want to bring IC2 to the ideal.
