### ISSUE TITLE
The nano shield does not lose energy.

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#663]
The nano shield does not lose energy.

**Comment by Meduris** [comment]
do you have a battery/energy crystal in your inventory that might be charging the shield?

(Not saying there is no bug but thats just one possibility)

**Comment by MrJorman** [comment]
Hmm, maybe I'll check again, sorry!

**Comment by MrJorman** [comment]
I checked again. The problem is relevant.

**Comment by Meduris** [comment]
Thanks, we'll have to look into that then. Just for reference, could you provide a screenshot of your inventory and if installed the curios slots and a list of armor modules you are using (just in case something might interfere or behave weird if used together)

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/224187959-549481f5-cbe6-4437-b769-a119f13738bc.png)
![image](https://user-images.githubusercontent.com/55187962/224187974-e5218b1a-aa5b-4f54-91b5-3f951b5d092b.png)
Curios off

**Comment by Speiger** [comment]
This is kinda thing in vanilla.
You need to deal a certain amount of damage to get the shield damaged...
At least that is what we found out when researching this behavior the first time.
