### ISSUE TITLE
Incorrect model of the nano saber when I throw it on the ground

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#666]
Incorrect model of the nano saber when I throw it on the ground
![image](https://user-images.githubusercontent.com/55187962/224178521-50472501-3bd6-498d-8a03-3983a1ae8c2e.png)

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/224178706-bc2af9c1-f719-4548-8b80-0b7ff69442f6.png)
![image](https://user-images.githubusercontent.com/55187962/224178763-db262e82-a9be-4aee-ba24-1262c38545e6.png)

**Comment by MrJorman** [comment]
Many tools are not displayed correctly, fix it)

**Comment by Speiger** [comment]
@MrJorman could you explain what isn't correct with it?

You know showing only wrong things doesn't always tell whats it is supposed to look like.

**Comment by BeryL12138** [comment]
> @MrJorman could you explain what isn't correct with it?
> 
> You know showing only wrong things doesn't always tell whats it is supposed to look like.

I agree you.
