### ISSUE TITLE
What is the principle of hybridization

### ISSUE THREAD

**Issue by BeryL12138** [TinyModularThings/IC2Classic#677]
I want to know how sugarcane hybridization works. I have tried many times and can't get sugarcane that can harvest resin (even cactus hybridized). The wiki entry in the game does not specify how to obtain this special sugarcane. Is there a problem with my method？
:）

**Comment by Speiger** [comment]
The crop when you analyze it with the crop analyzer either says: Sugarcane or Sticky Reed.
If it doesn't say sticky reed you can't harvest said crop.

Simply put 2 crops together that will result in sticky reed (crop breeding mode in the analyzer)
And breed until you get sticky reed out of it. You can already scan crops with the analyzer item the moment its at stage 0 to find out if it is sugarcane or sticky reed.

Thats how it is done.

**Comment by BeryL12138** [comment]
> The crop when you analyze it with the crop analyzer either says: Sugarcane or Sticky Reed.
> If it doesn't say sticky reed you can't harvest said crop.
> 
> Simply put 2 crops together that will result in sticky reed (crop breeding mode in the analyzer)
> And breed until you get sticky reed out of it. You can already scan crops with the analyzer item the moment its at stage 0 to find out if it is sugarcane or sticky reed.
> 
> Thats how it is done.

Thanks a lot.  ：）
