### ISSUE TITLE
[Suggestion] Macerator produces 2 coal dusts from 1 coal ore

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#68]
It is possible, with silk touch, to mine coal ore directly. Then put it in the macerator should produce 2 coal dust. And burning a coal dust could done a coal as well. ^^ This idea is good only for coal, not for redstone and lapis, since they drop more than one item, and not for diamonds either, but maybe for diamond, I don't know.

**Comment by Speiger** [comment]
I can add a Recipe Coal Ore To dust directly. I was thinking also to do it.
But smelting it back will not work. Also Coal Blocks to dust should be also an Recipe...
What i still think of is that you can use a Extractor on Ores (that can be silkharvested) and then you gain a little bit more out of it then a normal pickaxe would do. (maybe random) do not know yet totally

**Comment by Speiger** [comment]
Maybe add something this comming update to that...

**Comment by Carbon-Ghost** [comment]
Can't we use the macerator for silk touch ore doubling ? I mean it's the best way imo....
And it should be directly converted into dust, that's a bad idea, I don't like it ;P

**Comment by Carbon-Ghost** [comment]
Can't we use the macerator for silk touch ore doubling ? I mean it's the best way imo....
And it should be directly converted into dust, that's a bad idea, I don't like it ;P

**Comment by Carbon-Ghost** [comment]
Can't we use the macerator for silk touch ore doubling ? I mean it's the best way imo....
And it should be directly converted into dust, that's a bad idea, I don't like it ;P

**Comment by Carbon-Ghost** [comment]
Can't we use the macerator for silk touch ore doubling ? I mean it's the best way imo....
And it should be directly converted into dust, that's a bad idea, I don't like it ;P

**Comment by Carbon-Ghost** [comment]
WTF here too ? What happened.... Multiple msgs..

**Comment by Speiger** [comment]
Meh Extractor with fortune 2 effect (+2x generally Drops) should be fine. But the IC2 API for RecipeOutputs does not support those things...

**Comment by Carbon-Ghost** [comment]
Then macerator ftw, and I still don't like the idea of dusts, unless I can recompress the dusts back into their initial form...

**Comment by Speiger** [comment]
Well i like the idea of dusts... And the solution causes the same problem. It is not the Block that is  causing the Problem. It is the IC2 API. They simply say. This OutputClass is set. You can not modify it or build on Top of it. And the things it provides are only 1 NBTTagCompound and a list of ItemStack, which seems to be fine... but it does not provide enough things for some features. Like Random Results (which would be possible with some HardCoded things) or Fortune effect or some things...
Have to talk with aroma about that^^

**Comment by Carbon-Ghost** [comment]
But I don't want pourcentages, I want macerators to always output 2 products, to it's or you use macerator to be sure to have ore doubled, or you cross your fingers and use your fortune 3 pickaxe or drill :D

**Comment by Speiger** [comment]
The Extractor would have 2x by itself with that idea and gain a fortune bonus on top of it. So it would be even bigger then Fortune 3 itself...

**Comment by Carbon-Ghost** [comment]
Then why make it experimental then ? Having crushed inpure ore with bonus that can come if you extract it ?

**Comment by Speiger** [comment]
Because it is nothing that you would macerate: coal, redstone, lapis, diamond, emerald ore
Thats the ores that would be able  to put in the Extractor.

**Comment by Carbon-Ghost** [comment]
Config then ? At least both ideas will be here xD

**Comment by Speiger** [comment]
implemented the coal recipe. The other stuff oh well joins as soon IC2 Exp releases the required api which i need...
