### ISSUE TITLE
Nano boots are not working correctly.

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#684]
When I fall from a small height, the boots absorb my damage and waste energy. But when I fall from a great height, I take no damage, but the sound of damage is heard, but the damage does not pass.

**Comment by MrJorman** [comment]
I consider this a bug since the damage should pass if I fall from a great height. Now nano boots = this is a means of invulnerability from falls.

**Comment by CrossVas** [comment]
There is indeed a chance of not using energy for fall damage absorption when you fall from a short heigh, but when it comes to long fall, energy and health is taken (See attached video)
https://imgur.com/a/h7gbPJj

**Comment by MrJorman** [comment]
I don't get lost at all

**Comment by MrJorman** [comment]
I don't lose my health

**Comment by MrJorman** [comment]
Oh no, it disappears.
