### ISSUE TITLE
Incorrect display of shields from IC2 in the frame of the Quark mod.

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#688]
Incorrect display of shields from IC2 in the frame of the Quark mod.

example: glass_item_frame

![image](https://user-images.githubusercontent.com/55187962/224807762-51dec849-d611-4845-9365-b4609699761a.png)
![image](https://user-images.githubusercontent.com/55187962/224807804-2bcaa31b-44c8-425e-b3d3-d53beb6e3fd0.png)

**Comment by Speiger** [comment]
@MrJorman vanilla renders it properly meaning its a quark bug not a ic2c bug.
