### ISSUE TITLE
Ocean generator (or common generator) problem?

### ISSUE THREAD

**Issue by Shizz00** [TinyModularThings/IC2Classic#689]
So... there is this guy on my server that has ~4000 ocean generators (well i only have 1500)...

Anyway so he built it all at once without any transformers. He could only for a brief moment see, when he connected the last cable of doom, that there was like 4000+ packets... Long story short: Noone could get close to this cluster without timing out. I managed with /setblock to cut the cable after hours of trying. After that the lag was gone. So... is this just the limitation of the mod/java itself to handle such an amount or could this be a bug?

Thanks!

**Comment by Speiger** [comment]
why do you need 400kEU/t production?

The question is how many receivers had the did the Emitters have?
The Calculation is Emitters * Receivers.
Meaning if you have 4000 emitters go against 300 receivers the calculation goes crazy...

My suggestion is: If your emitter count is high have a low receiver count.
And the same goes if you have a high receiver count have a low emitter count.
This can medigate that.

But basically this is a limitation of the mod where the calculation just gets to expensive...
And there is not much i can do about it except rewrite it and lose a lot of functionality.

**Comment by Speiger** [comment]
If you think this question is answered you can close the issue
