### ISSUE TITLE
ic2:pressure_alloy_furnace_structure no broken and no wrench

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#690]
ic2:pressure_alloy_furnace_structure no broken and no wrench
The players dismantled 1 block of the structure, and the rest cannot be broken and cannot be twisted
![image](https://user-images.githubusercontent.com/55187962/224858822-5343e2a4-e176-47a1-baeb-74c5cef5067f.png)

**Comment by Speiger** [comment]
Not a bug these frame blocks are not machines they are supposed to be mined with a pickaxe.
