### ISSUE TITLE
Pressure Alloy Furnace Structure doesn't drop and the incorrect digging speed

### ISSUE THREAD

**Issue by Karo4a** [TinyModularThings/IC2Classic#691]
Yes, the main machine block of the Pressure Alloy Furnace is removed with a wrench, but in no way can the other 7 structural blocks be removed.
Also, the digging speed is always the same when digging these blocks, both by hand and with any pickaxe/drill

https://user-images.githubusercontent.com/90093987/224996110-e4d0b4a6-1c64-4bc6-9690-bb1b18c3cd82.mp4

**Comment by Speiger** [comment]
Will fix the breaking speed issue the rest is intended.
