### ISSUE TITLE
crash server #2

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#692]
[crash-2023-03-14_14.41.19-server.txt](https://github.com/TinyModularThings/IC2Classic/files/10968480/crash-2023-03-14_14.41.19-server.txt)

**Comment by Speiger** [comment]
duplicate #683

**Comment by Karo4a** [comment]
Not duplicate. These crash from updating neighbours near reactor chamber. #683 these is crash from ic2 crops

**Comment by MrJorman** [comment]
https://pastebin.com/bGMJsmQb in console

**Comment by Speiger** [comment]
Yeah ok not a duplicate, but i have this exact crash already as a entry in my todolist.
I forgot its on the internal list not on this one.
