### ISSUE TITLE
Advanced Drill in Multi-Mining mode does not drop experience

### ISSUE THREAD

**Issue by Karo4a** [TinyModularThings/IC2Classic#693]
In the single block mining mode, the experience drops, but when you turn on multi-mining, the experience stops drop.

https://user-images.githubusercontent.com/90093987/225000364-29103f19-5c8a-41d0-a186-f2baf6f18b9d.mp4

**Comment by MrJorman** [comment]
+ this drill does not check neighboring blocks whether they can be broken or not, I use the Lootr mod, and if there is a chest nearby that cannot be broken, the drill will ignore and break.
