### ISSUE TITLE
Adman metal seeds stop growing

### ISSUE THREAD

**Issue by BeryL12138** [TinyModularThings/IC2Classic#694]
Well,I tried to plant diamond seeds using the method of planting mineral crops on wiki. At first, I succeeded in obtaining diamond powder (using overgrowth fertilizer), but later they did not grow. I ensured that other conditions were the same, including sunlight, humidity, herbicide, etc. Is it the reason for overgrowth fertilizer? But after I destroyed them and replanted them, they still did not grow, which made me very confused.![5098702b50509128.jpg](https://user-images.githubusercontent.com/126538334/225025833-7c5a6dae-e753-45df-8230-19bef8d64f62.jpg)

**Comment by PrincessOfEvil** [comment]
You need a diamond block under the plant (anywhere up to four layers
straight down).

**Comment by BeryL12138** [comment]
> You need a diamond block under the plant (anywhere up to four layers
> straight down).
> Message ID: ***@***.***>
> 
> >
> 

I did it....

**Comment by BeryL12138** [comment]
@Speiger This is my Discord ID:BeryL12138#5603
I want to discuss some IC2C issues with you on discord.
:)

**Comment by Meduris** [comment]
@BeryL12138 for that you should probably join the ic2 classic discord linked at the top of the curseforge page https://www.curseforge.com/minecraft/mc-mods/ic2-classic

**Comment by BeryL12138** [comment]
> @BeryL12138 for that you should probably join the ic2 classic discord linked at the top of the curseforge page https://www.curseforge.com/minecraft/mc-mods/ic2-classic

Sorry I can't find the link.
Where?
（crying）

**Comment by Meduris** [comment]
right at the top. you need to click on the "Discord xxx online" thing
![grafik](https://user-images.githubusercontent.com/15174539/225263394-2bee24cb-ac47-4b93-a5ee-1e7332dd6ebd.png)
