### ISSUE TITLE
Curios API would like to be able to disable the "Back" mode and leave only the "Belt" mode.

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#696]
Curios API would like to be able to disable the "Back" mode and leave only the "Belt" mode. Please add to the configuration to disable the Spin mode, since I don’t want people to wear 2 packs for a flight or an energy pack, but the charging belt is very necessary!

**Comment by Speiger** [comment]
Ehhh What?

**Comment by MrJorman** [comment]
I want to be able to enable only belt support in IC2 in conjunction with the Curios mod

**Comment by Speiger** [comment]
Oh that. No i am not changing how the curio support was added.
