### ISSUE TITLE
Issue with Pumps not accepting unversell cells 1.19.2

### ISSUE THREAD

**Issue by IchigoGames** [TinyModularThings/IC2Classic#697]
at first i thought it would not work at all but after some testing it seems to work if you use a internal power like a re_battery but not if your useing outside power it could just be that pump is not powered but still seems like even if it has no power it should accept the cells even if it does not fill them.

https://clipchamp.com/watch/2qQYNF89iP9

Minecraft 1.19.2
Forge 43.2.6
IC2Classic-1.19.2-2.0.4
Modpack Tekkit The Resurrection 1.9

issue happans on single and multiplayer.

**Comment by IchigoGames** [comment]
![image](https://user-images.githubusercontent.com/11888162/225159896-b1304d2f-b334-4d5e-a673-0da42a9ea3f8.png)
i was able to get it to work like this after some testing but not with cables pump will not power on and accept cells with cables connected to batbox but will work if batbox is right next to it.

**Comment by IchigoGames** [comment]
ok the more i look into this i think we are just stupid and was not using the mod right i may close this.

**Comment by Speiger** [comment]
@IchigoGames the pump only pumps the direct block underneath it.
And it automatically tries to eject the fluid into the neighbor tank.
The filter how i coded it only allows cells if there was a fluid in the internal tank of the pump.

If you want to mass drain fluids you want to look at the "ranged pump" that thing can even clear oceans easily xD

**Comment by IchigoGames** [comment]
yah that how i thought it worked its juse been a while sense i used it
