### ISSUE TITLE
Could I revise the recipes in ic2c？

### ISSUE THREAD

**Issue by BeryL12138** [TinyModularThings/IC2Classic#699]
I want to modify some recipes in IC2 through datapackets or directly modify the module file. Where is the recipe file in the module file? I haven't found it for a long time

**Comment by CrossVas** [comment]
You can get IC2Classic datapack by typing '/ic2c_export' in console. The Datapack.zip file will be generated at "mc_directory/config/ic2c".

**Comment by Meduris** [comment]
you will have to add a proper pack.mcmeta file on your own though, as the zip includes only the recipes.

You can find some explanation about the datapack and ic2 classic specific recipes here: https://github.com/TinyModularThings/IC2Classic/wiki/1.19.x-ResourcePacks#datapack
(this also explains how to disable recipes etc)

Also as mentioned on that linked page, it is highly recommended, that for the final datapack, you only include the recipes you actually want to modify/disable as the json recipes are a lot slower to load then the ones we have in the source code
