### ISSUE TITLE
[Idea] Generator, a way to prevent waste of coal

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#70]
The generator, at this moment, consumes coals every time its buffer is not full of energy. My idea is create an option that if is on, the generator will consume a coal only if its buffer is full empty.

For example, you have 64 coal into the generator, its buffer is full and you macerate 1 iron ore in a macerator next to it. The generator will lost a bit of energy to fill the macerator's buffer, but will consume a coal that every excess of energy will be lost, wasted. With this new setting, the generator will begins to consume a coal only if its buffer is full empty, so it will never waste any coal.

If you implement my idea about the Nuclear Generator, my idea is also applied to it, in order to prevent any waste of uranium.

**Comment by Speiger** [comment]
Use the Fuelcan. It can be filled with coal and even make more fuel out of it and it drops only Tiny Amounts of Fuel into anything that fuels it. With that you do not waste to much fuel.

**Comment by ExDomino** [comment]
How to use them?

**Comment by Speiger** [comment]
I will add a Nei Plugin to the Canning machine because you can make a Really high fuel ot of resources ^^

**Comment by ExDomino** [comment]
But the generator continues to consume the fuel into the fuel can even if its buffer is full.

**Comment by Speiger** [comment]
What about making it that it takes energy if the buffer is lower then 90% (9000/10000 EU)?

**Comment by Speiger** [comment]
That makes it more efficent?

**Comment by ExDomino** [comment]
Err maybe yes, but as generator is a basic machine that is don't supposed to know its internal storage level more than just 0=empty, 1=full, my idea is more realistic. You have to empty it in order to consume another piece of coal.

**Comment by Speiger** [comment]
ok. Testing now the bugreport on the Fuelcan.

**Comment by Speiger** [comment]
Fuel can shows now his durability right.
And the problem was that the Generator did consume all fuel but the fuelcan removed only 250 Fuel Points (which is 1250 EU) now everything should be fine.

**Comment by ExDomino** [comment]
Ok, but for my idea about the coal generator that can prevent to consume a piece of coal if its buffer is not completely empty, do you accept my idea? It would be either a new button in the top-right of the generator to enable/disable this feature.

**Comment by Speiger** [comment]
Nope. Generator is really basic as you said. It knows only the full or empty state. (Also keep close to the classic and that is one of his features).

**Comment by ExDomino** [comment]
So, could you add another tier of generator that could prevent waste of coal ? ^^

**Comment by Speiger** [comment]
The Generator itself nope. From external maybe. Not sure what i should make. So that generators can be upgraded a little bit.
