### ISSUE TITLE
Replenishment of the industrial table does not work

### ISSUE THREAD

**Issue by RainbowExile** [TinyModularThings/IC2Classic#705]
When requested from a tubenet, items do not enter the workbench and are thrown onto the floor. Entrance is available on all sides.

**Comment by Speiger** [comment]
@RainbowExile please provide a clip.

**Comment by Karo4a** [comment]
https://user-images.githubusercontent.com/90093987/225589243-7aa17ae3-9673-4cdc-9366-9cb7a78afccd.mp4

**Comment by Speiger** [comment]
@Karo4a @RainbowExile the Industrial Workbench is a requester tube itself, you don't need a Requester tube attached to it.
