### ISSUE TITLE
[1.19.2] Tooltip/messages are hardcoded. 

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#707]
Block: Miner;
Place: GUI, Chat
Hardcoded entry: Workgroup related tooltip, chat messages.
![image](https://user-images.githubusercontent.com/25727222/225619010-748076c7-effd-442e-9771-26437ff64678.png)

UPDATE: 
Block: Electrolyzer.
Place: JEI Electrolyzer Category.
Hardcoded entries: Recipe type entry, Energy entry.
![image](https://user-images.githubusercontent.com/25727222/225628723-fe9c9e5d-a8df-402e-ae55-8df229e0588f.png)

**Comment by Speiger** [comment]
@CrossVas 
"gui.ic2.miner.workgroup": "Create/Remove Workgroup",
"gui.ic2.electrolyzer.energy": "Energy: %s EU",
"gui.ic2.electrolyzer.dual": "Type: Dual",
"gui.ic2.electrolyzer.charging": "Type: Charging",
"gui.ic2.electrolyzer.discharging": "Type: Discharging",
