### ISSUE TITLE
Work Provider and Receiver pipes with Teleport pipe?

### ISSUE THREAD

**Issue by Karo4a** [TinyModularThings/IC2Classic#708]
Can work be added with these pipes?

**Comment by Speiger** [comment]
Sorry but no.
The Tube net was designed to be dimension specific, they can not interact with each other.
On top of that the Multi Tile support was never implemented.

So that would require a redesign from scratch how it worked.
In this case get creative and find solutions to your problems :)

**Comment by Karo4a** [comment]
Can you tell us about Multi Tile support? I didn't understand what it was.

**Comment by Speiger** [comment]
This feature could have allowed to link teleport tubes together in the grid, but that isn't supported in the tube net.

**Comment by Karo4a** [comment]
That is, the implementation of this, which I see, is a cover for shortcomings?

**Comment by Karo4a** [comment]
Okay. Thanks
