### ISSUE TITLE
[Old Bug ?] Machine sounds don't last long enough

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#71]
Machine sounds don't last long enough. For example, when you put more than one thing to smelth into the furnace, the smelting sound is not a continuous sound. It stops something 1 second before the end of the smelting and restarts for the next one. Same thing with the macerator and other machines. It's really old as bug (if it's a bug) though.

**Comment by Speiger** [comment]
Also fixed. I implemented some new Functions to the Custom Audio System and call them (Loop function)

**Comment by ExDomino** [comment]
Are you the guy that fix a bug the most fastest in the web? ^^

**Comment by Speiger** [comment]
I fixed during the adding of the Advanced machines. So its long ago. (3-5 days)
