### ISSUE TITLE
Problem with Ranged Pumps and Electric Fluid Pipe Pump

### ISSUE THREAD

**Issue by matheusrp007** [TinyModularThings/IC2Classic#710]
Problem 1: Ranged pump's content doesnt flow through pipes to a tank.

Problem 2: Electric Fluid Pipe Pump cant be removed using a wrench (any kind), and a pickaxe destroys it.

Using Minecraft 1.19.2 and IC2 Classic 1.19.2-2.0.4

**Comment by Speiger** [comment]
Thanks will be addressed in the next patch.

Sadly this will take until april at the very least!

**Comment by matheusrp007** [comment]
Np
Thanks for adressing it
