### ISSUE TITLE
Increase amount of items extraction pipe can extract per sec

### ISSUE THREAD

**Issue by urbeastfriend** [TinyModularThings/IC2Classic#713]
In some cases, for example with QuarryPlus mod this pipe is almost useless because quarry acts like a chest and this pipe extracts only few items per second. Even if u attach 5 of those its still not enough.

**Comment by CrossVas** [comment]
You can use filtered extraction tube which provides you upgrade slots, in which you can put Overclockers upgrades. The more upgrades the faster is extraction.

**Comment by urbeastfriend** [comment]
Yoo, just tested, this is amazing, but kinda not intuitive. Thank you

**Comment by Speiger** [comment]
@urbeastfriend @CrossVas you can also use Import upgrades on the filter tube.
Overclocker => Speed of the extraction
Import Upgrade => Quantity of the extraction
