### ISSUE TITLE
Why does Portable Teleporter use energy from any energy source in the inventory?

### ISSUE THREAD

**Issue by Karo4a** [TinyModularThings/IC2Classic#716]
My Quantum Helmet has Module: Charger installed and this Portable Teleporter uses the helmet's energy, although it itself has a buffer of 50,000,000 eu, which should be more than enough.

And don't tell me that this is Charger's idea and you need to take off your helmet so as not to charge the Portable Teleporter, I'll tell you one thing - It's very inconvenient. Charger should not power items whose energy buffer is similar to or exceeds the item energy buffer in which it is installed.

**Comment by Speiger** [comment]
Fun fact, a Backpack can recharge a mininglaser.
By that logic that would be no longer possible too.
But yeah a charger upgrade does only discriminate between:
Is a tool or is it armor.
if armor: Don't charge it.
if tool: charge it xD

Not a bug. Intentional Design :)
