### ISSUE TITLE
Nano shield doesn't lose EU on block (and more)

### ISSUE THREAD

**Issue by basanets** [TinyModularThings/IC2Classic#719]
Hello

Thank you for the mode remaster, enjoyed it a lot. 
I was playing version 2.0.4 and found several issues, can create separate issues if you ask to. (I didn't find the fixes for in the 2.0.5 version patch notes, however I didn't test if they are present there)

1. Nano-Shield doesn't lose EU on block.
2. Cannot craft nano bow, no recipe in JEI (have seen it in your video on youtube).
![no_bow_in_jei](https://user-images.githubusercontent.com/38219600/226746001-22590a7e-4522-4a0d-aa0b-b98fece3f59f.png)
3. Basic wrench doesn't spend EU in lossless mode (only if loss is encountered, then it saves the block and spends EU).
4. No recipe for Plasma Cell in JEI and no interactions with Plasmafier in JEI.
![plasmafier_plasma_cell](https://user-images.githubusercontent.com/38219600/226746006-243f2309-66a4-4190-8678-617c5e2705bf.png)
5. Quantum armor doesn't accept Advanced Solar Helmet (5eu/t) as a module (however it does accept simple Solar Helmet (1eu/t)) - not sure if it is intended.
![solar_charger_module](https://user-images.githubusercontent.com/38219600/226746009-7d91bfe5-b10b-4684-a903-c2a770c33a3d.png)
6. Villager trades are full of coffee, tea and cacao trades (and they usually occur instead of useful trades :( ) - not sure if it is intended.
![trash_trades](https://user-images.githubusercontent.com/38219600/226746010-d95000cf-0f6b-42f6-9529-6dbc64a66cca.png)
7. HV solar panels use IV transformer to craft instead of HV one - not sure if it is intended (cause HV water mill uses HV transformer).
![hv_solar](https://user-images.githubusercontent.com/38219600/226745993-a70bdca3-3716-4c1e-93e7-c361518c3c34.png)

**Comment by basanets** [comment]
@Meduris Thank you for explanations!

**Comment by CrossVas** [comment]
3. This is intentional. For more info, read here: #698
4. This is also known. For more info, read here: #714
Meanwhile, you can use [IC2C UU-Matter](https://www.curseforge.com/minecraft/mc-mods/ic2cuumatter).

**Comment by Speiger** [comment]
5: Yes that is a bug.
6: Technically that is intended, for the idea of sources where you can sell these things to villagers. More sources of emeralds. Though i can see the inconvience that causes. Not sure how to solve that yet besides maybe a config setting.
7: Not a bug this is to give a shock effect to people who go by default: HV SOLARS NOTHING ELSE. So they start looking into other directions.

**Comment by basanets** [comment]
I would highly appreciate a config flag to disable beverage trades
