### ISSUE TITLE
[Suggestion] Luminators need too many energy and their buffer is too high

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#72]
Luminators need to many ernergy (in IC2 classic, I don't know if you already fixed that) to be really efficient, because don't forget torchs are already an unfinite source of light. And as well, their internal storage prevent to make on/off switch. But I know that the first goal is to be able to power them with a single RE-Battery and to prevent them to blink if the power is insufficient. But with another mods, there is always a lot of way to make modern light without the need of energy.

My idea is either make that luminators don't need energy at all, OR reduce their need of energy and their internal buffer, and making that a turned off luminator can still prevent mods to spawn in their light area, but I think it would be really hard to code.

**Comment by Speiger** [comment]
Reason for that is because he is draining from the Battery Two EU which last about 8 Ticks. (He is using 1 EU per 4 Ticks) but you can plug them to cables and they have a internal storage of 10K EU. (Max Accepting can you figure out with the EU Reader Sneak click)

**Comment by ExDomino** [comment]
You don't think that luminators needs too many energy to work? A simple torch can do the same without any need of energy, so why you have to use a luminator for?

**Comment by Speiger** [comment]
Well they use energy to provide light. I know that they need quite a bit of energy, but they do not use the normal way...
I am thinking of rewriting them since they are a hassle to use in bases.
But i do not know if i can do that so fast since i have now a time limit. 10 days from now on and then my coding time is really limited...

**Comment by ExDomino** [comment]
Your coding time?

**Comment by Chocohead** [comment]
Luminators can burn monsters that walk on them, torches don't do that. The main problem is that the buffers are massively too big, having a simple on/off switch for them (a splitter cable + a lever) is impossible as their buffers leave them on for a long time after the power stops. The actual power use isn't that high, it's still only 0.5 EU/t right?

**Comment by Speiger** [comment]
Its actually 0.25EU/Tick... And yeah the Burn monsters part is a cool part^^"

But some changes with Luminators will come but how big they are i will not know it^^

**Comment by ExDomino** [comment]
Maybe increasing the light radius of them? Because a simple torch produces as much light and requires no power. Luminators should have an advantage.

The only advantage of luminators is when you use other mods like Enviromine or Terrafirmacraft, when with Enviromine torchs produces heat and with Terrafirmacraft normal torchs don't last forever. But used alone without any mod of that kind, the only idea that I could have is either remove their need of power or increase their light area. The second idea is far away the better, according to me, and one luminator could light a big room, especialy if the ceilling is too high for normal light block like glowstone that don't light the ground correctly, except if you place torchs on the ground. What are you thinking about this idea?

**Comment by Speiger** [comment]
Even if i wanted to i can not increase the max size because the mechanic of ligh allows only a max of 16 which means simply 16 Blocks (including the sourceBlocks) radius of light... Which you actually see only 8 blocks of... Thats a MC rule....

**Comment by Carbon-Ghost** [comment]
Maybe make luminator work like the thaumcraft lamp or Greg's Lightning advanced luminator ( which also uses eu btw ) ?

**Comment by Speiger** [comment]
Fixed Hitboxes..

**Comment by Speiger** [comment]
I will close that because it is now a useless thing i will open another one later^^
