### ISSUE TITLE
[1.19.2] Filtered Fluid Scanner GUI wrong y pos for 'Inventory'

### ISSUE THREAD

**Issue by CrossVas** [TinyModularThings/IC2Classic#723]
Minecraft: 1.19.2
IC2Classic: 1.19.2-2.0.5
![image](https://user-images.githubusercontent.com/25727222/226927607-e28deb21-8d8e-4471-a6d4-4373dc36c825.png)

**Comment by Speiger** [comment]
whoops xD
Thanks xD
