### ISSUE TITLE
[Suggestion] Wrench: always in lost-less mode, even for no-electrical ones

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#73]
The idea of the possibility of lost a machine even if you use a wrench is really aweful. I often use an electrical wrench setted in lostless mode. My idea is to make all wrench, electrical and normal ones able to dismatle all machines without any lost. So the key 'm' would be used only for jetpack. Did you know that Gregtech removed that feature when installed?

**Comment by Carbon-Ghost** [comment]
Well, imo we instead should have another type of config mode : 
Classic : Works like normal.
Alternative : You can break any machines with a diamond level pick, but it takes 20 second to break them, so making wrench is better, and the drop chance is 100% all the time...

**Comment by Speiger** [comment]
@Carbon-Ghost requires a rewrite of Every Block File that exsist in IC2...
And also a ServerSided Force

**Comment by Carbon-Ghost** [comment]
Nevermind then, unless you like my idea, I will do it myself when I am better at Java ( currently progress = Half life 3 ).

**Comment by Speiger** [comment]
Its not JavaCoding with MC... The problem here is simply that i need to detect what config is enabled and need to change all Drops that would normally Happen instead...
Which is kind of much work...

**Comment by ExDomino** [comment]
Just do that wrench always dismantle without any lose will be fine for me. ^^

**Comment by Carbon-Ghost** [comment]
@Speiger : Oh, well then forget about what I said ^^

**Comment by Speiger** [comment]
@ExDomino Just use a Electric Wrench in lossless mod with Lappack or Batpack, or if you have baubles installed use a Battery/EnergyCrystal/LapotronCrystal in the Baubles belt slot...

**Comment by ExDomino** [comment]
I already know how to dismantle my machines without any lost. Just, according to me, a percentage of lost even when you're using the right tool, is just stupid.

**Comment by Speiger** [comment]
I can not make it for everyone right.... If i change it other people yell at me that this is not anymore like IC2...

**Comment by Carbon-Ghost** [comment]
And although we integrated an easy mode to the E-net to make it similar to most of modded minecraft power systems ( no BOOOOOOOOOOOM, but still loss ), we still try to make this mod feel like IC2 classic ;)

**Comment by ExDomino** [comment]
A config option for that would be useful then. ^^

**Comment by Speiger** [comment]
Not sure if i am gona implement this. Requires more input from outside...

**Comment by Carbon-Ghost** [comment]
Kinda agree here...

**Comment by Speiger** [comment]
Closed for now. Because no implementation but if people yell then maybe...

**Comment by Carbon-Ghost** [comment]
IF YELL < 5 

that is ^^
