### ISSUE TITLE
[1.7.10] crash with ae2 RV3

### ISSUE THREAD

**Issue by unix-supremacist** [TinyModularThings/IC2Classic#730]
[fml-client-latest.log](https://github.com/TinyModularThings/IC2Classic/files/11090195/fml-client-latest.log)

affects the latest official AE2 on curseforge, and the GTNH version of AE2, caused by a field being made private in RV3 to be replaced with getters

**Comment by Speiger** [comment]
ok should be fixed. but i am not sure if P2P tunnels work ^^"
