### ISSUE TITLE
[1.12.2-1.5.7]How can I solve this problem?(Wires, machines and generators all failed)

### ISSUE THREAD

**Issue by NineMeowICT** [TinyModularThings/IC2Classic#733]
![image](https://user-images.githubusercontent.com/115801669/228418525-9efb95be-d157-41ad-a93c-d9dc4329b331.png)
Putting them on the ground again can make them work temporarily, but this bug occurs from time to time.

**Comment by NineMeowICT** [comment]
[latest.log](https://github.com/TinyModularThings/IC2Classic/files/11096405/latest.log)
server log

**Comment by Speiger** [comment]
just relog the version.
That should fix it.
