### ISSUE TITLE
Mod conflict problem

### ISSUE THREAD

**Issue by BeryL12138** [TinyModularThings/IC2Classic#734]
IE's villager trade fair conflicts with ic2c's villager trade (current investigation). The specific problem is that villagers do not replenish goods and villagers trade blank![320e267cc8ac72ca.jpg](https://user-images.githubusercontent.com/126538334/228881861-cb7a8988-02c2-49b5-8c7d-f4f3e5d332cf.jpg)

![7bf6e9598e46ff7d.jpg](https://user-images.githubusercontent.com/126538334/228881872-dbddcaf2-c3a0-46b5-a614-0cdfa1e7f96b.jpg)

**Comment by Speiger** [comment]
hopefully addressed this now
