### ISSUE TITLE
[1.12.2] More dupes with alchemical chests

### ISSUE THREAD

**Issue by xJon** [TinyModularThings/IC2Classic#737]
> I’ve got an alchemical chest almost filled with iron with a hopper below going into a rotary macerator. The macerator is piped out into other alchemical chests. Originally I wanted to do just do almost a full chest of refined iron ingots but the whole alchemical chest of refined iron ingots filled up and my iron supply was untouched. Long story short, I have filled up 9 alchemical chests full of refined iron ingots and my iron supply hasn’t gone down by 1 iron.

(from https://github.com/xJon/Tekkit-2/issues/174, using the latest version of IC2C)

**Comment by Speiger** [comment]
Can't reproduce it in tekkit 2 sooo not a bug.

**Comment by xJon** [comment]
Seems to be reproducible in this video: https://youtu.be/8FVhy3Inq_w?t=1272
I also managed to reproduce it myself using a Rotary Macerator with Import and Export upgrades, adjacent to alchemical chests on each side, with the imported-from chest containing multiple stacks of Iron Ore.

**Comment by murilorodelli** [comment]
I`m having the same problem.

**Comment by Speiger** [comment]
@xJon the bug was on ProjectsEs side.
They didn't sanitize their outputs from inventories when you extracted them.
Which caused this issue.
I simply now forcefully sanitize the data and now it works just fine...
