### ISSUE TITLE
Terraformer causes chunk rendering issues 1.19.2

### ISSUE THREAD

**Issue by NickKornienko** [TinyModularThings/IC2Classic#739]
Using a terraformer will cause the chunks it is terraforming to not render. 

To replicate: Leave the render area of the terraformer and come back.

The only way to fix this issue seems to be to exit and reopen the world(singleplayer) or restart the server (multiplayer) and load in within render distance. 

![Screenshot_1](https://user-images.githubusercontent.com/43100481/230228341-c213f824-3676-49ee-9d7f-7ee9bc333b81.png)

**Comment by Speiger** [comment]
@NickKornienko does this happen even with Only IC2C being installed?

**Comment by NickKornienko** [comment]
@Speiger Yes, I just put a fresh pack together with only IC2 (and forge) to test it and got the same result.
![Screenshot_2](https://user-images.githubusercontent.com/43100481/230229954-97a4a864-f919-4a36-95b8-55050a3a4520.png)

**Comment by Speiger** [comment]
thank you ill look into it.
