### ISSUE TITLE
[Idea] A way to lock upgrades into machines

### ISSUE THREAD

**Issue by ExDomino** [TinyModularThings/IC2Classic#74]
With the EasyMode set to false, a simple miss click on a transformer upgrade can make your machine explode violently (not a bug: it receives a too big packet so it explodes as intented). My idea is to make that upgrades can only be insered and removed from machines if you click on them with a wrench. Else, the upgrades slots are grayed out. You have to sneak click with the wrench to dismantle them. But for other kind of machines, like transformers and batboxes, the wrench would works as usual.

**Comment by Speiger** [comment]
They do that only Explode if they need electricty and You remove the Transformer upgrade.
So as lon the machine does not run you do not need to worry. And since with the next upgrade you can make them redstone sensitive to work you do not need to worry at all about that. (Beeing uncarefull has his price)

**Comment by Carbon-Ghost** [comment]
Maybe make your upgrade system similar to mekanism ? I honestly am neutral about this idea..

**Comment by Speiger** [comment]
No Lockbutton -.-

**Comment by Carbon-Ghost** [comment]
Kk Senpai ^.^''

**Comment by ExDomino** [comment]
Ok so I have a better idea: make that it's impossible to remove a transformer upgrade if the machine is on or if its internal buffer is recharging. Because, miss click and BOOM !

**Comment by Chocohead** [comment]
I don't get how you can misclick the upgrades out anyway, they're not directly next to the output slot.

It's not like it happening is a new mechanic either.

**Comment by ExDomino** [comment]
I don't count the amount of time I or a friend of mine have misclicked on the upgrade slot. XD

**Comment by Speiger** [comment]
Sorry but the mouse is only 4 pixels big (length) and according to my source is that the between each slots are 20 Pixels... how can you misskick that extremly? You need to get yourself glasses...

**Comment by Speiger** [comment]
will not gonna happen...
