### ISSUE TITLE
Suggestion: Fusion Reactor should be renamed as Thermonuclear Reactor

### ISSUE THREAD

**Issue by EnderVonSlayer** [TinyModularThings/IC2Classic#740]
Reasoning: It makes heat, it melts things, if anything it's a molten liquid reactor as it's not fusing cobble/items into a new element.

**Comment by Speiger** [comment]
Done... But it breaks a LOT of texts for me <.< 
You will pay for that at some point xD
Oh wait.... You did already.... Sry forgot xD
