### ISSUE TITLE
1.12.2 version has issues with Evil Craft

### ISSUE THREAD

**Issue by WolffangSorano** [TinyModularThings/IC2Classic#741]
From what I gather this issue may be caused by Evil Craft but I'm not 100% sure. I hope it's a quick fix.
[crash-2023-04-06_16.11.58-client.txt](https://github.com/TinyModularThings/IC2Classic/files/11174499/crash-2023-04-06_16.11.58-client.txt)

**Comment by Meduris** [comment]
As discussed on discord, EvilCraft is using ic2 experimental specific internal classes instead of the api to add recipes which (unsurprisingly) fails. Turning off the ic2 compat in evilcrafts config got rid of the crash.
