### ISSUE TITLE
IC2 crashes the game on startup when added to direwolf20 1.1.9 pack

### ISSUE THREAD

**Issue by Maxster991** [TinyModularThings/IC2Classic#744]
Optifine isnt installed in this modpack, so this cant be the problem. Couldn't find a solution.
[crash-2023-04-10_20.38.46-client.txt](https://github.com/TinyModularThings/IC2Classic/files/11193501/crash-2023-04-10_20.38.46-client.txt)

**Comment by Speiger** [comment]
Direwolf back has a Texture file in it that violates resource pack rules. If you scan through texture folders that will cause the crash.
That is not a bug in ic2c look into the direwolf pack and search for a texture that has a upper case texture.
(its most likely a custom resource pack or something.

**Comment by Maxster991** [comment]
> Direwolf back has a Texture file in it that violates resource pack rules. If you scan through texture folders that will cause the crash. That is not a bug in ic2c look into the direwolf pack and search for a texture that has a upper case texture. (its most likely a custom resource pack or something.

thank you for the fast response.

Where may I find the texture? in the resource packs folder?

**Comment by Speiger** [comment]
@Maxster991 honestly i have no idea. I never installed the pack or got explained by others where the issue file lays.
Just search for that file name.

**Comment by Maxster991** [comment]
> @Maxster991 honestly i have no idea. I never installed the pack or got explained by others where the issue file lays. Just search for that file name.

allright. its working now. had do delete all awl.png files. thank you so much
