### ISSUE TITLE
Hi i have a saw mill issue with anothermod Quark 

### ISSUE THREAD

**Issue by DAONE33** [TinyModularThings/IC2Classic#749]
hi i asked this already to quark mod dev team and they suggest i askes ic2 team as they could not figure it out 

it over here  i have a more detailed post over their 

but the short version is the ic2 sawmill upgrades durable and efficent do not give the correct amount of planks when installed with quark 
efficeint upgrade 10 planks 
durable upgrade 8 planks 

when quark is installed along side ic2 classic 

they only give 6 planks regardless of upgrades 
https://github.com/VazkiiMods/Quark/issues/4145

**Comment by Speiger** [comment]
@DAONE33 please open the original issue too since ill try to find out what exactly the issue is.
What info i need is what Modpack are you using and is the author contactable?

**Comment by DAONE33** [comment]
Hi for some resson the issue has fixed itself i presume i must have installed a mod that overided the normal code responsable for the math of the planks and their subsequant upgraded

apologies next time i have any issues to report i will see if i can repliacate it serveral times before reporting to any mod issue repository  going forward appreciate your reponse thank you

**Comment by DAONE33** [comment]
closed

**Comment by DAONE33** [comment]
if you are still intrested despite the fact i cant replicate it the orginal log is this the right thing you may need 

[2023-04-11-6.log.gz](https://github.com/TinyModularThings/IC2Classic/files/11276040/2023-04-11-6.log.gz)

i found the same world and configuration but what log would you need 

as for the author yes they are contactable
