### ISSUE TITLE
Upgrade Suggestion.

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#75]
A world Interaction Upgrade with these Functions.

-Extractor next to sticky resin spot will auto collect it and process it
-Auto sand factory if you have cobble above the macerator
-Auto smooth stone factory if you have cobble above furnace

What do you think? Additions Opiniens tell them just?

**Comment by Carbon-Ghost** [comment]
That's exactly what I wanted :D Additionnnally there is some things I want to make use the w.i.u. , one of them is the compressor, when placed next to a pump pumping water, it will auto make snowballs, but can you make it require a  w.i.u. for doing that ? ( and if possible also make this feature possible if water is above compressor ? Although it kinda defeat the whole pump purpose... ). ^^

**Comment by Speiger** [comment]
@Carbon-Ghost i copied it from your suggestion because it was something that got my interesting and i am waiting for input simply^^"

**Comment by Carbon-Ghost** [comment]
Hehe :D

**Comment by Speiger** [comment]
not joining. closing
