### ISSUE TITLE
Colossal recycler

### ISSUE THREAD

**Issue by SHEEEEPER** [TinyModularThings/IC2Classic#750]
Hello, i'm playing with IC for the first time, and need some help with colossal recycler, how can i start it? I am not able to get water into the recycler.
p.s. i just spent 2 iridium plates on this machine, and cannot use it(
No addons instaled, just IC2 CLASSIC

**Comment by Speiger** [comment]
@SHEEEEPER try placing a pump next to it with a infinite watersource underneath the pump.
Dont use the ranged pump.

Also pipes can when they are connected to a tank be set to "Extract mode" if you open the gui with a empty hand

**Comment by SHEEEEPER** [comment]
got it, thank you!
