### ISSUE TITLE
Centrifugal Rare Earth Extractor does not maintain speed with a redstone signal or a Redstone Sensitivity upgrade

### ISSUE THREAD

**Issue by NickKornienko** [TinyModularThings/IC2Classic#752]
Centrifugal Rare Earth Extractor does not maintain speed with a redstone signal or a Redstone Sensitivity upgrade, the only way for the speed to ramp up is for items to be present in the machine.

Expected behavior is similar to the other advanced machines which maintain speed when given a Redstone Sensitivity upgrade or a signal.

**Comment by Speiger** [comment]
Good Catch! Ty we will address that next patch.
