### ISSUE TITLE
iron plate uncraftable?

### ISSUE THREAD

**Issue by sidrew** [TinyModularThings/IC2Classic#753]
I'm not finding a recipe for iron plate... making machine blocks uncraftable.  IC2 Classic 1.19.2-2.0.5

**Comment by Speiger** [comment]
@sidrew wait Since when did ic2c have iron plates?

**Comment by sidrew** [comment]
Right then... so, how does one craft machine blocks then? I can't seem to find a recipe...

**Comment by CrossVas** [comment]
![image](https://user-images.githubusercontent.com/25727222/233899674-c654357d-c27c-4de0-a5ea-0b144dcc24da.png)
using 8 refined iron ingot
Also, make sure you have JEI installed. JEI will show you all the recipes in the game.
CurseForge Link: https://www.curseforge.com/minecraft/mc-mods/jei

**Comment by sidrew** [comment]
Well... alrighty... feelin' dumb. Thought for sure I tried that one. :/

**Comment by CrossVas** [comment]
You might have used Silver Ingots, as they look nearly same as Refined Iron.
