### ISSUE TITLE
Rocket miners get stuck when they encounter water or magma, and they can't return to base or continue mining.

### ISSUE THREAD

**Issue by zy2644599218** [TinyModularThings/IC2Classic#754]

**Comment by zy2644599218** [comment]
Hopefully this bug will be fixed, as it somewhat affects the usefulness of rocket miners.

**Comment by Speiger** [comment]
@zy2644599218 fixed the issue hopefully.
If not i provided a emergency shutdown mode that will allow you to collected safely wherever it is.

**Comment by triangulumoportunity** [comment]
I'm glad to hear that you fixed this issue. I have been struggling with this issue recently, but I still enjoy using this mod.

Could you please tell me how I can obtain the patched version? Currently, I am using version IC2Classic-1.19.2-2.0.5.

> @zy2644599218 fixed the issue hopefully. If not i provided a emergency shutdown mode that will allow you to collected safely wherever it is.

**Comment by Speiger** [comment]
@zy2644599218 the patch is still not released.
I am finishing the patch at the moment still. 
It should come out in the next couple days.
