### ISSUE TITLE
Venomilia does not yield grin powder by hand

### ISSUE THREAD

**Issue by Rafael-Bello** [TinyModularThings/IC2Classic#755]
To harvest it, you need to use a crop harvester. Manual harvesting only yields purple die. Here's what I tried so far:

- Harvesting with and without the overgrowth fertilizer
- Harvesting at least 20 times in each growth stages (4,5 and 6)
- Tried every farmland available

**Comment by Speiger** [comment]
@Rafael-Bello you need to sneak to manually harvest it on that stage.
