### ISSUE TITLE
Invalid ItemStack crash

### ISSUE THREAD

**Issue by nanakisan** [TinyModularThings/IC2Classic#76]
I can't explain what happened honestly. On 1st and 2nd run of my instance with the mod, ran just fine. However on the 3rd for some reason or another this cropped up. http://paste.ee/p/uH5bm  
  
I honestly don't know how I could reproduce this.

**Comment by nanakisan** [comment]
I found the issue. Reasons unknown to me but the default configs are generating with block-id 241. Which apparently does not exist and is causing the crash.

**Comment by Speiger** [comment]
just remove the complete part of the recycler Blacklist config that will reset everything and it will be fine.

**Comment by Speiger** [comment]
Fixed and added Block/ItemName support...
Note: With this update you have to reset the Recycler BlackList config. Even if it supports ids you should reset it to load properly.
