### ISSUE TITLE
Help! I can't proceed anymore at MIxed Metal Ingot! (Ic2 classic 1.19.2)

### ISSUE THREAD

**Issue by CuiteKitty** [TinyModularThings/IC2Classic#761]
I can't crafting Mixed Metal Ingot.. because I CAN'T FIND A ALUMINUM ANYWHERE IN THR WORLD!!!!
Please help me.. what should I do for get a aluminum???
I used spectator mod and X-ray resourcepack to look it up overworld and nether, but it wasn't anywhere !!!

**Comment by Daenara** [comment]
Aluminum isn't supposed to be found via mining, that is a gimmick. There is a recipe for it that you can look up in jei (and most likely the wiki)

**Comment by CuiteKitty** [comment]
Oh no,, is there any other way to get it then?

**Comment by CuiteKitty** [comment]
> Aluminum isn't supposed to be found via mining, that is a gimmick. There is a recipe for it that you can look up in jei (and most likely the wiki)

Oh no,, is there any other way to get it then?

**Comment by Speiger** [comment]
@CuiteKitty rare earth extractor with a certain resource

**Comment by CuiteKitty** [comment]
> @CuiteKitty rare earth extractor with a certain resource

Thank you so much ❤
