### ISSUE TITLE
Check Nuke

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#77]
Comparing the Nuke from 1.4.7 with the current one.
Just a reminder.

**Comment by nanakisan** [comment]
https://imgur.com/a/zwgoW  
picture 1: nuke primed by torch  
picture 3: second nuke primed by 1st nuke  
picture 4: outcome of the second nukes priming  
picture 5: detonation of 1 nuke into a 3x3 box of nukes with combined total damage calculated.

**Comment by Speiger** [comment]
@nanakisan yeah i saw that also in the code that these things are possible. But their work are not in the first priority thats why i placed this reminder here so implement the fix before i push the update^^

**Comment by nanakisan** [comment]
Hey no worries just thought I'd do the research for yah and confirm it. I'm a IC2 purist and having these features are a absolute must. It made the mod rather dangerous when you didn't properly set up reactor containment and such.

**Comment by Speiger** [comment]
Ok. But thanks for the ingame Validation of this bug.

**Comment by nanakisan** [comment]
oh and by the way thanks for keeping the config for reactor damage. https://imgur.com/a/hci2G I ..kinda ramped it up ...for reasons or another. heh heh heh

**Comment by Speiger** [comment]
xD yeah know how that feels.
Anyway sleeping time.

**Comment by Carbon-Ghost** [comment]
I also tested and all config values works like IC2 1.4.7 ( I actually tested it ), but I set it at the explosion of a tnt for the sake of my modpack :D

**Comment by Speiger** [comment]
@nanakisan i found that Nukes could not stack each other (in terms of explosions), there you are right.
The lever part is in 1.4.7 remove that i can read for sure out of these unreadable code parts...
Below that version it might be that it was the case but i can not say that for sure. For now you require a lever to activte a Nuke... Only nuke. Just to prevent Server Spam Crasing...
Like with AE&FrameBuilds...
