### ISSUE TITLE
Sawblade Upgrades incorrect usage

### ISSUE THREAD

**Issue by TheYxel** [TinyModularThings/IC2Classic#770]
I think Sawblade Upgrades shouldn't be used in any other machine then Sawblade

![2023-05-19_12 12 29](https://github.com/TinyModularThings/IC2Classic/assets/131541322/2b4cb1ac-a9e1-4d63-bf72-1199035b961b)

**Comment by Speiger** [comment]
yes that is correct but the way the upgrade system works that is IIRC unfixable.
Basically i can only declare a "class" of Upgrade not a machine specific upgrade in the filters.
