### ISSUE TITLE
Sawblade upgrades still works with zero durability

### ISSUE THREAD

**Issue by TheYxel** [TinyModularThings/IC2Classic#771]
https://github.com/TinyModularThings/IC2Classic/assets/131541322/4eb86720-22b9-44c3-9eee-e57ac0fc33a6

**Comment by Speiger** [comment]
@TheYxel the Speed Buff isn't bound to the durability. Only the extra yields are.
That way if your durability runs out and you have multiple of these in the sawmill the speed buff stays but the yields go down if none are left.
