### ISSUE TITLE
[1.12.2] Stacked recipes dupe

### ISSUE THREAD

**Issue by xJon** [TinyModularThings/IC2Classic#772]
(Reported over https://github.com/xJon/Tekkit-2/issues/190)
> When crafting the Rotary Macerator, pressumably with resources for 2 of more, it allows for the infinite crafting of Rotary Macerators.
It happens when using the recipe with the Obsidian blades requiring 2 per slots in the crafting table.
>
> Upon clicking an item in the crafting grid after crafting the item, the items return as if the item was not crafting, except you get to keep it.
>
> I have added a video of the "dupe" in action.
> 
> https://github.com/xJon/Tekkit-2/assets/72791212/8955b72b-3e3b-483f-8cf1-333d796478df

I can confirm I managed to reproduce this, only on a server. Afterwards I tried in a singleplayer world it crashes instead: https://mclo.gs/tl0VSCc, although only testing in a singleplayer world seems to not have this issue.

**Comment by Speiger** [comment]
@xJon can you reproduce this in ic2c itself? with just it.

**Comment by xJon** [comment]
@Speiger Will test!

**Comment by xJon** [comment]
Seems to be a conflict with Universal Tweaks' Crafting Cache: https://github.com/ACGaming/UniversalTweaks/issues/189
