### ISSUE TITLE
Wiki controls section is too out-of-the-way

### ISSUE THREAD

**Issue by Maoman1** [TinyModularThings/IC2Classic#774]
Currently to find the controls you have to go to the main page and then flip backwards a couple of pages, which is not really noted anywhere, you just have to sort of remember they're there when you forget the controls. The wiki has unique controls unlike anything else in the game or even any mod I can think of, so they are easily forgotten between sessions, especially if you go more than a few days between sessions. I suggest putting the controls section somewhere much more obvious, like it's own separate little flag sticking out the side.

**Comment by Speiger** [comment]
@Maoman1 sounds like a great idea.
Though I wouldn't put it on the side since it is more for the "User tabs" and "Main page".
Since it is a "Extra thing" like "search" for example. It could be also at the bottom.
