### ISSUE TITLE
Elytra + Rocket Boost/Jetpack Rework

### ISSUE THREAD

**Issue by EnderVonSlayer** [TinyModularThings/IC2Classic#776]
Ender Von Slayer — Today at 1:26 AM
so, the upper tiers of jetpack have rocket mode
which just launches you up in the sky by a bunch
what if
and hear me out now
what if when you charge rocket mode WITH an elytra, you get a firework boost
so horizontal movement

Speiger — Today at 1:27 AM
I would bind that on a condition, that you may dislike...

Ender Von Slayer — Today at 1:27 AM
that being

Speiger — Today at 1:28 AM
during elytra flight state the jetpack (outside of the rocket mode) doesn't work.

Ender Von Slayer — Today at 1:28 AM
no I like that more

Speiger — Today at 1:28 AM
maybe instead of pushing you up it gives a small boost to normal flight speed.
(like pushing you)

Ender Von Slayer — Today at 1:29 AM
testing will be required

Speiger — Today at 1:29 AM
and rocket boost would be like a huge buff.

**Comment by Speiger** [comment]
Took a while but its now there xD
Also includes bugfixes and something that wasn't talked about here xd
