### ISSUE TITLE
Uranium cells don't cause radiation poisoning

### ISSUE THREAD

**Issue by nanakisan** [TinyModularThings/IC2Classic#78]
As per to title, in 1.4.7 holding a cell without a hazmat suit gave you radiation effect. Which is not the case unless a nuke or a reactor explode.

**Comment by Speiger** [comment]
Is as far as i know only a Exp thing (1.6.4)

**Comment by nanakisan** [comment]
huh could swear that was a feature...I just tested it and seems I was wrong. Perhaps this should be a feature? Seems weird handling highly radioactive isotopes without protection.

**Comment by Speiger** [comment]
Well unused Uraniumcells should not hurt because they got not activated. Also it can bother really without AE to must have a Suit weared. I think if you handle damaged ones then a radioactivty effect would be fine..

**Comment by Speiger** [comment]
Added, but with some conditions... If the Uranium cell is not used (raw uranium does not hurt) then it does not apply the effect on the player.
The PotionEffect also gets only based on the damage applied.. The higher the damage the more often you gain the Effect. (between 1-20 sec delay between effect apply) and also the effect gets only 10 seconds (it stacks per uraniumcell and per applying)

**Comment by Carbon-Ghost** [comment]
Wait what ? So it poison you if the cell is used ?

**Comment by Speiger** [comment]
Yeah because i was bothered wearing always a Armor to modify my reactors just a little bit...
So parly used cells count as activated and the more their used (depleted are not hurt) the higher the damage is the more of the potioneffect applied^^"

**Comment by Carbon-Ghost** [comment]
And it applies radiation right ? Maybe wither for very damaged one for extreme effects... :3

**Comment by Speiger** [comment]
Mehh. The Radiotaion effect applying happens between 1-20 seconds (10 seconds effect (can stack))

**Comment by Carbon-Ghost** [comment]
ah lol xD Also add config, some people might dislike the idea ;P
