### ISSUE TITLE
Problem recipe hardened steel

### ISSUE THREAD

**Issue by TheKlimoT** [TinyModularThings/IC2Classic#787]
Hardened steel cannot be melted in a melting furnace. Version 2.0.6

This video - https://youtu.be/oZo1FEITDgI

**Comment by MrJorman** [comment]
*refined_ingot, too problem. terribly uncomfortable! I want to smelt iron, but no way!

**Comment by Speiger** [comment]
@TheKlimoT not a bug.
This was done due to compat reasons due to some mods making steel in the blast furnace exclusively for decorative blocks.
That's why its not there.

Just use a normal furnace.
