### ISSUE TITLE
Villager sell ic2:nuclear_jetpack 1 emerald???

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#789]
Villager sell ic2:nuclear_jetpack 1 emerald???
I cured zombie villagers and he sells it for 1 emerald????

![image](https://github.com/TinyModularThings/IC2Classic/assets/55187962/77fc2ab8-b59c-429f-8684-829bef2106cd)

**Comment by MrJorman** [comment]
![Uploading image.png…]()
craft jetpack, 1 emerald yes?

**Comment by MrJorman** [comment]
this villager

![image](https://github.com/TinyModularThings/IC2Classic/assets/55187962/7c93978b-23c2-425f-beb6-1bc1b9c517bf)

**Comment by MrJorman** [comment]
craft jetpack, 1 emerald yes?
![image](https://github.com/TinyModularThings/IC2Classic/assets/55187962/37e47215-95c8-4744-9177-c1ee125dc2e0)

**Comment by Speiger** [comment]
@MrJorman use it and still say its a bug :)

**Comment by MrJorman** [comment]
Where can I change the number of emeralds? and why is it so cheap? it breaks the game and the economy.

**Comment by Meduris** [comment]
have you even tried to use it? there is a reason for that price...

**Comment by Speiger** [comment]
@MrJorman USE THE JETPACK. ONCE YOU USED IT YOU UNDERSTAND THE PRICE

**Comment by MrJorman** [comment]
Ok.

**Comment by MrJorman** [comment]
Not yet. I don't know how to use it. Then I'll figure it out.

**Comment by MrJorman** [comment]
By the way, I'm testing the mod on the server, there are 50 people online, so far 20.0 tps, IC2 does not load.

**Comment by Speiger** [comment]
@MrJorman you charge it like a normal reactor would.
(Throw in uranium rods, with cooling vents)

Also yeah. I coded it to be efficient.
