### ISSUE TITLE
Luminator Hitboxes

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#79]
They act as a full block hitbox, even if the selection box is the right shape.
![2015-07-12_18 33 56](https://cloud.githubusercontent.com/assets/4021725/8639022/b688d0c6-28c4-11e5-92ac-468dd3ead207.png)
![2015-07-12_18 34 03](https://cloud.githubusercontent.com/assets/4021725/8639023/b7f017b2-28c4-11e5-900f-329f67743742.png)

**Comment by Speiger** [comment]
As i said in the #72 i will work on them^^ The will get maybe even a Cable Multipart addition so that you can place them directly on cables and then having no problems with hitboxes anymore^^

**Comment by Speiger** [comment]
Fixed. Added missing things to it and now it is adjusting its bounding boxes to it.
