### ISSUE TITLE
CTD When using Compacted Electric Jetpack

### ISSUE THREAD

**Issue by TealSeer** [TinyModularThings/IC2Classic#798]
Got a CTD in single-player when trying to use the rocket mode of the Compacted Electric Jetpack, I held to charge and then when i hit the release button I crashed, for reference I'm using it as a module in a nano armor chest plate.

[crash-2023-06-04_17.41.04-client.txt](https://github.com/TinyModularThings/IC2Classic/files/11646790/crash-2023-06-04_17.41.04-client.txt)

**Comment by Speiger** [comment]
Issue is that ic2c sends a packet to the client even so the tick is done on the client.
Will be addressed in the next patch, but no ETA yet.
