### ISSUE TITLE
[1.19] Configuration

### ISSUE THREAD

**Issue by Sa1ZeR** [TinyModularThings/IC2Classic#799]
Can you add a setting to the config to edit the amount of energy to create matter?

**Comment by Speiger** [comment]
@Sa1ZeR why?
I am not saying yes or no. I am just curious why.

**Comment by Speiger** [comment]
Well since no comment on this. Closing.

**Comment by Sa1ZeR** [comment]
> @Sa1ZeR why? I am not saying yes or no. I am just curious why.

I want to make the creation of matter more harder. I'm sorry for the long answer
