### ISSUE TITLE
Texture Tracker

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#80]
If you want to help me out with Textures, or want to suggestion better textures,
then post me a download/view link here.
Here is the list of textures i need for updates/whatevery is going to be created at the moment.
https://www.dropbox.com/s/bp0plkvuhge9id6/Needed%20Textures.java?dl=0

**Comment by ExDomino** [comment]
Don't forget the uranium jetpack.

**Comment by Carbon-Ghost** [comment]
Texture is finished, but I still need to finalise it so it fits in the texture sheet ( assets ), "sigh" why is there size limitation anyway ;P

**Comment by Carbon-Ghost** [comment]
Texture is finished, but I still need to finalise it so it fits in the texture sheet ( assets ), "sigh" why is there size limitation anyway ;P

**Comment by Carbon-Ghost** [comment]
Texture is finished, but I still need to finalise it so it fits in the texture sheet ( assets ), "sigh" why is there size limitation anyway ;P

**Comment by Carbon-Ghost** [comment]
Why do my messages keep getting tripled xD

**Comment by Speiger** [comment]
(Yeah) cleaned up. So no worry did not delete important messages^^.
And @Carbon-Ghost i did explain you that already, i can not load differend sizes from a TextureFile because they have to be all the same size... What i did try in my version of texture loading is to override that. The Result was a complete mess which created more problems then it helped...

**Comment by Carbon-Ghost** [comment]
Yeah I know that, I just said "sigh" because I really wished the size limitation didn't exist ^^'' xD

**Comment by Speiger** [comment]
^^" If you provide me with a patch i applied it...
You do not how hard to add modularity to something without making a mess really hard.

**Comment by Carbon-Ghost** [comment]
I perfectly trust you and it's not your fault :P xD

**Comment by Carbon-Ghost** [comment]
Blame Al-baka xD

**Comment by Speiger** [comment]
Ablaka did not make this system.
Immibis did keep the TextureSprites when forge did remove them...

**Comment by Carbon-Ghost** [comment]
Well blame the baka who made the texture system then xD

**Comment by Speiger** [comment]
That would be then Minecraft and forge which supported that system...

**Comment by Carbon-Ghost** [comment]
Then blame them :D

**Comment by Speiger** [comment]
I will not blame forge again. If they make something wrong i simply kick the things they are providing and making my own.
Only downside they can steal it and say thats their own...
(Still thinking that the BlockBreakEvent from forge is copied from me, did create the logic for it.... -.-")

**Comment by Carbon-Ghost** [comment]
Did they at least give you credit for that ?

**Comment by Speiger** [comment]
Nope. They added that thing and i do not know if they copied it. But i think it -.-

**Comment by Carbon-Ghost** [comment]
:/

**Comment by ExDomino** [comment]
The nuclear jetpack is simple to do, just change the texture of red to make them green and voila. ^^

**Comment by Speiger** [comment]
You know that the Nuclear Jetpack is heavyer then the Electric jetpack.
Also it has a mod that turns it into a rocket.

**Comment by Carbon-Ghost** [comment]
And you know there is a better ingame model now in IC2 classic of jetpacks ? So changing states from active reactor and inactive is too hard, instead we better have an E-jetpack with a nuclear module on it :D and some advanced thrusters, and a pair of wing to kind of slow down the hover mode flight because of the heavy modules... ( but you will still fall a bit faster ;P ), actually textures already exists, I just need to fix it because it's too big ;P
