### ISSUE TITLE
[Feature Request] I want to suggest that the nano saber should spend 1250/2500 EU per hit

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#801]
I want to suggest that the nano saber should spend 1250/2500 EU per hit. I explain why, the nano saber is a rather strong weapon and when we hit nano / quantum armor with it, it can even break, but for some reason the nano saber does not spend enough energy per hit. A full charge of the saber is enough for me for the whole game day.

What do you think, gentlemen, am I right? To increase the amount of energy per hit.

**Comment by Speiger** [comment]
> A full charge of the saber is enough for me for the whole game day

That's the point. It should last you a good chunk of time.
It isn't the best damage dealing weapon inside ic2c.
Increasing it to 1-2k would basically mean you have only a few hits before you run out and when you are adventuring, duration is the most important thing you need.

Anyways. Atm no that is not changing.

**Comment by MrJorman** [comment]
Wait, what's the best weapon then? Could you tell?

**Comment by Speiger** [comment]
Mining Laser

**Comment by MrJorman** [comment]
> Mining Laser

oh maan, I banned this item, it is not balanced. For example, any of its modes spends very little energy, and the map breaks at 50 online in 2 clicks.

**Comment by MrJorman** [comment]
In our RU community, we fixed this laser by disabling some modes in the config and configuring the energies for each mode. That is, the explosion mode ate about 50,000 EU

**Comment by MrJorman** [comment]
We disabled the scatter mode, it's terrible, it creates a load on the server, and also breaks the map.
