### ISSUE TITLE
Aluminium ore not spawning in world

### ISSUE THREAD

**Issue by Gillym8** [TinyModularThings/IC2Classic#803]
Hi, are there any known issues with why there wouldnt be any aluminium spawning in world? or if it is, i cannot find any.. please help, thanks.

**Comment by Meduris** [comment]
Aluminium ore isn't supposed to spawn in the overword.
Check out JEI look for how to create aluminium ingots etc

**Comment by Gillym8** [comment]
ok i thought so, but i couldnt find it in the nether, is it uncommon there?

**Comment by Meduris** [comment]
Relatively uncommon and not too easy to spot.
Though the other ways to obtain it shown in JEI are the main options you should use
