### ISSUE TITLE
Duping resources. see video and screenshots.

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#804]
https://youtu.be/e7z5M7F_Abk

![image](https://github.com/TinyModularThings/IC2Classic/assets/55187962/179e671f-7a2d-4ea2-b958-79fb5edb0423)
![image](https://github.com/TinyModularThings/IC2Classic/assets/55187962/c6eb4f52-c30d-4a6a-9215-3fee8f16c856)

Is there an option how to fix this? You can dupe any resources and blocks

**Comment by Speiger** [comment]
@MrJorman HOW IS THAT A IC2BUG?
when Clearly this is a Minecraft bug?

**Comment by GitJhopa** [comment]
> @MrJorman HOW IS THAT A IC2C BUG? when Clearly this is a Minecraft bug?

I'm sorry, but did you read that I asked how this can be fixed? Since even from IC2 boxes can be duped.

**Comment by Speiger** [comment]
@GitJhopa the only thing i can do is do a stacksize check.
But the bug lies with minecrafts block allowing to stack any item even if it wasn't supposed to be stacked :)

**Comment by GitJhopa** [comment]
> the only thing i can do is do a stacksize check.
> But the bug lies with minecrafts block allowing to stack any item even if it wasn't supposed to be stacked :)

yes bro ((( I can dupe through Quark Shulkers Tweak, through IC2 crates, through vanilla bags. this is terrible... the server is suffering.. help me out if you can?

**Comment by GitJhopa** [comment]
> @GitJhopa no

aha, my player found new dup ic2, wait i give you new video :D

**Comment by Speiger** [comment]
Ok i will make the toolbox not storeable in a bundle. K, Thanks bye.
