### ISSUE TITLE
ic2:compacted_electric_jetpack Does not charge items in hand, such as a drill.

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#808]
ic2:compacted_electric_jetpack Does not charge items in hand, such as a drill.  This backpack is made from lappack and batpack , but it doesn't charge my items, it doesn't make sense

**Comment by Meduris** [comment]
jetpacks never were intended to charge items. They use the lappack etc from the crafting recipe as their own energy storage, not as a provider for other stuff. If you want that functionality, you'll have to add gravisuit classic (https://www.curseforge.com/minecraft/mc-mods/gravisuit-classic)

Trinsdar added config options for the different jetpacks to allow them to charge items in that addon, though you'll have to live with his changes to the crafting recipes.

Also I can tell you from experience that you do **NOT** want non nuclear jetpacks to charge your items... I don't even want to know how often I had to deal with my jetpack suddenly no longer having power after using a mining laser etc
