### ISSUE TITLE
[Feature Request] Please make sure that the saplings of rubber do not grow from 1 time when using bone meal.

### ISSUE THREAD

**Issue by MrJorman** [TinyModularThings/IC2Classic#809]
Please make sure that the saplings of rubber do not grow from 1 time when using bone meal. To grow any tree in minecraft, you need to poke a seedling with bone meal several times, thus bone meal for trees will be costly, and to get a rubber tree - only 1 flour is needed, this is an imbalance.

**Comment by MrJorman** [comment]
Let's respect the mechanics of minecraft, on the version on which we play 1.19.2

**Comment by Meduris** [comment]
this was intentionally this way in all versions of ic2 classic and I can tell you without even asking Speiger, that this won't change anytime soon
