### ISSUE TITLE
Hoppers do not pull from output slot

### ISSUE THREAD

**Issue by nanakisan** [TinyModularThings/IC2Classic#81]
As observed it will pull from the power source slot but not the output slots of processing machines.
https://imgur.com/a/ySooo

Outputs are not being pulled as shown in images.

**Comment by Speiger** [comment]
@nanakisan yeah... Bottomslot is currently the BatterySlot.
Immibis did change that extremly (every slot to side).
Problem is i do not know how it should be.
Litte request: Could you test the machines and tell me how it should be?
Because sided slots came only in the 1.6.4 version, 1.4.7 do not give any hints about that...

**Comment by nanakisan** [comment]
If memory serves me well. All the machines used sided input and output. Back was the battery slot, front, top and sides were input. The bottom of all machines was for the output.

**Comment by Speiger** [comment]
Would't it be better that all sides are input and output?
(I mean now ingame, how i do this in code is a completly differend story)

**Comment by nanakisan** [comment]
Oh wait thats right all sides were input but bottom was specifically output. The battery slot if i recall was never able to be automated unless it was a storage block. Batboxes, MFE's, MFSU's could be automated with battery insertion just never the machines.  
  
Your best hope is to hop over onto the minecraftforge irc and simply ask someone.

**Comment by Speiger** [comment]
Ok. good to know. Basic Machines to change is easy. Because shared data...
The Advanced once are a little bit harder^^"
Also a note for the future: The InductionFurnace sorts its outputs now. (Because of the way of the upgrade support)

**Comment by Speiger** [comment]
Fixed. Input and Output are the same sides (you can extract/import from any side and it will work how it should be)
