### ISSUE TITLE
LOL, advanced_drill can broken minecraft:bedrock in mode 3x3

### ISSUE THREAD

**Issue by GitJhopa** [TinyModularThings/IC2Classic#815]
LOL, advanced_drill can broken minecraft:bedrock in mode 3x3

**Comment by GitJhopa** [comment]
> @GitJhopa could you please provide a clip how you do it? Also was it done with ic2c alone?

yes only IC2.

**Comment by GitJhopa** [comment]
https://youtu.be/GD74-pQE0MQ

**Comment by Speiger** [comment]
Ty this will be addressed with the next patch!
