### ISSUE TITLE
Rocket Mode in jetpack causes a crash when pressing alt

### ISSUE THREAD

**Issue by Trinsdar** [TinyModularThings/IC2Classic#816]
Ic2c: 2.0.6.2
forge: 43.2.14
minecraft 1.19.2
https://gist.github.com/Trinsdar/a433555628624a6b0cc5b88ee564a898
it happened after I pressed alt after trying to charge the rocket mode, which didn't seem to display by the way.

**Comment by Speiger** [comment]
Duplicate #798
