### ISSUE TITLE
???

### ISSUE THREAD

**Issue by GitJhopa** [TinyModularThings/IC2Classic#823]
???
![image](https://github.com/TinyModularThings/IC2Classic/assets/86250668/b78f436b-43ab-4df3-9203-0a175cd827ac)

**Comment by GitJhopa** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/86250668/e6e9e56e-83c9-4cc3-b0cc-232f164a3e32)

**Comment by GitJhopa** [comment]
This is very annoying. Not the first time. And when there are pipes, they turn off and things just fall out.

**Comment by Speiger** [comment]
@GitJhopa you lost a few network packets of TileEntityData, thats the reason.
I am already using minecrafts internal system to reduce the chance of that.
There is not much i can do to fix that.
