### ISSUE TITLE
Fisher

### ISSUE THREAD

**Issue by overhealer** [TinyModularThings/IC2Classic#826]
Yo.
Im playing on server with ic2classic and found Fisher machine in wiki book. I try to build multiblock structure like in wiki, but nothing happened. Is this machine still in development? Or it is need something else to work?

**Comment by Speiger** [comment]
the mod is completed and tested, while there can be bugs in it, a "Feature being unfinished" isn't a qualifier. 
But semantics aside, did you put it into water? Where the logs are in water too? (On the same y level as the water)

**Comment by overhealer** [comment]
Yeah, problem was about that, just rebuild it on same water level and it works. Thanks for fast answer!
