### ISSUE TITLE
[Suggastion] More armor

### ISSUE THREAD

**Issue by Sa1ZeR** [TinyModularThings/IC2Classic#828]
In the current version of the mod, making quantum armor is very easy. Maybe add another variety? Yes, quantum armor can be improved, but it seems to me that this is not enough.
Interesting multi-block structures have been added to the current version of the mod, but they are not really needed when you have already been able to make quantum armor.

**Comment by GitJhopa** [comment]
🤡 diversemine

**Comment by Speiger** [comment]
The quantum armor was made a modular armor. Same with the nano armor.

To allow customization.
If the strength of the armor is not enough for you then I am sorry but there won't be another "higher tier"
All we do might add more modules in later major versions.

There were during development a few new armor variants planned and scrapped that would give a bit more style options but that was it.
