### ISSUE TITLE
Incompatible with NotEnoughResources

### ISSUE THREAD

**Issue by axzxc1236** [TinyModularThings/IC2Classic#83]
Sorry for opening two issue tickets in one day.

When I added NotEnoughResources, I won't be able to create or load a single player world, it didn't crash, just send me back to minecraft main menu.

Log : https://gist.github.com/axzxc1236/d05686235beeb5bda81d

**Comment by Speiger** [comment]
^^" Never heard of that mod. Interesting.Requires IC2 Exp Main Classes. Would be helpfull if you can give me a link to that mod that i can take a look into it and try to make a little compatiblity patch with the next update.
Also you help me out with that finding bugs and thanks for that^^

**Comment by axzxc1236** [comment]
http://minecraft.curseforge.com/mc-mods/225815-notenoughresources

This is one of my favorite mod, it is so useful to me, but I have to remove it for now.

**Comment by Speiger** [comment]
Ahh ok. Thats why it is reading the IC2 Exp config...
Well... I will look what i can do.

**Comment by Speiger** [comment]
@axzxc1236
the mod dev did a fix which should prevent crashes... (testing will proof it)
I will add oreDetection support from my side. Joins with the next update.
Please go with any Crashes to the NotEnoughResources mod and tell them that...

**Comment by dustojnikhummer** [comment]
Can you post link for that fix?

**Comment by axzxc1236** [comment]
http://jenkins.jakimfett.com/job/NotEnoughResources/

**Comment by dustojnikhummer** [comment]
Thanks :)

**Comment by Speiger** [comment]
Support is added...
So no longer a problem
Joins with the next update
