### ISSUE TITLE
Adjacent Storage Expansions not linking to Industrial Worktable

### ISSUE THREAD

**Issue by Urkchar** [TinyModularThings/IC2Classic#837]
How to reproduce:
1. Place two Storage Expansions followed by the Industrial Worktable in a line
![image](https://github.com/TinyModularThings/IC2Classic/assets/49205496/f3900b88-d912-416e-bd4e-8652dde32837)
2. Place crafting materials in Storage Expansion on the far left.
3. Setup a crafting recipe in the Industrial Worktable
4. Ensure all materials are available in the far left storage expansion. 
5. Click the crafting output in the Industrial Worktable.
You will get a message saying there is no recipe for the materials in the Storage Expansion. 
![image](https://github.com/TinyModularThings/IC2Classic/assets/49205496/7bcb0088-f80a-4d50-9525-98b08480d9ff)

**Comment by CrossVas** [comment]
By default The Industrial Worktable supports up to 6 expansion modules/blocks. 
You might wanna check `ic2c.cfg` for `I:expansion_limit` and increase the number.
