### ISSUE TITLE
[Functional rework] ic2:sonar_module need rework functional

### ISSUE THREAD

**Issue by GitJhopa** [TinyModularThings/IC2Classic#839]
I would like to ask you about the ic2:sonar_module item, is it possible to remake it somehow? And then at 100 online, if this module is activated, minecraft freezes and crashes.

**Comment by GitJhopa** [comment]
I think this module is not stable, that if there is a lot of online on the server, then the highlight goes on all the players in the vicinity, even if there are more than 50-60 of them in one place, minecraft just freezes and the fps goes to 0-1, I would not want to prohibit this object, and ask you to remake its function to a more adequate one. I propose to come up with it together.

**Comment by Speiger** [comment]
@GitJhopa if there is CRASHES, provide CRASHLOGS.

**Comment by GitJhopa** [comment]
> @GitJhopa if there is CRASHES, provide CRASHLOGS.

There is no crash. I write that minecraft freezes in FPS due to the glow effect on more than 60+ players

**Comment by Speiger** [comment]
> "if this module is activated, minecraft freezes and crashes."

Really?

**Comment by Speiger** [comment]
Anyways the sonar module effect is a bit heavy and i optimized the shit out of it already. There is no more optimization i can apply at this point anymore...

**Comment by GitJhopa** [comment]
The problem is that all players see the glow effect, and not just the person who has a helmet with a module, this is his main problem.

**Comment by Speiger** [comment]
Yeah that is a intended feature.
