### ISSUE TITLE
Recipe Mistake

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#84]
The charged electrolyiser uses a recycler in the middle:
![2015-07-18_11 36 53](https://cloud.githubusercontent.com/assets/4021725/8761289/6bb4a878-2d41-11e5-88c1-2eba35f212ba.png)
There is also a spelling mistake with the vacuum canner ;)

**Comment by Speiger** [comment]
Thanks^^" Forgot to replace this item when i copied the recipe^^

**Comment by Speiger** [comment]
Fixed. But changed TileEntityClassName too so it could be that the VacumCanner could disapear/crash game/get Skipped when you load with the name... Mapping is still the same but className itself changed..
