### ISSUE TITLE
[Feature Request] Give the ability to change/add/remove loot table from scrapbox

### ISSUE THREAD

**Issue by GitJhopa** [TinyModularThings/IC2Classic#840]
Give the ability to change/add/remove loot table from scrapbox in datapack or in the mod itself in tags or loot tables

**Comment by Speiger** [comment]
"ic2:toolbox"
Already a thing.
Its not a loot table but a tag that decides what can be put into the Toolbox.

**Comment by GitJhopa** [comment]
SCRAPBOX.

**Comment by Speiger** [comment]
@GitJhopa https://github.com/TinyModularThings/IC2Classic/wiki/1.19.x-ResourcePacks
Under Machines is the scrapbox
