### ISSUE TITLE
[BUG] No NBT data is saved when crafting IC2

### ISSUE THREAD

**Issue by GitJhopa** [TinyModularThings/IC2Classic#847]
When crafting, % of energy is not saved, for example, if I take a charged energy crystal, then I won’t be able to craft nano armor from it with already stored energy, if I take a nano bib with a built-in jetpack for crafting quantum armor, then the jetpack will disappear when crafting.

**Comment by Meduris** [comment]
1. literally not happening with the latest ic2 classic and the modpack we used during the whole mod development to test stuff ![grafik](https://github.com/TinyModularThings/IC2Classic/assets/15174539/032b8f57-ab68-4e05-969c-6a17c86349e1)
2. also not a thing 
![grafik](https://github.com/TinyModularThings/IC2Classic/assets/15174539/01cb188d-4b7b-4d3e-ae08-ea6790d2cd77)
![grafik](https://github.com/TinyModularThings/IC2Classic/assets/15174539/251ad6ef-2bec-4e86-b691-10600d855c12)


there is something in your modpack breaking this and that's not something we can do anything about...

**Comment by GitJhopa** [comment]
yes? :D upgrade crystal - good luck xD 
![image](https://github.com/TinyModularThings/IC2Classic/assets/86250668/5ba607a8-c6b6-4a49-90e5-12e69b60738b)

**Comment by GitJhopa** [comment]
see jetpack when crafting a quantum chestplate - it will disappear
![image](https://github.com/TinyModularThings/IC2Classic/assets/86250668/7de336d6-29d3-4e2d-be48-c7695844ef64)
![image](https://github.com/TinyModularThings/IC2Classic/assets/86250668/c49588bc-0999-46a6-b1cc-0c7b18f7d555)

Recipes JEI bugged? what?
![image](https://github.com/TinyModularThings/IC2Classic/assets/86250668/42b4640d-0076-43a8-9cb3-5ffecf828978)
![image](https://github.com/TinyModularThings/IC2Classic/assets/86250668/68ff1c90-0166-4fc3-8aee-066d1df463fb)

**Comment by GitJhopa** [comment]
Reopen this ticket, error found in IC2.

**Comment by CrossVas** [comment]
1. Lapotron Crystal takes regular circuits, not the advanced advanced one.
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/cf752d8a-2590-427b-afa5-14137ee202e5)

2. Yes, it will. And JEI tells you that.
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/02f3190b-0281-4f4c-9770-3b76a0574330)

Please, use JEI properly.

**Comment by Speiger** [comment]
This is not a problem.
And we closed because of that.
Anyways locked this conversation because you started spamming.
