### ISSUE TITLE
Bug about thermometer

### ISSUE THREAD

**Issue by shoucan77** [TinyModularThings/IC2Classic#848]
When I click barrel using thermometer, it can't normally display information of  barrel except water information，just like this:

**Comment by Speiger** [comment]
@shoucan77 the barrel has multiple modes by default non is set.
Only AFTER you primed the barrel into a mode it shows you more information.

**Comment by shoucan77** [comment]
I can get thick white ale from barrel,can it be primed?But it still can't display specific information except follows:

![20230724141652](https://github.com/TinyModularThings/IC2Classic/assets/135426949/9a82c01f-cadf-429f-8300-70016abfb067)

After look up in probe_en_us.json, I found the key value of ic2.probe.barrel.beer.solid.5.name is "Solid Ratio: Thick", but why the key value can't be display?

**Comment by Speiger** [comment]
@shoucan77 thank you i will fix that in the next patch!

**Comment by Speiger** [comment]
@shoucan77 keeping it open until it was actually fixed.

**Comment by shoucan77** [comment]
ok,thanks for your repair
