### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#85]
The compacting recycler GUI texture is broken, and the rotary macerator's is missing it's upgrade slots.
![2015-07-18_11 41 06](https://cloud.githubusercontent.com/assets/4021725/8761302/01dba4f0-2d42-11e5-8b5b-08f5d0ead3f7.png)
![2015-07-18_11 40 58](https://cloud.githubusercontent.com/assets/4021725/8761304/037b2222-2d42-11e5-8db4-70f88270554b.png)

**Comment by Carbon-Ghost** [comment]
Also reported in PM about the Rotary Macerator, the upgrade slots are "present" but not visually ^^''

**Comment by Carbon-Ghost** [comment]
Also reported in PM about the Rotary Macerator, the upgrade slots are "present" but not visually ^^''

**Comment by Carbon-Ghost** [comment]
Also reported in PM about the Rotary Macerator, the upgrade slots are "present" but not visually ^^''

**Comment by Carbon-Ghost** [comment]
Why the hell did my msg spammed 3 times ...

**Comment by Speiger** [comment]
Yeah sry i was thinking while i created the GUI Code that i have the same engine as in TMT.
(It autodraws slots, progressbars and the gui itself) and i forgot that one.
Lool the Recycler did work on my side. Maybe my sync program did not detect the file...
Or me beeing derp. Who knows^^

**Comment by Speiger** [comment]
Fixed.

**Comment by Carbon-Ghost** [comment]
Another bug, recycler doesn't have 2 input slots like induction furnace ;(

**Comment by Speiger** [comment]
Immibis version did not had that either and since he did create that ill stay with that...

**Comment by Carbon-Ghost** [comment]
Well it's supposed to be an equivalent to induction furnace, sure I am ok with the extractor following this convention, but imo, compressor, macerator and furnace should have 2 input-output slots ;P

**Comment by Carbon-Ghost** [comment]
Advanced version ofc ;P xD
