### ISSUE TITLE
Allow FE/RF to be converted back to EU (please read first before denying)

### ISSUE THREAD

**Issue by SigmaFlame** [TinyModularThings/IC2Classic#851]
Hello,

I know your point: you do not want RF to be converted to EU because of mods like Extreme Reactors that completely destroy the energy economy of your mod.

But...

For those who play with only few mods, like me with only Create, Create & Additions, Pneumatic Craft.
A convenient way to get the power back from these mods would be really appreciated.

Or...

You can add machines that are able to get the power from only these mods.
These mods that you know there are not too powerful and will not break your mod.

Thank you in advance.

**Comment by Speiger** [comment]
o/ My answer isn't going to change.
Mainly for the reason that I haven't played with these mods yet.

And we only add compat to anything we we actively use and want.

Ignoring that, create would immediately fall under the exact same problem RF/FE falls under.

The best power generation (a 2x2x? Steam boiler) should produce 512EU Max. That turns the Stress units -> EU conversion to 0.0017x 

So a fully maxed out windmill produces 14EU.
A waterwheel at 320RPM produces 0.5EU, which is maybe a bit to high...
Especially for it's price.

But you see how this is already a major problem.


The other way around is a different story.
That could be argued. Though it would break the create mod balance or be useless. Nvm then.


Now about pneumatic craft, I have no idea how their balancing is so I can't judge that.
But that automatically makes it a no too for the first point.


I am sorry if that answer is not satisfactory to you.
But I hope you understand.

Have a great week!
