### ISSUE TITLE
crash ic2c bug

### ISSUE THREAD

**Issue by Lonelyxiya** [TinyModularThings/IC2Classic#852]
[crash-2023-07-30_13.47.53-client.txt](https://github.com/TinyModularThings/IC2Classic/files/12208576/crash-2023-07-30_13.47.53-client.txt)

**Comment by GitJhopa** [comment]
1.12.2 lol

**Comment by Meduris** [comment]
@GitJhopa if you have some useful stuff to say, sure go ahead.

But we do **NOT** need you here spamming useless bullshit like ``1.12 lol`` or whatever crap you think of on random issues.

That is not going to help anyone and is not welcome here

**Comment by Speiger** [comment]
@Lonelyxiya sorry that it took so long.
I checked out the issue and the recipe in question is the "Thermal Generator".
Which uses a Magma Block.
![javaw_tDoScU4V1E](https://github.com/TinyModularThings/IC2Classic/assets/2556269/9b972783-5a5c-4d3e-bce7-316ae2034c74)
You must have added a mod that modifies said block to be invalid.

This is not a IC2Classic bug.
