### ISSUE TITLE
Crash IC2 

### ISSUE THREAD

**Issue by ShiftyMLG** [TinyModularThings/IC2Classic#853]
When crafting a plasma core which is a recipe that requires multiple items for certain slots of the recipe, my game instantly crashes.
<img width="265" alt="CleanShot 2023-07-31 at 16 02 16@2x" src="https://github.com/TinyModularThings/IC2Classic/assets/36298934/be534c2f-bf34-437a-bdd3-1270dbaefe65">

**Comment by Meduris** [comment]
Can you please post a crashlog and the minceraft and ic2classic version you are using? Without that we can't do anything about this

**Comment by ShiftyMLG** [comment]
Thought you was gonna ask this. Apologies. Version is 2.2.999
https://mclo.gs/cezLmQ5

**Comment by Speiger** [comment]
@ShiftyMLG thank you.
Did you try that with Just IC2Classic or with a modpack?
Can you confirm this is a IC2 Classic bug or a Modpack bug?

**Comment by ShiftyMLG** [comment]
It was with tekkit 2. How can I find out if it’s modpack related or not?

**Comment by Speiger** [comment]
@ShiftyMLG no worry xD
@xjon your turn please.
