### ISSUE TITLE
Crash when crafting Pump

### ISSUE THREAD

**Issue by joaopatrocinio** [TinyModularThings/IC2Classic#854]
The mod crashes when trying to craft a Pump. Crash report below.
Mod version: IC2Classic-1.19.2-2.0.6.2

![image](https://github.com/TinyModularThings/IC2Classic/assets/28317418/d73ab40b-7a8f-4321-9a43-0442dc48b0cc)

[crash-2023-08-01_09.33.41-server.txt](https://github.com/TinyModularThings/IC2Classic/files/12226330/crash-2023-08-01_09.33.41-server.txt)

**Comment by Geekerandy** [comment]
Based on a glance at your crash report, can you make a backup of your world, disable Immersive Engineering, and then retry crafting it?

**Comment by CrossVas** [comment]
Seems to be related to this issue on IE's github page: https://github.com/BluSunrize/ImmersiveEngineering/issues/5690

**Comment by Speiger** [comment]
I would classify that as a forge bug but i can also see how this is just a dick move by forge...

I will address this in the next patch.
No ETA atm.
