### ISSUE TITLE
Rocket mode crashing the game if you hold it more than 10 secs

### ISSUE THREAD

**Issue by Kevitachi** [TinyModularThings/IC2Classic#855]
I was testing limits with the rocket mode of the upgraded electric jetpack and i found that if you hold it a little more than usual the game will crash

Version 1.19.2 2062

**Comment by Speiger** [comment]
without a crashlog there is nothing i can do. also did you make sure it wasn't a duplicate?

**Comment by Kevitachi** [comment]
Of course, let me do it again and i will post the png

**Comment by Speiger** [comment]
@Kevitachi just drag & drop the crashlog file itself.

**Comment by Kevitachi** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/84929565/4d4ed291-4d0d-4ce5-b3f1-d500f411b1a4)

[crash-2023-08-05_17.16.47-client.txt](https://github.com/TinyModularThings/IC2Classic/files/12268103/crash-2023-08-05_17.16.47-client.txt)

**Comment by Speiger** [comment]
@Kevitachi known bug will be fixed in the next patch.
