### ISSUE TITLE
Why IC2Classic doesn't have RF/FE->EU support and never will

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#856]
I have recently found this explanation by [VT-14](https://www.reddit.com/r/feedthebeast/comments/15jvnv3/comment/jv2p58c/?utm_source=share&utm_medium=web2x&context=3), which beautifully explains why IC2Classic doesn't have RF/FE to EU generation and also never will have it.

## VT-14s Explanation

"Open" Power Converters are fundamentally broken. IC2's EU and the vast majority of mods using RF/FE were never designed with each other in mind, so they have massively different scaling factors. The only mods adding a "Open" power conversion, and by that I mean the ability to turn any source of RF into any consumer of EU, and usually visa versa, do not give a crap about balance and typically rip the heart out of EU's mechanics.

When looking at IC2's Reactor output, its worth remembering that the mod's largest battery (the MFSU) can only output a single 2048 EU Packet every Tick, and the top tier cables can only support up to 8192 EU Packets. IC2 was designed with those values being very late-game. Those limits are also its main balancing mechanic for its upgrades; you can just throw a ton of Overclocking upgrades in a machine until it is processing 1 item per tick (if not up to an entire stack of items every tick)... but you would need something like 700 MFSUs to do it! Possible, but quite impractical.

Reminder that on the other end of the spectrum, IC2 starts out with a Coal generator that produces 10 EU/t.

--------------------------------------------------------------------------------------------------------------------------------------------------

RF Coal Generators tend to start out around 40-80 RF/t. The upper end is highly dependent on how power creeped the mods you are using have gotten. 5k RF/t is usually pretty trivial. A lot of reactors and such seem to aim for the 25k RF/t mark. A few just... keep going up.

So, what is a "fair" conversion between EU and RF? Should we balance around the Coal Generator end? There 1 EU to 4 RF sounds pretty fair... but at the high end we have a roughly 1k EU/t reactor converting to only 4k RF/t, where as other RF mods for less effort are producing 25k+ RF/t. EU's generators are massively underperforming here, but worse is that you can pump that RF into EU and blow IC2's power balance out of the water, especially when you have especially power creeped mods generating millions of RF/t; so much for needing '700 MFSUs' when you have Mekanism and its Ultimate Universal Cables and insanely powerful Reactors!

Ok, so what about balancing around the 1k EU = 25k RF mark? Well we do now have the more moderate reactors seeming more balanced... but now IC2's Coal Generator is producing an insane early-game 250 RF/t, and Mekanism is still generating so much power that EU's power infrastructure is still blown out of the water.

Ok, so what about a scaling conversion? 10 EU = 40 RF and 1k EU = 25k RF? This idea could actually work... for "Closed" power converters such as Advanced Generators [strictly a power producer] or Applied Energistics 2 [strictly a power consumer]; these are strictly controlled by the mod adding the conversion, and frankly doesn't even really look like a conversion ("My ME system needs 250 EU/t"). With an Open converter you've simply made a way to generate power simply by converting between the two systems and limiting the throughputs. 100x 40 RF/t inputs (4,000 RF/t) produces a combined 1,000 EU/t, which converts into 25k RF/t, for a net increase of 21k RF/t.

**Comment by Aidan647** [comment]
It would be greate to have some integration with Applied storage or Refined storage
