### ISSUE TITLE
Export upgrade dont work on extractor.

### ISSUE THREAD

**Issue by dez64ru** [TinyModularThings/IC2Classic#857]
Seems to be export upgrade don't work for some cases.

https://github.com/TinyModularThings/IC2Classic/assets/32451886/e4efe021-1cea-4c1c-8c4a-57183924c7c7

**Comment by CrossVas** [comment]
Yes, this is happening because the output slot has the `Top` side disabled in the `Machine Access Control` tab. If you enable it, it'll work.
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/f84e3301-b7cc-4444-adbb-78ea3f682385)

**Comment by Speiger** [comment]
@dez64ru well @CrossVas is correct. Not a bug

**Comment by dez64ru** [comment]
@Speiger not sure about it.
https://youtu.be/_l4VSyhmKbw

**Comment by dez64ru** [comment]
Also, while i had test it (click on every button in machine settings) import upgrade also breaks (on valid settings, all inputs/outputs are had allowed). Only when I reinstall the extractor block, import upgrade start work.

**Comment by dez64ru** [comment]
nvm, i`ve got it.
