### ISSUE TITLE
Treetap usage by a fake player

### ISSUE THREAD

**Issue by neksword** [TinyModularThings/IC2Classic#859]
I am trying to automate alcohol production and it seems that treetap cannot be put on the barrel to stop brewing by a fake player. Is it so? I am using IntegratedDynamics and Player Simulator tries to use a treetap but then just puts it back into the chest. But whisky grist, water can be easily put also also whisky can be drained.

**Comment by Speiger** [comment]
@neksword the barrel does the logic with the whisky grist and water.
While placing the treetap on the barrel happens on the "item" logic.

In other words if you know how to call the "useOn" function with Integrated dynamics then it should be fine.
(if you know how to automate the rubber tree using fake players, its the exact same way with the barrel)

**Comment by neksword** [comment]
@Speiger I am sorry but I do not understand your point. What does “item”logic means? I am trying to right-click the barrel with a treetap. It works with putting grist and water

**Comment by Speiger** [comment]
@neksword there is 2 sides of a rightclick with an item.
- The Block side: When a block is clicked on, it will do some logic based on that. (Setting your spawn when clicking on a bed, or opening the gui when clicking on a furnace)
- The Item side: Hoe turning dirt to farmland, bucket placing water, ender crystal spawning the crystal.

The watercells/whisky grist is on the block side, while the treetap is on the "Item side"

you have to ask the Integrated dynamics dev about it.
You can reference this issue to him maybe he has an answer.

But this is not a bug.
