### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by busa4** [TinyModularThings/IC2Classic#860]
java.lang.NullPointerException: Cannot invoke "ic2.core.energy.EnergyNetLocal$Connectivity.get(boolean)" because the return value of "java.util.Map.get(Object)" is null at ic2.core.energy.EnergyNetLocal.getConnectivity(EnergyNetLocal.java:858) ~[common-IC2Classic-1.19.2-2.0.6.2.jar%23208!/:1.19.2-2.0.6.2] {re:classloading} at ic2.core.energy.EnergyNetLocal.discoverPaths(EnergyNetLocal.java:878) ~[common-IC2Classic-1.19.2-2.0.6.2.jar%23208!/:1.19.2-2.0.6.2] {re:classloading} at ic2.core.energy.EnergyNetGrid.updatePaths(EnergyNetGrid.java:223) ~[common-IC2Classic-1.19.2-2.0.6.2.jar%23208!/:1.19.2-2.0.6.2] {re:classloading} at ic2.core.energy.EnergyNetGrid.processChanges(EnergyNetGrid.java:206) ~[common-IC2Classic-1.19.2-2.0.6.2.jar%23208!/:1.19.2-2.0.6.2] {re:classloading} at ic2.core.energy.EnergyNetLocal.onTickStop(EnergyNetLocal.java:136) ~[common-IC2Classic-1.19.2-2.0.6.2.jar%23208!/:1.19.2-2.0.6.2] {re:classloading} at ic2.core.energy.EnergyNetGlobal.onWorldTickStop(EnergyNetGlobal.java:161) ~[common-IC2Classic-1.19.2-2.0.6.2.jar%23208!/:1.19.2-2.0.6.2] {re:classloading} at ic2.core.platform.events.IC2EventHandler.onWorldTickEvent(IC2EventHandler.java:443) ~[common-IC2Classic-1.19.2-2.0.6.2.jar%23208!/:1.19.2-2.0.6.2] {re:classloading,pl:runtimedistcleaner:A} at ic2.core.platform.events._IC2EventHandler_onWorldTickEvent_LevelTickEvent.invoke(.dynamic) ~[common-IC2Classic-1.19.2-2.0.6.2.jar%23208!/:1.19.2-2.0.6.2] {re:classloading,pl:eventbus:B} at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2384!/:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2384!/:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2384!/:?] {} at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactoryMixin.java:820) ~[forge-1.19.2-43.2.11-universal.jar%23242!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.forge.json:ForgeEventFactoryMixin,pl:mixin:A} at net.minecraft.server.MinecraftServer.m_5703(MinecraftServerMixin.java:872) ~[server-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B} at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A} at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127) ~[server-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23237!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B} at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin}

**Comment by Speiger** [comment]
A duplicate, can be fixed in the config.
Though will be depricated in the next patch.
