### ISSUE TITLE
How to add custom recipies to macerator now?

### ISSUE THREAD

**Issue by vaziliybober** [TinyModularThings/IC2Classic#861]
Hello, thank you for this mod!

I play 1.19.2 with ic2c with ae2, and i'd like to be able to put my certus quartz crystals in macerator in order to get certus quartz dust.

In previous versions of ic2, like 1.12.2, I could put a macerator.ini file in my .minecraft/config/ic2 folder and specify all the desired recipies for macerator.

It seems I can no longer do it this way. Could you please tell me how to do it in ic2c 1.19.2? And if there is no way currently, maybe it would be good to add such customization to the mod?

Thanks again!

**Comment by CrossVas** [comment]
The way you play AE2 on 1.19.2 has changed compared to 1.12.2. 
I would suggest checking out the actual way of playing with AE2 on 1.19.2 before going into this.

Now back to customizing IC2Classic's recipes.
IC2Classic for 1.19.2 uses a datapack driven recipe system for almost every machine, so all you have to do is make a datapack, containing all the recipes needed. More info about this here: [IC2C wiki](https://github.com/TinyModularThings/IC2Classic/wiki/1.19.x-ResourcePacks)

How to get the datapack:
1. To get the ic2 datapack you need to type in the `/ic2c_export` command, then a datapack `.zip` archive will be saved at `<mc_directory>/config/ic2c`.
2. Add the new files to the folder of the specific machine you need (`canner`, `compressor`, `extractor`, `macerator`, etc.), check `data/ic2/ic2_recipes` for available machines. 

For Reference: [how to create a datapack](https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack)

**!!! MAKE SURE TO REMOVE THE UNCHANGED FILES. ONLY KEEP THE ONE YOU EDITED / ADDED!!!**

**Comment by vaziliybober** [comment]
Thank you for your answer and the tip! I will definetely check out the ae2 1.19.2 changes first now.

**Comment by SikiciBebek** [comment]
Where do i put the changed/recreated file?
