### ISSUE TITLE
Attempting to get redstone signal from reactor heat via machine tool (but it doesnt exist in the mod)

### ISSUE THREAD

**Issue by azrellie** [TinyModularThings/IC2Classic#865]
I'm trying to use a comparator to get a redstone signal strength from the heat in a nuclear reactor using the machine tool. but for some reason, the machine tool doesnt even exist in the mod.

![image](https://github.com/TinyModularThings/IC2Classic/assets/98503938/c6532c92-4f92-4a80-bccb-8117e059ccfd)

Game version: 1.19.2
Mod version: 1.19.2-2.0.6.2
Forge version: 43.2.14

**Comment by EnderVonSlayer** [comment]
The machine tool was removed in favor of the "C" buttom that allows for specific comparator data to be configured

**Comment by azrellie** [comment]
> The machine tool was removed in favor of the "C" buttom that allows for specific comparator data to be configured

Did not expect such a fast reply, but anyway. How am I supposed to use the comparator data to get a redstone signal strength based on reactor heat (this feature is completely new to me)?

**Comment by azrellie** [comment]
> > > The machine tool was removed in favor of the "C" buttom that allows for specific comparator data to be configured
> > 
> > 
> > Did not expect such a fast reply, but anyway. How am I supposed to use the comparator data to get a redstone signal strength based on reactor heat (this feature is completely new to me)? Is there any tutorials for it?
> 
> The easiest way to do this is selecting the `Heat` option from the `Sources` list.
> 
> ![image](https://user-images.githubusercontent.com/25727222/263876905-dcbf03e8-bcf0-47a3-a29a-02d2ef552ed6.png)

Ah I see. Appreciate the help you two.
