### ISSUE TITLE
[1.19.2 Forge] crash server

### ISSUE THREAD

**Issue by GitJhopa** [TinyModularThings/IC2Classic#866]
[crash-2023-09-04_18.09.28-server.txt](https://github.com/TinyModularThings/IC2Classic/files/12516139/crash-2023-09-04_18.09.28-server.txt)

**Comment by Speiger** [comment]
@GitJhopa very specific setup in the energy grid. 
You can either provide a setup that allows me to fix it or you simply turn it off in the config.

Note that next patch this config setting is removed to encurage people to report how to fix it.
@GitJhopa close if you want to just use the config.

**Comment by GitJhopa** [comment]
https://pastebin.com/6gLqx0q9

**Comment by Speiger** [comment]
Found the issue.
