### ISSUE TITLE
 The Filtered Extraction Tube cannot maintain the quantity of items beyond one stack

### ISSUE THREAD

**Issue by IR8104** [TinyModularThings/IC2Classic#869]
When I use the Filtered Extraction Tube to keep items, they do not stack beyond one stack, and it works fine; any excess items are extracted. However, when I set it to over two stacks, the Tube still extracts more than one stack's worth.

For example, when I try to keep 128 sands, and there are two stacks of sands in the chest, the Tube wiil extracts the excess beyond 64 sands and only keeps 64 sands in the chest.

A similar issue occurs with non-stackable items, like cakes. When I try to keep 3 cakes in the chest, and there are originally 3 cakes in the chest, it only keeps one cake, and the extras are taken away by the Filtered Extraction Tube.

**Comment by Speiger** [comment]
Ty for reporting it
yep found the issue.
But that issue was even before 2.0.7.
And right now ic2c is on cooldown for few months for patches because i do love to bulk patch them.
Please leave this issue open because next time i do a patch it will be a addressed.
(Not a matter of if, but when)

**Comment by Speiger** [comment]
Fixed in the next patch which should be out any minute (at the time of writing)
