### ISSUE TITLE
Crash 1.19.2 Biomes O Plenty

### ISSUE THREAD

**Issue by msanabria99** [TinyModularThings/IC2Classic#871]
Hello, I entered the nether for the first time and am currently experiencing a crash every time. I was able to isolate it to just IC2 Classic crashing when loaded together with Biomes O Plenty. Everything loads fine when in the Overworld but the moment I enter a Nether portal, I am greeted with nothing but a void and then crash. Hopefully, this is something that could possibly be fixed in a upcoming update as both mods are wonderful to have. I know it isn't a RAM problem as I give Minecraft more than 8gbs of RAM. 
[crash-2023-09-10_00.20.59-server.txt](https://github.com/TinyModularThings/IC2Classic/files/12567491/crash-2023-09-10_00.20.59-server.txt)

**Comment by Speiger** [comment]
Hello. I don't know how that is ic2s fault when the crashlog doesn't even contain ic2.

Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / biomesoplenty:withered_abyss]=net.minecraft.world.level.biome.Biome@cfaa2ae}]

**Comment by CrossVas** [comment]
Found some old issues, that might be related: 
https://github.com/Glitchfiend/BiomesOPlenty/issues/2083

More references here: 
https://forums.minecraftforge.net/topic/123680-what-am-i-doing-wrong-here-with-adding-features-to-my-biomes-minecraft-1182-solved/
and here: 
https://misode.github.io/guides/feature-order-cycle/

After adding 'cyanide' mod, I got this:

```
com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

Cycle:
At step 6
Feature 'ic2:ore_silver'
  must be before 'ic2:ore_silver' (defined in 'biomesoplenty:visceral_heap' at index 2, 5 and 8 others)
```

Hope this will help :)

**Comment by msanabria99** [comment]
> Found some old issues that might be related: [Glitchfiend/BiomesOPlenty#2083](https://github.com/Glitchfiend/BiomesOPlenty/issues/2083) [Glitchfiend/BiomesOPlenty#2109](https://github.com/Glitchfiend/BiomesOPlenty/issues/2109)
> 
> More references here: https://forums.minecraftforge.net/topic/123680-what-am-i-doing-wrong-here-with-adding-features-to-my-biomes-minecraft-1182-solved/ and here: https://misode.github.io/guides/feature-order-cycle/
> 
> After adding 'cyanide' mod, I've got this in my crash log:
> 
> ```
> com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.
> 
> Cycle:
> At step 6
> Feature 'ic2:ore_silver'
>   must be before 'ic2:ore_silver' (defined in 'biomesoplenty:visceral_heap' at index 2, 5 and 8 others)
> ```
> 
> Hope this will help :)
> 
> EDIT: Disabling both overworld and nether silver ores seems to prevent minecraft from crashing on Nether load.

This did work, thank you!

**Comment by Speiger** [comment]
@msanabria99 found the issue. I had all 3 ores (silver/nether ores) registered as SILVER ORE... OFC that breaks shit...
Patch will come out later today.

**Comment by Speiger** [comment]
Fixed in the next patch which should be out any minute (at the time of writing)
