### ISSUE TITLE
Nuclear jetpack rocket mode crashes game when released in singleplayer

### ISSUE THREAD

**Issue by azrellie** [TinyModularThings/IC2Classic#873]
When the rocket mode on the compacted nuclear jetpack is charged to any amount and released, it plays an explosion sound effect and then crashes the game (tested on singleplayer).
![image](https://github.com/TinyModularThings/IC2Classic/assets/98503938/f6d04ae7-3110-4b49-857a-66dde6686880)

Crash logs:
[crash-2023-09-18_14.13.17-client.txt](https://github.com/TinyModularThings/IC2Classic/files/12653564/crash-2023-09-18_14.13.17-client.txt)

Mod version:
1.19.2-2.0.6.2

**Comment by Speiger** [comment]
@Speiger fixed in the latest patch
