### ISSUE TITLE
Crash when placing IC2 signs with The Aether (1.0.0-beta.1.2-forge) installed (1.19.2-2.0.7.1).

### ISSUE THREAD

**Issue by togera13** [TinyModularThings/IC2Classic#876]
When using The Aether along with Industrial Craft 2 Classic the game will crash when **any sign from IC2C** is placed, Aether signs are completely unaffected.

I went around and placed a bunch of blocks with the Aether & IC2C installed & the only time the game crashed was when I placed any sign from the IC2C mod, I have yet to find any other crashes though I did not use every machine & item from either mod, I did however place most IC2C blocks & Items to see if the signs were the only problem & only ran into issues when any sign from IC2C was placed.

Mods installed:
aether-1.19.2-1.0.0-beta.1.2-forge
curios-forge-1.19.2-5.1.4.1
IC2Classic-1.19.2-2.0.7.1
theoneprobe-1.19-6.2.2

Mod Links:
https://www.curseforge.com/minecraft/mc-mods/aether/files/4771515
https://www.curseforge.com/minecraft/mc-mods/ic2-classic/files/4746971
https://legacy.curseforge.com/minecraft/mc-mods/curios/files/4523009
https://legacy.curseforge.com/minecraft/mc-mods/the-one-probe/files/3965693

Exit Code:
The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m_119194_(net.minecraft.client.renderer.MultiBufferSource, java.util.function.Function)" because "$$12" is null

Crash Log Forge 1.19.2 (3.3.0) As soon as the sign was placed:
[crash-2023-10-04_12.52.49-client.txt](https://github.com/TinyModularThings/IC2Classic/files/12806143/crash-2023-10-04_12.52.49-client.txt)
Crash Log Forge 1.19.2 (3.3.2) Reloading into the world that it was placed in:
[crash-2023-10-04_12.56.37-client.txt](https://github.com/TinyModularThings/IC2Classic/files/12806183/crash-2023-10-04_12.56.37-client.txt)
Crash Log Forge 1.19.2 (3.3.2) The Aether & IC2C only (curios & the one probe disabled) Reloading into the world it was placed in:
[crash-2023-10-04_13.14.22-client.txt](https://github.com/TinyModularThings/IC2Classic/files/12806293/crash-2023-10-04_13.14.22-client.txt)

The crash can be worked around by disabling The Aether & getting rid of every IC2C sign then re-enabling The Aether, or by disabling IC2C loading in & then re-enabling IC2C when the sign is gone. So, the mods can still currently be used together, but the Industrial Craft 2 Classic signs need to be avoided like the plague in order for no conflict to happen & if the crash happens one mod will have to lose its progress to resolve it.

**Comment by xiPakuL** [comment]
Can confirm this, is there an eta on this?
It just borked my world for me and i extensively used both mods so i can't just remove one to get back into the world.

**Comment by xiPakuL** [comment]
For anyone coming to this later, i solved the issue by looking at the blocks coordinate in the Crash-Report and using the /setblock command in the server console to remove the sign.

**Comment by Speiger** [comment]
Aether and @bconlon1 helped me figure it out @togera13 and @LKD-PIX
Basically when we added the blocks in 1.14.4 
This function didn't exist:
https://github.com/The-Aether-Team/The-Aether/blob/1.20.1-develop/src/main/java/com/aetherteam/aether/client/AetherAtlases.java#L26

This will be a pretty simple fix :)
