### ISSUE TITLE
Client Crash when using the Crop Library (1.19.2-2.0.7.1)

### ISSUE THREAD

**Issue by PianoManu** [TinyModularThings/IC2Classic#877]
[crash-2023-10-07_14.33.47-client.txt](https://github.com/TinyModularThings/IC2Classic/files/12837768/crash-2023-10-07_14.33.47-client.txt)

Hello there! I'm the weird guy from CurseForge who asked how the planter pots work. I was messing around with the crop library (I think this is what it was called), when my client crashed. I tried to figure out twice which Item exactly causes the crash, but I was unable to keep track of whenever the crash happens. Maybe it has something to do with Mystical Agriculture or Apotheosis. I'll provide further information once I've figured out the Item causing the crash. Concluding from the crash-report, it has something to do with some Tooltip...

I am using the newest version available on CurseForge. Also, I've searched through the issues and did not find anything related, so hopefully, this is not a duplicate.

Thanks in advance!
Regards, Manu

**Comment by PianoManu** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/59123244/847643e7-fda4-4c8f-a7a2-6865e6c21cab)

I have additional information. I somehow managed to pick up an **empty** planter's pot. Whenever I hover over this item inside the crop library's GUI, the client crashes

**Comment by Speiger** [comment]
Yeah how the f did you get the empty planter pot...
I implemented logic to prevent that....

**Comment by PianoManu** [comment]
Sorry for the late response. I'm uncertain how I managed to collect this pot in the first place. However, I got another one later on, when I used the give command with the NBT tag being the ID of a farmland block from Mystical Agriculture

`{id="mysticalagriculture:inferium_farmland"}`

I checked multiple times and it wasn't misspelled, so I figured that you cannot have planter pots of modded blocks. Maybe you could check for invalid tags and give the player the standard planter pot instead? Just an idea 😊

Thanks a bunch, and have a great weekend!

**Comment by Speiger** [comment]
@PianoManu technically i am testing if they are valid farm lands. Maybe one of the filters isn't strict enough.

**Comment by PianoManu** [comment]
It probably isn't even that important, since I only got it reliably via /give which is unavailable to the common player. I cannot figure out how I got the pot that crashed my game initially however... And taking in account how long the version is already released and no one encountered this error besides me, I guess you can just ignore it. At least it made me feel special for once in my life 😂
