### ISSUE TITLE
Bronze tool recipes are not reversible

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#878]
Vanilla hoe and axe recipes can be horizontally flipped and will still work. Your bronze hoe and axe recipes should work that way too.

![image](https://github.com/TinyModularThings/IC2Classic/assets/4080989/eda2c533-41a1-44f9-8ec8-639cf9b44f3b)

I'm using `IC2Classic-1.12-1.5.8.jar` and `1.12.2-forge-14.23.5.2859.jar`.

**Comment by Speiger** [comment]
Not a bug
