### ISSUE TITLE
CobbleGen Upgrade recipe doesn't accept Lava Cells

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#879]
The CobbleGen Upgrade's recipe accepts either a Water Cell or a Water Bucket on the right, but it only accepts a Lava Bucket on the left. It does not accept a Lava Cell. I think it should work with both.

![image](https://github.com/TinyModularThings/IC2Classic/assets/4080989/45435f20-54d6-47b9-b177-34e5804c49ae)
![image](https://github.com/TinyModularThings/IC2Classic/assets/4080989/1e27fec6-be80-4f6b-a51d-09180e68e73d)
I'm using `IC2Classic-1.12-1.5.8.jar` and `1.12.2-forge-14.23.5.2859.jar`.

**Comment by Speiger** [comment]
Intended
