### ISSUE TITLE
Nanosaber Sound spam when not charged

### ISSUE THREAD

**Issue by nanakisan** [TinyModularThings/IC2Classic#88]
Dunno how to explain this one. But when the nanosaber has no power left. Instead of playing it's on/off sounds 1 time. It gets stuck and constantly spams the sounds. This happens more consistently when you spam turning on and off. It's like the sound source is caught in a loop. Pausing the game seems to fix this issue however. But only until the saber does it again

**Comment by Speiger** [comment]
Ok. Need to test that.
Maybe i fixed that already in the 1.1.0 version...

**Comment by Speiger** [comment]
Turns out that the whole Nano Saber needs a rewrite (the 3rd time now). Working on it.
Audio Spam no clue why it comes i try to solve it... (it has something todo with moving sounds)

**Comment by Speiger** [comment]
Fixed. Stupid amount of work because of bugs...
