### ISSUE TITLE
Ingrident crops

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#880]
Some crops (for example, Tea) have the "Ingrident" attribute. Other crops (for example, Hops) have the "Ingredient" attribute.

If this was just a typo it wouldn't be a big deal, but I think the fact that this is inconsistent affects crop breeding. Tea and Hops are supposed to get a bonus because they have "Ingredient" as a matching attribute, but because one of them is misspelled it actually doesn't match.

All of the Ingrident crops should be changed to Ingredient.

I'm using `IC2Classic-1.12-1.5.8.jar` and `1.12.2-forge-14.23.5.2859.jar`.

**Comment by Speiger** [comment]
Ty
