### ISSUE TITLE
Some tools accept inapplicable enchantments

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#881]
![image](https://github.com/TinyModularThings/IC2Classic/assets/4080989/a3250d6b-2b67-4b74-8756-8eacfb73618e)

Shields shouldn't be able to have those enchantments, and I doubt they even work. I've seen the same issue with Electric Treetap, and it probably affects other tools too.

I'm using `IC2Classic-1.12-1.5.8.jar` and `1.12.2-forge-14.23.5.2859.jar`.

**Comment by Speiger** [comment]
Ty.

**Comment by Speiger** [comment]
@dwentz89 just checked it.
This is only possible while you are in creative mode.
Where minecraft disables all "Validity checks".

This is not an IC2C bug.

**Comment by Speiger** [comment]
@dwentz89 yeah ok that is a good example.
Good that i didn't finish the update yesterday.
I will patch it today and depending how long i wait on responses on other issues it will either release tonight or tomorrow.
