### ISSUE TITLE
Chainsaw drops both normal drops and shear drops

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#882]
Mining blocks with the Chainsaw causes them to drop both their normal drops from being mined with a regular tool, AND their special drops from being mined with shears. The only block I've found in vanilla that this affects is leaves, but I'm sure there are modded blocks where this is a much bigger issue.

The Chainsaw should only make blocks generate one type of drops, not both.

![image](https://github.com/TinyModularThings/IC2Classic/assets/4080989/69177c7b-2bf9-4741-aa9b-0243ae183720)
![image](https://github.com/TinyModularThings/IC2Classic/assets/4080989/586ad74a-e22c-4ffa-9bfb-51a38cdd19b3)
![image](https://github.com/TinyModularThings/IC2Classic/assets/4080989/c6abd11f-84bf-4fb2-bdfd-3eaae62dfb6f)

I'm using `IC2Classic-1.12-1.5.8.jar` and `1.12.2-forge-14.23.5.2859.jar`.

**Comment by Speiger** [comment]
That is actually a vanilla mechanic iirc.

**Comment by dwentz89** [comment]
No, it's not vanilla. When you mine Leaves with Shears, they never drop Saplings. I just tested it myself, and [the wiki also says so](https://minecraft.wiki/w/Leaves#Usage):
> Leaves that decay, or are destroyed **without using [Silk Touch](https://minecraft.wiki/w/Silk_Touch) or [shears](https://minecraft.wiki/w/Shears)**, yield [saplings](https://minecraft.wiki/w/Sapling) 5% (1⁄20) of the time, sticks 2% of the time, and otherwise drop nothing.

**Comment by Speiger** [comment]
yeah it was 3AM when i wrote that.
Still it's intended behavior.
