### ISSUE TITLE
Most reactor heat effects don't work

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#883]
The wiki says:
> - When a Reactor reaches 40% of its heat limit, random blocks within a 2-block range of the Reactor will start catching fire
> - When a Reactor reaches 50% of its heat limit, Water blocks within that area will start to randomly evaporate
> - When a Reactor reaches 70% of its heat limit, entities within a 3-block range of the Reactor will start taking damage from the radiation
> - When a Reactor reaches 85% of its heat limit, random blocks within 2 blocks of the Reactor will start transforming into Flowing Lava. Blocks with high Blast Resistance values (such as Obsidian or Reinforced Stone) can still survive this.
> - If a Reactor ever reaches its full heat limit, it will explode extremely violently, with the explosion force depending on the number of fuel cells it contains.

Only the 40% and 100% effects work. The 50%, 70%, and 85% ones never activate, no matter how high the heat gets.

I'm using `IC2Classic-1.12-1.5.8.jar` and `1.12.2-forge-14.23.5.2859.jar`.

**Comment by Speiger** [comment]
This implies 2 blocks from the core. Not the chambers.

**Comment by dwentz89** [comment]
Okay? Those effects don't work 2 blocks from the core either. Or 3 blocks. Or 4 blocks. Or 1 block.

**Comment by Speiger** [comment]
Ok i checked the code you are right. 
I am missing a divide by 100 in the logic. So right now it needs to be 700% for example.
