### ISSUE TITLE
enableGreg config is backwards

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#884]
When the "enableGreg" setting is set to true, Greg's trades are disabled. When it is set to false, the trades are enabled. That's the opposite of what the name and comment indicate.

I'm using `IC2Classic-1.12-1.5.8.jar` and `1.12.2-forge-14.23.5.2859.jar`.

**Comment by Speiger** [comment]
The config is planned to be redone anyways fairly soon, so that will be automatically fixed with it.
