### ISSUE TITLE
Many beers are uncraftable

### ISSUE THREAD

**Issue by dwentz89** [TinyModularThings/IC2Classic#885]
JEI shows a lot of types of beer that are, as far as I can tell, uncraftable.
For example, you're supposed to get "Watery" for having a very low solid/water ratio, "Lite" for a higher ratio, "", for a higher ratio than that, and so on.
However, if I use 32 Water Cells, 31 Wheat, and 0 Hops, I get "Watery Soup Brew", and if I use 32 Water Cells, 32 Wheat, and 0 Hops, I get "Soup Brew". It skipped over "Lite" completely.
Almost half of the stages get skipped like that.

I'm using `IC2Classic-1.12-1.5.8.jar` and `1.12.2-forge-14.23.5.2859.jar`.

**Comment by Speiger** [comment]
Interesting.
Not sure if ill address this.

**Comment by Speiger** [comment]
@dwentz89 i checked this. I know 4 months late.

Yeah you are right it skis from watery to invisible.
I fixed the bug found :)
