### ISSUE TITLE
Advanced diamond drill in 3x3 mode breaks all blocks and even bedrock

### ISSUE THREAD

**Issue by kitovoi111** [TinyModularThings/IC2Classic#886]
Advanced diamond drill in 3x3 mode breaks all blocks and even bedrock
Ic2 version: IC2Classic-1.19.2-2.0.7.1.jar

**Comment by Speiger** [comment]
@kitovoi111 please show video proof of that with just IC2Classic installed, that has to be shown in the video too.

**Comment by Speiger** [comment]
https://github.com/TinyModularThings/IC2Classic/assets/2556269/aaa1d636-7dbe-4757-b7c8-cb2def5c8d73

Closing

**Comment by kitovoi111** [comment]
> javaw_NY74XxoWnU.mp4 
> Closing

you cheking in server side?

**Comment by kitovoi111** [comment]
Forge 1.19.2 - 43.2.21

**Comment by kitovoi111** [comment]
Checked in Client Side - one mod - IC2. Problem actual. IC2Classic-1.19.2-2.0.7.1.jar

**Comment by Speiger** [comment]
@kitovoi111 without video proof i dont believe you.

**Comment by kitovoi111** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/147491823/864ef622-b4a6-49ff-b643-90870d73108e)

**Comment by kitovoi111** [comment]
video: https://youtu.be/nt3buNlD8i4

**Comment by Speiger** [comment]
@kitovoi111 hello CrackedLix, weren't you banned for being an asshole?
Sorry but this issue is now closed, and as i have proven you must have done something to break the mod :)
