### ISSUE TITLE
Small Visual Bug

### ISSUE THREAD

**Issue by MugooMeister** [TinyModularThings/IC2Classic#887]
When 2 or more steam tunnels are directly adjacent to each other or you place a machine structure block next to a steam tunnel multi-block, there is a visual bug. Likely due to machine structure blocks having connected textures. Attached is an image:
![2023-10-11_13 19 10](https://github.com/TinyModularThings/IC2Classic/assets/147574364/591961ee-11e4-4956-8aff-86e5820580ae)

**Comment by Speiger** [comment]
Yeah i looked into it.
And unless i am doing very drastic changes to the blocks It won't be possible to fix this.
And i attempted to fix it but failed ^^"

Sorry.
