### ISSUE TITLE
Server shuts down with OutOfMemory error

### ISSUE THREAD

**Issue by kitovoi111** [TinyModularThings/IC2Classic#888]
I checked it on Forge 1.19.2 and GoldenForge 1.19.2 kernels - the error is the same, the server completely stops working and freezes, although the server with the Create mod works stably, the assemblies are similar, only on one server is the IndustrialCraft mod, and on the other is the mod Create.

24 GB of memory allocated to the server, with 60-70 online players, the server may freeze due to electric fishing (not exactly)

log: https://drive.google.com/file/d/1akZ6CppVUSIFdXvKJi4KHad3JKOqGAqn/view?usp=sharing
jvm arguments: https://pastebin.com/b6kG94s8
jvm BellSoft JDK 17

**Comment by Speiger** [comment]
@kitovoi111 hello CrackedLix, sadly what you are doing is a issue with another mod.
Also weren't you banned for being an asshole?
Sorry but "YOU" are specifically are not supported.
Making accounts to bypass bans, will simply now cause that you will be banned without question or support.

**Comment by Speiger** [comment]
Also you are banned now
