### ISSUE TITLE
GoldenForge core + IC2 classic = critical crash server .ElectricReactorChamberTileEntity.getReactor

### ISSUE THREAD

**Issue by kitovoi111** [TinyModularThings/IC2Classic#889]
crashing: 
[crash-2023-10-14_14.22.24-server.txt](https://github.com/TinyModularThings/IC2Classic/files/12908310/crash-2023-10-14_14.22.24-server.txt)
core: https://github.com/GoldenForge/GoldenForge

**Comment by Speiger** [comment]
@kitovoi111 Hello CrackedLix,
this could be due to a different mod not IC2Classics fault.
Also GoldenForge isn't supported.
