### ISSUE TITLE
The GraviSuite addon spams the console a lot, 300MB of logs

### ISSUE THREAD

**Issue by kitovoi111** [TinyModularThings/IC2Classic#890]
![image](https://github.com/TinyModularThings/IC2Classic/assets/147491823/bc40fc4b-457b-4d04-ac2e-9c6d6b6f96c1)

**Comment by Meduris** [comment]
this is advanced solars classic.

Neither IC2 Classic nor Gravisuite.

**Comment by Speiger** [comment]
@kitovoi111 Hello CrackedLix, this is a API warning that clearly referenced that Advanced Solar Classic isn't implementing the API properly.
Meaning this is nothing that is IC2Cs fault. Please go to the author of the addon instead of me.
Also your account is banned.
