### ISSUE TITLE
crash server IC2 Classic

### ISSUE THREAD

**Issue by biglovemiss** [TinyModularThings/IC2Classic#892]
[crash-2023-10-17_08.43.23-server.txt](https://github.com/TinyModularThings/IC2Classic/files/12924731/crash-2023-10-17_08.43.23-server.txt)

**Comment by biglovemiss** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/148185815/29f51641-d12c-4875-ad83-19aac3d7f32f)

**Comment by biglovemiss** [comment]
It is now impossible to start the server.

**Comment by Speiger** [comment]
Dunno what you did but obviously this isn't supposed to happen.

Maybe a bit more detail how you achieved that could help fix this.

**Comment by biglovemiss** [comment]
I don't know, the server just won't start. I'm at the player's base and he has mechanisms there.

**Comment by biglovemiss** [comment]
latest.log : https://pastebin.com/8uTEcfPv

**Comment by Speiger** [comment]
@biglovemiss ok i am sorry for asking this.
But we have a particular spammer that i don't want to deal with.
Please show me the following folders contents: ``C:\Users`` and the entire path to your minecraft instance via screenshot.

Until that is shown no support is provided.
Have a nice day.

**Comment by biglovemiss** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/148185815/e753a3f2-186b-4621-948d-4aee0d9f0a69)
hmm okay

**Comment by Speiger** [comment]
Doesn't matter at this point.
We have found evidence that you are either "CrackedLix" or are part of his server group.
Either way, I don't care what the issue is it will not be supported.

And since this account was just freshly created for this issue, it will be automatically banned.
Thank you
