### ISSUE TITLE
Qol improvement and few bugs(1.19.2)

### ISSUE THREAD

**Issue by Tomat777** [TinyModularThings/IC2Classic#893]
1. Advanced drill breaks bedrock in 3x3 mode.
2. Boiler dont accept fuel.
3. Some dusts missing dust tag and some recepies could be altered for tags instead of items(like cables) for better mod compat.

**Comment by Speiger** [comment]
- 1: Already showed in other issues that it isn't a problem.
- 2: Not a bug, it accepts the fuel and the "i" button shows you what exactly.
- 3: Let me guess aluminium dust? Not a bug, also about cables, nah not needed.

**Comment by Tomat777** [comment]
https://github.com/TinyModularThings/IC2Classic/assets/146892171/b32b5469-d958-417c-8ce1-7def261a78ef

Tried drill in full clear instalation it still breaks

**Comment by Speiger** [comment]
well that means the version i am using has patches in it that never made it into a release.
Meaning it will be released next patch automatically
