### ISSUE TITLE
No wiki page about refinery

### ISSUE THREAD

**Issue by gudvinr** [TinyModularThings/IC2Classic#894]
There is no wiki page about refinery neither here nor in-game.

E.g. it's not clear how do you fill it. When you use cell/bucket on refinery, it fills only primary tank but doesn't fill secondary tank.
And for recipes you need to fill secondary tank to use.

So, basically, it's black box and is not explained anywhere.

**Comment by CrossVas** [comment]
Input tanks can be filled by using fluid pipes or by clicking with a fluid container on the refinery itself.
Make sure the internal tank is empty before filling it. 

The only recipe that requires double fluid input is Bio Fuel.
Both Woodgas and Water can be provided by using pipes or cells.


https://github.com/TinyModularThings/IC2Classic/assets/25727222/5ccd3682-0136-4fbc-9057-ed42fe02094f

**Comment by Speiger** [comment]
@gudvinr @CrossVas explained it best.
It seem like a blackbox but the moment you try around with it it should become clear what to do.
I mean the only thing you need to figure is "how do i pump fluids into it".
And at that point is: "What previous methods in any other mod have i not tried yet?", or if this is your first mod: "What methods does the mod offer me?"

Personally it is reasonable to expect of the user to try/fail a bit to figure stuff out.
IMO its pretty boring if you get everything handfeed.

**Comment by gudvinr** [comment]
> Personally it is reasonable to expect of the user to try/fail a bit to figure stuff out.
> IMO its pretty boring if you get everything handfeed.

It's not about being handfed but rather about choice. If there's an option, no one is forcing anyone to have fun one way or another.

But this wasn't a point. There are wiki pages about even simpler machines like [furnace](https://github.com/TinyModularThings/IC2Classic/wiki/Electric-Furnace) or [geothermal generator](https://github.com/TinyModularThings/IC2Classic/wiki/Geothermal-Generator) but refinery seem to be non existent apart from recipe inside in-game book.

**Comment by Speiger** [comment]
@gudvinr that is the 1.12 documentation :)
the 1.19.2 documentation is ingame.

**Comment by Speiger** [comment]
@gudvinr which modpack are you playing?
Because IC2Classic FORCES A WIKI ON YOU

**Comment by gudvinr** [comment]
> which modpack are you playing

Just IC2C, no modpacks.  
FWIW I do use wiki, it's only refinery that's somewhat frustrating.
