### ISSUE TITLE
Mining Drill/Laser

### ISSUE THREAD

**Issue by dustojnikhummer** [TinyModularThings/IC2Classic#90]
You cannot mine blocks like Enchantment Table,CBs chunkloader,items from Forestry,some items from BC and few more blocks. Same issue is with Mining Laser. And also,Mining Laser doesnt work in horizontal mode.
Using IC2 Classic Version 1.0.9.10

**Comment by Speiger** [comment]
for the Mininglaser horizontal mode you need to click ok a block and look horizontal. 
It is like in IC2 1.4.7 or lower.
Checked that..
Everything else i will check...

**Comment by Carbon-Ghost** [comment]
Wait what ? They weren't broken last time I tried them, wait are you using a normal mining drill and a normal mining laser on obsidian level stuff xD No wonder they aren't mineable...

Although enchanting table should work, you sure it doesn't ? Last time I checked it worked wonderfully..

**Comment by dustojnikhummer** [comment]
I was using Diamond Drill. And i know how works horizotal mode in laser. But it simlpy doesnt break any block.

**Comment by Carbon-Ghost** [comment]
Weird...

**Comment by dustojnikhummer** [comment]
Wait few minutes,i will post here link to video where im showing it. And bug update, Mining Laser in Horizontal mode work only like Low Focus and horizontal.

**Comment by dustojnikhummer** [comment]
Is this useful? https://www.youtube.com/watch?v=aAVSIWjki9w

**Comment by Carbon-Ghost** [comment]
I am going to test this with the latest dev version and normal version... It seems like the drill doesn't have any mining abilities at all...  As for the laser, I am not 100% sure, but I think it's due to the blocks requiring a diamond level pick, and laser is redstone level ^^ Again gonna test...

**Comment by Carbon-Ghost** [comment]
Also saw the bug with horizontal mode...

**Comment by Carbon-Ghost** [comment]
Actually the whole mining laser is bugged
;(

**Comment by dustojnikhummer** [comment]
And i forgot one block that you cannot mine, Stone Brick.. but you can mine stone,cobble,ores and obsidian.

**Comment by dustojnikhummer** [comment]
do you know what is causing this? maybe wrong mining level calculation on each block or something like that?

**Comment by Carbon-Ghost** [comment]
Yeah, I also thought about that ;/

**Comment by Speiger** [comment]
Old IC2 (and maybe exp to) has a List of valid blocks it can break. And if the block is not contained it can not break it...
I will work later on that. I have not much time at the moment...

**Comment by Carbon-Ghost** [comment]
Well that is wrong ;P How was it able to break foreign blocks then ? And it worked...

**Comment by Speiger** [comment]
Maybe i broke some code after the update between 1.6.4 and 1.7.10
This version is still my custom version which was copied from immibis 1.6.4 version.
So i did the update by myself...
(Good choice)
Anyway it did work like that before and i will check that this evening... I have about 4,5 hours from now on before i need to go sleep... (Still on my way to my home)

**Comment by Carbon-Ghost** [comment]
Weird, it worked perfectly else a few versions before....

**Comment by Speiger** [comment]
Unbeliveable but this is not a IC2 Classic bug. (at least codewise),
Minecraft did never define their ToolClasses right. So the Tool is saying: I am a Pickaxe can i mine you?
Block answers: Pickaxe? What is that? Never heared of that. No you can not mine me...
Vanilla Tools simply say. Do not care if you know me i break you because you are a valid thing for me...

**Comment by Speiger** [comment]
I will do a workaround for that...

**Comment by Speiger** [comment]
Fixed.
