### ISSUE TITLE
Terraformer TFPB Radius Setting

### ISSUE THREAD

**Issue by random51** [TinyModularThings/IC2Classic#905]
Terraformer TFBP does not honor and/or remember radius setting.

Set it to 100(max), put it in Terraformer, when the terraformer completes and you get the TFBP back it is at 30(default).

Open settings gui on TFBP, set it to 100, close GUI with escape, open it again, still at 100.
Open GUI again and it is back to 30.

IC2Classic-1.19.2-2.0.7.1
1.19.2-forge-43.2.21

**Comment by Speiger** [comment]
Ty will be addressed in the next patch
