### ISSUE TITLE
[1.19.2] Crash crop sticks - Cannot get property IntegerProperty

### ISSUE THREAD

**Issue by jinkhya** [TinyModularThings/IC2Classic#909]
Hello,
Hosting FTB Genesis modpack and here's the crashlog about the crop sticks crashing : 
https://gist.github.com/jinkhya/47eacbf15793509be63b9547d807ad11

Thanks in advance,
Jin

**Comment by Speiger** [comment]
@jinkhya could you please tell me how you achieved that?
Like a bit more instructions how to replicate this

**Comment by jinkhya** [comment]
I'm trying to reproduce it but what is happening so far is, the crop is in the ae2 spacial cell and as soon as I turn it off it it crashes. Not sure why since an another player tried it and it's not crashing.

**Comment by Speiger** [comment]
I put in some bandage fix, but there is not much more i can do than that.

**Comment by jinkhya** [comment]
do you have a jar I could try ?

**Comment by Speiger** [comment]
@jinkhya no, I will publish the release.
I it will fix the crash for sure there is no doubt about it.

ETA is like a day or two at most.
I am actively working on a patch (started today)

**Comment by jinkhya** [comment]
sounds good, tyvm !
