### ISSUE TITLE
Recycler Crash

### ISSUE THREAD

**Issue by dustojnikhummer** [TinyModularThings/IC2Classic#91]
Sometimes (it could be random) recycler cause crash of server. 
This is one of crashlogs.
http://pastebin.com/4w70fT1r
Crashing with and without automation (Logistics Pipes and AE2)

**Comment by Speiger** [comment]
Yeah knowen bug. Happens always when the last item get processed. (When the progress finished) I did make there a stupid mistake. Was one of the first things i fixed... But the update needs time.
Just keep your recycler full enough that he never runs out of Resources to progress or remove the items during the progress...

**Comment by dustojnikhummer** [comment]
And can i ask you,how big is chance to get scrap from cobble (quarry)? Because im using ProjectE,and if cobble has chance,lets say 10%,i can set EMC for scrap at 10EMC = 10 cobble.

**Comment by Carbon-Ghost** [comment]
1 chance on 8 and no don't add EMC, loops will exist as it's a chance, it's not static, I also use project E, trust me ;O

**Comment by Speiger** [comment]
The chance is 12,5%
So nope do not use EMC on that.
Also If you use Metals for recycling you gain scrap metal which has a higer Amplified then scrap boxes.
That has a 25% chance per metal ingot. (oredictionary check defines what a metal is)
