### ISSUE TITLE
Infinite pipe buffer

### ISSUE THREAD

**Issue by Enroteg** [TinyModularThings/IC2Classic#911]
My friends and I created an iron generator on the server using the Create mod. To supply resources, pipes made of IС2 Сlassic were used. After we left this scheme to work for a day, a message about chunk overflow appeared in the server console. After checking everything, we did not find a problem and decided to transfer the scheme. After the object tube was broken, all hell broke loose. Gravel flew out of it at 3.5 stacks per N time. There were about 7-10 stacks of items per second. The pipe accumulated hundreds of thousands, if not millions of blocks within a day. It is necessary to limit the pipe buffer, this is a serious problem if there are more objects at the inlet than at the outlet.

**Comment by Speiger** [comment]
@Enroteg thats why the stacking pipe exists to merge things.
Luckily this is only causing a safefile increase not a networking/ups/fps problem because pipes have a limit on how many items it can process and the rest gets put into cold storage until there is room.

This is more of a layer8 issue.
