### ISSUE TITLE
Jetpack flight with inventory open

### ISSUE THREAD

**Issue by Len923** [TinyModularThings/IC2Classic#912]
A friend is playing FTB Genesis. While using the IC2Classic Jetpack, he noticed it can trigger while inside his inventory. Is it intended behaviour that you can fly while you have a UI open?

**Comment by PrincessOfEvil** [comment]
It is.Message ID: ***@***.***>

>

**Comment by Speiger** [comment]
@Len923 like the evil princess said, it is.

Why?:
Crap i am in a lavasea and i can't get out, but i can put my items away before my jetpack runs out of fuel.
Let's open my inventory: OH CRAP I AM DEAD...

**Comment by PrincessOfEvil** [comment]
A part of it is that none of the electric jetpacks can even reach the
maximum Y world height, so you can't even bank some height to transfer.Message
ID: ***@***.***
com>

>
