### ISSUE TITLE
Server crash reported in energyNet

### ISSUE THREAD

**Issue by Saereth** [TinyModularThings/IC2Classic#913]
MC: 1.19.2
IC2C: IC2Classic-1.19.2-2.0.8.jar
forge: 43.3.5

ChosenArchitect reported he crashed more than once when breaking cables after the update, he provided this crashlog. I have not reproduced the issue myself so it may be some kinda edge case I'm not sure. Let me know if I can do any additional testing for you.

https://gist.github.com/Saereth/c30a681f8886856fb8b098a229b6a11e

**Comment by Speiger** [comment]
@Saereth i am on it...

**Comment by Speiger** [comment]
@Saereth once i have confirmation that the patch works i will publish it.

**Comment by Speiger** [comment]
ok should be fixed for good!
