### ISSUE TITLE
[1.12.2] Glass Fibre Cables desync

### ISSUE THREAD

**Issue by xJon** [TinyModularThings/IC2Classic#916]
Been a known issue that sometimes occurred, e.g. https://github.com/xJon/Tekkit-2/issues/233:
> Every single one of my glass fibre cable blocks disconnect from each other when i go away from my base area to explore the world. I need to exit the server and load back to the server for the cables to return to normal.

An attempt to resolve it would be welcome, thanks :)

**Comment by Speiger** [comment]
@xJon this should be fixed now.
Went through portals (best test case) a ton of times with the patch and it never happened. So  thats a good indicator.
(Note that this is the 1.19.2 way so if that doesn't work i have 0 ways to fix it after this)

**Comment by Speiger** [comment]
@xJon thank god. Otherwise i would have had no solution anymore.
