### ISSUE TITLE
world crashes due to advanced comparator.

### ISSUE THREAD

**Issue by E100-cpu** [TinyModularThings/IC2Classic#918]
My test world keeps crashing due to the advanced comparator. I was building a Large TNT cannon and at one point directly connected a vanilla repeater (with a 4 tick delay) directly to the rear of the advanced comparator. I then activated the cannon and when the Redstone signal was about to reach the comparator the world crashed. I reloaded the world again and it immediately crashed.
[crash-2023-11-24_16.20.46-server.txt](https://github.com/TinyModularThings/IC2Classic/files/13455645/crash-2023-11-24_16.20.46-server.txt)

**Comment by Speiger** [comment]
Thank you it will be addressed in the next patch :)

**Comment by ChalinC** [comment]
The issue hasn't been fixed in curse Forget yet still crashes when "Advanced Comparator" is present in the mod

**Comment by ChalinC** [comment]
> The issue hasn't been fixed in curse Forget yet still crashes when "Advanced Comparator" is present in the mod

Nevermind It just interferes with the "Botarium" Mod , sorry for the incovinience! xD
