### ISSUE TITLE
Ranged Pump Issue

### ISSUE THREAD

**Issue by TFC-343** [TinyModularThings/IC2Classic#919]
I am on the 1.12.2 version of the mod (with the tekkit 2 pack) and cannot for the life of me get the ranged pump to work.
It can't even connect to fluid pipes like the normal pump can so I think it may be bugged.

**Comment by Speiger** [comment]
@TFC-343 you need to attach it to a tank.
Also https://github.com/TinyModularThings/IC2Classic/wiki/Ranged-Pump
