### ISSUE TITLE
[1.19.2] quantum and nonfiber armor

### ISSUE THREAD

**Issue by Enroteg** [TinyModularThings/IC2Classic#921]
quantum and nonfiber armor in a full set do not protect against any damage at all. I tried adding an energy shield upgrade to my helmet and it didn't work either. I’ll also note that in a single-player game the armor works great, but on the server (the config file has not been modified) it works a little better than diamond, and completely blocking damage is out of the question

**Comment by Speiger** [comment]
Is it magic damage?
Because that is the only damage it doesn't protect against.

**Comment by Enroteg** [comment]
fall damage, zombies, creeper/block explosion IC 2. In a single player game, armor protects against this damage, on the server it only slightly reduces it like regular armor

**Comment by Speiger** [comment]
@Enroteg do you have power inside the armor?

**Comment by Speiger** [comment]
@Enroteg tested it with both Nano & Quantum Armor.
https://youtu.be/95Jl5lSOPPs
