### ISSUE TITLE
crop died on the boost growth that the block itself gives nether/Terraward + game crush

### ISSUE THREAD

**Issue by nightmare3007** [TinyModularThings/IC2Classic#922]
Minecraft: 1.19.2
Mod: forge
pack: FTB Genesis 
IC2 Ver: IC2Classic-1.19.2-2.0.8.1.jar
it is about the netherwart over snow
the moment i did that the game crush or after a few sec the netherwart disappeared.
test in FTB and spatial storage demoantion.
[crash-2023-11-29_00.42.13-server.txt](https://github.com/TinyModularThings/IC2Classic/files/13496774/crash-2023-11-29_00.42.13-server.txt)
[crash-2023-11-29_07.20.38-server.txt](https://github.com/TinyModularThings/IC2Classic/files/13496775/crash-2023-11-29_07.20.38-server.txt)
[crash-2023-11-29_08.31.30-server.txt](https://github.com/TinyModularThings/IC2Classic/files/13496776/crash-2023-11-29_08.31.30-server.txt)
[crash-2023-11-29_08.39.22-server.txt](https://github.com/TinyModularThings/IC2Classic/files/13496777/crash-2023-11-29_08.39.22-server.txt)
[crash-2023-11-29_08.45.15-server.txt](https://github.com/TinyModularThings/IC2Classic/files/13496779/crash-2023-11-29_08.45.15-server.txt)
[crash-2023-11-29_08.53.12-server.txt](https://github.com/TinyModularThings/IC2Classic/files/13496782/crash-2023-11-29_08.53.12-server.txt)

**Comment by Speiger** [comment]
Thank you, I will address it in the next patch
