### ISSUE TITLE
Steam reactor sometimes doesn't fill with water until you reattach the pipe

### ISSUE THREAD

**Issue by gudvinr** [TinyModularThings/IC2Classic#923]
This already happened for me twice but it doesn't happen always.

When I join the game after some time being offline and send redstone signal to reactor, it drains water from internal tank but tank itself is not getting water.

I have pump (that is powered from separate source, not from reactor output) that is connected to reactor and steam tunnels also back feed water to reactor through the same inlet.

If I destroy pipe that is directly attached to reactor and put it back, it immediately starts filling with water. If I destroy any other pipe segment between water sources and reactor, it doesn't help.

**Comment by Speiger** [comment]
Ok this took a while to figure out...
But it is now finally fixed.
The issue was that the pathing was when build Reactor -> pump but when the game loads its pump -> Reactor which didn't work due to a design flaw...
UGH was that hard to debug.
