### ISSUE TITLE
Ic2C machines doen'st working

### ISSUE THREAD

**Issue by Tokemm** [TinyModularThings/IC2Classic#924]
When i put a machine, and energize it, nothing happens, the middle thunder who represents the energy dont fullfill, and the machine dont work
<img width="960" alt="Screenshot_3" src="https://github.com/TinyModularThings/IC2Classic/assets/66322854/bf833f02-fad2-4725-8d2d-2e6aea4fbb49">

But, when i put the cable in the battery (like the PESU in the left), it charge, and work, but even when i put a cable from the pesu to Machine, it doenst work too
<img width="960" alt="Screenshot_4" src="https://github.com/TinyModularThings/IC2Classic/assets/66322854/0440e265-d1dc-4ec7-a456-d97d2e2e4546">

it look like all the machines are happening that

**Comment by Geekerandy** [comment]
So you tried to 
a) send EU from a storage unit with a packet size larger than even the storage capacity of the Rotary Macerator
b) through a cable in which the EU packet is far too large for
c) sending an EU packet that exceeds the packet size limit of the Rotary Macerator
And you’re asking why it doesn’t work despite never having read the wiki book?
