### ISSUE TITLE
[1.19.2] Rubberwood Sign crash

### ISSUE THREAD

**Issue by MartinVitkovic** [TinyModularThings/IC2Classic#926]
Hi, 
After place Rubberwood Sign server crach with NPE and there is not possible join again.
I use MC 1.19.2, forge version 43.3.0, IC2Classic version 2.0.8.1, Curios API 5.1.4.3. I try it without Curios API and same issue. Are you sure that Curios API is dependencie for IC2Classic? Mod is working without Curios API.

Error msg by launcher:
`java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m_119194_(net.minecraft.client.renderer.MultiBufferSource, java.util.function.Function)" because "$$12" is null`

**Comment by Speiger** [comment]
Duplicate #876
Will be fixed next patch
