### ISSUE TITLE
Crop Analyzer isn't utilizing overclocker upgrades

### ISSUE THREAD

**Issue by Saereth** [TinyModularThings/IC2Classic#927]
Prepare: Crop Analyzer, some Overclocker Upgrades, Creative Source, EU Reader and some Unanalyzed Seeds.

Place down a Crop Analyzer next to the Creative Source.
Put EU Reader on the hotbar.
Open UI and place Unanalyzed Seeds into the machine.
Observe the rate at which the seeds are analyzed in the machine progress bar and what The One Probe is showing.
Add Overclocker Updates one at a time.
Observe that the speed does not actually increase but The One Prove is showing a smaller total time that does not progress as fast as it would imply.
Expected behaviour
Overclocker Upgrades should work on the Crop Analyzer Machine

https://www.youtube.com/watch?v=KO-W8puc_QE

originally reported here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4421

**Comment by Speiger** [comment]
Thank you will be addressed in the next patch.
