### ISSUE TITLE
FTB Genesis Crash to Desktop when hovering with IC2C Advanced jet pack and interacting with Pneumaticraft interfaces

### ISSUE THREAD

**Issue by OhmegaWolf** [TinyModularThings/IC2Classic#929]
As the title says, if im hovering with my jetpack and i right click to access a PNCR block the game will instantly crash to desktop, Crash log attached
[crash-2023-12-09_23.56.12-client.txt](https://github.com/TinyModularThings/IC2Classic/files/13626507/crash-2023-12-09_23.56.12-client.txt)

**Comment by Speiger** [comment]
I'll check on my side too, but this looks like a pneumatic craft bug @OhmegaWolf
