### ISSUE TITLE
A thing

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#93]
So I loaded my world up after you fixed the upgrade crash, and uh, this happened.
![2015-07-23_17 44 33](https://cloud.githubusercontent.com/assets/4021725/8856491/24ea9076-3163-11e5-811e-e58fc7c0855d.png)

**Comment by Speiger** [comment]
Data did not get saved-Loaded corretly. Did a replace fix it?

**Comment by Chocohead** [comment]
Seemed to. I can only presume that because the world crashed shortly after I placed it down it broke.

**Comment by Speiger** [comment]
Nope. The Reason why it did not save its data because the world did crash at the point where you put in the Modul. So it the data got never saved... ^^" Well at least it is nothing to fix anymore..

**Comment by Chocohead** [comment]
It didn't crash when I placed it, it crashed when I put the redstone inverter upgrade in the induction furnace next to it :P

**Comment by Speiger** [comment]
Yeah reason was because it try to check which upgrades which valid which caused a crash because of the wrong class i did call (i hate scala for that) that is fixed....
