### ISSUE TITLE
Filtered extraction tube durability filter doesn't work properly

### ISSUE THREAD

**Issue by nofoe4** [TinyModularThings/IC2Classic#932]
Using the filtered extraction tube I set to extract coolant cells when they have less than 75% durability than the full one as I understand. Still, it's extracting all damaged ones

https://github.com/TinyModularThings/IC2Classic/assets/135857857/8a2beaac-1007-4054-9a4f-b9ff3d0c3d53

**Comment by Speiger** [comment]
Yeah, this was on you.
You need to configure it before saving.
The settings you set it to only get saved/applied when you hit said save button ^^"

Not a bug.
