### ISSUE TITLE
transformer bug..

### ISSUE THREAD

**Issue by dlfal6338** [TinyModularThings/IC2Classic#934]
There is a bug that does not open the voltage control window even when you right-click the transformer. IC2Classic-1.19.2-2.0.8.1

**Comment by dlfal6338** [comment]
![1](https://github.com/TinyModularThings/IC2Classic/assets/9782277/b29fe4fb-bde7-46f2-8d4d-158c6e9f1932)
![2](https://github.com/TinyModularThings/IC2Classic/assets/9782277/cdd9374c-5679-4d74-b8bc-1f8d0221bfe9)

**Comment by Speiger** [comment]
@dlfal6338 this is not a bug, this was never inside the mod itself.
What you are comparing against is IC2Experimental.

IC2Classic started in 1.6.4 when IC2Experimental started.
