### ISSUE TITLE
Minor Texture Problem

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#94]
The Rotary Macerator right output slot is too far over to the right relative to the texture.
![2015-07-23_17 44 50](https://cloud.githubusercontent.com/assets/4021725/8856507/40337f00-3163-11e5-970b-b0987ba4a80a.png)

**Comment by Speiger** [comment]
Ok. I will do the adjustments...

**Comment by Carbon-Ghost** [comment]
Also request, may you please add a second input slot :3 ? For more inputs, like induction furnace :D

**Comment by Speiger** [comment]
Not for this release... Balancing Release could have it...

**Comment by Carbon-Ghost** [comment]
Thx :D

**Comment by Speiger** [comment]
Fixed...
