### ISSUE TITLE
Addition to ticket #940

### ISSUE THREAD

**Issue by Fxkz** [TinyModularThings/IC2Classic#941]
I think we're misunderstanding each other a little bit. In my understanding, you actually need to draw at most 1 new texture (or even use/adapt any of the ones you already have) I gave the example of blast furnaces, this time I will attach screenshots for clarity.

(https://github.com/TinyModularThings/IC2Classic/assets/76595035/0a70127e-ae8c-4884-a049-f8d415497dd5)

(https://github.com/TinyModularThings/IC2Classic/assets/76595035/83d483db-4434-44e7-9352-148e32186895)

 Look at them and imagine instead of a functional furnace block, for example, a regular 1x1 crusher, and instead of all other brick blocks - a regular white texture like on the side walls of any of your mechanisms. 
I understand that we can evaluate the beauty of certain things differently, but when we have a nuclear reactor structure, completely assembled from 1x1 blocks and perfectly matching the rest of the blocks, a regular crusher enlarged several times against the background of this does not fit into the style at all. 

This is not a priority fix, but I would highly recommend changing it in the future. If necessary, I am ready to offer my assistance in this matter absolutely free of charge.

**Comment by Speiger** [comment]
closing because i don't plan on changing that in this mc version
