### ISSUE TITLE
Rocket Miner and Mechanisms Wiki

### ISSUE THREAD

**Issue by Ullimunate** [TinyModularThings/IC2Classic#944]
Good afternoon, I have encountered two unpleasant problems for myself. I would say very unpleasant.
The first problem is the rocket miner. I found out about IC 2 through a video on YouTube, was immediately interested and installed the mod on my vanilla build, but that’s not the point.
The point is that even during the first viewing of the video, at the moment where they were already explaining the miner, I wondered how he extracts that very ore?
Subsequently, in my survival, I realized that the miner literally flies away and stops in some “random” places. places and digs down a pillar and somehow gets something there, I didn’t watch the process.
Let's move on to the problem, which is that this same damn miner can land on some of your buildings and just break them :/, yes, just break them.
I would like to fix this somehow, perhaps there is an opportunity to give the miner such a function that he cannot break what the player has set, and this will most likely be the solution.

The second problem is information about the machines.
And here in more detail and this is the real problem (perhaps there is a detailed wiki, but I didn’t find it :/.
I am extremely grateful for the detailed guide through the VIKI book that is given when creating the world, this book is truly useful until you get to Transformers, energy storage, mechanisms and wires.
There is no absolutely detailed information about these things.
Any other information on the Internet about Ic2 comes from 1.7.10, 1.12.2, but our mod for 1.19.2 is slightly more or less modified and most of the information is simply outdated and no longer relevant.

Let me give you an example of what I mean:
Suppose we have 4 windmills, fiberglass 120 blocks long, Energy Storage BH, transformers HH, CH, BH and then the “crusher, extractor, etc.” mechanisms.
On what information and logic should I connect all this so that it all doesn’t explode to hell and why doesn’t it explode with these very blocks?
I literally sit for hours in creative on some issues and try to understand some questions for myself, for example, how, how much EU/t fiberglass wire loss occurs after 40 blocks (that’s 2EU/t each block if that)
This is how I connect windmills, wires, energy storage, transformers and mechanisms so that nothing melts (wires) and nothing explodes and WHY, why transformers work and why at some points you need to set just HH, CH and in order to from the Energy Storage BH nothing exploded I have to install transformers HH,CH,BH.
And how to find out what the max. Can the same crusher absorb energy so as not to explode? - this information is not available.
Why does an improvement transformer work and how many pieces are needed and how.
In general, everything is not clear and I would like some answers to my questions and to understand whether this will be somehow corrected.

I would also like to know how exactly nuclear reactors work, where to get the circuit diagrams and how they appear? How to maintain stability of a nuclear reactor and why it works at all, etc.

I immediately apologize for a certain amount of water, and no, if it seemed that I was trying to offend someone or that I was angry - you are wrong, I expressed my opinion as loyally as possible regarding 3 moments that I encountered during survival.

**Comment by Speiger** [comment]
ok, wow that is a monster of a issue.

Though 90% of the issues would be solved by simply looking into the wiki.
The ingame wiki specifically which is forced upon you unless a modpack disabled it. (It is only accessible to modpacks really to disable it)

Most issues you have would be explained there.

Why we moved to an ingame wiki:
I had the choice of either hosting my own website or make the github more annoying or make an ingame wiki.
- Github Wiki: No I want it to stay for 1.12.2, and that most likely won't change.
- Self hosted wiki: If I ever forget to pay the bills or cant pay them for whatever reason its going to be taken down and if nobody has a backup, welp... So not an option either because I want something you can play in 15-20 years without having to worry that it is still there or not. (Github fulfills that requirement FYI)
- Ingame Wiki: You have to run the game anyways so why not. Its as reliable as the mod is downloadable.


### The Miner issue:
> The point is that even during the first viewing of the video, at the moment where they were already explaining the miner, I wondered how he extracts that very ore?

By digging it up. Similar how a player would. But it has some form of Xray vision.

> Subsequently, in my survival, I realized that the miner literally flies away and stops in some “random” places. places and digs down a pillar and somehow gets something there, I didn’t watch the process.

While it seems random it isn't. Its a spiral pattern going outwards from the starting position.

> Let's move on to the problem, which is that this same damn miner can land on some of your buildings and just break them :/, yes, just break them.
I would like to fix this somehow, perhaps there is an opportunity to give the miner such a function that he cannot break what the player has set, and this will most likely be the solution.

And this is why you don't place a rocket miner really close to your base.
A miner sure yes. But a "Rocket" miner. That flies away. Eh yeah I would call that having to deal with the consequences of your choices.
First of all, we can't track every single position that a player placed a block. Technically we could but it would eat gigabytes of ram or some form of a database that just would waste some space or cost you performance.

If I remember correctly the miner supports FTB chunks claims. (You can claim entire chunks and it should respect it and not dig in these chunks, but you have to test that)

### The Machines/Information Problem
> And here in more detail and this is the real problem (perhaps there is a detailed wiki, but I didn’t find it :/.
I am extremely grateful for the detailed guide through the VIKI book that is given when creating the world, this book is truly useful until you get to Transformers, energy storage, mechanisms and wires.

Ingame Wiki or a EUReader in the hotbar gives you a lot more information.
The ingame wiki also has plenty of tutorials with Images showing you information that you will need!
Including that.

### The Reactor
> I would also like to know how exactly nuclear reactors work, where to get the circuit diagrams and how they appear? How to maintain stability of a nuclear reactor and why it works at all, etc.

Technically 1.12.2 Reactor information on the wiki is accurate to 95%
Some values might have changed but the functionality is still the same.
Or some components that are new are simply missing in the wiki.

But yeah again Ingame wiki.

I hope that helps you.

**Comment by Ullimunate** [comment]
Thank you for your quick response, if you don’t mind a discussion then I’ll start.

> While it seems random it isn't. Its a spiral pattern going outwards from the starting position.

What about the miner, I assumed all the information that you voiced, and I circled it in brackets “” that he randomly chooses a place.


> If I remember correctly the miner supports FTB chunks claims. (You can claim entire chunks and it should respect it and not dig in these chunks, but you have to test that
What about FTB Chunks, if you have the information, could you briefly explain how to set up a claim for chunks.


The in-game wiki, again, is very convenient and informative, it really helps and there is a lot of information there, but again not without gaps.
Let's return to my words about the lack of some data. You specified about EuReader, I crafted it almost at the beginning, but I still didn’t understand what it displays in the chat and what these words and numbers mean (below is a screenshot)
![image](https://github.com/TinyModularThings/IC2Classic/assets/112324101/8e67e782-fade-4a70-b810-f4fc4d37a5b3)


![image](https://github.com/TinyModularThings/IC2Classic/assets/112324101/3e4ebac9-14d1-4998-8842-7fc590c5c8f3)
![image](https://github.com/TinyModularThings/IC2Classic/assets/112324101/7d549a06-8c1b-481c-a66b-17de805c9ec3)
![image](https://github.com/TinyModularThings/IC2Classic/assets/112324101/f47f2ea4-15af-4fd5-8216-d96e154cd2de)
Yes, when you click on 40/41+ fiberglass blocks you see the losses, but first you need to measure these 40 blocks, but I would like to know the losses right away, on top there are 2 screenshots of the wires, 1 on the 39th block, the other 40, the value has changed there to 39.91 - is this a loss in EU/T?
such a question, because in the in-game WIKI..
![image](https://github.com/TinyModularThings/IC2Classic/assets/112324101/b995de8f-fe13-45cb-b1d2-4829210deb46)
..there is no information about the amount of loss in Eu/t, which is the same for aluminum wire , it simply says that it can withstand something around 8k Eu/t with constant losses (what kind of losses and what does this mean)
![image](https://github.com/TinyModularThings/IC2Classic/assets/112324101/9b8c4348-cc46-4940-8d49-6eda7bdc54c2)


Also, again, the question is how to understand what kind of energy the same crusher or induction cooker CAN receive?
![image](https://github.com/TinyModularThings/IC2Classic/assets/112324101/8cbf0b52-4539-4232-82a1-0958cca5d265)
Energy storage devices contain information about the output, for example 512, but I did not find information about exactly what maximum energy this or that mechanism can absorb.
![image](https://github.com/TinyModularThings/IC2Classic/assets/112324101/c2c3ad6c-0d79-4125-a216-a6cece34f17c)

As for information about transformers, I found some information, I would like to know if it is reliable and true?
![image](https://github.com/TinyModularThings/IC2Classic/assets/112324101/8202466d-9fa0-4f4b-bddf-48820fdc05f7)

As for the InGame wiki, I looked briefly on the Internet for information about the mod, and didn’t quite understand how it works, could you also briefly clarify how to interact with it?
![image](https://github.com/TinyModularThings/IC2Classic/assets/112324101/79c6c74e-53ec-43c6-869f-eebaaf3cb390)


Thanks in advance for your answers and patience!

**Comment by Meduris** [comment]
The EU Reader also has the passive effect of showing you stats for machines, generators and cables in their tooltip while you have the EU Reader in your hotbar.
So while hovering over the machine in e.g. your inventory, jei, rei etc you'll see additional information about its tier (at least I think that was part of it), the energy output/usage and for cables also how much eu per packet they support and their loss. Loss only happens once the cable is long enough and will happen on a per packet basis, not per tick

EU also kinda works different from what you might be used to with RF. The different tiers are limited to a certain amount of EU per Packet, though, you can send multiple packets at the same. So a single cable with 32eu supported will be safe as long as each individual packet only has up to 32eu, even if you connect it to 100 generators at once and each sends a packet every tick.
Same for machines that receive energy and energy storages.

> As for the InGame wiki, I looked briefly on the Internet for information about the mod, and didn’t quite understand how it works, could you also briefly clarify how to interact with it?

With "Ingame Wiki" Speiger refered to the Wiki Item ic2 classic adds (which you already found and looked into), not a separate mod.

**Comment by Meduris** [comment]
also for energy storages, their energy output should be the exact same as the maximum input per packet they can take

**Comment by Meduris** [comment]
In the Wiki, there is a Tutorial Section, in that, if you select Electricity under Essentials, a lot of the basic workings of eu are explained in more detail then what I just tried to summarize.
I would also try looking into the section about Wrenches there, as it will save you a lot of frustration.

**Comment by Speiger** [comment]
@Ullimunate what Meduris is writing is correct so far.
Now to your questions he didn't elaborate on.

> Yes, when you click on 40/41+ fiberglass blocks you see the losses, but first you need to measure these 40 blocks, but I would like to know the losses right away, on top there are 2 screenshots of the wires, 1 on the 39th block, the other 40, the value has changed there to 39.91 - is this a loss in EU/T?

The EU that is transferred is averaged. So 39.91 could have been an upper bound of that average.
Loss is rounded down to the nearest full number. So 0.99 => 0 but 1.1 => 1

> ..there is no information about the amount of loss in Eu/t, which is the same for aluminum wire , it simply says that it can withstand something around 8k Eu/t with constant losses (what kind of losses and what does this mean)

That is with the tooltip that meduris mentioned.

> Also, again, the question is how to understand what kind of energy the same crusher or induction cooker CAN receive?

Tooltip or Energy Capabilities mode on the eureader. (Mode change is explained in the tooltip of the EUReader)

> Energy storage devices contain information about the output, for example 512, but I did not find information about exactly what maximum energy this or that mechanism can absorb.

These numbers are not per tick but per packet.
What packets are is explained in the wiki.

> As for information about transformers, I found some information, I would like to know if it is reliable and true?

No that is the IC2Exp wiki which has significantly changed over the ic2c wiki.
The 1.12 wiki is when you scroll up on github and press the "wiki" button.

> As for the InGame wiki, I looked briefly on the Internet for information about the mod, and didn’t quite understand how it works, could you also briefly clarify how to interact with it?

IC2Classic has a wiki Item.
Look it up in JEI or your convenient recipe viewer.
It takes 2 carbon plates to make if you lose it or throw it away.

And how to interact with it. Simply take the wiki item into your hand and right click it.

> Thanks in advance for your answers and patience!

No problem!

**Comment by Ullimunate** [comment]
Hello, the problem is that my rocket miner does not mine: Uranium, tin and silver. Although on another survival I had all this work properly. No matter how much I tried, I removed it and put it back in - to no avail.
