### ISSUE TITLE
Rocket miner is not working well

### ISSUE THREAD

**Issue by SpookyS1337** [TinyModularThings/IC2Classic#946]
Playing in single player mode made a rocket miner. He steadily returned and brought resources, but after I installed another one and started running them simultaneously (sometimes alternately) and noticed that they took a very long time to return to base. In addition, they arrive completely discharged (I use a lapis lazuli crystal in the miner) and completely without resources (it sometimes brings a crust of raw materials because a utilizer is installed in the miner). Using the remote control, he began to run around the world and find his miners. I noticed that he digs down and as soon as he reaches the ore that I indicated in the filter at the scanner, stops digging and continues to go down. I found some miners randomly flying back and forth, looking into it I saw that it was empty and completely de-energized. For a long time now, miners have only been giving me extra nerves. Can you tell me how to fix this problem? I point the miner to the point of return with the remote control, allocate the necessary resources with the scanner, check the charge, but every time I launch it on the road, I have to go and look for it all over the world and find it empty and discharged.

**Comment by Speiger** [comment]
@SpookyS1337 hmmmm not sure what it could be.
The main issue could be that everything together eats just to much power for it to run long enough.
10 Million EU is a lot.

It would be interesting if you could provide clips or something because that is simply a blind fix for something that i can't really target.

**Comment by SpookyS1337** [comment]
Энергии хватает .перед запуском шахтера я всегда проверяю его уровень заряда и все равно он возвращается пустым и разряженным.

**Comment by SpookyS1337** [comment]
@Speiger I'm attaching a link :  https://www.youtube.com/watch?v=lVvWiCyk9Gg
I've put together a few clips, I'm making them right now.(All except the first one) . In the 1st clip, you can see how my friend and I are talking about the poor work of the miners and suddenly one of the miners falls next to the base (although he has a charging point indicated).
2 clip I was making right now. On it, I clearly show the procedure for starting a miner. But in the video I use an ordinary crystal and not lapis lazuli, this is done so that it returns quickly, otherwise it would have to wait for several hours.
Clip 3 shows me going to look for the miner I sent 15 minutes ago (at that time I thought he was discharged and would not return).  But in the end I find my old miner with a lapis lazuli crystal, strangely enough I find it completely discharged and completely empty. Although having walked through his tunnels earlier, I saw how he found ore but did not dig it, sometimes there was no ore at the end of the miner's tunnel and I thought that he had extracted it, but in the end it still turned out to be empty(.
Clip 4 shows how I was returning to the base with my old miner and noticed that the miner sent in clip 2 had not yet arrived. But when I finished putting things in the locker, I immediately discovered my miner. As always, it turned out to be empty and, I think, it was discharged, but because of the small volume of the crystal, it quickly charged, because I have a lot of energy.

**Comment by SpookyS1337** [comment]
I think there is enough energy to service 2 miners . because at first they steadily flew away and returned with a bunch of resources. But at one point everything changed and they began to behave as shown in the clips. This has been happening for several days now.

**Comment by Speiger** [comment]
@SpookyS1337 this looks like the miner doesn't recognize that it has finished mining and stays stuck....
Yeah this is relevant to the "mines bedrock".

I think once i fixed the bedrock bug your should be fixed too.
I will look into the voiding bug too.

That helps a lot

**Comment by SpookyS1337** [comment]
could this be related to the number of miner pipes in the rocket miner?  And if it gets stuck when it hits the bedrock.  Why is there no ore in it that he mined during his descent?
