### ISSUE TITLE
Rocket Miner breaks bedrock

### ISSUE THREAD

**Issue by okovalenko0** [TinyModularThings/IC2Classic#947]
In this particular case, I launched a rocket miner, but he did not return for a long time. I found it discharged; after changing its crystal, it did not fly away. He dug to the -64 height (the last block was bedrock) and placed a pipe block there, which broke the last layer of the world and hung over the abyss, endlessly trying to dig something up.

![image](https://github.com/TinyModularThings/IC2Classic/assets/40452632/9a37fd94-7d40-4ea4-be4f-5fa3ac09f3b0)

Mod version: IC2Classic-1.19.2-2.0.7.1

**Comment by SpookyS1337** [comment]
I had such a situation, I wrote a post before yours, so far there is no answer

**Comment by Speiger** [comment]
Sorry. I simply forgot to answer.
It will be addressed in the next patch

**Comment by SpookyS1337** [comment]
So you've read my post? Do you think this is a miner's bug or did I make a mistake somewhere?
