### ISSUE TITLE
Extractor

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#95]
The centrifuge extractor should really be called the Centrifugal Extractor, and it's output slots could do with being closer together so the far left and right ones aren't right at the edge of the texture box.

**Comment by Speiger** [comment]
Ok. Did read but could not really understand what you mean. (I am really tired sry).
Weekend will give me hopefull enough power...

**Comment by Speiger** [comment]
Ok merged slots and texture a little bit...
You need to reset the Config part where the Centrifugal Name will be loaded... (Or just remove the name config)
