### ISSUE TITLE
Thermonuclear reactor does not form

### ISSUE THREAD

**Issue by DmitryProskurin** [TinyModularThings/IC2Classic#951]
I did it according to the description in the wiki: the frame and base were made of reinforced stone, the other sides were made of reinforced glass (tried 2 types), installed 4 valves (tried different types), tried changing the location of the main reactor block - the structure did not form.
What am I doing wrong?
![2024-01-24_09 52 13](https://github.com/TinyModularThings/IC2Classic/assets/14220482/bf21640d-8e15-4dd7-bf57-018676186237)
![2024-01-24_09 52 27](https://github.com/TinyModularThings/IC2Classic/assets/14220482/c0348113-ac71-49eb-acab-c0d729eedefd)

Minecraft 1.19.2
Mods:
Forge 43.3.0
IC2 Classic 2.0.8.1
Curious API 5.1.5.0
The One Probe  6.2.2

**Comment by CrossVas** [comment]
When assembling the structure, the main block should be placed in top left block from player's POV.
This is top left: valid
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/02c6ad80-ced2-4fce-9b95-d4482a518775)
This is top right: invalid
![image](https://github.com/TinyModularThings/IC2Classic/assets/25727222/21c0c493-c48c-4753-9ac1-301a26a4d620)

**Comment by DmitryProskurin** [comment]
@CrossVas, really, when i placed reactor block at left top corner - construction builds succeeded. Thanks! I don't find that information at in game wiki...

**Comment by CrossVas** [comment]
@DmitryProskurin it is mentioned on Colossal Machine pages, but can be applied on other multiblocks, too.
Glad it helped 👍

**Comment by DmitryProskurin** [comment]
Solved.
