### ISSUE TITLE
Blocks installed in place of the burnt cable disappear

### ISSUE THREAD

**Issue by DmitryProskurin** [TinyModularThings/IC2Classic#952]
Video with reproduce. After re sign in to world blocks placed normal.

https://github.com/TinyModularThings/IC2Classic/assets/14220482/b302d866-b5d8-4db6-b787-abc02e2dc3f2

I see some issues with video(i compress it by ffmpeg after record, so preview not available, but MPC-HC playing it). In some words: when i try to place any block at place of burned glassfiber cable, that block just disappear(from my inventory too).

Minecraft 1.19.2
Mods:
Forge 43.3.0
IC2 Classic 2.0.8.1
Curious API 5.1.5.0
The One Probe 6.2.2

**Comment by Speiger** [comment]
Ouch...

Yeah that is a bug with cable burning.

But I do assume you know why the glassfiber burns in the first place?

(If not, energy does always try to go the least loss applying path)

But yeah that will be addressed in the next patch.

**Comment by DmitryProskurin** [comment]
> But I do assume you know why the glassfiber burns in the first place?

At first I thought (the first connection of glassfiber & insulated iron cable) that packets from the iron cable do not go through glassfiber(I didn’t think that it would work), and when I connected glassfiber to the storage, large packets went through it and it burned out.

I will know that the packages choose the cable with the least resistance (as in real life :)).

I also noticed that Сrystalizer сhargepad(and higher) do not increase the charging area after installing the field expansion upgrade.  The value in the hint increases to 5 blocks, but in fact you need to stand on the platform. Also, they accept 64 such upgrades in one slot, but the radius remains 5 blocks(Crop harvester allow only one in slot). Am I doing something wrong or is this a bug?

**Comment by Speiger** [comment]
@DmitryProskurin the functionality of the charge pad is intentional.
The area of effect only grows the area of the charging effect, not the activation range.

Technically armor stands can activate chargepads too :)

But the whole idea was: The expansion is there so many more players can be charged at once :)

**Comment by DmitryProskurin** [comment]
@Speiger I expected that installing upgrades would also increase the activation area. Well, I'll put an armor stand on top of the chargepad. Maybe should add information about this to the chargepad wiki?

**Comment by Speiger** [comment]
@DmitryProskurin that was a really hard bug to discover.
But TL:DR the grid splitter basically didn't take into account if the paths that were transferred had invalid cables in them.
