### ISSUE TITLE
Too high Repair Cost value will require more XP than the Electric Enchanter can hold for a Combine operation.

### ISSUE THREAD

**Issue by Geekerandy** [TinyModularThings/IC2Classic#954]
I'm not sure how *exactly* you would refer to the function that determines the scaling exponential XP costs of repeatedly anviling items together, but it seems like the Electric Enchanter scales the XP costs of some of its operations based on this function.

For understanding, I will refer to it as Repair Cost.
IC2 Classic 1.19.2, _IC2Classic-1.19.2-2.0.8.1.jar_
Forge 43.3.7, the latest as of this issue.

If the Repair Cost is too high, the XP requirement for a Combine operation will exceed the XP capacity of the Electric Enchanter.

![image](https://github.com/TinyModularThings/IC2Classic/assets/14936715/627a4d22-bef2-40f4-9148-31e05116ecbc)
![image](https://github.com/TinyModularThings/IC2Classic/assets/14936715/de7cc0c2-2e14-4c01-afe8-1f7157109eac)

This issue is not gamebreaking, as this can be circumvented by disenchanting one enchant off each the book and the pickaxe, which will also clear the Repair Cost from each item as well.  Then the enchants can simply be Combined without issue.

It is also worth mentioning that encountering this issue is highly unlikely due to the fact that one will likely use the Electric Enchanter for earlier steps (thus clearing the Repair Cost), as well as just naturally encountering the Anvil "Too Expensive!" message before the XP costs are too high for the Electric Enchanter.

I had to perform a very specific route of combining enchants to barely exceed the XP cap, in a manner one would call "sloppy". 
Alternatively, having higher-than-vanilla level enchants combined with no limit on Anvil xp may also encounter this issue.

As for how exactly to patch this issue, I would just have the maximum cost for an operation with the Electric Enchanter be 1000 XP.

**Comment by Geekerandy** [comment]
oh and it looks like the Electric Enchanter uses a period for "1.000 XP", this is for the en_us localization, it should be a comma.

**Comment by Speiger** [comment]
@Geekerandy no its a comma. A period would be 1 pixel instead of 2

**Comment by Geekerandy** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/14936715/2942dcf7-121e-41ac-83e0-1a1ae215bfb8)
@Speiger I mean, this looks like one pixel

**Comment by Speiger** [comment]
OH xD
