### ISSUE TITLE
Coins merge in trade-o-mat when selling items 1.19.2

### ISSUE THREAD

**Issue by pod1425** [TinyModularThings/IC2Classic#955]
When using coins in trade-o-mat to buy resources from other players, trade-o-mat merges coins into higher possible, effectively limiting amount of trades that can be done to 8 without owner manually changing coins back to smaller nominals. Trade-o-mat is then unable to split coins to continue trading.

putting enough coins for 320 trades:

![image](https://github.com/TinyModularThings/IC2Classic/assets/91281678/349bf7a5-3acc-4028-bc21-c1e073604dd1)

doing one trade:

![image](https://github.com/TinyModularThings/IC2Classic/assets/91281678/2bda3e1c-8f6a-4d87-95b1-74c2160055b9)

doing 7 more trades, now no more trades are possible:

![image](https://github.com/TinyModularThings/IC2Classic/assets/91281678/e5bc7e0c-a66c-473d-9987-45f0a765b1e5)

Back in personal storage, we see coins has merged:

![image](https://github.com/TinyModularThings/IC2Classic/assets/91281678/b554bb84-c976-4174-9468-ea30034d5c0b)

**Comment by Speiger** [comment]
Only 1.19.2 since i rewrote the entire system in each version and they work completely different in each
