### ISSUE TITLE
Plethora inventory manipulation into energy storage units/battery station

### ISSUE THREAD

**Issue by The0mbudsman** [TinyModularThings/IC2Classic#957]
If I have a turtle sat on top of a Batbox/MFE/MFSU/Battery Station, plethora's push/pullitems dont work as expected.

```
batbox = peripheral.wrap('bottom')
batbox.getTransferLocations()
   { "south", "bottom", "self", "right", "up"}
batbox.pushItems('up',1,1,1)
   0
```
Doesn't matter which slot you have a lapotron/energy crystal in, it doesn't go into the turtles inventory, when I would expect it to

**Comment by Speiger** [comment]
@The0mbudsman did you configure the slots to be inserted/extracted?
The "S" button allows to configure stuff.
Also try clicking the Slot when you are in the S mode.

**Comment by The0mbudsman** [comment]
![image](https://github.com/TinyModularThings/IC2Classic/assets/37667514/7a2c16b1-68d4-4e53-93ba-ba3a5bc33e15)
Pressing S does nothing, and theres no gui element to configure the slots

Which of these binds is it supposed to be?
![image](https://github.com/TinyModularThings/IC2Classic/assets/37667514/a6ad3286-89d6-4147-9f97-e3a05576b956)

**Comment by Speiger** [comment]
Oh i read battery station and thought you meant 1.19.2 but this is 1.12.2.

Oops.
Question, can you insert/extract things with a vanilla hopper?

**Comment by The0mbudsman** [comment]
Hey, inserting things with a vanilla hopper works, but not extracting

**Comment by Speiger** [comment]
@The0mbudsman you need an automation upgrade which basically makes all slots accessible from all sides.
Which you insert with a machine tool. (By clicking with a machine tool on to the machine)

This is the first iteration of this kind of system where you could configure everything.
The second iteration is a lot better in 1.19.2.

**Comment by Speiger** [comment]
@The0mbudsman i investigated this but ran into the following problem.
After getting batbox = peripheral.wrap('bottom') running it will simply return a nil for everything.
Including chests and other things...
I am not sure what i am doing wrong.
But i can't even test anything.

I am not sure how to help here ^^"
