### ISSUE TITLE
Wrong one probe info when brewing "Lite normal beer"

### ISSUE THREAD

**Issue by DmitryProskurin** [TinyModularThings/IC2Classic#958]
One probe says it's "Lite dark beer", but you take from barrel "Lite normal beer". Also, displayed alcohol level at 1 above that it should be for "Lite dark youngster". 

https://github.com/TinyModularThings/IC2Classic/assets/14220482/64cdbda3-17ed-4793-aecb-15736a100e0a

MC 1.19.2, IC2 Classic 2.0.8.1.

**Comment by DmitryProskurin** [comment]
I found another several drinks with same issue(format: display in JEI(display in one probe)):
Lite Normal Brew(lite dark brew)
Lite dark brew(lite full brew)
Lite full brew(lite black brew)
Lite normal youngster(Lite dark youngster)
Lite dark youngster(lite full youngster)
Lite full youngster(Lite black youngster)
Lite dark beer(Lite full beer)
Lite full ale(Lite black ale)

I compared the proportions of drinks with problems and discovered the following pattern with proportions and alcohol level display(wheat/hops/water - JEI/One probe):
1/2/4 - normal/dark
1/3/5 - dark/full
1/4/6 - full/black

**Comment by Speiger** [comment]
Thank you. This somehow got missed even so we got a ton of people brewing on the beta server xD
