### ISSUE TITLE
Export upgrade and durability/NBT comparison

### ISSUE THREAD

**Issue by DmitryProskurin** [TinyModularThings/IC2Classic#959]
I setup export upgrade for export jetpack(whitelist) and it works well, but after i flуц on jetpack it's not export's anymore. Compare NBT and durability is disabled.
It's a bug or i missing something?

https://github.com/TinyModularThings/IC2Classic/assets/14220482/c3d67110-5da5-400f-9c65-dd88d3758190

MC 1.19.2, IC2 Classic 2.0.8.1.

**Comment by Speiger** [comment]
@DmitryProskurin sorry but this MP4 file is not playable on github and downloading it causes a TXT to be downloaded.

**Comment by DmitryProskurin** [comment]
@Speiger
1. Does iridium reflector don't has durability(display something another value at durability) too?
2. Is there a way to ignore charge value at export/import filter except inverting condition for item(like i did in video)?

**Comment by Speiger** [comment]
@DmitryProskurin

- 1: No looks like it uses durability.
- 2: If you disable NBT checks it should only compare items not their NBT... Maybe something is broken? Not sure

**Comment by DmitryProskurin** [comment]
@Speiger NBT comparison is disabled by default, i did not change this value(filter setup at 0:13).

I ask about reflectors, because i have similar issue with them too(i use machine buffer & crafting upgrade instead of canning machine) - they don't import immediately to machine buffer from chest(import of empty cells work perfect). I need to put them to machine buffer, reinstall upgrades and they become import, but not always.

**Comment by DmitryProskurin** [comment]
@Speiger I used completely full jetpack for import upgrade setup and upgrade imports only that one. Damaged jetpack stay in chest.

https://github.com/TinyModularThings/IC2Classic/assets/14220482/c2f73e96-48dd-4299-a075-da6347910436

Enable/disable NBT check has no effect.

https://github.com/TinyModularThings/IC2Classic/assets/14220482/fc5423db-ca4a-4c89-bdfe-642cc53c3672

**Comment by Speiger** [comment]
Yeah already realized that.
