### ISSUE TITLE
Recycler Texture

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#96]
The energy bolt is way too far over to the left:
![2015-07-23_17 54 31](https://cloud.githubusercontent.com/assets/4021725/8856648/ffc6ca0c-3163-11e5-8a54-bc9333122527.png)

**Comment by Speiger** [comment]
ok. That should be done really easy.
Thanks

**Comment by Speiger** [comment]
Fixed... Also draw now the always items on progress finished. (before it did draw only items when it made scrap)
