### ISSUE TITLE
[1.19.2] Extracting output from barrel, mug duplication

### ISSUE THREAD

**Issue by gostedlogeka** [TinyModularThings/IC2Classic#960]
Extracting output from barrel while holding alt and 32 mugs/glasses extracts everything at once and gives you 32 filled mugs/glasses, if was loaded to the top, however it only takes only 1 empty mug/glass for it, thus duplicating mugs in 1 to 32 ratio. Tested on barebones 
forge[43.3.7]-ic2c[2.0.8.1]-curios[5.1.4.4]

**Comment by Geekerandy** [comment]
I was able to reproduce the issue. Same conditions.
https://youtu.be/C0hByKZZzHw
Note that I am holding Left Alt the entire time in the video.
