### ISSUE TITLE
Charged Electrolzer Bug

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2Classic#97]
Well, it doesn't seem to work.
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 23/07/15 17:59
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at ic2.core.block.machine.tileentity.TileEntityElectrolyzer$ItemRecipe.<init>(TileEntityElectrolyzer.java:353)
	at ic2.core.block.machine.tileentity.TileEntityCharged.getRecipe(TileEntityCharged.java:76)
	at ic2.core.block.machine.tileentity.TileEntityCharged.power(TileEntityCharged.java:167)
	at ic2.core.block.machine.tileentity.TileEntityCharged.func_145845_h(TileEntityCharged.java:129)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ic2.core.block.machine.tileentity.TileEntityElectrolyzer$ItemRecipe.<init>(TileEntityElectrolyzer.java:353)
	at ic2.core.block.machine.tileentity.TileEntityCharged.getRecipe(TileEntityCharged.java:76)
	at ic2.core.block.machine.tileentity.TileEntityCharged.power(TileEntityCharged.java:167)
	at ic2.core.block.machine.tileentity.TileEntityCharged.func_145845_h(TileEntityCharged.java:129)

-- Block entity being ticked --
Details:
	Name: Charged-Electorlyzer-Classic // ic2.core.block.machine.tileentity.TileEntityCharged
	Block type: ID #178 (tile.null // ic2.core.block.machine.BlockMachine2)
	Block data value: 6 / 0x6 / 0b0110
	Block location: World: (-266,64,-34), Chunk: (at 6,4,14 in -17,-3; contains blocks -272,0,-48 to -257,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #178 (tile.null // ic2.core.block.machine.BlockMachine2)
	Actual block data value: 6 / 0x6 / 0b0110
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Addon Testing/Crashing World
	All players: 1 total; [EntityPlayerMP['Chocohead'/375, l='Addon Testing/Crashing World', x=-265.95, y=65.00, z=-32.77]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 1548898019326874587
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-248,64,-12), Chunk: (at 8,4,4 in -16,-1; contains blocks -256,0,-16 to -241,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 259259 game time, 259259 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 94840 (now: false), thunder time: 137424 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.7.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 333802208 bytes (318 MB) / 619184128 bytes (590 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.88.1307 Minecraft Forge 10.13.2.1307 Optifine OptiFine_1.7.10_HD_B7 24 mods loaded, 24 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.88.1307} [Forge Mod Loader] (forge-1.7.10-10.13.2.1307-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1307} [Minecraft Forge] (forge-1.7.10-10.13.2.1307-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FastCraft{1.22} [FastCraft] (fastcraft-1.22-ctest8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2{2.2.999} [Industrial Craft Classic] (IC2 Classic Version 1.1.0.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ImmibisCore{59.0.5} [Immibis Core] (immibis-core-59.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AdvancedRepulsionSystems{59.0.2} [Advanced Repulsion Systems] (adv-repulsion-systems-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AdvancedPowerManagement{2.0.0b} [Advanced Power Management] (AdvPowerMan-2.0.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ElectricalAddition{1.0} [ElectricalAddition] (ElectricalAddition-1.7.10-1.0.0.1.b4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2BackpackHUD{3.0} [IC2 Backpack HUD] (IC2 Backpack HUD v3.0 - MC 1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Ic2Nei{1.0} [IC2 Nei Plugin] (IC2 Nei Plugin Version 1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2NuclearControl{2.2.1a-Yolo} [Nuclear Control 2] (IC2NuclearControl-2.2.1a-Yolo.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PowerConverters{1.7.10_3.2.2-jenkins.70} [Power Converters] (PowerConverters-1.7.10_3.2.2-jenkins.70.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PowerUtils{1.7.10-1.0.4} [PowerUtils] (PowerUtils-1.7.10-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ReiMinimap{1.7.10} [Rei's Minimap] (ReiMinimap-1.7.10-3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Tubestuff{59.0.1} [Tubestuff] (tubestuff-59.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Chocohead'/375, l='Addon Testing/Crashing World', x=-265.95, y=65.00, z=-32.77]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Speiger** [comment]
Ok. Did fix it. At least gave it a secure system. So that it does no longer crash.

**Comment by Speiger** [comment]
Gave the Basic Electrolyzer the same secure System...
