### ISSUE TITLE
Electric Enchanter does not work

### ISSUE THREAD

**Issue by MRGRD56** [TinyModularThings/IC2Classic#970]
I've placed an electric enchanter, surrounded it by bookshelves, connected it to electricity. However, I can't do anything with it. When I put anything there, in this case it's a Diamond Drill, I can't enchant it, despite having enough EXP, books, and lapis in the table. Is this a bug, or am I doing something wrong?

![image](https://github.com/TinyModularThings/IC2Classic/assets/35491968/7a2c4c5d-77a4-4e57-8595-b94febc0bb66)

![image](https://github.com/TinyModularThings/IC2Classic/assets/35491968/eebe12be-f3e1-4073-a0e2-49baa19983fa)

Switching the modes of the table does not help.

I'm using `IC2Classic-1.19.2-2.0.8.1`

**Comment by Speiger** [comment]
Looks like you are missing Experience stored inside of the electric enchanter

**Comment by MRGRD56** [comment]
@Speiger Oops, yeah, that's right. I tried pressing "+" and "-" and it didn't seem to work  

![image](https://github.com/TinyModularThings/IC2Classic/assets/35491968/3a42fc61-dbef-4637-b8b0-1d9d1fa02cd8)

but it turns out simply pressing those buttons changes the experience of enchanter by an almost unnoticeable value. I realized that you can use `Shift` and `Ctrl` to add more experience at a time.  

Thanks a lot!

**Comment by Speiger** [comment]
Yeah there is a reason why Shift + Control are there :)
Though a slider would be cool too if possible... Future ideas.

Anyways no problem :)

**Comment by DmitryProskurin** [comment]
@Speiger, I also didn’t understand, why the enchantment didn’t work, because... +\- buttons moved the experience in insignificant amounts and nothing happened. Thanks The One probe, I saw that the xp value was changing, and then I guessed what these buttons do. Maybe you should remove that buttons and take xp directly from character?

**Comment by Speiger** [comment]
@DmitryProskurin nah, then a player has to constantly look at the machine.
The machine drains XP once the process is done.

Also it allows other people to merge their XP together if they don't have enough on their own. 

So it stays that way.

**Comment by DmitryProskurin** [comment]
@Speiger, maybe increase the amount of experience that is taken/returned? It will be more noticeable on the XP progress bar.
