### ISSUE TITLE
ForcedSoundsMuffling

### ISSUE THREAD

**Issue by cpbplus** [TinyModularThings/IC2Classic#98]
Godd day, sir.
Here is the problem:
All machines and items(except NanoSaber) doesn't have sounds.
It's not so terrible but when i try to use Alarms from NuclearControl2 they also silent.
With IC2Exp Alarms works fine.
Sounds were enabled in configs.
---
If you already know about that problem - sorry for disturbing.

**Comment by Speiger** [comment]
Yeah i am aware of that. And it is already fixed in the 1.1.0.x Update^^

Thanks for your help
