### ISSUE TITLE
Planned Mod support for the 1.1.0.x update

### ISSUE THREAD

**Issue by Speiger** [TinyModularThings/IC2Classic#99]
I did plan to add special support to some mods since they would not really give their full support by default. So i try to make the modifikations by myself... Some will be maybe not possible so keep in mind that they could change...

Plans:
-AE2 Support (PTP Tunnels that support multipackets and do not be sources and receivers... Not sure if i can do it)
-Not Enough Resources support (Ore Support since they made a fix for me that i can add the ores by myself really easy)
-Thaumcraft support: (Adding asspects to the machines and co... Could be possible that i it will be not completed to this release but at least started with some machines/items that are not supportet by default)

Plans after 1.1.0.x update:
-RF support. (Converter block.. Nothing special)

**Comment by Speiger** [comment]
Canceled some stuff for now...

**Comment by Carbon-Ghost** [comment]
My suggestion on plans ( let's do the easier stuff first ) : 
-Thaumcraft support

Then if you didn't cancelled this one : 
- NER support
Then because it's quite nice : 
- Converter
Last one because complex ( from what I understand ) 
-Fix P2P

**Comment by Carbon-Ghost** [comment]
Another thing I would really love is compatibility with open modular turrets :3

**Comment by Speiger** [comment]
@Carbon-Ghost my list has no order i do what is easier for me...
Ner Support would be the easiest one because adding some easy numbers is no problem...
AE Thing is maybe the hardest in codeing wise but not that big...
And thaumcraft is the longest project^^

**Comment by Speiger** [comment]
@Carbon-Ghost what did you ahve in mind?

**Comment by Carbon-Ghost** [comment]
Add IC2 like recipes and maybe eu integration ? 

But that would be last since it's minor ^^

**Comment by Speiger** [comment]
Ill have to talk to the modauther for that. For now... Nope... I did not even know that mod and do not know what the authers plans are... Without these informations ill do nothing...
If you want to know why: NGNL is a good reference...

**Comment by Carbon-Ghost** [comment]
xD Well let's first do the 
- NER support Then because it's quite nice 
- Thaumcraft support
- Converter RF-EU
- Config for adding new armor to have eu generation ( options are : solar, body heat by consuming hunger and static walking )
- P2P fix, no not that P2P NSA, I mean't AE2 one ;P

**Comment by Speiger** [comment]
Well you have to listen sometimes better...
At some part you are right but let me corret you.
This Update gains these mod compatiblity things:

-[ ] Ner support
-[ ] Thaumcraft aspect Support (better defined)
-[ ] P2P packet version...

Everything else is merged to next update^^. I said that to you a couple times. (I do not mean that bad)

**Comment by Carbon-Ghost** [comment]
Ah kk ^^0''

**Comment by Speiger** [comment]
Update:
Ner Support and P2P Packet Support are done.
Last thing is thaumcraft support... Will work on that later. next couple days is breaking time^^

**Comment by Carbon-Ghost** [comment]
kk ^^ Meanwhile gonna to talk to Jared for our plan of IC2 classic support :D

**Comment by Speiger** [comment]
Canceled Thaumcraft support...
Reason? @Azanor could implement a registry which allows people to extends his aspect detection and i could support it without any problem... But i do not want to implement for each IC2 Classic Item/Block a custom aspect, when i could simply extend his detection system by a simply recipeHelper..

**Comment by Speiger** [comment]
When @Azanor adds that i will implement the Thaumcraft support at the time i get a dev version :)
